--
-- NAVISION_CLIENTES  (Table) 
--
CREATE TABLE NAVISION_CLIENTES
(
  COD_CLI          VARCHAR2(6 BYTE)             NOT NULL,
  NOMBRE           VARCHAR2(30 BYTE)            NOT NULL,
  CIF              VARCHAR2(17 BYTE)            NOT NULL,
  DIRECCION        VARCHAR2(50 BYTE),
  COD_POST         VARCHAR2(5 BYTE),
  POBLACION        VARCHAR2(30 BYTE),
  TELEFONO         VARCHAR2(13 BYTE),
  FAX              VARCHAR2(13 BYTE),
  GR_CONT_NEGOCIO  VARCHAR2(7 BYTE),
  GR_REG_IVA       VARCHAR2(2 BYTE),
  GR_CONT_CLIENTE  VARCHAR2(8 BYTE),
  TERMINO_PAGO     VARCHAR2(7 BYTE),
  FORMA_PAGO       VARCHAR2(10 BYTE),
  METODO_LIQUID    VARCHAR2(10 BYTE)
)
TABLESPACE INTEGRADOSPLANTILLA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


--
-- NAVISION_ENVIOS  (Table) 
--
CREATE TABLE NAVISION_ENVIOS
(
  SERIFACT      VARCHAR2(1 BYTE)                NOT NULL,
  ANYOREFE      NUMBER(4)                       NOT NULL,
  NUMEFACT      NUMBER(9)                       NOT NULL,
  FECHA_ENVIO   DATE                            NOT NULL,
  NUMERO_ENVIO  NUMBER(9)                       NOT NULL
)
TABLESPACE INTEGRADOSPLANTILLA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


--
-- NAVISION_ENVIOS_HISTORICA  (Table) 
--
CREATE TABLE NAVISION_ENVIOS_HISTORICA
(
  SERIFACT      VARCHAR2(1 BYTE)                NOT NULL,
  ANYOREFE      VARCHAR2(4 BYTE)                NOT NULL,
  NUMEFACT      VARCHAR2(9 BYTE)                NOT NULL,
  FECHA_ENVIO   DATE                            NOT NULL,
  NUMERO_ENVIO  NUMBER(9)                       NOT NULL
)
TABLESPACE INTEGRADOSPLANTILLA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


--
-- NAVISION_INTERFASE  (Table) 
--
CREATE TABLE NAVISION_INTERFASE
(
  SERIFACT            VARCHAR2(1 BYTE)          NOT NULL,
  ANYOREFE            NUMBER(4)                 NOT NULL,
  NUMEFACT            NUMBER(9)                 NOT NULL,
  TIPO_DOCUMENTO      VARCHAR2(7 BYTE),
  CLIENTE             VARCHAR2(6 BYTE),
  TIPO_CUENTA         VARCHAR2(10 BYTE),
  FECHA_REGISTRO      DATE,
  FECHA_FACTURA       DATE,
  FACTURA             VARCHAR2(12 BYTE),
  FECHA_ENVIO         DATE,
  NUM_ENVIO           NUMBER(9),
  TARIFA              VARCHAR2(8 BYTE),
  BASE                NUMBER(9,2),
  IVA                 NUMBER(9,2),
  TOTAL               NUMBER(9,2),
  CUENTA_INGRESO      VARCHAR2(7 BYTE),
  BASE_LINEA          NUMBER,
  TARIFA_LINEA        VARCHAR2(8 BYTE),
  DESCRIPCION         VARCHAR2(60 BYTE),
  GRUPO_IVA_NEGOCIO   VARCHAR2(3 BYTE),
  GRUPO_IVA_PRODUCTO  VARCHAR2(10 BYTE),
  TERMINO_PAGO        VARCHAR2(10 BYTE),
  BUQUE               VARCHAR2(8 BYTE),
  NOMBRE_BUQUE        VARCHAR2(20 BYTE),
  CLAVE_OPERACION     VARCHAR2(1 BYTE),
  FECHA_OPERACION     DATE
)
TABLESPACE INTEGRADOSPLANTILLA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


--
-- NAVISION_INTERFASE_UPD  (Table) 
--
CREATE TABLE NAVISION_INTERFASE_UPD
(
  FACTURA  VARCHAR2(9 BYTE)
)
TABLESPACE INTEGRADOSPLANTILLA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


--
-- NAVISION_TIPOS_IVAS  (Table) 
--
CREATE TABLE NAVISION_TIPOS_IVAS
(
  PORCEIVA            NUMBER,
  GRUPO_IVA_PRODUCTO  VARCHAR2(10 BYTE)
)
TABLESPACE INTEGRADOSPLANTILLA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


--
-- NAVISION_TIPOS_IVAS_PR  (Table) 
--
CREATE TABLE NAVISION_TIPOS_IVAS_PR
(
  PORCEIVA            NUMBER,
  GRUPO_IVA_PRODUCTO  VARCHAR2(10 BYTE)
)
TABLESPACE INTEGRADOSPLANTILLA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


--
-- NAVISION_TIPO_CUENTA  (Table) 
--
CREATE TABLE NAVISION_TIPO_CUENTA
(
  TARIFA        VARCHAR2(8 BYTE),
  TIPO_CUENTA   VARCHAR2(10 BYTE),
  TERMINO_PAGO  VARCHAR2(10 BYTE)
)
TABLESPACE INTEGRADOSPLANTILLA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


--
-- NOVEDAD_RODANTE  (Table) 
--
CREATE TABLE NOVEDAD_RODANTE
(
  CODIGO         INTEGER                        NOT NULL,
  DESCRIPCION    VARCHAR2(500 BYTE)             NOT NULL,
  FECHA          DATE                           NOT NULL,
  USRALTA        VARCHAR2(20 BYTE),
  USRMODIF       VARCHAR2(20 BYTE),
  FECALTA        DATE,
  FECMODIF       DATE,
  CODPUE         VARCHAR2(5 BYTE)               NOT NULL,
  INDBAJA        VARCHAR2(1 BYTE),
  FECBAJA        DATE,
  USRBAJA        VARCHAR2(20 BYTE),
  INDALTATABLET  VARCHAR2(1 BYTE)
)
TABLESPACE INTEGRADOSPLANTILLA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE NOVEDAD_RODANTE IS 'Novedades rodantes - Tablet';

COMMENT ON COLUMN NOVEDAD_RODANTE.CODIGO IS 'Código';

COMMENT ON COLUMN NOVEDAD_RODANTE.DESCRIPCION IS 'Descripción';

COMMENT ON COLUMN NOVEDAD_RODANTE.FECHA IS 'Fecha novedad';

COMMENT ON COLUMN NOVEDAD_RODANTE.USRALTA IS 'Usuario alta';

COMMENT ON COLUMN NOVEDAD_RODANTE.USRMODIF IS 'Usuario modificación';

COMMENT ON COLUMN NOVEDAD_RODANTE.FECALTA IS 'Fecha alta';

COMMENT ON COLUMN NOVEDAD_RODANTE.FECMODIF IS 'Fecha modificación';

COMMENT ON COLUMN NOVEDAD_RODANTE.CODPUE IS 'Código puerto';

COMMENT ON COLUMN NOVEDAD_RODANTE.INDBAJA IS 'Check para indicar que está dado de baja';

COMMENT ON COLUMN NOVEDAD_RODANTE.FECBAJA IS 'Fecha de baja';

COMMENT ON COLUMN NOVEDAD_RODANTE.USRBAJA IS 'Usuario da de baja';

COMMENT ON COLUMN NOVEDAD_RODANTE.INDALTATABLET IS 'Check para indicar si se ha creado vía la tablet';


--
-- OCUPSUP_EXENHORAS  (Table) 
--
CREATE TABLE OCUPSUP_EXENHORAS
(
  CODIGO       VARCHAR2(2 BYTE)                 NOT NULL,
  DESCRIPCION  VARCHAR2(100 BYTE)               NOT NULL
)
TABLESPACE INTEGRADOSPLANTILLA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE OCUPSUP_EXENHORAS IS 'Ocupación Superficie - Tipos de exención horas ';

COMMENT ON COLUMN OCUPSUP_EXENHORAS.CODIGO IS 'Código';

COMMENT ON COLUMN OCUPSUP_EXENHORAS.DESCRIPCION IS 'Descripción';


--
-- OCUPSUP_TIPOALM  (Table) 
--
CREATE TABLE OCUPSUP_TIPOALM
(
  CODIGO       VARCHAR2(2 BYTE)                 NOT NULL,
  DESCRIPCION  VARCHAR2(100 BYTE)               NOT NULL,
  BAJA         VARCHAR2(1 BYTE)
)
TABLESPACE INTEGRADOSPLANTILLA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE OCUPSUP_TIPOALM IS 'Modalidad almacenamiento ';

COMMENT ON COLUMN OCUPSUP_TIPOALM.CODIGO IS 'Código';

COMMENT ON COLUMN OCUPSUP_TIPOALM.DESCRIPCION IS 'Descripción';

COMMENT ON COLUMN OCUPSUP_TIPOALM.BAJA IS 'Check para indicar que está dado de baja';


--
-- OCUPSUP_TIPOEMB  (Table) 
--
CREATE TABLE OCUPSUP_TIPOEMB
(
  CODIGO       VARCHAR2(1 BYTE),
  DESCRIPCION  VARCHAR2(50 BYTE)
)
TABLESPACE INTEGRADOSPLANTILLA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE OCUPSUP_TIPOEMB IS 'Tipo Embarque Ocupación';

COMMENT ON COLUMN OCUPSUP_TIPOEMB.CODIGO IS 'Código';

COMMENT ON COLUMN OCUPSUP_TIPOEMB.DESCRIPCION IS 'Descripción';


--
-- OCUPSUP_TIPOOPE  (Table) 
--
CREATE TABLE OCUPSUP_TIPOOPE
(
  CODIGO       VARCHAR2(1 BYTE),
  DESCRIPCION  VARCHAR2(50 BYTE),
  BAJA         VARCHAR2(1 BYTE),
  INDTASA      VARCHAR2(1 BYTE)
)
TABLESPACE INTEGRADOSPLANTILLA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE OCUPSUP_TIPOOPE IS 'Tipo Zona Ocupación ';

COMMENT ON COLUMN OCUPSUP_TIPOOPE.CODIGO IS 'Código';

COMMENT ON COLUMN OCUPSUP_TIPOOPE.DESCRIPCION IS 'Descripción';

COMMENT ON COLUMN OCUPSUP_TIPOOPE.BAJA IS 'Check para indicar que está dado de baja';

COMMENT ON COLUMN OCUPSUP_TIPOOPE.INDTASA IS 'Check para indicar que lo que genera es tasa';


--
-- OCUPSUP_TIPORODANTE  (Table) 
--
CREATE TABLE OCUPSUP_TIPORODANTE
(
  CODIGO        VARCHAR2(3 BYTE)                NOT NULL,
  DESCRIPCION   VARCHAR2(100 BYTE)              NOT NULL,
  CODBAREMO     VARCHAR2(15 BYTE)               NOT NULL,
  INDBONIF      VARCHAR2(1 BYTE),
  BAJA          VARCHAR2(1 BYTE),
  INDOBLIGDIAS  VARCHAR2(1 BYTE),
  ORDENLQAGRUP  NUMBER(3)                       NOT NULL
)
TABLESPACE INTEGRADOSPLANTILLA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE OCUPSUP_TIPORODANTE IS 'Tipo elemento rodante - Vigo';

COMMENT ON COLUMN OCUPSUP_TIPORODANTE.CODIGO IS 'Código';

COMMENT ON COLUMN OCUPSUP_TIPORODANTE.DESCRIPCION IS 'Descripción';

COMMENT ON COLUMN OCUPSUP_TIPORODANTE.CODBAREMO IS 'Baremo Negocio';

COMMENT ON COLUMN OCUPSUP_TIPORODANTE.INDBONIF IS 'Check para indicar que lleva bonificación';

COMMENT ON COLUMN OCUPSUP_TIPORODANTE.BAJA IS 'Check para indicar que está dado de baja';

COMMENT ON COLUMN OCUPSUP_TIPORODANTE.INDOBLIGDIAS IS 'Check para indicar que es obligatorio indicar el número de días';

COMMENT ON COLUMN OCUPSUP_TIPORODANTE.ORDENLQAGRUP IS 'Orden de generación  para el valorador';


--
-- OPERACION  (Table) 
--
CREATE TABLE OPERACION
(
  CODPUE                VARCHAR2(5 BYTE)        NOT NULL,
  ANYO                  INTEGER                 NOT NULL,
  CODESCALA             INTEGER                 NOT NULL,
  CODESTADIA            INTEGER                 NOT NULL,
  CODOPERACION          INTEGER                 NOT NULL,
  INDMANUAL             VARCHAR2(1 BYTE),
  CODTIPOPE             VARCHAR2(2 BYTE)        NOT NULL,
  CODTIPCARGA           VARCHAR2(3 BYTE),
  CODTIPUNIDAD          VARCHAR2(3 BYTE),
  LUGAR                 VARCHAR2(100 BYTE),
  PESOMAXPORUNIDAD      NUMBER(10,2),
  FECINI                DATE,
  FECFIN                DATE,
  TERMINAL              VARCHAR2(100 BYTE),
  CODTIPMEDIOMANIP      VARCHAR2(3 BYTE),
  NUMMEDIOS             INTEGER,
  INDPROPPUERTO         VARCHAR2(1 BYTE),
  OBSERVACIONES         VARCHAR2(500 BYTE),
  CODOPERACIONDUE       VARCHAR2(4 BYTE),
  NUMUNIDADES           NUMBER(10,2),
  CODGRUA               INTEGER,
  CODPUECONTADOR        VARCHAR2(5 BYTE),
  NUMCONTADOR           VARCHAR2(20 BYTE),
  LECINICIAL            NUMBER(8,2),
  LECFINAL              NUMBER(8,2),
  CODTIPODESECHO        VARCHAR2(2 BYTE),
  INDJUSTIFENTDESECHO   VARCHAR2(1 BYTE),
  CODMODSUMINCOMB       VARCHAR2(1 BYTE),
  CODCOMBSUMINCOMB      VARCHAR2(1 BYTE),
  CODBARCAZA            INTEGER,
  CODTIPSUMINAGUA       VARCHAR2(1 BYTE),
  CODPASARELA           INTEGER,
  FECSOLICITUD          DATE,
  FECALTA               DATE,
  FECMODIF              DATE,
  USRALTA               VARCHAR2(20 BYTE),
  USRMODIF              VARCHAR2(20 BYTE),
  OBSMEDIOSMANIP        VARCHAR2(300 BYTE),
  INDLIQUIDADO          VARCHAR2(1 BYTE),
  GUIDSRV               VARCHAR2(40 BYTE),
  INDYOKTRAS            VARCHAR2(1 BYTE),
  INDYOKUSO             VARCHAR2(1 BYTE),
  INDYOKCOLOC           VARCHAR2(1 BYTE),
  INDRAMMANIPUSU        VARCHAR2(1 BYTE),
  INDRAMMANIPMANTUSU    VARCHAR2(1 BYTE),
  INDNOPOSIBLELEC       VARCHAR2(1 BYTE),
  CODTIPOALQPAS         VARCHAR2(2 BYTE),
  INDNOAPLICMIN         VARCHAR2(1 BYTE),
  IDSUJPASIVO           INTEGER,
  INDACUERDOMARPOL      VARCHAR2(1 BYTE),
  NUMTONMARPOLI         NUMBER(11,4),
  NUMTONMARPOLV         NUMBER(11,4),
  INDIGICINTERINSULAR   VARCHAR2(1 BYTE),
  ESTINDEXENTA          VARCHAR2(1 BYTE),
  INDRECJORNLAB         VARCHAR2(1 BYTE),
  INDEXENTOLIQ          VARCHAR2(1 BYTE),
  NUMKGGASOIL           NUMBER(9,2),
  NUMKGDIESEL           NUMBER(9,2),
  NUMKGFUELOIL          NUMBER(9,2),
  NUMKGACEITES          NUMBER(9,2),
  CODPUEESCTI           VARCHAR2(5 BYTE),
  ANYOESCTI             INTEGER,
  CODESCTI              INTEGER,
  NUMKGFUELOIL380       NUMBER(9,2),
  DENSIDADFUELOIL       NUMBER(13,6),
  DENSIDADFUELOIL380    NUMBER(13,6),
  DENSIDADGASOIL        NUMBER(13,6),
  DENSIDADDIESEL        NUMBER(13,6),
  DENSIDADACEITE        NUMBER(13,6),
  LITROSFUELOIL         NUMBER(9,2),
  LITROSFUELOIL380      NUMBER(9,2),
  LITROSGASOIL          NUMBER(9,2),
  LITROSDIESEL          NUMBER(9,2),
  LITROSACEITE          NUMBER(9,2),
  INDAVITEXCLUSIVO      VARCHAR2(1 BYTE),
  CODDECLARANTE         INTEGER,
  CODEMPSUMIN           NUMBER(5),
  NUMKGFUELOIL280       NUMBER(9,2),
  DENSIDADFUELOIL280    NUMBER(13,6),
  LITROSFUELOIL280      NUMBER(9,2),
  NUMKGFUELOIL120       NUMBER(9,2),
  DENSIDADFUELOIL120    NUMBER(13,6),
  LITROSFUELOIL120      NUMBER(9,2),
  NUMKGFUELOIL80        NUMBER(9,2),
  DENSIDADFUELOIL80     NUMBER(13,6),
  LITROSFUELOIL80       NUMBER(9,2),
  NUMKGFUELOIL60        NUMBER(9,2),
  DENSIDADFUELOIL60     NUMBER(13,6),
  LITROSFUELOIL60       NUMBER(9,2),
  NUMKGFUELOIL40        NUMBER(9,2),
  DENSIDADFUELOIL40     NUMBER(13,6),
  LITROSFUELOIL40       NUMBER(9,2),
  NUMKGFUELOIL30        NUMBER(9,2),
  DENSIDADFUELOIL30     NUMBER(13,6),
  LITROSFUELOIL30       NUMBER(9,2),
  NUMKGFUELOIL380LS     NUMBER(9,2),
  DENSIDADFUELOIL380LS  NUMBER(13,6),
  LITROSFUELOIL380LS    NUMBER(9,2),
  NUMKGFUELOIL280LS     NUMBER(9,2),
  DENSIDADFUELOIL280LS  NUMBER(13,6),
  LITROSFUELOIL280LS    NUMBER(9,2),
  NUMKGFUELOIL180LS     NUMBER(9,2),
  DENSIDADFUELOIL180LS  NUMBER(13,6),
  LITROSFUELOIL180LS    NUMBER(9,2),
  NUMKGFUELOIL120LS     NUMBER(9,2),
  DENSIDADFUELOIL120LS  NUMBER(13,6),
  LITROSFUELOIL120LS    NUMBER(9,2),
  NUMKGFUELOIL80LS      NUMBER(9,2),
  DENSIDADFUELOIL80LS   NUMBER(13,6),
  LITROSFUELOIL80LS     NUMBER(9,2),
  NUMKGFUELOIL60LS      NUMBER(9,2),
  DENSIDADFUELOIL60LS   NUMBER(13,6),
  LITROSFUELOIL60LS     NUMBER(9,2),
  NUMKGRKM              NUMBER(9,2),
  IDESTIBADOR           INTEGER
)
TABLESPACE INTEGRADOSPLANTILLA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE OPERACION IS 'Operación portuaria asociada a escala';

COMMENT ON COLUMN OPERACION.INDLIQUIDADO IS 'Check para indicar liquidado - No se usa';

COMMENT ON COLUMN OPERACION.GUIDSRV IS 'ID único';

COMMENT ON COLUMN OPERACION.INDYOKTRAS IS 'Defensas Yokohama- No se usa';

COMMENT ON COLUMN OPERACION.INDYOKUSO IS 'Defensas Yokohama- No se usa';

COMMENT ON COLUMN OPERACION.INDYOKCOLOC IS 'Defensas Yokohama- No se usa';

COMMENT ON COLUMN OPERACION.INDRAMMANIPUSU IS 'Rampas - No se usa';

COMMENT ON COLUMN OPERACION.INDRAMMANIPMANTUSU IS 'Rampas - No se usa';

COMMENT ON COLUMN OPERACION.INDNOPOSIBLELEC IS 'Suministros- no se usa';

COMMENT ON COLUMN OPERACION.CODTIPOALQPAS IS 'Tipo alquiler pasarelas- No se usa';

COMMENT ON COLUMN OPERACION.INDNOAPLICMIN IS 'Suministros no aplicar mínimos - No se usa';

COMMENT ON COLUMN OPERACION.IDSUJPASIVO IS 'Sujeto pasivo - No se usa';

COMMENT ON COLUMN OPERACION.INDACUERDOMARPOL IS 'Residuos - No se usa';

COMMENT ON COLUMN OPERACION.NUMTONMARPOLI IS 'Residuos - No se usa';

COMMENT ON COLUMN OPERACION.NUMTONMARPOLV IS 'Residuos - No se usa';

COMMENT ON COLUMN OPERACION.INDIGICINTERINSULAR IS 'IGIC para interinsular- No se usa';

COMMENT ON COLUMN OPERACION.ESTINDEXENTA IS 'Check de exento a efectos estadísticos';

COMMENT ON COLUMN OPERACION.INDRECJORNLAB IS 'Recogida jornada laboral- No se usa';

COMMENT ON COLUMN OPERACION.INDEXENTOLIQ IS 'Check exento liquidación - No se usa';

COMMENT ON COLUMN OPERACION.NUMKGGASOIL IS 'Suministro combustible - No se usa';

COMMENT ON COLUMN OPERACION.NUMKGDIESEL IS 'Suministro combustible - No se usa';

COMMENT ON COLUMN OPERACION.NUMKGFUELOIL IS 'Suministro combustible - No se usa';

COMMENT ON COLUMN OPERACION.NUMKGACEITES IS 'Suministro combustible - No se usa';

COMMENT ON COLUMN OPERACION.CODPUEESCTI IS 'Escala tráfico interior - No se usa';

COMMENT ON COLUMN OPERACION.ANYOESCTI IS 'Escala tráfico interior - No se usa';

COMMENT ON COLUMN OPERACION.CODESCTI IS 'Escala tráfico interior - No se usa';

COMMENT ON COLUMN OPERACION.NUMKGFUELOIL380 IS 'Suministro combustible - No se usa';

COMMENT ON COLUMN OPERACION.DENSIDADFUELOIL IS 'Suministro combustible - No se usa';

COMMENT ON COLUMN OPERACION.DENSIDADFUELOIL380 IS 'Suministro combustible - No se usa';

COMMENT ON COLUMN OPERACION.DENSIDADGASOIL IS 'Suministro combustible - No se usa';

COMMENT ON COLUMN OPERACION.DENSIDADDIESEL IS 'Suministro combustible - No se usa';

COMMENT ON COLUMN OPERACION.DENSIDADACEITE IS 'Suministro combustible - No se usa';

COMMENT ON COLUMN OPERACION.LITROSFUELOIL IS 'Suministro combustible - No se usa';

COMMENT ON COLUMN OPERACION.LITROSFUELOIL380 IS 'Suministro combustible - No se usa';

COMMENT ON COLUMN OPERACION.LITROSGASOIL IS 'Suministro combustible - No se usa';

COMMENT ON COLUMN OPERACION.LITROSDIESEL IS 'Suministro combustible - No se usa';

COMMENT ON COLUMN OPERACION.LITROSACEITE IS 'Suministro combustible - No se usa';

COMMENT ON COLUMN OPERACION.INDAVITEXCLUSIVO IS 'Suministro combustible - No se usa';

COMMENT ON COLUMN OPERACION.CODDECLARANTE IS 'Suministro combustible - No se usa';

COMMENT ON COLUMN OPERACION.CODEMPSUMIN IS 'Suministro combustible - No se usa';

COMMENT ON COLUMN OPERACION.NUMKGFUELOIL280 IS 'Suministro combustible - No se usa';

COMMENT ON COLUMN OPERACION.DENSIDADFUELOIL280 IS 'Suministro combustible - No se usa';

COMMENT ON COLUMN OPERACION.LITROSFUELOIL280 IS 'Suministro combustible - No se usa';

COMMENT ON COLUMN OPERACION.NUMKGFUELOIL120 IS 'Suministro combustible - No se usa';

COMMENT ON COLUMN OPERACION.DENSIDADFUELOIL120 IS 'Suministro combustible - No se usa';

COMMENT ON COLUMN OPERACION.LITROSFUELOIL120 IS 'Suministro combustible - No se usa';

COMMENT ON COLUMN OPERACION.NUMKGFUELOIL80 IS 'Suministro combustible - No se usa';

COMMENT ON COLUMN OPERACION.DENSIDADFUELOIL80 IS 'Suministro combustible - No se usa';

COMMENT ON COLUMN OPERACION.LITROSFUELOIL80 IS 'Suministro combustible - No se usa';

COMMENT ON COLUMN OPERACION.NUMKGFUELOIL60 IS 'Suministro combustible - No se usa';

COMMENT ON COLUMN OPERACION.DENSIDADFUELOIL60 IS 'Suministro combustible - No se usa';

COMMENT ON COLUMN OPERACION.LITROSFUELOIL60 IS 'Suministro combustible - No se usa';

COMMENT ON COLUMN OPERACION.NUMKGFUELOIL40 IS 'Suministro combustible - No se usa';

COMMENT ON COLUMN OPERACION.DENSIDADFUELOIL40 IS 'Suministro combustible - No se usa';

COMMENT ON COLUMN OPERACION.LITROSFUELOIL40 IS 'Suministro combustible - No se usa';

COMMENT ON COLUMN OPERACION.NUMKGFUELOIL30 IS 'Suministro combustible - No se usa';

COMMENT ON COLUMN OPERACION.DENSIDADFUELOIL30 IS 'Suministro combustible - No se usa';

COMMENT ON COLUMN OPERACION.LITROSFUELOIL30 IS 'Suministro combustible - No se usa';

COMMENT ON COLUMN OPERACION.NUMKGFUELOIL380LS IS 'Suministro combustible - No se usa';

COMMENT ON COLUMN OPERACION.DENSIDADFUELOIL380LS IS 'Suministro combustible - No se usa';

COMMENT ON COLUMN OPERACION.LITROSFUELOIL380LS IS 'Suministro combustible - No se usa';

COMMENT ON COLUMN OPERACION.NUMKGFUELOIL280LS IS 'Suministro combustible - No se usa';

COMMENT ON COLUMN OPERACION.DENSIDADFUELOIL280LS IS 'Suministro combustible - No se usa';

COMMENT ON COLUMN OPERACION.LITROSFUELOIL280LS IS 'Suministro combustible - No se usa';

COMMENT ON COLUMN OPERACION.NUMKGFUELOIL180LS IS 'Suministro combustible - No se usa';

COMMENT ON COLUMN OPERACION.DENSIDADFUELOIL180LS IS 'Suministro combustible - No se usa';

COMMENT ON COLUMN OPERACION.LITROSFUELOIL180LS IS 'Suministro combustible - No se usa';

COMMENT ON COLUMN OPERACION.NUMKGFUELOIL120LS IS 'Suministro combustible - No se usa';

COMMENT ON COLUMN OPERACION.DENSIDADFUELOIL120LS IS 'Suministro combustible - No se usa';

COMMENT ON COLUMN OPERACION.LITROSFUELOIL120LS IS 'Suministro combustible - No se usa';

COMMENT ON COLUMN OPERACION.NUMKGFUELOIL80LS IS 'Suministro combustible - No se usa';

COMMENT ON COLUMN OPERACION.DENSIDADFUELOIL80LS IS 'Suministro combustible - No se usa';

COMMENT ON COLUMN OPERACION.LITROSFUELOIL80LS IS 'Suministro combustible - No se usa';

COMMENT ON COLUMN OPERACION.NUMKGFUELOIL60LS IS 'Suministro combustible - No se usa';

COMMENT ON COLUMN OPERACION.DENSIDADFUELOIL60LS IS 'Suministro combustible - No se usa';

COMMENT ON COLUMN OPERACION.LITROSFUELOIL60LS IS 'Suministro combustible - No se usa';

COMMENT ON COLUMN OPERACION.NUMKGRKM IS 'Suministro combustible - No se usa';

COMMENT ON COLUMN OPERACION.IDESTIBADOR IS 'Estibador';

COMMENT ON COLUMN OPERACION.CODPUE IS 'Código puerto';

COMMENT ON COLUMN OPERACION.ANYO IS 'Año Escala';

COMMENT ON COLUMN OPERACION.CODESCALA IS 'Código Escala';

COMMENT ON COLUMN OPERACION.CODESTADIA IS 'Código Atraque';

COMMENT ON COLUMN OPERACION.CODOPERACION IS 'Código Operación';

COMMENT ON COLUMN OPERACION.INDMANUAL IS 'Check para indicar que ha sido creada manualmente y no vía EDI';

COMMENT ON COLUMN OPERACION.CODTIPOPE IS 'Tipo Operación';

COMMENT ON COLUMN OPERACION.CODTIPCARGA IS 'Tipo Carga';

COMMENT ON COLUMN OPERACION.CODTIPUNIDAD IS 'Tipo Unidad';

COMMENT ON COLUMN OPERACION.LUGAR IS 'Lugar operación';

COMMENT ON COLUMN OPERACION.PESOMAXPORUNIDAD IS 'Peso máximo por unidad';

COMMENT ON COLUMN OPERACION.FECINI IS 'Fecha inicio operación';

COMMENT ON COLUMN OPERACION.FECFIN IS 'Fecha fin operación';

COMMENT ON COLUMN OPERACION.TERMINAL IS 'Terminal';

COMMENT ON COLUMN OPERACION.CODTIPMEDIOMANIP IS 'Tipo medio manipulación';

COMMENT ON COLUMN OPERACION.NUMMEDIOS IS 'Número de medios';

COMMENT ON COLUMN OPERACION.INDPROPPUERTO IS 'Check para indicar que son propiedad del puerto los medios';

COMMENT ON COLUMN OPERACION.OBSERVACIONES IS 'Observaciones';

COMMENT ON COLUMN OPERACION.CODOPERACIONDUE IS 'Código DUE operación';

COMMENT ON COLUMN OPERACION.NUMUNIDADES IS 'Número unidades';

COMMENT ON COLUMN OPERACION.CODGRUA IS 'Código Grúa - No se usa';

COMMENT ON COLUMN OPERACION.CODPUECONTADOR IS 'Puerto Contador- No se usa';

COMMENT ON COLUMN OPERACION.NUMCONTADOR IS 'Número Contador- No se usa';

COMMENT ON COLUMN OPERACION.LECINICIAL IS 'Lectura inicial - No se usa';

COMMENT ON COLUMN OPERACION.LECFINAL IS 'Lectura final- No se usa';

COMMENT ON COLUMN OPERACION.CODTIPODESECHO IS 'Tipo desecho- No se usa';

COMMENT ON COLUMN OPERACION.INDJUSTIFENTDESECHO IS 'Check justificante desecho- No se usa';

COMMENT ON COLUMN OPERACION.CODMODSUMINCOMB IS 'Modalidad suministro- No se usa';

COMMENT ON COLUMN OPERACION.CODCOMBSUMINCOMB IS 'Suministro - No se usa';

COMMENT ON COLUMN OPERACION.CODBARCAZA IS 'Suministro - No se usa';

COMMENT ON COLUMN OPERACION.CODTIPSUMINAGUA IS 'Suministro - No se usa';

COMMENT ON COLUMN OPERACION.CODPASARELA IS 'Pasarela- No se usa';

COMMENT ON COLUMN OPERACION.FECSOLICITUD IS 'Fecha solicitud operación';

COMMENT ON COLUMN OPERACION.FECALTA IS 'Fecha alta';

COMMENT ON COLUMN OPERACION.FECMODIF IS 'Fecha modificación';

COMMENT ON COLUMN OPERACION.USRALTA IS 'Usuario alta';

COMMENT ON COLUMN OPERACION.USRMODIF IS 'Usuario modificación';

COMMENT ON COLUMN OPERACION.OBSMEDIOSMANIP IS 'Observaciones medios manipulación';


--
-- OPER_EVENT_AIS  (Table) 
--
CREATE TABLE OPER_EVENT_AIS
(
  PORTAUT     VARCHAR2(2 BYTE)                  NOT NULL,
  IDEVENTAIS  VARCHAR2(50 BYTE),
  EVENTNAME   VARCHAR2(100 BYTE)
)
TABLESPACE INTEGRADOSPLANTILLA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON COLUMN OPER_EVENT_AIS.PORTAUT IS 'Autoridad portuaria';

COMMENT ON COLUMN OPER_EVENT_AIS.IDEVENTAIS IS 'Identificador tipo de evento AIS';

COMMENT ON COLUMN OPER_EVENT_AIS.EVENTNAME IS 'Nombre descriptivo del tipo de evento';


--
-- OPER_PARAM_GET_CALL  (Table) 
--
CREATE TABLE OPER_PARAM_GET_CALL
(
  PORTAUT        VARCHAR2(2 BYTE)               NOT NULL,
  PORTCOD        VARCHAR2(5 BYTE)               NOT NULL,
  EVENTTYPE      VARCHAR2(50 BYTE)              NOT NULL,
  CODCALLSTATUS  VARCHAR2(2 BYTE)               NOT NULL
)
TABLESPACE INTEGRADOSPLANTILLA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON COLUMN OPER_PARAM_GET_CALL.PORTAUT IS 'Autoridad portuaria';

COMMENT ON COLUMN OPER_PARAM_GET_CALL.PORTCOD IS 'Código del puerto';

COMMENT ON COLUMN OPER_PARAM_GET_CALL.EVENTTYPE IS 'Identificador tipo de evento AIS';

COMMENT ON COLUMN OPER_PARAM_GET_CALL.CODCALLSTATUS IS 'Código del estado de la escala';


--
-- OPER_PARAM_INTEGRATION  (Table) 
--
CREATE TABLE OPER_PARAM_INTEGRATION
(
  PORTAUT      VARCHAR2(2 BYTE)                 NOT NULL,
  PORTCOD      VARCHAR2(5 BYTE)                 NOT NULL,
  CODE         VARCHAR2(30 BYTE)                NOT NULL,
  DESCRIPTION  VARCHAR2(300 BYTE)               NOT NULL,
  VALUE        VARCHAR2(300 BYTE)               NOT NULL
)
TABLESPACE INTEGRADOSPLANTILLA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON COLUMN OPER_PARAM_INTEGRATION.PORTAUT IS 'Autoridad portuaria';

COMMENT ON COLUMN OPER_PARAM_INTEGRATION.PORTCOD IS 'Código del puerto';

COMMENT ON COLUMN OPER_PARAM_INTEGRATION.CODE IS 'Código del parámetro de integración';

COMMENT ON COLUMN OPER_PARAM_INTEGRATION.DESCRIPTION IS 'Descripción del parámetro de integración';

COMMENT ON COLUMN OPER_PARAM_INTEGRATION.VALUE IS 'Valor del parámetro de integración';


--
-- IX_NOVEDADRODANTE1  (Index) 
--
CREATE INDEX IX_NOVEDADRODANTE1 ON NOVEDAD_RODANTE
(CODPUE)
LOGGING
TABLESPACE INTEGRADOSPLANTILLA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


--
-- IX_OPERACION1  (Index) 
--
CREATE INDEX IX_OPERACION1 ON OPERACION
(CODPUE, ANYO, CODESCALA, CODESTADIA)
LOGGING
TABLESPACE INTEGRADOSPLANTILLA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


--
-- IX_OPERACION10  (Index) 
--
CREATE INDEX IX_OPERACION10 ON OPERACION
(CODTIPMEDIOMANIP)
LOGGING
TABLESPACE INTEGRADOSPLANTILLA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


--
-- IX_OPERACION11  (Index) 
--
CREATE INDEX IX_OPERACION11 ON OPERACION
(CODGRUA)
LOGGING
TABLESPACE INTEGRADOSPLANTILLA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


--
-- IX_OPERACION12  (Index) 
--
CREATE INDEX IX_OPERACION12 ON OPERACION
(CODTIPODESECHO)
LOGGING
TABLESPACE INTEGRADOSPLANTILLA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


--
-- IX_OPERACION13  (Index) 
--
CREATE INDEX IX_OPERACION13 ON OPERACION
(CODTIPOALQPAS)
LOGGING
TABLESPACE INTEGRADOSPLANTILLA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


--
-- IX_OPERACION14  (Index) 
--
CREATE INDEX IX_OPERACION14 ON OPERACION
(IDSUJPASIVO)
LOGGING
TABLESPACE INTEGRADOSPLANTILLA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


--
-- IX_OPERACION16  (Index) 
--
CREATE INDEX IX_OPERACION16 ON OPERACION
(CODPUECONTADOR, NUMCONTADOR)
LOGGING
TABLESPACE INTEGRADOSPLANTILLA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


--
-- IX_OPERACION17  (Index) 
--
CREATE INDEX IX_OPERACION17 ON OPERACION
(CODPUEESCTI, ANYOESCTI, CODESCTI)
LOGGING
TABLESPACE INTEGRADOSPLANTILLA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


--
-- IX_OPERACION18  (Index) 
--
CREATE INDEX IX_OPERACION18 ON OPERACION
(CODDECLARANTE)
LOGGING
TABLESPACE INTEGRADOSPLANTILLA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


--
-- IX_OPERACION19  (Index) 
--
CREATE INDEX IX_OPERACION19 ON OPERACION
(CODEMPSUMIN)
LOGGING
TABLESPACE INTEGRADOSPLANTILLA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


--
-- IX_OPERACION2  (Index) 
--
CREATE INDEX IX_OPERACION2 ON OPERACION
(CODMODSUMINCOMB)
LOGGING
TABLESPACE INTEGRADOSPLANTILLA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


--
-- IX_OPERACION20  (Index) 
--
CREATE INDEX IX_OPERACION20 ON OPERACION
(IDESTIBADOR)
LOGGING
TABLESPACE INTEGRADOSPLANTILLA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


--
-- IX_OPERACION3  (Index) 
--
CREATE INDEX IX_OPERACION3 ON OPERACION
(CODCOMBSUMINCOMB)
LOGGING
TABLESPACE INTEGRADOSPLANTILLA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


--
-- IX_OPERACION4  (Index) 
--
CREATE INDEX IX_OPERACION4 ON OPERACION
(CODBARCAZA)
LOGGING
TABLESPACE INTEGRADOSPLANTILLA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


--
-- IX_OPERACION5  (Index) 
--
CREATE INDEX IX_OPERACION5 ON OPERACION
(CODTIPSUMINAGUA)
LOGGING
TABLESPACE INTEGRADOSPLANTILLA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


--
-- IX_OPERACION6  (Index) 
--
CREATE INDEX IX_OPERACION6 ON OPERACION
(CODPASARELA)
LOGGING
TABLESPACE INTEGRADOSPLANTILLA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


--
-- IX_OPERACION7  (Index) 
--
CREATE INDEX IX_OPERACION7 ON OPERACION
(CODTIPOPE)
LOGGING
TABLESPACE INTEGRADOSPLANTILLA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


--
-- IX_OPERACION8  (Index) 
--
CREATE INDEX IX_OPERACION8 ON OPERACION
(CODTIPCARGA)
LOGGING
TABLESPACE INTEGRADOSPLANTILLA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


--
-- IX_OPERACION9  (Index) 
--
CREATE INDEX IX_OPERACION9 ON OPERACION
(CODTIPUNIDAD)
LOGGING
TABLESPACE INTEGRADOSPLANTILLA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


--
-- NOVEDAD_RODANTE_PK  (Index) 
--
CREATE UNIQUE INDEX NOVEDAD_RODANTE_PK ON NOVEDAD_RODANTE
(CODIGO)
LOGGING
TABLESPACE INTEGRADOSPLANTILLA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


--
-- OCUPSUP_EXENHORAS_PK  (Index) 
--
CREATE UNIQUE INDEX OCUPSUP_EXENHORAS_PK ON OCUPSUP_EXENHORAS
(CODIGO)
LOGGING
TABLESPACE INTEGRADOSPLANTILLA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


--
-- OCUPSUP_TIPOALM_PK  (Index) 
--
CREATE UNIQUE INDEX OCUPSUP_TIPOALM_PK ON OCUPSUP_TIPOALM
(CODIGO)
LOGGING
TABLESPACE INTEGRADOSPLANTILLA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


--
-- OCUPSUP_TIPOEMB_PK  (Index) 
--
CREATE UNIQUE INDEX OCUPSUP_TIPOEMB_PK ON OCUPSUP_TIPOEMB
(CODIGO)
LOGGING
TABLESPACE INTEGRADOSPLANTILLA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


--
-- OCUPSUP_TIPOOPE_PK  (Index) 
--
CREATE UNIQUE INDEX OCUPSUP_TIPOOPE_PK ON OCUPSUP_TIPOOPE
(CODIGO)
LOGGING
TABLESPACE INTEGRADOSPLANTILLA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


--
-- OCUPSUP_TIPORODANTE_PK  (Index) 
--
CREATE UNIQUE INDEX OCUPSUP_TIPORODANTE_PK ON OCUPSUP_TIPORODANTE
(CODIGO)
LOGGING
TABLESPACE INTEGRADOSPLANTILLA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


--
-- PK_OPERACION  (Index) 
--
CREATE UNIQUE INDEX PK_OPERACION ON OPERACION
(CODPUE, ANYO, CODESCALA, CODESTADIA, CODOPERACION)
LOGGING
TABLESPACE INTEGRADOSPLANTILLA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


--
-- PK_OPER_EVENT_AIS  (Index) 
--
CREATE UNIQUE INDEX PK_OPER_EVENT_AIS ON OPER_EVENT_AIS
(PORTAUT, IDEVENTAIS)
LOGGING
TABLESPACE INTEGRADOSPLANTILLA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


--
-- PK_OPER_PARAM_GET_CALL  (Index) 
--
CREATE UNIQUE INDEX PK_OPER_PARAM_GET_CALL ON OPER_PARAM_GET_CALL
(PORTAUT, PORTCOD, EVENTTYPE, CODCALLSTATUS)
LOGGING
TABLESPACE INTEGRADOSPLANTILLA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


--
-- PK_OPER_PARAM_INTEGRACION  (Index) 
--
CREATE UNIQUE INDEX PK_OPER_PARAM_INTEGRACION ON OPER_PARAM_INTEGRATION
(PORTAUT, PORTCOD, CODE)
LOGGING
TABLESPACE INTEGRADOSPLANTILLA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


--
-- OPERACION_SRV  (Trigger) 
--
CREATE OR REPLACE TRIGGER "OPERACION_SRV" 
BEFORE INSERT
ON OPERACION
REFERENCING NEW AS New OLD AS Old
FOR EACH ROW
DECLARE
BEGIN
   :NEW.GUIDSRV := SYS_GUID();

   EXCEPTION
     WHEN OTHERS THEN
       -- Consider logging the error and then re-raise
       RAISE;
END ;
/


--
-- OCUPSUPBUQUE  (Table) 
--
CREATE TABLE OCUPSUPBUQUE
(
  CODPUE                   VARCHAR2(5 BYTE),
  ANYO                     INTEGER,
  CODSER                   INTEGER,
  CODPUEESC                VARCHAR2(5 BYTE),
  ANYOESC                  INTEGER,
  CODESC                   INTEGER,
  CODESTADIA               INTEGER,
  FECINI                   DATE,
  FECFIN                   DATE,
  CODTIPOEMBARQUE          VARCHAR2(1 BYTE),
  CODTIPOOPERACION         VARCHAR2(1 BYTE),
  INDRORO                  VARCHAR2(1 BYTE),
  INDFINALIZADO            VARCHAR2(1 BYTE),
  FECULTLIQ                DATE,
  GUIDSRV                  VARCHAR2(40 BYTE),
  OBSERVACIONES            VARCHAR2(300 BYTE),
  USRALTA                  VARCHAR2(20 BYTE),
  USRMODIF                 VARCHAR2(20 BYTE),
  FECALTA                  DATE,
  FECMODIF                 DATE,
  INDNOMERCANCIA           VARCHAR2(1 BYTE),
  IDCLIENTE                INTEGER,
  INDUNALIQ                VARCHAR2(1 BYTE)     DEFAULT 0                     NOT NULL,
  CODPUEZONA               VARCHAR2(5 BYTE),
  CODZONA                  VARCHAR2(5 BYTE),
  INDLIQUIDADO             VARCHAR2(1 BYTE),
  INDEXENTOLIQ             VARCHAR2(1 BYTE),
  INDTABLET                VARCHAR2(1 BYTE),
  INDSINELEMRODMAESTRO     VARCHAR2(1 BYTE),
  MATRICULATABLET          VARCHAR2(100 BYTE),
  FECMEDIDATABLET          DATE,
  FECCAPTMEDIDATABLET      DATE,
  CODTIPOELEMRODTABLET     NUMBER(5),
  CODTIPOIVA               VARCHAR2(1 BYTE)     NOT NULL,
  CODTIPOALM               VARCHAR2(2 BYTE),
  CODEXENHORAS             VARCHAR2(2 BYTE)     NOT NULL,
  MOTEXENTOLIQ             VARCHAR2(300 BYTE),
  FECPROGPOR2              DATE,
  FECPROGPOR4              DATE,
  FECPROGPOR8              DATE,
  INDNOAPLICPROGRESIVIDAD  VARCHAR2(1 BYTE),
  OBSERVACIONESFACT        VARCHAR2(200 BYTE)
)
TABLESPACE INTEGRADOSPLANTILLA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE OCUPSUPBUQUE IS 'Servicio de ocupación zona tránsito-maniobra';

COMMENT ON COLUMN OCUPSUPBUQUE.CODPUE IS 'Código puerto';

COMMENT ON COLUMN OCUPSUPBUQUE.ANYO IS 'Año Servicio';

COMMENT ON COLUMN OCUPSUPBUQUE.CODSER IS 'Código Servicio';

COMMENT ON COLUMN OCUPSUPBUQUE.CODPUEESC IS 'Puerto Escala asociada';

COMMENT ON COLUMN OCUPSUPBUQUE.ANYOESC IS 'Año Escala asociada';

COMMENT ON COLUMN OCUPSUPBUQUE.CODESC IS 'Código Escala asociada';

COMMENT ON COLUMN OCUPSUPBUQUE.CODESTADIA IS 'Código Atraque asociado';

COMMENT ON COLUMN OCUPSUPBUQUE.FECINI IS 'Fecha inicio servicio';

COMMENT ON COLUMN OCUPSUPBUQUE.FECFIN IS 'Fecha fin servicio';

COMMENT ON COLUMN OCUPSUPBUQUE.CODTIPOEMBARQUE IS 'Tipo embarque';

COMMENT ON COLUMN OCUPSUPBUQUE.CODTIPOOPERACION IS 'Tipo Operación';

COMMENT ON COLUMN OCUPSUPBUQUE.INDRORO IS 'Check para indicar que es RO-RO';

COMMENT ON COLUMN OCUPSUPBUQUE.INDFINALIZADO IS 'Check para indicar que está finalizado';

COMMENT ON COLUMN OCUPSUPBUQUE.FECULTLIQ IS 'Última Fecha Liquidada';

COMMENT ON COLUMN OCUPSUPBUQUE.GUIDSRV IS 'ID único';

COMMENT ON COLUMN OCUPSUPBUQUE.OBSERVACIONES IS 'Observaciones';

COMMENT ON COLUMN OCUPSUPBUQUE.USRALTA IS 'Usuario alta';

COMMENT ON COLUMN OCUPSUPBUQUE.USRMODIF IS 'Usuario modificación';

COMMENT ON COLUMN OCUPSUPBUQUE.FECALTA IS 'Fecha alta';

COMMENT ON COLUMN OCUPSUPBUQUE.FECMODIF IS 'Fecha modificación';

COMMENT ON COLUMN OCUPSUPBUQUE.INDNOMERCANCIA IS 'Check para indicar que no es de mercancías';

COMMENT ON COLUMN OCUPSUPBUQUE.IDCLIENTE IS 'Sujeto pasivo';

COMMENT ON COLUMN OCUPSUPBUQUE.INDUNALIQ IS 'Check para indicar que solo tendrá una liquidación';

COMMENT ON COLUMN OCUPSUPBUQUE.CODPUEZONA IS 'Puerto zona asociada al servicio';

COMMENT ON COLUMN OCUPSUPBUQUE.CODZONA IS 'Código zona asociada al servicio';

COMMENT ON COLUMN OCUPSUPBUQUE.INDLIQUIDADO IS 'Check para indicar que está liquidado';

COMMENT ON COLUMN OCUPSUPBUQUE.INDEXENTOLIQ IS 'Check para indicar que está exento liquidación';

COMMENT ON COLUMN OCUPSUPBUQUE.INDTABLET IS 'Check para indicar que el servicio ha sido creado vía aplicación tablet';

COMMENT ON COLUMN OCUPSUPBUQUE.INDSINELEMRODMAESTRO IS 'Tablet- Check para indicar que matrícula rodante no está en maestro';

COMMENT ON COLUMN OCUPSUPBUQUE.MATRICULATABLET IS 'Tablet- Matrícula elemento';

COMMENT ON COLUMN OCUPSUPBUQUE.FECMEDIDATABLET IS 'Tablet - Fecha medida';

COMMENT ON COLUMN OCUPSUPBUQUE.FECCAPTMEDIDATABLET IS 'Tablet- Fecha real captación';

COMMENT ON COLUMN OCUPSUPBUQUE.CODTIPOELEMRODTABLET IS 'Tablet - Tipo elemento rodante';

COMMENT ON COLUMN OCUPSUPBUQUE.CODTIPOIVA IS 'Tipo IVA';

COMMENT ON COLUMN OCUPSUPBUQUE.CODTIPOALM IS 'Modalidad almacenaje';

COMMENT ON COLUMN OCUPSUPBUQUE.CODEXENHORAS IS 'Exención horas';

COMMENT ON COLUMN OCUPSUPBUQUE.MOTEXENTOLIQ IS 'Motivo exención liquidación';

COMMENT ON COLUMN OCUPSUPBUQUE.FECPROGPOR2 IS 'Fecha progresividad por 2';

COMMENT ON COLUMN OCUPSUPBUQUE.FECPROGPOR4 IS 'Fecha progresividad por 4';

COMMENT ON COLUMN OCUPSUPBUQUE.FECPROGPOR8 IS 'Fecha progresividad por 8';

COMMENT ON COLUMN OCUPSUPBUQUE.INDNOAPLICPROGRESIVIDAD IS 'Indicador de no aplicar progresividad';


--
-- OCUPSUPBUQUE_LECTURA  (Table) 
--
CREATE TABLE OCUPSUPBUQUE_LECTURA
(
  CODPUE         VARCHAR2(5 BYTE),
  ANYO           INTEGER,
  CODSER         INTEGER,
  FECLEC         DATE,
  OBSERVACIONES  VARCHAR2(300 BYTE),
  USRALTA        VARCHAR2(20 BYTE),
  USRMODIF       VARCHAR2(20 BYTE),
  FECALTA        DATE,
  FECMODIF       DATE,
  CODCAMION1     NUMBER(9),
  CODCAMION2     NUMBER(9),
  CODCAMION3     NUMBER(9),
  CODCAMION4     NUMBER(9),
  CODCAMION5     NUMBER(9),
  CODCAMION6     NUMBER(9),
  CODCAMION7     NUMBER(9),
  CODCAMION8     NUMBER(9),
  CODCAMION9     NUMBER(9),
  CODCAMION10    NUMBER(9),
  CODCAMION11    NUMBER(9),
  CODCAMION12    NUMBER(9),
  CODCAMION13    NUMBER(9),
  CODCAMION14    NUMBER(9),
  CODCAMION15    NUMBER(9),
  CODCAMION16    NUMBER(9),
  CODCAMION17    NUMBER(9),
  CODCAMION18    NUMBER(9),
  CODCAMION19    NUMBER(9),
  CODCAMION20    NUMBER(9),
  NUMM2          NUMBER(11,2)
)
TABLESPACE INTEGRADOSPLANTILLA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE OCUPSUPBUQUE_LECTURA IS 'Servicio de ocupación superficie- Medidas asociadas';

COMMENT ON COLUMN OCUPSUPBUQUE_LECTURA.FECLEC IS 'Fecha medida';

COMMENT ON COLUMN OCUPSUPBUQUE_LECTURA.OBSERVACIONES IS 'Observaciones';

COMMENT ON COLUMN OCUPSUPBUQUE_LECTURA.USRALTA IS 'Usuario alta';

COMMENT ON COLUMN OCUPSUPBUQUE_LECTURA.USRMODIF IS 'Usuario modificación';

COMMENT ON COLUMN OCUPSUPBUQUE_LECTURA.FECALTA IS 'Fecha alta';

COMMENT ON COLUMN OCUPSUPBUQUE_LECTURA.FECMODIF IS 'Fecha modificación';

COMMENT ON COLUMN OCUPSUPBUQUE_LECTURA.CODCAMION1 IS 'Elemento rodante camión - No se usa';

COMMENT ON COLUMN OCUPSUPBUQUE_LECTURA.CODCAMION2 IS 'Elemento rodante camión - No se usa';

COMMENT ON COLUMN OCUPSUPBUQUE_LECTURA.CODCAMION3 IS 'Elemento rodante camión - No se usa';

COMMENT ON COLUMN OCUPSUPBUQUE_LECTURA.CODCAMION4 IS 'Elemento rodante camión - No se usa';

COMMENT ON COLUMN OCUPSUPBUQUE_LECTURA.CODCAMION5 IS 'Elemento rodante camión - No se usa';

COMMENT ON COLUMN OCUPSUPBUQUE_LECTURA.CODCAMION6 IS 'Elemento rodante camión - No se usa';

COMMENT ON COLUMN OCUPSUPBUQUE_LECTURA.CODCAMION7 IS 'Elemento rodante camión - No se usa';

COMMENT ON COLUMN OCUPSUPBUQUE_LECTURA.CODCAMION8 IS 'Elemento rodante camión - No se usa';

COMMENT ON COLUMN OCUPSUPBUQUE_LECTURA.CODCAMION9 IS 'Elemento rodante camión - No se usa';

COMMENT ON COLUMN OCUPSUPBUQUE_LECTURA.CODCAMION10 IS 'Elemento rodante camión - No se usa';

COMMENT ON COLUMN OCUPSUPBUQUE_LECTURA.CODCAMION11 IS 'Elemento rodante camión - No se usa';

COMMENT ON COLUMN OCUPSUPBUQUE_LECTURA.CODCAMION12 IS 'Elemento rodante camión - No se usa';

COMMENT ON COLUMN OCUPSUPBUQUE_LECTURA.CODCAMION13 IS 'Elemento rodante camión - No se usa';

COMMENT ON COLUMN OCUPSUPBUQUE_LECTURA.CODCAMION14 IS 'Elemento rodante camión - No se usa';

COMMENT ON COLUMN OCUPSUPBUQUE_LECTURA.CODCAMION15 IS 'Elemento rodante camión - No se usa';

COMMENT ON COLUMN OCUPSUPBUQUE_LECTURA.CODCAMION16 IS 'Elemento rodante camión - No se usa';

COMMENT ON COLUMN OCUPSUPBUQUE_LECTURA.CODCAMION17 IS 'Elemento rodante camión - No se usa';

COMMENT ON COLUMN OCUPSUPBUQUE_LECTURA.CODCAMION18 IS 'Elemento rodante camión - No se usa';

COMMENT ON COLUMN OCUPSUPBUQUE_LECTURA.CODCAMION19 IS 'Elemento rodante camión - No se usa';

COMMENT ON COLUMN OCUPSUPBUQUE_LECTURA.CODCAMION20 IS 'Elemento rodante camión - No se usa';

COMMENT ON COLUMN OCUPSUPBUQUE_LECTURA.NUMM2 IS 'Número m2 medida';

COMMENT ON COLUMN OCUPSUPBUQUE_LECTURA.CODPUE IS 'Código puerto';

COMMENT ON COLUMN OCUPSUPBUQUE_LECTURA.ANYO IS 'Año Servicio';

COMMENT ON COLUMN OCUPSUPBUQUE_LECTURA.CODSER IS 'Código servicio';


--
-- OCUPSUP_RODANTE  (Table) 
--
CREATE TABLE OCUPSUP_RODANTE
(
  CODPUE             VARCHAR2(5 BYTE)           NOT NULL,
  ANYO               INTEGER                    NOT NULL,
  CODSER             INTEGER                    NOT NULL,
  FECINI             DATE                       NOT NULL,
  FECFIN             DATE                       NOT NULL,
  CODTIPOIVA         VARCHAR2(1 BYTE)           NOT NULL,
  IDCLIENTE          INTEGER                    NOT NULL,
  CODPUEZONA         VARCHAR2(5 BYTE)           NOT NULL,
  CODZONA            VARCHAR2(5 BYTE)           NOT NULL,
  CODTIPORODANTE     VARCHAR2(3 BYTE)           NOT NULL,
  UNIDADES           INTEGER                    NOT NULL,
  NUMDIAS            NUMBER(9,6),
  INDBONIF           VARCHAR2(1 BYTE),
  CODBONIFICACION    INTEGER,
  PORCBONIFICACION   NUMBER(7,4),
  INDLIQUIDADO       VARCHAR2(1 BYTE),
  INDEXENTOLIQ       VARCHAR2(1 BYTE),
  MOTEXENTOLIQ       VARCHAR2(300 BYTE),
  OBSERVACIONES      VARCHAR2(500 BYTE),
  GUIDSRV            VARCHAR2(40 BYTE),
  USRALTA            VARCHAR2(20 BYTE),
  USRMODIF           VARCHAR2(20 BYTE),
  FECALTA            DATE,
  FECMODIF           DATE,
  OBSERVACIONESFACT  VARCHAR2(200 BYTE)
)
TABLESPACE INTEGRADOSPLANTILLA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE OCUPSUP_RODANTE IS 'Ocupación Superficie Rodantes - Vigo';

COMMENT ON COLUMN OCUPSUP_RODANTE.CODPUE IS 'Código puerto';

COMMENT ON COLUMN OCUPSUP_RODANTE.ANYO IS 'Año Servicio';

COMMENT ON COLUMN OCUPSUP_RODANTE.CODSER IS 'Código Servicio';

COMMENT ON COLUMN OCUPSUP_RODANTE.FECINI IS 'Fecha inicio servicio';

COMMENT ON COLUMN OCUPSUP_RODANTE.FECFIN IS 'Fecha fin servicio';

COMMENT ON COLUMN OCUPSUP_RODANTE.CODTIPOIVA IS 'Tipo IVA';

COMMENT ON COLUMN OCUPSUP_RODANTE.IDCLIENTE IS 'Sujeto pasivo';

COMMENT ON COLUMN OCUPSUP_RODANTE.CODPUEZONA IS 'Puerto Zona';

COMMENT ON COLUMN OCUPSUP_RODANTE.CODZONA IS 'Código Zona';

COMMENT ON COLUMN OCUPSUP_RODANTE.CODTIPORODANTE IS 'Tipo rodante';

COMMENT ON COLUMN OCUPSUP_RODANTE.UNIDADES IS 'Unidades';

COMMENT ON COLUMN OCUPSUP_RODANTE.NUMDIAS IS 'Días';

COMMENT ON COLUMN OCUPSUP_RODANTE.INDBONIF IS 'Check para indicar que aplica bonificación';

COMMENT ON COLUMN OCUPSUP_RODANTE.CODBONIFICACION IS 'Bonificación';

COMMENT ON COLUMN OCUPSUP_RODANTE.PORCBONIFICACION IS 'Porcentaje bonificación';

COMMENT ON COLUMN OCUPSUP_RODANTE.INDLIQUIDADO IS 'Check para indicar que está liquidado';

COMMENT ON COLUMN OCUPSUP_RODANTE.INDEXENTOLIQ IS 'Check para indicar que está exento liquidación';

COMMENT ON COLUMN OCUPSUP_RODANTE.MOTEXENTOLIQ IS 'Motivo exento liquidación';

COMMENT ON COLUMN OCUPSUP_RODANTE.OBSERVACIONES IS 'Observaciones';

COMMENT ON COLUMN OCUPSUP_RODANTE.GUIDSRV IS 'ID único';

COMMENT ON COLUMN OCUPSUP_RODANTE.USRALTA IS 'Usuario alta';

COMMENT ON COLUMN OCUPSUP_RODANTE.USRMODIF IS 'Usuario modificación';

COMMENT ON COLUMN OCUPSUP_RODANTE.FECALTA IS 'Fecha alta';

COMMENT ON COLUMN OCUPSUP_RODANTE.FECMODIF IS 'Fecha modificación';


--
-- IX_OCUPSUPBUQUE1  (Index) 
--
CREATE INDEX IX_OCUPSUPBUQUE1 ON OCUPSUPBUQUE
(CODPUEESC, ANYOESC, CODESC, CODESTADIA)
LOGGING
TABLESPACE INTEGRADOSPLANTILLA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


--
-- IX_OCUPSUPBUQUE2  (Index) 
--
CREATE INDEX IX_OCUPSUPBUQUE2 ON OCUPSUPBUQUE
(IDCLIENTE)
LOGGING
TABLESPACE INTEGRADOSPLANTILLA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


--
-- IX_OCUPSUPBUQUE24  (Index) 
--
CREATE INDEX IX_OCUPSUPBUQUE24 ON OCUPSUPBUQUE
(CODTIPOEMBARQUE)
LOGGING
TABLESPACE INTEGRADOSPLANTILLA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


--
-- IX_OCUPSUPBUQUE25  (Index) 
--
CREATE INDEX IX_OCUPSUPBUQUE25 ON OCUPSUPBUQUE
(CODTIPOOPERACION)
LOGGING
TABLESPACE INTEGRADOSPLANTILLA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


--
-- IX_OCUPSUPBUQUE26  (Index) 
--
CREATE INDEX IX_OCUPSUPBUQUE26 ON OCUPSUPBUQUE
(CODTIPOELEMRODTABLET)
LOGGING
TABLESPACE INTEGRADOSPLANTILLA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


--
-- IX_OCUPSUPBUQUE27  (Index) 
--
CREATE INDEX IX_OCUPSUPBUQUE27 ON OCUPSUPBUQUE
(CODTIPOIVA)
LOGGING
TABLESPACE INTEGRADOSPLANTILLA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


--
-- IX_OCUPSUPBUQUE3  (Index) 
--
CREATE INDEX IX_OCUPSUPBUQUE3 ON OCUPSUPBUQUE
(CODPUEZONA, CODZONA)
LOGGING
TABLESPACE INTEGRADOSPLANTILLA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


--
-- IX_OCUPSUPBUQUELECTURA1  (Index) 
--
CREATE INDEX IX_OCUPSUPBUQUELECTURA1 ON OCUPSUPBUQUE_LECTURA
(CODPUE, ANYO, CODSER)
LOGGING
TABLESPACE INTEGRADOSPLANTILLA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


--
-- IX_OCUPSUPBUQUELECTURA10  (Index) 
--
CREATE INDEX IX_OCUPSUPBUQUELECTURA10 ON OCUPSUPBUQUE_LECTURA
(CODCAMION9)
LOGGING
TABLESPACE INTEGRADOSPLANTILLA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


--
-- IX_OCUPSUPBUQUELECTURA11  (Index) 
--
CREATE INDEX IX_OCUPSUPBUQUELECTURA11 ON OCUPSUPBUQUE_LECTURA
(CODCAMION10)
LOGGING
TABLESPACE INTEGRADOSPLANTILLA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


--
-- IX_OCUPSUPBUQUELECTURA12  (Index) 
--
CREATE INDEX IX_OCUPSUPBUQUELECTURA12 ON OCUPSUPBUQUE_LECTURA
(CODCAMION11)
LOGGING
TABLESPACE INTEGRADOSPLANTILLA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


--
-- IX_OCUPSUPBUQUELECTURA13  (Index) 
--
CREATE INDEX IX_OCUPSUPBUQUELECTURA13 ON OCUPSUPBUQUE_LECTURA
(CODCAMION12)
LOGGING
TABLESPACE INTEGRADOSPLANTILLA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


--
-- IX_OCUPSUPBUQUELECTURA14  (Index) 
--
CREATE INDEX IX_OCUPSUPBUQUELECTURA14 ON OCUPSUPBUQUE_LECTURA
(CODCAMION13)
LOGGING
TABLESPACE INTEGRADOSPLANTILLA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


--
-- IX_OCUPSUPBUQUELECTURA15  (Index) 
--
CREATE INDEX IX_OCUPSUPBUQUELECTURA15 ON OCUPSUPBUQUE_LECTURA
(CODCAMION14)
LOGGING
TABLESPACE INTEGRADOSPLANTILLA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


--
-- IX_OCUPSUPBUQUELECTURA16  (Index) 
--
CREATE INDEX IX_OCUPSUPBUQUELECTURA16 ON OCUPSUPBUQUE_LECTURA
(CODCAMION15)
LOGGING
TABLESPACE INTEGRADOSPLANTILLA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


--
-- IX_OCUPSUPBUQUELECTURA17  (Index) 
--
CREATE INDEX IX_OCUPSUPBUQUELECTURA17 ON OCUPSUPBUQUE_LECTURA
(CODCAMION16)
LOGGING
TABLESPACE INTEGRADOSPLANTILLA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


--
-- IX_OCUPSUPBUQUELECTURA18  (Index) 
--
CREATE INDEX IX_OCUPSUPBUQUELECTURA18 ON OCUPSUPBUQUE_LECTURA
(CODCAMION17)
LOGGING
TABLESPACE INTEGRADOSPLANTILLA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


--
-- IX_OCUPSUPBUQUELECTURA19  (Index) 
--
CREATE INDEX IX_OCUPSUPBUQUELECTURA19 ON OCUPSUPBUQUE_LECTURA
(CODCAMION18)
LOGGING
TABLESPACE INTEGRADOSPLANTILLA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


--
-- IX_OCUPSUPBUQUELECTURA2  (Index) 
--
CREATE INDEX IX_OCUPSUPBUQUELECTURA2 ON OCUPSUPBUQUE_LECTURA
(CODCAMION1)
LOGGING
TABLESPACE INTEGRADOSPLANTILLA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


--
-- IX_OCUPSUPBUQUELECTURA20  (Index) 
--
CREATE INDEX IX_OCUPSUPBUQUELECTURA20 ON OCUPSUPBUQUE_LECTURA
(CODCAMION19)
LOGGING
TABLESPACE INTEGRADOSPLANTILLA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


--
-- IX_OCUPSUPBUQUELECTURA21  (Index) 
--
CREATE INDEX IX_OCUPSUPBUQUELECTURA21 ON OCUPSUPBUQUE_LECTURA
(CODCAMION20)
LOGGING
TABLESPACE INTEGRADOSPLANTILLA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


--
-- IX_OCUPSUPBUQUELECTURA3  (Index) 
--
CREATE INDEX IX_OCUPSUPBUQUELECTURA3 ON OCUPSUPBUQUE_LECTURA
(CODCAMION2)
LOGGING
TABLESPACE INTEGRADOSPLANTILLA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


--
-- IX_OCUPSUPBUQUELECTURA4  (Index) 
--
CREATE INDEX IX_OCUPSUPBUQUELECTURA4 ON OCUPSUPBUQUE_LECTURA
(CODCAMION3)
LOGGING
TABLESPACE INTEGRADOSPLANTILLA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


--
-- IX_OCUPSUPBUQUELECTURA5  (Index) 
--
CREATE INDEX IX_OCUPSUPBUQUELECTURA5 ON OCUPSUPBUQUE_LECTURA
(CODCAMION4)
LOGGING
TABLESPACE INTEGRADOSPLANTILLA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


--
-- IX_OCUPSUPBUQUELECTURA6  (Index) 
--
CREATE INDEX IX_OCUPSUPBUQUELECTURA6 ON OCUPSUPBUQUE_LECTURA
(CODCAMION5)
LOGGING
TABLESPACE INTEGRADOSPLANTILLA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


--
-- IX_OCUPSUPBUQUELECTURA7  (Index) 
--
CREATE INDEX IX_OCUPSUPBUQUELECTURA7 ON OCUPSUPBUQUE_LECTURA
(CODCAMION6)
LOGGING
TABLESPACE INTEGRADOSPLANTILLA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


--
-- IX_OCUPSUPBUQUELECTURA8  (Index) 
--
CREATE INDEX IX_OCUPSUPBUQUELECTURA8 ON OCUPSUPBUQUE_LECTURA
(CODCAMION7)
LOGGING
TABLESPACE INTEGRADOSPLANTILLA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


--
-- IX_OCUPSUPBUQUELECTURA9  (Index) 
--
CREATE INDEX IX_OCUPSUPBUQUELECTURA9 ON OCUPSUPBUQUE_LECTURA
(CODCAMION8)
LOGGING
TABLESPACE INTEGRADOSPLANTILLA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


--
-- IX_OCUPSUPRODANTE1  (Index) 
--
CREATE INDEX IX_OCUPSUPRODANTE1 ON OCUPSUP_RODANTE
(CODPUE)
LOGGING
TABLESPACE INTEGRADOSPLANTILLA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


--
-- IX_OCUPSUPRODANTE2  (Index) 
--
CREATE INDEX IX_OCUPSUPRODANTE2 ON OCUPSUP_RODANTE
(CODTIPOIVA)
LOGGING
TABLESPACE INTEGRADOSPLANTILLA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


--
-- IX_OCUPSUPRODANTE3  (Index) 
--
CREATE INDEX IX_OCUPSUPRODANTE3 ON OCUPSUP_RODANTE
(IDCLIENTE)
LOGGING
TABLESPACE INTEGRADOSPLANTILLA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


--
-- IX_OCUPSUPRODANTE4  (Index) 
--
CREATE INDEX IX_OCUPSUPRODANTE4 ON OCUPSUP_RODANTE
(CODPUEZONA, CODZONA)
LOGGING
TABLESPACE INTEGRADOSPLANTILLA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


--
-- IX_OCUPSUPRODANTE5  (Index) 
--
CREATE INDEX IX_OCUPSUPRODANTE5 ON OCUPSUP_RODANTE
(CODTIPORODANTE)
LOGGING
TABLESPACE INTEGRADOSPLANTILLA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


--
-- IX_OCUPSUPRODANTE6  (Index) 
--
CREATE INDEX IX_OCUPSUPRODANTE6 ON OCUPSUP_RODANTE
(CODBONIFICACION)
LOGGING
TABLESPACE INTEGRADOSPLANTILLA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


--
-- OCUPSUPBUQUE_LECTURA_PK  (Index) 
--
CREATE UNIQUE INDEX OCUPSUPBUQUE_LECTURA_PK ON OCUPSUPBUQUE_LECTURA
(CODPUE, ANYO, CODSER, FECLEC)
LOGGING
TABLESPACE INTEGRADOSPLANTILLA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


--
-- OCUPSUPBUQUE_PK  (Index) 
--
CREATE UNIQUE INDEX OCUPSUPBUQUE_PK ON OCUPSUPBUQUE
(CODPUE, ANYO, CODSER)
LOGGING
TABLESPACE INTEGRADOSPLANTILLA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


--
-- OCUPSUP_RODANTE_PK  (Index) 
--
CREATE UNIQUE INDEX OCUPSUP_RODANTE_PK ON OCUPSUP_RODANTE
(CODPUE, ANYO, CODSER)
LOGGING
TABLESPACE INTEGRADOSPLANTILLA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


--
-- OCUPSUPBUQUE_SRV  (Trigger) 
--
CREATE OR REPLACE TRIGGER "OCUPSUPBUQUE_SRV" 
BEFORE INSERT
ON OCUPSUPBUQUE REFERENCING NEW AS New OLD AS Old
FOR EACH ROW
DECLARE
BEGIN
   :NEW.GUIDSRV := SYS_GUID();

   EXCEPTION
     WHEN OTHERS THEN
       -- Consider logging the error and then re-raise
       RAISE;
END ;
/


--
-- OCUPSUP_RODANTE_SRV  (Trigger) 
--
CREATE OR REPLACE TRIGGER "OCUPSUP_RODANTE_SRV" 
BEFORE INSERT
ON OCUPSUP_RODANTE REFERENCING NEW AS New OLD AS Old
FOR EACH ROW
DECLARE
BEGIN
   :NEW.GUIDSRV := SYS_GUID();

   EXCEPTION
     WHEN OTHERS THEN
       RAISE;
END ;
/


-- 
-- Non Foreign Key Constraints for Table NOVEDAD_RODANTE 
-- 
ALTER TABLE NOVEDAD_RODANTE ADD (
  CONSTRAINT NOVEDAD_RODANTE_PK
 PRIMARY KEY
 (CODIGO)
    USING INDEX 
    TABLESPACE INTEGRADOSPLANTILLA
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));

-- 
-- Non Foreign Key Constraints for Table OCUPSUP_EXENHORAS 
-- 
ALTER TABLE OCUPSUP_EXENHORAS ADD (
  CONSTRAINT OCUPSUP_EXENHORAS_PK
 PRIMARY KEY
 (CODIGO)
    USING INDEX 
    TABLESPACE INTEGRADOSPLANTILLA
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));

-- 
-- Non Foreign Key Constraints for Table OCUPSUP_TIPOALM 
-- 
ALTER TABLE OCUPSUP_TIPOALM ADD (
  CONSTRAINT OCUPSUP_TIPOALM_PK
 PRIMARY KEY
 (CODIGO)
    USING INDEX 
    TABLESPACE INTEGRADOSPLANTILLA
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));

-- 
-- Non Foreign Key Constraints for Table OCUPSUP_TIPOEMB 
-- 
ALTER TABLE OCUPSUP_TIPOEMB ADD (
  CONSTRAINT OCUPSUP_TIPOEMB_PK
 PRIMARY KEY
 (CODIGO)
    USING INDEX 
    TABLESPACE INTEGRADOSPLANTILLA
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));

-- 
-- Non Foreign Key Constraints for Table OCUPSUP_TIPOOPE 
-- 
ALTER TABLE OCUPSUP_TIPOOPE ADD (
  CONSTRAINT OCUPSUP_TIPOOPE_PK
 PRIMARY KEY
 (CODIGO)
    USING INDEX 
    TABLESPACE INTEGRADOSPLANTILLA
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));

-- 
-- Non Foreign Key Constraints for Table OCUPSUP_TIPORODANTE 
-- 
ALTER TABLE OCUPSUP_TIPORODANTE ADD (
  CONSTRAINT OCUPSUP_TIPORODANTE_PK
 PRIMARY KEY
 (CODIGO)
    USING INDEX 
    TABLESPACE INTEGRADOSPLANTILLA
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));

-- 
-- Non Foreign Key Constraints for Table OPERACION 
-- 
ALTER TABLE OPERACION ADD (
  CONSTRAINT PK_OPERACION
 PRIMARY KEY
 (CODPUE, ANYO, CODESCALA, CODESTADIA, CODOPERACION)
    USING INDEX 
    TABLESPACE INTEGRADOSPLANTILLA
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));

-- 
-- Non Foreign Key Constraints for Table OPER_EVENT_AIS 
-- 
ALTER TABLE OPER_EVENT_AIS ADD (
  CONSTRAINT PK_OPER_EVENT_AIS
 PRIMARY KEY
 (PORTAUT, IDEVENTAIS)
    USING INDEX 
    TABLESPACE INTEGRADOSPLANTILLA
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));

-- 
-- Non Foreign Key Constraints for Table OPER_PARAM_GET_CALL 
-- 
ALTER TABLE OPER_PARAM_GET_CALL ADD (
  CONSTRAINT PK_OPER_PARAM_GET_CALL
 PRIMARY KEY
 (PORTAUT, PORTCOD, EVENTTYPE, CODCALLSTATUS)
    USING INDEX 
    TABLESPACE INTEGRADOSPLANTILLA
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));

-- 
-- Non Foreign Key Constraints for Table OPER_PARAM_INTEGRATION 
-- 
ALTER TABLE OPER_PARAM_INTEGRATION ADD (
  CONSTRAINT PK_OPER_PARAM_INTEGRATION
 PRIMARY KEY
 (PORTAUT, PORTCOD, CODE));

-- 
-- Non Foreign Key Constraints for Table OCUPSUPBUQUE 
-- 
ALTER TABLE OCUPSUPBUQUE ADD (
  CONSTRAINT OCUPSUPBUQUE_PK
 PRIMARY KEY
 (CODPUE, ANYO, CODSER)
    USING INDEX 
    TABLESPACE INTEGRADOSPLANTILLA
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));

-- 
-- Non Foreign Key Constraints for Table OCUPSUPBUQUE_LECTURA 
-- 
ALTER TABLE OCUPSUPBUQUE_LECTURA ADD (
  CONSTRAINT OCUPSUPBUQUE_LECTURA_PK
 PRIMARY KEY
 (CODPUE, ANYO, CODSER, FECLEC)
    USING INDEX 
    TABLESPACE INTEGRADOSPLANTILLA
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));

-- 
-- Non Foreign Key Constraints for Table OCUPSUP_RODANTE 
-- 
ALTER TABLE OCUPSUP_RODANTE ADD (
  CONSTRAINT OCUPSUP_RODANTE_PK
 PRIMARY KEY
 (CODPUE, ANYO, CODSER)
    USING INDEX 
    TABLESPACE INTEGRADOSPLANTILLA
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));

-- 
-- Foreign Key Constraints for Table NOVEDAD_RODANTE 
-- 
ALTER TABLE NOVEDAD_RODANTE ADD (
  CONSTRAINT FK_NOVEDAD_RODANTE_01 
 FOREIGN KEY (CODPUE) 
 REFERENCES M_PUERTO_LOCAL (CODPUE));

-- 
-- Foreign Key Constraints for Table OPERACION 
-- 
ALTER TABLE OPERACION ADD (
  CONSTRAINT FK_OPERACION1 
 FOREIGN KEY (CODPUE, ANYO, CODESCALA, CODESTADIA) 
 REFERENCES ESTADIA (CODPUE,ANYO,CODESCALA,CODESTADIA),
  CONSTRAINT FK_OPERACION10 
 FOREIGN KEY (CODMODSUMINCOMB) 
 REFERENCES TIPO_MOD_SUMINCOMB (CODIGO),
  CONSTRAINT FK_OPERACION11 
 FOREIGN KEY (CODCOMBSUMINCOMB) 
 REFERENCES TIPO_COMB_SUMINCOMB (CODIGO),
  CONSTRAINT FK_OPERACION12 
 FOREIGN KEY (CODBARCAZA) 
 REFERENCES M_BARCAZA (CODIGO),
  CONSTRAINT FK_OPERACION13 
 FOREIGN KEY (CODTIPSUMINAGUA) 
 REFERENCES TIPO_SUMINAGUA (CODIGO),
  CONSTRAINT FK_OPERACION14 
 FOREIGN KEY (CODPASARELA) 
 REFERENCES M_PASARELA (CODIGO),
  CONSTRAINT FK_OPERACION16 
 FOREIGN KEY (CODPUECONTADOR, NUMCONTADOR) 
 REFERENCES M_CONTADOR (CODPUE,NUMCON),
  CONSTRAINT FK_OPERACION2 
 FOREIGN KEY (CODTIPOPE) 
 REFERENCES TIPO_OPERACION (CODTIPOPE),
  CONSTRAINT FK_OPERACION3 
 FOREIGN KEY (CODTIPCARGA) 
 REFERENCES TIPO_CARGA_OPERACION (CODTIPCARGA),
  CONSTRAINT FK_OPERACION4 
 FOREIGN KEY (CODTIPUNIDAD) 
 REFERENCES TIPO_UNIDAD_OPERACION (CODTIPUNIDAD),
  CONSTRAINT FK_OPERACION5 
 FOREIGN KEY (CODTIPMEDIOMANIP) 
 REFERENCES TIPO_MEDIO_MANIPULACION (CODTIPMEDIO),
  CONSTRAINT FK_OPERACION6 
 FOREIGN KEY (CODGRUA) 
 REFERENCES M_GRUA (CODIGO),
  CONSTRAINT FK_OPERACION8 
 FOREIGN KEY (CODTIPODESECHO) 
 REFERENCES TIPO_DESECHO (CODIGO),
  CONSTRAINT FK_OPERACION9 
 FOREIGN KEY (CODTIPOALQPAS) 
 REFERENCES TIPO_ALQPASARELA (CODIGO),
  CONSTRAINT FK_OPERACION_17 
 FOREIGN KEY (CODPUEESCTI, ANYOESCTI, CODESCTI) 
 REFERENCES ESCALA (CODPUE,ANYO,CODESCALA),
  CONSTRAINT FK_OPERACION_18 
 FOREIGN KEY (CODDECLARANTE) 
 REFERENCES M_USUARIO (CODUSUARIO),
  CONSTRAINT FK_OPERACION_19 
 FOREIGN KEY (CODEMPSUMIN) 
 REFERENCES M_EMPRESA_SUMIN (CODIGO),
  CONSTRAINT FK_OPERACION_20 
 FOREIGN KEY (IDESTIBADOR) 
 REFERENCES M_USUARIO (CODUSUARIO),
  CONSTRAINT PK_OPERACION15 
 FOREIGN KEY (IDSUJPASIVO) 
 REFERENCES M_USUARIO (CODUSUARIO));

-- 
-- Foreign Key Constraints for Table OPER_PARAM_GET_CALL 
-- 
ALTER TABLE OPER_PARAM_GET_CALL ADD (
  CONSTRAINT FK_OPER_EVENT_AIS 
 FOREIGN KEY (PORTAUT, EVENTTYPE) 
 REFERENCES OPER_EVENT_AIS (PORTAUT,IDEVENTAIS));

-- 
-- Foreign Key Constraints for Table OPER_PARAM_INTEGRATION 
-- 
ALTER TABLE OPER_PARAM_INTEGRATION ADD (
  CONSTRAINT FK_OPER_PARAM_INTE_PUERTO 
 FOREIGN KEY (PORTCOD) 
 REFERENCES M_PUERTO_LOCAL (CODPUE));

-- 
-- Foreign Key Constraints for Table OCUPSUPBUQUE 
-- 
ALTER TABLE OCUPSUPBUQUE ADD (
  CONSTRAINT OCUPSUPBUQUE_R01 
 FOREIGN KEY (CODPUEESC, ANYOESC, CODESC, CODESTADIA) 
 REFERENCES ESTADIA (CODPUE,ANYO,CODESCALA,CODESTADIA),
  CONSTRAINT OCUPSUPBUQUE_R02 
 FOREIGN KEY (IDCLIENTE) 
 REFERENCES M_USUARIO (CODUSUARIO),
  CONSTRAINT OCUPSUPBUQUE_R03 
 FOREIGN KEY (CODPUEZONA, CODZONA) 
 REFERENCES M_ZONAOCUP (CODPUE,CODZONA),
  CONSTRAINT OCUPSUPBUQUE_R10 
 FOREIGN KEY (CODPUEESC, ANYOESC, CODESC) 
 REFERENCES ESCALA (CODPUE,ANYO,CODESCALA),
  CONSTRAINT OCUPSUPBUQUE_R24 
 FOREIGN KEY (CODTIPOEMBARQUE) 
 REFERENCES OCUPSUP_TIPOEMB (CODIGO),
  CONSTRAINT OCUPSUPBUQUE_R25 
 FOREIGN KEY (CODTIPOOPERACION) 
 REFERENCES OCUPSUP_TIPOOPE (CODIGO),
  CONSTRAINT OCUPSUPBUQUE_R26 
 FOREIGN KEY (CODTIPOELEMRODTABLET) 
 REFERENCES TIPO_ELEM_RODANTE_TABLET (CODIGO),
  CONSTRAINT OCUPSUPBUQUE_R27 
 FOREIGN KEY (CODTIPOIVA) 
 REFERENCES LQ_TIPO_IMPUESTOGLOBAL (CODIGO),
  CONSTRAINT OCUPSUPBUQUE_R28 
 FOREIGN KEY (CODTIPOALM) 
 REFERENCES OCUPSUP_TIPOALM (CODIGO),
  CONSTRAINT OCUPSUPBUQUE_R29 
 FOREIGN KEY (CODEXENHORAS) 
 REFERENCES OCUPSUP_EXENHORAS (CODIGO));

-- 
-- Foreign Key Constraints for Table OCUPSUPBUQUE_LECTURA 
-- 
ALTER TABLE OCUPSUPBUQUE_LECTURA ADD (
  CONSTRAINT OCUPSUPBUQUE_LECTURA_R01 
 FOREIGN KEY (CODPUE, ANYO, CODSER) 
 REFERENCES OCUPSUPBUQUE (CODPUE,ANYO,CODSER),
  CONSTRAINT OCUPSUPBUQUE_LECTURA_R02 
 FOREIGN KEY (CODCAMION1) 
 REFERENCES M_CAMION (CODIGO),
  CONSTRAINT OCUPSUPBUQUE_LECTURA_R03 
 FOREIGN KEY (CODCAMION2) 
 REFERENCES M_CAMION (CODIGO),
  CONSTRAINT OCUPSUPBUQUE_LECTURA_R04 
 FOREIGN KEY (CODCAMION3) 
 REFERENCES M_CAMION (CODIGO),
  CONSTRAINT OCUPSUPBUQUE_LECTURA_R05 
 FOREIGN KEY (CODCAMION4) 
 REFERENCES M_CAMION (CODIGO),
  CONSTRAINT OCUPSUPBUQUE_LECTURA_R06 
 FOREIGN KEY (CODCAMION5) 
 REFERENCES M_CAMION (CODIGO),
  CONSTRAINT OCUPSUPBUQUE_LECTURA_R07 
 FOREIGN KEY (CODCAMION6) 
 REFERENCES M_CAMION (CODIGO),
  CONSTRAINT OCUPSUPBUQUE_LECTURA_R08 
 FOREIGN KEY (CODCAMION7) 
 REFERENCES M_CAMION (CODIGO),
  CONSTRAINT OCUPSUPBUQUE_LECTURA_R09 
 FOREIGN KEY (CODCAMION8) 
 REFERENCES M_CAMION (CODIGO),
  CONSTRAINT OCUPSUPBUQUE_LECTURA_R10 
 FOREIGN KEY (CODCAMION9) 
 REFERENCES M_CAMION (CODIGO),
  CONSTRAINT OCUPSUPBUQUE_LECTURA_R11 
 FOREIGN KEY (CODCAMION10) 
 REFERENCES M_CAMION (CODIGO),
  CONSTRAINT OCUPSUPBUQUE_LECTURA_R12 
 FOREIGN KEY (CODCAMION11) 
 REFERENCES M_CAMION (CODIGO),
  CONSTRAINT OCUPSUPBUQUE_LECTURA_R13 
 FOREIGN KEY (CODCAMION12) 
 REFERENCES M_CAMION (CODIGO),
  CONSTRAINT OCUPSUPBUQUE_LECTURA_R14 
 FOREIGN KEY (CODCAMION13) 
 REFERENCES M_CAMION (CODIGO),
  CONSTRAINT OCUPSUPBUQUE_LECTURA_R15 
 FOREIGN KEY (CODCAMION14) 
 REFERENCES M_CAMION (CODIGO),
  CONSTRAINT OCUPSUPBUQUE_LECTURA_R16 
 FOREIGN KEY (CODCAMION15) 
 REFERENCES M_CAMION (CODIGO),
  CONSTRAINT OCUPSUPBUQUE_LECTURA_R17 
 FOREIGN KEY (CODCAMION16) 
 REFERENCES M_CAMION (CODIGO),
  CONSTRAINT OCUPSUPBUQUE_LECTURA_R18 
 FOREIGN KEY (CODCAMION17) 
 REFERENCES M_CAMION (CODIGO),
  CONSTRAINT OCUPSUPBUQUE_LECTURA_R19 
 FOREIGN KEY (CODCAMION18) 
 REFERENCES M_CAMION (CODIGO),
  CONSTRAINT OCUPSUPBUQUE_LECTURA_R20 
 FOREIGN KEY (CODCAMION19) 
 REFERENCES M_CAMION (CODIGO),
  CONSTRAINT OCUPSUPBUQUE_LECTURA_R21 
 FOREIGN KEY (CODCAMION20) 
 REFERENCES M_CAMION (CODIGO));

-- 
-- Foreign Key Constraints for Table OCUPSUP_RODANTE 
-- 
ALTER TABLE OCUPSUP_RODANTE ADD (
  CONSTRAINT FK_OCUPSUP_RODANTE_01 
 FOREIGN KEY (CODPUE) 
 REFERENCES M_PUERTO_LOCAL (CODPUE),
  CONSTRAINT FK_OCUPSUP_RODANTE_02 
 FOREIGN KEY (CODTIPOIVA) 
 REFERENCES LQ_TIPO_IMPUESTOGLOBAL (CODIGO),
  CONSTRAINT FK_OCUPSUP_RODANTE_03 
 FOREIGN KEY (IDCLIENTE) 
 REFERENCES M_USUARIO (CODUSUARIO),
  CONSTRAINT FK_OCUPSUP_RODANTE_04 
 FOREIGN KEY (CODPUEZONA, CODZONA) 
 REFERENCES M_ZONAOCUP (CODPUE,CODZONA),
  CONSTRAINT FK_OCUPSUP_RODANTE_05 
 FOREIGN KEY (CODTIPORODANTE) 
 REFERENCES OCUPSUP_TIPORODANTE (CODIGO),
  CONSTRAINT FK_OCUPSUP_RODANTE_06 
 FOREIGN KEY (CODBONIFICACION) 
 REFERENCES M_BONIFICACION (CODIGO));

GRANT SELECT ON OPERACION TO GISPORTGIJ;
