--
-- PARAMETRO  (Table) 
--
CREATE TABLE PARAMETRO
(
  CODIGO      VARCHAR2(30 BYTE)                 NOT NULL,
  VALOR       VARCHAR2(1000 BYTE)               NOT NULL,
  COMENTARIO  VARCHAR2(200 BYTE)                NOT NULL
)
TABLESPACE INTEGRADOSPLANTILLA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE PARAMETRO IS 'Parametrización de aspectos globales ';

COMMENT ON COLUMN PARAMETRO.CODIGO IS 'Código';

COMMENT ON COLUMN PARAMETRO.VALOR IS 'Valor parámetro';

COMMENT ON COLUMN PARAMETRO.COMENTARIO IS 'Comentario-explicación del parámetro y sus posibles valores';


--
-- PARAM_DOCUMENTOS  (Table) 
--
CREATE TABLE PARAM_DOCUMENTOS
(
  CODIGO       VARCHAR2(30 BYTE)                NOT NULL,
  DESCRIPCION  VARCHAR2(200 BYTE)               NOT NULL,
  VALOR        VARCHAR2(300 BYTE)               NOT NULL
)
TABLESPACE INTEGRADOSPLANTILLA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE PARAM_DOCUMENTOS IS 'Parametrización documentos asociados';

COMMENT ON COLUMN PARAM_DOCUMENTOS.CODIGO IS 'Código';

COMMENT ON COLUMN PARAM_DOCUMENTOS.DESCRIPCION IS 'Descripción';

COMMENT ON COLUMN PARAM_DOCUMENTOS.VALOR IS 'Valor parámetro';


--
-- PARAM_EDI  (Table) 
--
CREATE TABLE PARAM_EDI
(
  CODIGO      VARCHAR2(100 BYTE)                NOT NULL,
  VALOR       VARCHAR2(1000 BYTE)               NOT NULL,
  COMENTARIO  VARCHAR2(1000 BYTE)               NOT NULL
)
TABLESPACE INTEGRADOSPLANTILLA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE PARAM_EDI IS 'Parametrización EDI';

COMMENT ON COLUMN PARAM_EDI.CODIGO IS 'Código';

COMMENT ON COLUMN PARAM_EDI.VALOR IS 'Valor parámetro';

COMMENT ON COLUMN PARAM_EDI.COMENTARIO IS 'Comentario - explicación del parámetro';


--
-- PARAM_ESTADISTICA  (Table) 
--
CREATE TABLE PARAM_ESTADISTICA
(
  CODIGO            INTEGER                     NOT NULL,
  NOMBREREGLA       VARCHAR2(60 BYTE)           NOT NULL,
  DESCRIPCIONREGLA  VARCHAR2(1000 BYTE)         NOT NULL,
  VALOR             VARCHAR2(300 BYTE)          NOT NULL
)
TABLESPACE INTEGRADOSPLANTILLA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE PARAM_ESTADISTICA IS 'Parametrización estadística';

COMMENT ON COLUMN PARAM_ESTADISTICA.VALOR IS 'Valor';

COMMENT ON COLUMN PARAM_ESTADISTICA.CODIGO IS 'Código';

COMMENT ON COLUMN PARAM_ESTADISTICA.NOMBREREGLA IS 'Nombre regla';

COMMENT ON COLUMN PARAM_ESTADISTICA.DESCRIPCIONREGLA IS 'Descripción regla';


--
-- PARAM_FACTURACION  (Table) 
--
CREATE TABLE PARAM_FACTURACION
(
  CODIGO      VARCHAR2(30 BYTE)                 NOT NULL,
  VALOR       VARCHAR2(1000 BYTE)               NOT NULL,
  COMENTARIO  VARCHAR2(100 BYTE)                NOT NULL
)
TABLESPACE INTEGRADOSPLANTILLA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE PARAM_FACTURACION IS 'Parametrización facturación';

COMMENT ON COLUMN PARAM_FACTURACION.CODIGO IS 'Código';

COMMENT ON COLUMN PARAM_FACTURACION.VALOR IS 'Valor';

COMMENT ON COLUMN PARAM_FACTURACION.COMENTARIO IS 'Comentario';


--
-- PARAM_FACTURAE  (Table) 
--
CREATE TABLE PARAM_FACTURAE
(
  CODIGO       VARCHAR2(30 BYTE)                NOT NULL,
  DESCRIPCION  VARCHAR2(300 BYTE)               NOT NULL,
  VALOR        VARCHAR2(300 BYTE)               NOT NULL
)
TABLESPACE INTEGRADOSPLANTILLA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE PARAM_FACTURAE IS 'Parametrización facturae';

COMMENT ON COLUMN PARAM_FACTURAE.CODIGO IS 'Código';

COMMENT ON COLUMN PARAM_FACTURAE.DESCRIPCION IS 'Descripción';

COMMENT ON COLUMN PARAM_FACTURAE.VALOR IS 'Valor';


--
-- PARAM_FORMULARIO  (Table) 
--
CREATE TABLE PARAM_FORMULARIO
(
  CODIGO          VARCHAR2(60 BYTE)             NOT NULL,
  DESCRIPCION     VARCHAR2(300 BYTE)            NOT NULL,
  INDOCULTO       VARCHAR2(1 BYTE)              NOT NULL,
  JSPASOCIADA     VARCHAR2(300 BYTE),
  TIPO            VARCHAR2(1 BYTE)              NOT NULL,
  ACTIONASOCIADO  VARCHAR2(300 BYTE)
)
TABLESPACE INTEGRADOSPLANTILLA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE PARAM_FORMULARIO IS 'Parametrización formularios';

COMMENT ON COLUMN PARAM_FORMULARIO.CODIGO IS 'Código';

COMMENT ON COLUMN PARAM_FORMULARIO.DESCRIPCION IS 'Descripción';

COMMENT ON COLUMN PARAM_FORMULARIO.INDOCULTO IS 'Para indicar si está oculto o no';

COMMENT ON COLUMN PARAM_FORMULARIO.JSPASOCIADA IS 'JSP asociada';

COMMENT ON COLUMN PARAM_FORMULARIO.TIPO IS 'Para indicar si parametrizas un campo del formulario de mantenimiento M o una acción del tcon A';

COMMENT ON COLUMN PARAM_FORMULARIO.ACTIONASOCIADO IS 'Action asociado';


--
-- PARAM_INTEGRATION  (Table) 
--
CREATE TABLE PARAM_INTEGRATION
(
  PORTAUT      VARCHAR2(2 BYTE),
  PORTCOD      VARCHAR2(5 BYTE),
  CODE         VARCHAR2(30 BYTE),
  DESCRIPTION  VARCHAR2(300 BYTE),
  VALUE        VARCHAR2(300 BYTE)
)
TABLESPACE INTEGRADOSPLANTILLA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


--
-- PARAM_REFERENCIA_FACTURA  (Table) 
--
CREATE TABLE PARAM_REFERENCIA_FACTURA
(
  IDTARIFA       VARCHAR2(2 BYTE)               NOT NULL,
  IDSUBTARIFA    VARCHAR2(2 BYTE)               NOT NULL,
  EXTENSION      VARCHAR2(4 BYTE)               NOT NULL,
  CAMPOBORRADOR  VARCHAR2(30 BYTE)              NOT NULL
)
TABLESPACE INTEGRADOSPLANTILLA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


--
-- PARAM_SUJPASB4_PUERTO  (Table) 
--
CREATE TABLE PARAM_SUJPASB4_PUERTO
(
  CODPUE     VARCHAR2(5 BYTE)                   NOT NULL,
  IDUSUARIO  INTEGER                            NOT NULL
)
TABLESPACE INTEGRADOSPLANTILLA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE PARAM_SUJPASB4_PUERTO IS 'Sujeto pasivo para B4';

COMMENT ON COLUMN PARAM_SUJPASB4_PUERTO.CODPUE IS 'Código puerto';

COMMENT ON COLUMN PARAM_SUJPASB4_PUERTO.IDUSUARIO IS 'Código sujeto pasivo';


--
-- PARAM_VALORADOR  (Table) 
--
CREATE TABLE PARAM_VALORADOR
(
  CODIGO             INTEGER                    NOT NULL,
  NOMBREREGLA        VARCHAR2(300 BYTE)         NOT NULL,
  DESCRIPCIONREGLA   VARCHAR2(1000 BYTE)        NOT NULL,
  VALORADORASOCIADO  VARCHAR2(100 BYTE)         NOT NULL,
  VALOR              VARCHAR2(300 BYTE)         NOT NULL,
  BAJA               VARCHAR2(1 BYTE),
  INDAP              VARCHAR2(1 BYTE)
)
TABLESPACE INTEGRADOSPLANTILLA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE PARAM_VALORADOR IS 'Parametrización valoradores';

COMMENT ON COLUMN PARAM_VALORADOR.CODIGO IS 'Código';

COMMENT ON COLUMN PARAM_VALORADOR.NOMBREREGLA IS 'Nombre de parámetro';

COMMENT ON COLUMN PARAM_VALORADOR.DESCRIPCIONREGLA IS 'Comentario-explicación del parámetro y sus posibles valores';

COMMENT ON COLUMN PARAM_VALORADOR.VALORADORASOCIADO IS 'Valorador o valoradores a los que afecta';

COMMENT ON COLUMN PARAM_VALORADOR.VALOR IS 'Valor del parámetro';

COMMENT ON COLUMN PARAM_VALORADOR.BAJA IS 'Check para indicar que está dado de baja';

COMMENT ON COLUMN PARAM_VALORADOR.INDAP IS 'Check para indicar que aplica a alguna autoridad portuaria en particular - En desuso';


--
-- PROCESOFACT  (Table) 
--
CREATE TABLE PROCESOFACT
(
  IDPROCESOFACT   NUMBER(9)                     NOT NULL,
  FECPROCESO      DATE                          NOT NULL,
  FECFACTURACION  DATE                          NOT NULL,
  NUMERRORES      NUMBER(4)                     NOT NULL,
  NUMFACTURAS     NUMBER(4)                     NOT NULL,
  USR             VARCHAR2(20 BYTE)             NOT NULL,
  ESTADO          VARCHAR2(1 BYTE)              NOT NULL
)
TABLESPACE INTEGRADOSPLANTILLA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE PROCESOFACT IS 'Proceso masivo facturación - No se usa. Se usan lotes';

COMMENT ON COLUMN PROCESOFACT.IDPROCESOFACT IS 'Código proceso';

COMMENT ON COLUMN PROCESOFACT.FECPROCESO IS 'Fecha proceso';

COMMENT ON COLUMN PROCESOFACT.FECFACTURACION IS 'Fecha factura';

COMMENT ON COLUMN PROCESOFACT.NUMERRORES IS 'Número errores';

COMMENT ON COLUMN PROCESOFACT.NUMFACTURAS IS 'Número facturas';

COMMENT ON COLUMN PROCESOFACT.USR IS 'Usuario que lanzó el proceso';

COMMENT ON COLUMN PROCESOFACT.ESTADO IS 'Estado proceso';


--
-- PROCESOFACT_ERROR  (Table) 
--
CREATE TABLE PROCESOFACT_ERROR
(
  IDPROCESOFACT  NUMBER(9)                      NOT NULL,
  IDERROR        NUMBER(4)                      NOT NULL,
  DESCSERVICIO   VARCHAR2(3999 BYTE)            NOT NULL,
  CODPUE         VARCHAR2(5 BYTE)               NOT NULL,
  ANYO           INTEGER                        NOT NULL,
  CODBORRADOR    INTEGER                        NOT NULL
)
TABLESPACE INTEGRADOSPLANTILLA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE PROCESOFACT_ERROR IS 'Proceso facturación error-  No se usa';

COMMENT ON COLUMN PROCESOFACT_ERROR.IDPROCESOFACT IS 'Código proceso';

COMMENT ON COLUMN PROCESOFACT_ERROR.IDERROR IS 'Código error';

COMMENT ON COLUMN PROCESOFACT_ERROR.DESCSERVICIO IS 'Descripción servicio y error';

COMMENT ON COLUMN PROCESOFACT_ERROR.CODPUE IS 'Código puerto borrador asociado';

COMMENT ON COLUMN PROCESOFACT_ERROR.ANYO IS 'Año borrador asociado';

COMMENT ON COLUMN PROCESOFACT_ERROR.CODBORRADOR IS 'Código borrador asociado';


--
-- PROCESOLIQUID  (Table) 
--
CREATE TABLE PROCESOLIQUID
(
  IDPROCESO       NUMBER(9)                     NOT NULL,
  FECPROCESO      DATE                          NOT NULL,
  FECLIQUIDACION  DATE                          NOT NULL,
  CODSER          VARCHAR2(4 BYTE)              NOT NULL,
  NUMERRORES      NUMBER(4)                     NOT NULL,
  NUMBORRADORES   NUMBER(4)                     NOT NULL,
  USR             VARCHAR2(20 BYTE)             NOT NULL,
  ESTADO          VARCHAR2(1 BYTE)              NOT NULL,
  INDAUTOMATICO   VARCHAR2(1 BYTE)
)
TABLESPACE INTEGRADOSPLANTILLA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE PROCESOLIQUID IS 'Proceso masivo de generación de borradores';

COMMENT ON COLUMN PROCESOLIQUID.IDPROCESO IS 'Código proceso';

COMMENT ON COLUMN PROCESOLIQUID.FECPROCESO IS 'Fecha proceso';

COMMENT ON COLUMN PROCESOLIQUID.FECLIQUIDACION IS 'Fecha borrador';

COMMENT ON COLUMN PROCESOLIQUID.CODSER IS 'Tipo tasa/tarifa asociada a la valoración masiva';

COMMENT ON COLUMN PROCESOLIQUID.NUMERRORES IS 'Número Errores';

COMMENT ON COLUMN PROCESOLIQUID.NUMBORRADORES IS 'Número borradores generados';

COMMENT ON COLUMN PROCESOLIQUID.USR IS 'Usuario que ha lanzado el proceso';

COMMENT ON COLUMN PROCESOLIQUID.ESTADO IS 'Estado proceso';

COMMENT ON COLUMN PROCESOLIQUID.INDAUTOMATICO IS 'Check para indicar que ha sido lanzado de manera automática - planificación nocturna';


--
-- PROCESOLIQUID_ERROR  (Table) 
--
CREATE TABLE PROCESOLIQUID_ERROR
(
  IDPROCESO     NUMBER(9)                       NOT NULL,
  IDERROR       NUMBER(4)                       NOT NULL,
  DESCSERVICIO  VARCHAR2(3999 BYTE)             NOT NULL
)
TABLESPACE INTEGRADOSPLANTILLA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE PROCESOLIQUID_ERROR IS 'Errores de proceso masivo generación de borradores';

COMMENT ON COLUMN PROCESOLIQUID_ERROR.IDPROCESO IS 'Código proceso';

COMMENT ON COLUMN PROCESOLIQUID_ERROR.IDERROR IS 'Código Error';

COMMENT ON COLUMN PROCESOLIQUID_ERROR.DESCSERVICIO IS 'Identificador del servicio que ha dado error y descripción error';


--
-- PROCESOSERVBAS  (Table) 
--
CREATE TABLE PROCESOSERVBAS
(
  IDPROCESO     NUMBER(9)                       NOT NULL,
  FECPROCESO    DATE                            NOT NULL,
  NUMERRORES    NUMBER(4)                       NOT NULL,
  NUMSERVICIOS  NUMBER(4)                       NOT NULL,
  USR           VARCHAR2(20 BYTE)               NOT NULL,
  ESTADO        VARCHAR2(1 BYTE)                NOT NULL,
  TIPO          VARCHAR2(1 BYTE)                NOT NULL
)
TABLESPACE INTEGRADOSPLANTILLA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE PROCESOSERVBAS IS 'Proceso de cálculo importes servicios básicos';

COMMENT ON COLUMN PROCESOSERVBAS.IDPROCESO IS 'Código proceso';

COMMENT ON COLUMN PROCESOSERVBAS.FECPROCESO IS 'Fecha Proceso';

COMMENT ON COLUMN PROCESOSERVBAS.NUMERRORES IS 'Número Errores';

COMMENT ON COLUMN PROCESOSERVBAS.NUMSERVICIOS IS 'Número Servicios valorados';

COMMENT ON COLUMN PROCESOSERVBAS.USR IS 'Usuario que ha ejecutado el proceso';

COMMENT ON COLUMN PROCESOSERVBAS.ESTADO IS 'Estado del proceso';

COMMENT ON COLUMN PROCESOSERVBAS.TIPO IS 'Tipo de proceso';


--
-- PROCESO_COARRI  (Table) 
--
CREATE TABLE PROCESO_COARRI
(
  IDPROCESO      NUMBER(9)                      NOT NULL,
  FECPROCESO     DATE                           NOT NULL,
  NUMCONTRASTES  NUMBER(9)                      NOT NULL,
  NUMERRORES     NUMBER(9)                      NOT NULL,
  ESTADO         VARCHAR2(1 BYTE)               NOT NULL
)
TABLESPACE INTEGRADOSPLANTILLA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE PROCESO_COARRI IS 'Proceso contraste COARRI-Tramo';

COMMENT ON COLUMN PROCESO_COARRI.IDPROCESO IS 'Código Proceso';

COMMENT ON COLUMN PROCESO_COARRI.FECPROCESO IS 'Fecha Proceso';

COMMENT ON COLUMN PROCESO_COARRI.NUMCONTRASTES IS 'Número contrastes realizados';

COMMENT ON COLUMN PROCESO_COARRI.NUMERRORES IS 'Número errores';

COMMENT ON COLUMN PROCESO_COARRI.ESTADO IS 'Estado proceso';


--
-- PROCESO_COARRI_ERROR  (Table) 
--
CREATE TABLE PROCESO_COARRI_ERROR
(
  IDPROCESO  NUMBER(9)                          NOT NULL,
  IDERROR    NUMBER(4)                          NOT NULL,
  DESCERROR  VARCHAR2(3999 BYTE)                NOT NULL,
  DESCTRAMO  VARCHAR2(200 BYTE)                 NOT NULL,
  CODPUE     VARCHAR2(5 BYTE)                   NOT NULL,
  ANYO       INTEGER                            NOT NULL,
  CODSER     INTEGER                            NOT NULL,
  CODTRAMO   INTEGER                            NOT NULL
)
TABLESPACE INTEGRADOSPLANTILLA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE PROCESO_COARRI_ERROR IS 'Proceso contraste COARRI-Tramo - Errores ';

COMMENT ON COLUMN PROCESO_COARRI_ERROR.IDPROCESO IS 'Código proceso';

COMMENT ON COLUMN PROCESO_COARRI_ERROR.IDERROR IS 'Código Error';

COMMENT ON COLUMN PROCESO_COARRI_ERROR.DESCERROR IS 'Descripción Error';

COMMENT ON COLUMN PROCESO_COARRI_ERROR.DESCTRAMO IS 'Descripción tramo';

COMMENT ON COLUMN PROCESO_COARRI_ERROR.CODPUE IS 'Código puerto tramo';

COMMENT ON COLUMN PROCESO_COARRI_ERROR.ANYO IS 'Año tramo';

COMMENT ON COLUMN PROCESO_COARRI_ERROR.CODSER IS 'Código manifiesto tramo';

COMMENT ON COLUMN PROCESO_COARRI_ERROR.CODTRAMO IS 'Código tramo';


--
-- PROCESO_MIGRACION  (Table) 
--
CREATE TABLE PROCESO_MIGRACION
(
  IDPROCESO        INTEGER                      NOT NULL,
  TIPO             VARCHAR2(1 BYTE)             NOT NULL,
  FECINIPROCESO    DATE                         NOT NULL,
  INDFINALIZADO    VARCHAR2(1 BYTE),
  FECFINPROCESO    DATE,
  NUMESCALASOK     INTEGER,
  NUMESCALASERROR  INTEGER,
  OBSERVACIONES    VARCHAR2(300 BYTE),
  USRALTA          VARCHAR2(20 BYTE),
  USRMODIF         VARCHAR2(20 BYTE),
  FECALTA          DATE,
  FECMODIF         DATE
)
TABLESPACE INTEGRADOSPLANTILLA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE PROCESO_MIGRACION IS 'Procesos de migración';

COMMENT ON COLUMN PROCESO_MIGRACION.IDPROCESO IS 'Código';

COMMENT ON COLUMN PROCESO_MIGRACION.TIPO IS 'Tipo';

COMMENT ON COLUMN PROCESO_MIGRACION.FECINIPROCESO IS 'Fecha inicio';

COMMENT ON COLUMN PROCESO_MIGRACION.INDFINALIZADO IS 'Check finalizado';

COMMENT ON COLUMN PROCESO_MIGRACION.FECFINPROCESO IS 'Fecha fin';

COMMENT ON COLUMN PROCESO_MIGRACION.NUMESCALASOK IS 'Escalas migradas';

COMMENT ON COLUMN PROCESO_MIGRACION.NUMESCALASERROR IS 'Escalas con error';

COMMENT ON COLUMN PROCESO_MIGRACION.OBSERVACIONES IS 'Observaciones';

COMMENT ON COLUMN PROCESO_MIGRACION.USRALTA IS 'Usuario alta';

COMMENT ON COLUMN PROCESO_MIGRACION.USRMODIF IS 'Usuario modificación';

COMMENT ON COLUMN PROCESO_MIGRACION.FECALTA IS 'Fecha alta';

COMMENT ON COLUMN PROCESO_MIGRACION.FECMODIF IS 'Fecha modificación';


--
-- PROCESO_MIGRACION_ERROR  (Table) 
--
CREATE TABLE PROCESO_MIGRACION_ERROR
(
  IDPROCESO  INTEGER                            NOT NULL,
  IDERROR    INTEGER                            NOT NULL,
  NUMESCALA  VARCHAR2(20 BYTE),
  DESCERROR  VARCHAR2(3999 BYTE)
)
TABLESPACE INTEGRADOSPLANTILLA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE PROCESO_MIGRACION_ERROR IS 'Errores de procesos de migración';

COMMENT ON COLUMN PROCESO_MIGRACION_ERROR.IDPROCESO IS 'Código proceso';

COMMENT ON COLUMN PROCESO_MIGRACION_ERROR.IDERROR IS 'Código error';

COMMENT ON COLUMN PROCESO_MIGRACION_ERROR.NUMESCALA IS 'Número escala';

COMMENT ON COLUMN PROCESO_MIGRACION_ERROR.DESCERROR IS 'Descripción del error';


--
-- RENDIMIENTO_GRUA  (Table) 
--
CREATE TABLE RENDIMIENTO_GRUA
(
  CODPUE         VARCHAR2(5 BYTE)               NOT NULL,
  ANYO           INTEGER                        NOT NULL,
  CODESCALA      INTEGER                        NOT NULL,
  CODESTADIA     INTEGER                        NOT NULL,
  CODOPERACION   INTEGER                        NOT NULL,
  SECUENCIAL     INTEGER                        NOT NULL,
  FECINICIO      DATE                           NOT NULL,
  FECFIN         DATE                           NOT NULL,
  CODGRUA        INTEGER                        NOT NULL,
  NUMTON         NUMBER(12,3)                   NOT NULL,
  OBSERVACIONES  VARCHAR2(300 BYTE),
  USRALTA        VARCHAR2(20 BYTE),
  USRMODIF       VARCHAR2(20 BYTE),
  FECALTA        DATE,
  FECMODIF       DATE
)
TABLESPACE INTEGRADOSPLANTILLA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE RENDIMIENTO_GRUA IS 'Tabla de Rendimiento grúa';

COMMENT ON COLUMN RENDIMIENTO_GRUA.CODPUE IS 'Código de puerto';

COMMENT ON COLUMN RENDIMIENTO_GRUA.ANYO IS 'Campo anyo';

COMMENT ON COLUMN RENDIMIENTO_GRUA.CODESCALA IS 'Código de la escala';

COMMENT ON COLUMN RENDIMIENTO_GRUA.CODESTADIA IS 'Código del atraque';

COMMENT ON COLUMN RENDIMIENTO_GRUA.CODOPERACION IS 'Código de la operación porturaria';

COMMENT ON COLUMN RENDIMIENTO_GRUA.SECUENCIAL IS 'Secuencial por operación';

COMMENT ON COLUMN RENDIMIENTO_GRUA.FECINICIO IS 'Fecha de inicio del registro';

COMMENT ON COLUMN RENDIMIENTO_GRUA.FECFIN IS 'Fecha de fin del registro';

COMMENT ON COLUMN RENDIMIENTO_GRUA.CODGRUA IS 'Código de grúa';

COMMENT ON COLUMN RENDIMIENTO_GRUA.NUMTON IS 'Número de toneladas implicadas';

COMMENT ON COLUMN RENDIMIENTO_GRUA.OBSERVACIONES IS 'Campo observaciones';

COMMENT ON COLUMN RENDIMIENTO_GRUA.USRALTA IS 'Usuario que realizó el alta del registro';

COMMENT ON COLUMN RENDIMIENTO_GRUA.USRMODIF IS 'Usuario que realizó la última modificación';

COMMENT ON COLUMN RENDIMIENTO_GRUA.FECALTA IS 'Fecha de alta del registro';

COMMENT ON COLUMN RENDIMIENTO_GRUA.FECMODIF IS 'Fecha de última modificación';


--
-- IX_PARAMSUJPASB4PUERTO1  (Index) 
--
CREATE INDEX IX_PARAMSUJPASB4PUERTO1 ON PARAM_SUJPASB4_PUERTO
(CODPUE)
LOGGING
TABLESPACE INTEGRADOSPLANTILLA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


--
-- IX_PARAMSUJPASB4PUERTO2  (Index) 
--
CREATE INDEX IX_PARAMSUJPASB4PUERTO2 ON PARAM_SUJPASB4_PUERTO
(IDUSUARIO)
LOGGING
TABLESPACE INTEGRADOSPLANTILLA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


--
-- IX_PROCESOCOARRIERROR1  (Index) 
--
CREATE INDEX IX_PROCESOCOARRIERROR1 ON PROCESO_COARRI_ERROR
(CODPUE, ANYO, CODSER, CODTRAMO)
LOGGING
TABLESPACE INTEGRADOSPLANTILLA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


--
-- IX_PROCESOFACTERROR1  (Index) 
--
CREATE INDEX IX_PROCESOFACTERROR1 ON PROCESOFACT_ERROR
(IDPROCESOFACT)
LOGGING
TABLESPACE INTEGRADOSPLANTILLA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


--
-- IX_PROCESOLIQUID1  (Index) 
--
CREATE INDEX IX_PROCESOLIQUID1 ON PROCESOLIQUID
(CODSER)
LOGGING
TABLESPACE INTEGRADOSPLANTILLA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


--
-- IX_PROCESOLIQUIDERROR1  (Index) 
--
CREATE INDEX IX_PROCESOLIQUIDERROR1 ON PROCESOLIQUID_ERROR
(IDPROCESO)
LOGGING
TABLESPACE INTEGRADOSPLANTILLA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


--
-- IX_PROCESOMIGRACIONERROR1  (Index) 
--
CREATE INDEX IX_PROCESOMIGRACIONERROR1 ON PROCESO_MIGRACION_ERROR
(IDPROCESO)
LOGGING
TABLESPACE INTEGRADOSPLANTILLA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


--
-- PARAMETRO_PK  (Index) 
--
CREATE UNIQUE INDEX PARAMETRO_PK ON PARAMETRO
(CODIGO)
LOGGING
TABLESPACE INTEGRADOSPLANTILLA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


--
-- PARAM_DOCUMENTOS_PK  (Index) 
--
CREATE UNIQUE INDEX PARAM_DOCUMENTOS_PK ON PARAM_DOCUMENTOS
(CODIGO)
LOGGING
TABLESPACE INTEGRADOSPLANTILLA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


--
-- PARAM_EDI_PK  (Index) 
--
CREATE UNIQUE INDEX PARAM_EDI_PK ON PARAM_EDI
(CODIGO)
LOGGING
TABLESPACE INTEGRADOSPLANTILLA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


--
-- PARAM_ESTADISTICA_PK  (Index) 
--
CREATE UNIQUE INDEX PARAM_ESTADISTICA_PK ON PARAM_ESTADISTICA
(CODIGO)
LOGGING
TABLESPACE INTEGRADOSPLANTILLA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


--
-- PARAM_FACTURACION_PK  (Index) 
--
CREATE UNIQUE INDEX PARAM_FACTURACION_PK ON PARAM_FACTURACION
(CODIGO)
LOGGING
TABLESPACE INTEGRADOSPLANTILLA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


--
-- PARAM_FACTURAE  (Index) 
--
CREATE UNIQUE INDEX PARAM_FACTURAE ON PARAM_FACTURAE
(CODIGO)
LOGGING
TABLESPACE INTEGRADOSPLANTILLA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


--
-- PARAM_FORMULARIO_PK  (Index) 
--
CREATE UNIQUE INDEX PARAM_FORMULARIO_PK ON PARAM_FORMULARIO
(CODIGO)
LOGGING
TABLESPACE INTEGRADOSPLANTILLA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


--
-- PARAM_REFERENCIA_FACTURA_PK  (Index) 
--
CREATE UNIQUE INDEX PARAM_REFERENCIA_FACTURA_PK ON PARAM_REFERENCIA_FACTURA
(IDTARIFA, IDSUBTARIFA, EXTENSION)
LOGGING
TABLESPACE INTEGRADOSPLANTILLA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


--
-- PARAM_SUJPASB4_PUERTO_PK  (Index) 
--
CREATE UNIQUE INDEX PARAM_SUJPASB4_PUERTO_PK ON PARAM_SUJPASB4_PUERTO
(CODPUE, IDUSUARIO)
LOGGING
TABLESPACE INTEGRADOSPLANTILLA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


--
-- PARAM_VALORADOR_PK  (Index) 
--
CREATE UNIQUE INDEX PARAM_VALORADOR_PK ON PARAM_VALORADOR
(CODIGO)
LOGGING
TABLESPACE INTEGRADOSPLANTILLA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


--
-- PK_PARAM_INTEGRATION  (Index) 
--
CREATE UNIQUE INDEX PK_PARAM_INTEGRATION ON PARAM_INTEGRATION
(PORTAUT, PORTCOD, CODE)
LOGGING
TABLESPACE INTEGRADOSPLANTILLA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


--
-- PROCESOFACT_ERROR_PK  (Index) 
--
CREATE UNIQUE INDEX PROCESOFACT_ERROR_PK ON PROCESOFACT_ERROR
(IDPROCESOFACT, IDERROR)
LOGGING
TABLESPACE INTEGRADOSPLANTILLA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


--
-- PROCESOFACT_PK  (Index) 
--
CREATE UNIQUE INDEX PROCESOFACT_PK ON PROCESOFACT
(IDPROCESOFACT)
LOGGING
TABLESPACE INTEGRADOSPLANTILLA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


--
-- PROCESOLIQUID_ERROR_PK  (Index) 
--
CREATE UNIQUE INDEX PROCESOLIQUID_ERROR_PK ON PROCESOLIQUID_ERROR
(IDPROCESO, IDERROR)
LOGGING
TABLESPACE INTEGRADOSPLANTILLA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


--
-- PROCESOLIQUID_PK  (Index) 
--
CREATE UNIQUE INDEX PROCESOLIQUID_PK ON PROCESOLIQUID
(IDPROCESO)
LOGGING
TABLESPACE INTEGRADOSPLANTILLA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


--
-- PROCESOSERVBAS_PK  (Index) 
--
CREATE UNIQUE INDEX PROCESOSERVBAS_PK ON PROCESOSERVBAS
(IDPROCESO)
LOGGING
TABLESPACE INTEGRADOSPLANTILLA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


--
-- PROCESO_COARRI_ERROR_PK  (Index) 
--
CREATE UNIQUE INDEX PROCESO_COARRI_ERROR_PK ON PROCESO_COARRI_ERROR
(IDPROCESO, IDERROR)
LOGGING
TABLESPACE INTEGRADOSPLANTILLA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


--
-- PROCESO_COARRI_PK  (Index) 
--
CREATE UNIQUE INDEX PROCESO_COARRI_PK ON PROCESO_COARRI
(IDPROCESO)
LOGGING
TABLESPACE INTEGRADOSPLANTILLA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


--
-- PROCESO_MIGRACION_ERROR_PK  (Index) 
--
CREATE UNIQUE INDEX PROCESO_MIGRACION_ERROR_PK ON PROCESO_MIGRACION_ERROR
(IDPROCESO, IDERROR)
LOGGING
TABLESPACE INTEGRADOSPLANTILLA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


--
-- PROCESO_MIGRACION_PK  (Index) 
--
CREATE UNIQUE INDEX PROCESO_MIGRACION_PK ON PROCESO_MIGRACION
(IDPROCESO)
LOGGING
TABLESPACE INTEGRADOSPLANTILLA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


--
-- RENDIMIENTO_GRUA_PK  (Index) 
--
CREATE UNIQUE INDEX RENDIMIENTO_GRUA_PK ON RENDIMIENTO_GRUA
(CODPUE, ANYO, CODESCALA, CODESTADIA, CODOPERACION, 
SECUENCIAL)
LOGGING
TABLESPACE INTEGRADOSPLANTILLA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


-- 
-- Non Foreign Key Constraints for Table PARAMETRO 
-- 
ALTER TABLE PARAMETRO ADD (
  CONSTRAINT PARAMETRO_PK
 PRIMARY KEY
 (CODIGO)
    USING INDEX 
    TABLESPACE INTEGRADOSPLANTILLA
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));

-- 
-- Non Foreign Key Constraints for Table PARAM_DOCUMENTOS 
-- 
ALTER TABLE PARAM_DOCUMENTOS ADD (
  CONSTRAINT PARAM_DOCUMENTOS_PK
 PRIMARY KEY
 (CODIGO)
    USING INDEX 
    TABLESPACE INTEGRADOSPLANTILLA
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));

-- 
-- Non Foreign Key Constraints for Table PARAM_EDI 
-- 
ALTER TABLE PARAM_EDI ADD (
  CONSTRAINT PARAM_EDI_PK
 PRIMARY KEY
 (CODIGO)
    USING INDEX 
    TABLESPACE INTEGRADOSPLANTILLA
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));

-- 
-- Non Foreign Key Constraints for Table PARAM_ESTADISTICA 
-- 
ALTER TABLE PARAM_ESTADISTICA ADD (
  CONSTRAINT PARAM_ESTADISTICA_PK
 PRIMARY KEY
 (CODIGO)
    USING INDEX 
    TABLESPACE INTEGRADOSPLANTILLA
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));

-- 
-- Non Foreign Key Constraints for Table PARAM_FACTURACION 
-- 
ALTER TABLE PARAM_FACTURACION ADD (
  CONSTRAINT PARAM_FACTURACION_PK
 PRIMARY KEY
 (CODIGO)
    USING INDEX 
    TABLESPACE INTEGRADOSPLANTILLA
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));

-- 
-- Non Foreign Key Constraints for Table PARAM_FACTURAE 
-- 
ALTER TABLE PARAM_FACTURAE ADD (
  CONSTRAINT PARAM_FACTURAE
 PRIMARY KEY
 (CODIGO)
    USING INDEX 
    TABLESPACE INTEGRADOSPLANTILLA
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));

-- 
-- Non Foreign Key Constraints for Table PARAM_FORMULARIO 
-- 
ALTER TABLE PARAM_FORMULARIO ADD (
  CONSTRAINT PARAM_FORMULARIO_PK
 PRIMARY KEY
 (CODIGO)
    USING INDEX 
    TABLESPACE INTEGRADOSPLANTILLA
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));

-- 
-- Non Foreign Key Constraints for Table PARAM_INTEGRATION 
-- 
ALTER TABLE PARAM_INTEGRATION ADD (
  CONSTRAINT PK_PARAM_INTEGRATION
 PRIMARY KEY
 (PORTAUT, PORTCOD, CODE)
    USING INDEX 
    TABLESPACE INTEGRADOSPLANTILLA
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));

-- 
-- Non Foreign Key Constraints for Table PARAM_REFERENCIA_FACTURA 
-- 
ALTER TABLE PARAM_REFERENCIA_FACTURA ADD (
  CONSTRAINT PARAM_REFERENCIA_FACTURA_PK
 PRIMARY KEY
 (IDTARIFA, IDSUBTARIFA, EXTENSION)
    USING INDEX 
    TABLESPACE INTEGRADOSPLANTILLA
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));

-- 
-- Non Foreign Key Constraints for Table PARAM_SUJPASB4_PUERTO 
-- 
ALTER TABLE PARAM_SUJPASB4_PUERTO ADD (
  CONSTRAINT PARAM_SUJPASB4_PUERTO_PK
 PRIMARY KEY
 (CODPUE, IDUSUARIO)
    USING INDEX 
    TABLESPACE INTEGRADOSPLANTILLA
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));

-- 
-- Non Foreign Key Constraints for Table PARAM_VALORADOR 
-- 
ALTER TABLE PARAM_VALORADOR ADD (
  CONSTRAINT PARAM_VALORADOR_PK
 PRIMARY KEY
 (CODIGO)
    USING INDEX 
    TABLESPACE INTEGRADOSPLANTILLA
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));

-- 
-- Non Foreign Key Constraints for Table PROCESOFACT 
-- 
ALTER TABLE PROCESOFACT ADD (
  CONSTRAINT PROCESOFACT_PK
 PRIMARY KEY
 (IDPROCESOFACT)
    USING INDEX 
    TABLESPACE INTEGRADOSPLANTILLA
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));

-- 
-- Non Foreign Key Constraints for Table PROCESOFACT_ERROR 
-- 
ALTER TABLE PROCESOFACT_ERROR ADD (
  CONSTRAINT PROCESOFACT_ERROR_PK
 PRIMARY KEY
 (IDPROCESOFACT, IDERROR)
    USING INDEX 
    TABLESPACE INTEGRADOSPLANTILLA
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));

-- 
-- Non Foreign Key Constraints for Table PROCESOLIQUID 
-- 
ALTER TABLE PROCESOLIQUID ADD (
  CONSTRAINT PROCESOLIQUID_PK
 PRIMARY KEY
 (IDPROCESO)
    USING INDEX 
    TABLESPACE INTEGRADOSPLANTILLA
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));

-- 
-- Non Foreign Key Constraints for Table PROCESOLIQUID_ERROR 
-- 
ALTER TABLE PROCESOLIQUID_ERROR ADD (
  CONSTRAINT PROCESOLIQUID_ERROR_PK
 PRIMARY KEY
 (IDPROCESO, IDERROR)
    USING INDEX 
    TABLESPACE INTEGRADOSPLANTILLA
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));

-- 
-- Non Foreign Key Constraints for Table PROCESOSERVBAS 
-- 
ALTER TABLE PROCESOSERVBAS ADD (
  CONSTRAINT PROCESOSERVBAS_PK
 PRIMARY KEY
 (IDPROCESO)
    USING INDEX 
    TABLESPACE INTEGRADOSPLANTILLA
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));

-- 
-- Non Foreign Key Constraints for Table PROCESO_COARRI 
-- 
ALTER TABLE PROCESO_COARRI ADD (
  CONSTRAINT PROCESO_COARRI_PK
 PRIMARY KEY
 (IDPROCESO)
    USING INDEX 
    TABLESPACE INTEGRADOSPLANTILLA
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));

-- 
-- Non Foreign Key Constraints for Table PROCESO_COARRI_ERROR 
-- 
ALTER TABLE PROCESO_COARRI_ERROR ADD (
  CONSTRAINT PROCESO_COARRI_ERROR_PK
 PRIMARY KEY
 (IDPROCESO, IDERROR)
    USING INDEX 
    TABLESPACE INTEGRADOSPLANTILLA
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));

-- 
-- Non Foreign Key Constraints for Table PROCESO_MIGRACION 
-- 
ALTER TABLE PROCESO_MIGRACION ADD (
  CONSTRAINT PROCESO_MIGRACION_PK
 PRIMARY KEY
 (IDPROCESO)
    USING INDEX 
    TABLESPACE INTEGRADOSPLANTILLA
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));

-- 
-- Non Foreign Key Constraints for Table PROCESO_MIGRACION_ERROR 
-- 
ALTER TABLE PROCESO_MIGRACION_ERROR ADD (
  CONSTRAINT PROCESO_MIGRACION_ERROR_PK
 PRIMARY KEY
 (IDPROCESO, IDERROR)
    USING INDEX 
    TABLESPACE INTEGRADOSPLANTILLA
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));

-- 
-- Non Foreign Key Constraints for Table RENDIMIENTO_GRUA 
-- 
ALTER TABLE RENDIMIENTO_GRUA ADD (
  CONSTRAINT RENDIMIENTO_GRUA_PK
 PRIMARY KEY
 (CODPUE, ANYO, CODESCALA, CODESTADIA, CODOPERACION, SECUENCIAL)
    USING INDEX 
    TABLESPACE INTEGRADOSPLANTILLA
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));

-- 
-- Foreign Key Constraints for Table PARAM_INTEGRATION 
-- 
ALTER TABLE PARAM_INTEGRATION ADD (
  CONSTRAINT FK_PARAM_INTEGRACION_PUERTO 
 FOREIGN KEY (PORTCOD) 
 REFERENCES M_PUERTO_LOCAL (CODPUE));

-- 
-- Foreign Key Constraints for Table PARAM_SUJPASB4_PUERTO 
-- 
ALTER TABLE PARAM_SUJPASB4_PUERTO ADD (
  CONSTRAINT FK_PARAM_SUJPASB4_PUERTO_02 
 FOREIGN KEY (IDUSUARIO) 
 REFERENCES M_USUARIO (CODUSUARIO),
  CONSTRAINT FK_PARAM_SUJPASB5_PUERTO_01 
 FOREIGN KEY (CODPUE) 
 REFERENCES M_PUERTO_LOCAL (CODPUE));

-- 
-- Foreign Key Constraints for Table PROCESOFACT_ERROR 
-- 
ALTER TABLE PROCESOFACT_ERROR ADD (
  CONSTRAINT FK_PROCESOFACT_ERROR_1 
 FOREIGN KEY (IDPROCESOFACT) 
 REFERENCES PROCESOFACT (IDPROCESOFACT));

-- 
-- Foreign Key Constraints for Table PROCESOLIQUID_ERROR 
-- 
ALTER TABLE PROCESOLIQUID_ERROR ADD (
  CONSTRAINT FK_PROCESOLIQUID_ERROR_1 
 FOREIGN KEY (IDPROCESO) 
 REFERENCES PROCESOLIQUID (IDPROCESO));

-- 
-- Foreign Key Constraints for Table PROCESO_COARRI_ERROR 
-- 
ALTER TABLE PROCESO_COARRI_ERROR ADD (
  CONSTRAINT FK_PROCESO_COARRI_ERROR_01 
 FOREIGN KEY (IDPROCESO) 
 REFERENCES PROCESO_COARRI (IDPROCESO),
  CONSTRAINT FK_PROCESO_COARRI_ERROR_02 
 FOREIGN KEY (CODPUE, ANYO, CODSER, CODTRAMO) 
 REFERENCES G3_TRAMO (CODPUE,ANYO,CODSER,CODTRAMO));

-- 
-- Foreign Key Constraints for Table PROCESO_MIGRACION_ERROR 
-- 
ALTER TABLE PROCESO_MIGRACION_ERROR ADD (
  CONSTRAINT FK_PROCESO_MIGRACION_ERROR_01 
 FOREIGN KEY (IDPROCESO) 
 REFERENCES PROCESO_MIGRACION (IDPROCESO));

-- 
-- Foreign Key Constraints for Table RENDIMIENTO_GRUA 
-- 
ALTER TABLE RENDIMIENTO_GRUA ADD (
  CONSTRAINT FK_RENDGRUA_GRUA 
 FOREIGN KEY (CODGRUA) 
 REFERENCES M_GRUA (CODIGO),
  CONSTRAINT FK_RENDGRUA_OPERAC 
 FOREIGN KEY (CODPUE, ANYO, CODESCALA, CODESTADIA, CODOPERACION) 
 REFERENCES OPERACION (CODPUE,ANYO,CODESCALA,CODESTADIA,CODOPERACION));

GRANT SELECT ON PARAM_VALORADOR TO GISPORTCOR;

GRANT SELECT ON PARAMETRO TO GISPORT_BALEARES;

GRANT SELECT ON PARAM_DOCUMENTOS TO GISPORT_BALEARES;

GRANT SELECT ON PARAM_EDI TO GISPORT_BALEARES;

GRANT SELECT ON PARAM_FACTURACION TO GISPORT_BALEARES;

GRANT SELECT ON PARAM_FACTURAE TO GISPORT_BALEARES;

GRANT SELECT ON PARAM_FORMULARIO TO GISPORT_BALEARES;

GRANT SELECT ON PARAM_VALORADOR TO POSIDONIASELECT;
