--
-- VM_TC_G3EQUIPAMIENTOS  (Table) 
--
CREATE TABLE VM_TC_G3EQUIPAMIENTOS
(
  CODPUE            VARCHAR2(5 BYTE)            NOT NULL,
  ANYO              INTEGER                     NOT NULL,
  CODSER            INTEGER                     NOT NULL,
  CODTRAMO          INTEGER                     NOT NULL,
  NUMORDEN          VARCHAR2(4 BYTE)            NOT NULL,
  TIPOCONOC         VARCHAR2(1 BYTE)            NOT NULL,
  CODEQUIP          INTEGER                     NOT NULL,
  DESPUE            VARCHAR2(50 BYTE)           NOT NULL,
  CODTIPOEQUIP      VARCHAR2(3 BYTE)            NOT NULL,
  TIPOEQUIP         VARCHAR2(50 BYTE),
  CODTIPOTAMANYO    VARCHAR2(4 BYTE),
  MATRICULA         VARCHAR2(30 BYTE),
  TARA              NUMBER(10,2),
  ESTNUMEQUIPS      INTEGER,
  ESTNUMTEUS        INTEGER,
  CODESTADO         VARCHAR2(1 BYTE),
  ESTADO            VARCHAR2(100 BYTE),
  CODTERMINAL       VARCHAR2(50 BYTE),
  CODMUELLE         VARCHAR2(20 BYTE),
  ESTTUCAOPPE       VARCHAR2(3 BYTE),
  DESESTTUCAOPPE    VARCHAR2(50 BYTE),
  CODPAI1           VARCHAR2(3 BYTE),
  CODPUE1           VARCHAR2(3 BYTE),
  DESPAI1           VARCHAR2(100 BYTE),
  DESPUE1           VARCHAR2(100 BYTE),
  CODPAI3           VARCHAR2(2 BYTE),
  CODPUE3           VARCHAR2(3 BYTE),
  DESPAI3           VARCHAR2(100 BYTE),
  DESPUE3           VARCHAR2(100 BYTE),
  CODTIPTRANSPORTE  VARCHAR2(3 BYTE)            NOT NULL,
  DESTIPTRANSPORTE  VARCHAR2(100 BYTE),
  IDCONSIGNATARIO   INTEGER                     NOT NULL,
  CIFCONSIGNATARIO  VARCHAR2(31 BYTE),
  CONSIGNATARIO     VARCHAR2(150 BYTE)          NOT NULL,
  INDREGSIMPLIF     VARCHAR2(2 BYTE),
  CODTIPOIVAT2      VARCHAR2(1 BYTE),
  CODTIPOIVAT3      VARCHAR2(1 BYTE),
  CODTIPCONCB3      VARCHAR2(1 BYTE),
  ESTINDEXENTA      CHAR(2 BYTE),
  PDTET2            CHAR(2 BYTE),
  PDTET3            CHAR(2 BYTE),
  TIPODECLARACION   VARCHAR2(100 BYTE)          NOT NULL,
  NUMDECLARACION    VARCHAR2(11 BYTE)           NOT NULL,
  FECDECLARACION    DATE                        NOT NULL,
  NUMESCALA         VARCHAR2(30 BYTE),
  FECINIREAL        DATE,
  FECFINREAL        DATE,
  CODIMO            VARCHAR2(12 BYTE),
  BUQUE             VARCHAR2(100 BYTE),
  ESLORATOTAL       NUMBER(5,2),
  MANGA             NUMBER(4,2),
  GT                NUMBER(10,3),
  BANDERA           VARCHAR2(2 BYTE),
  CODTIPOBUQUE      VARCHAR2(2 BYTE),
  CODPUEESCALA      VARCHAR2(5 BYTE),
  ANYOESCALA        INTEGER,
  CODESCALA         INTEGER
)
TABLESPACE INTEGRADOSPLANTILLA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOLOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


--
-- VM_TC_G3PARTIDAS  (Table) 
--
CREATE TABLE VM_TC_G3PARTIDAS
(
  CODPUE                 VARCHAR2(5 BYTE)       NOT NULL,
  ANYO                   INTEGER                NOT NULL,
  CODSER                 INTEGER                NOT NULL,
  CODTRAMO               INTEGER                NOT NULL,
  NUMORDEN               VARCHAR2(4 BYTE)       NOT NULL,
  TIPOCONOC              VARCHAR2(1 BYTE)       NOT NULL,
  NUMPARTIDA             VARCHAR2(5 BYTE)       NOT NULL,
  DESPUE                 VARCHAR2(50 BYTE)      NOT NULL,
  CODARAN                VARCHAR2(5 BYTE),
  VERCODARAN             NUMBER(5),
  DESMERCANCIA           VARCHAR2(50 BYTE),
  CODGRUPO               VARCHAR2(1 BYTE),
  CODSUBGRUPONATURALEZA  VARCHAR2(2 BYTE),
  PESO                   NUMBER(12,2),
  TONELADAS              NUMBER,
  NUMBULTOS              INTEGER,
  CODTERMINAL            VARCHAR2(50 BYTE),
  CODMUELLE              VARCHAR2(20 BYTE),
  ESTINDINSTALESPECIAL   VARCHAR2(2 BYTE),
  ESTTUCAOPPE            VARCHAR2(3 BYTE),
  DESESTTUCAOPPE         VARCHAR2(50 BYTE),
  ESTCODFORMAPRESENT     VARCHAR2(2 BYTE),
  CODPAI1                VARCHAR2(3 BYTE),
  CODPUE1                VARCHAR2(3 BYTE),
  DESPAI1                VARCHAR2(100 BYTE),
  DESPUE1                VARCHAR2(100 BYTE),
  CODPAI3                VARCHAR2(2 BYTE),
  CODPUE3                VARCHAR2(3 BYTE),
  DESPAI3                VARCHAR2(100 BYTE),
  DESPUE3                VARCHAR2(100 BYTE),
  CODTIPTRANSPORTE       VARCHAR2(3 BYTE)       NOT NULL,
  DESTIPTRANSPORTE       VARCHAR2(100 BYTE),
  IDCONSIGNATARIO        INTEGER                NOT NULL,
  CIFCONSIGNATARIO       VARCHAR2(31 BYTE),
  CONSIGNATARIO          VARCHAR2(150 BYTE)     NOT NULL,
  INDREGSIMPLIF          VARCHAR2(2 BYTE),
  CODTIPOIVAT2           VARCHAR2(1 BYTE),
  CODTIPOIVAT3           VARCHAR2(1 BYTE),
  CODTIPCONCB3           VARCHAR2(1 BYTE),
  ESTINDEXENTA           CHAR(2 BYTE),
  PDTET2                 CHAR(2 BYTE),
  PDTET3                 CHAR(2 BYTE),
  TIPODECLARACION        VARCHAR2(100 BYTE)     NOT NULL,
  NUMDECLARACION         VARCHAR2(11 BYTE)      NOT NULL,
  FECDECLARACION         DATE                   NOT NULL,
  NUMESCALA              VARCHAR2(30 BYTE),
  FECINIREAL             DATE,
  FECFINREAL             DATE,
  CODIMO                 VARCHAR2(12 BYTE),
  BUQUE                  VARCHAR2(100 BYTE),
  ESLORATOTAL            NUMBER(5,2),
  MANGA                  NUMBER(4,2),
  GT                     NUMBER(10,3),
  BANDERA                VARCHAR2(2 BYTE),
  CODTIPOBUQUE           VARCHAR2(2 BYTE),
  CODPUEESCALA           VARCHAR2(5 BYTE),
  ANYOESCALA             INTEGER,
  CODESCALA              INTEGER,
  CODINSTESP             VARCHAR2(10 BYTE)
)
TABLESPACE INTEGRADOSPLANTILLA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOLOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


--
-- X3_MERCANCIAS  (Table) 
--
CREATE TABLE X3_MERCANCIAS
(
  CODIARAN             VARCHAR2(5 BYTE),
  DESCRIPC             VARCHAR2(30 BYTE),
  DENOAMPL             VARCHAR2(2000 BYTE),
  DESCUENT             NUMBER(5,2),
  GARA_CODIGOID        VARCHAR2(1 BYTE),
  S43_MERCANCIA        VARCHAR2(2 BYTE),
  NATURALEZA           VARCHAR2(2 BYTE),
  TUCA_CODIGOID        VARCHAR2(3 BYTE),
  GRUP_EEE             VARCHAR2(2 BYTE),
  GARA_NUEVO_CODIGOID  VARCHAR2(1 BYTE),
  PELIGROS             VARCHAR2(1 BYTE),
  MERCANCIA            VARCHAR2(1 BYTE)
)
TABLESPACE INTEGRADOSPLANTILLA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


--
-- XE_SUBGRUPO_4_3_POR_PUERTO  (Table) 
--
CREATE TABLE XE_SUBGRUPO_4_3_POR_PUERTO
(
  CODIGOID  VARCHAR2(2 BYTE),
  DESCRIPC  VARCHAR2(40 BYTE)
)
TABLESPACE INTEGRADOSPLANTILLA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


--
-- MERC_PK  (Index) 
--
CREATE UNIQUE INDEX MERC_PK ON X3_MERCANCIAS
(CODIARAN)
LOGGING
TABLESPACE INTEGRADOSPLANTILLA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


--
-- PK_XE_011  (Index) 
--
CREATE UNIQUE INDEX PK_XE_011 ON XE_SUBGRUPO_4_3_POR_PUERTO
(CODIGOID)
LOGGING
TABLESPACE INTEGRADOSPLANTILLA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


--
-- VM_TC_G3EQUIPAMIENTOS_PK  (Index) 
--
CREATE UNIQUE INDEX VM_TC_G3EQUIPAMIENTOS_PK ON VM_TC_G3EQUIPAMIENTOS
(CODPUE, ANYO, CODSER, CODTRAMO, NUMORDEN, 
TIPOCONOC, CODEQUIP)
LOGGING
TABLESPACE INTEGRADOSPLANTILLA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


--
-- VM_TC_G3PARTIDAS_PK  (Index) 
--
CREATE UNIQUE INDEX VM_TC_G3PARTIDAS_PK ON VM_TC_G3PARTIDAS
(CODPUE, ANYO, CODSER, CODTRAMO, NUMORDEN, 
TIPOCONOC, NUMPARTIDA)
LOGGING
TABLESPACE INTEGRADOSPLANTILLA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


-- 
-- Non Foreign Key Constraints for Table X3_MERCANCIAS 
-- 
ALTER TABLE X3_MERCANCIAS ADD (
  CONSTRAINT MERC_PK
 PRIMARY KEY
 (CODIARAN)
    USING INDEX 
    TABLESPACE INTEGRADOSPLANTILLA
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));

-- 
-- Non Foreign Key Constraints for Table XE_SUBGRUPO_4_3_POR_PUERTO 
-- 
ALTER TABLE XE_SUBGRUPO_4_3_POR_PUERTO ADD (
  CONSTRAINT PK_XE_011
 PRIMARY KEY
 (CODIGOID)
    USING INDEX 
    TABLESPACE INTEGRADOSPLANTILLA
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));
