--
-- CANONXUNTACONTADOR  (Package) 
--
CREATE OR REPLACE PACKAGE CANONXUNTACONTADOR AS

  FUNCTION OBTENERWMESES(WDIAS NUMBER) RETURN NUMBER;
  FUNCTION OBTENERWCONSUMES(WDIAS NUMBER, WLECTURA NUMBER) RETURN NUMBER;

END CANONXUNTACONTADOR;
/
--
-- CANONXUNTACONTADOR  (Package Body) 
--
CREATE OR REPLACE PACKAGE BODY CANONXUNTACONTADOR AS

FUNCTION OBTENERWMESES(WDIAS NUMBER) RETURN NUMBER IS
WMESES NUMBER;
WDIAS1 NUMBER;
WDIAS2 NUMBER;
WDIAS3 NUMBER;
BEGIN
    WDIAS1:=WDIAS*12/365; 
    WDIAS2:=TRUNC(WDIAS1); 
    WDIAS3:=WDIAS1-WDIAS2; 
    WMESES:=WDIAS1; 
    IF WDIAS3<0.10 THEN 
       WMESES:=WDIAS2; 
    END IF; 
    IF WDIAS3>0.45 AND WDIAS3<0.55 THEN 
       WMESES:=WDIAS2+0.50; 
    END IF; 
    IF WDIAS3>0.90 THEN 
       WMESES:=WDIAS2+1; 
    END IF; 

   RETURN ROUND(WMESES,6);
   EXCEPTION
     WHEN NO_DATA_FOUND THEN
       NULL;
     WHEN OTHERS THEN
       NULL;
END;

FUNCTION OBTENERWCONSUMES(WDIAS NUMBER, WLECTURA NUMBER) RETURN NUMBER IS
WMESES NUMBER;
WCONSUMES NUMBER;

BEGIN

    WMESES := OBTENERWMESES(WDIAS);

    IF WMESES<1 THEN 
          WCONSUMES:=WLECTURA; 
    ELSE WCONSUMES:=WLECTURA/WMESES; 
    END IF; 
   RETURN ROUND(WCONSUMES,6);
   EXCEPTION
     WHEN NO_DATA_FOUND THEN
       NULL;
     WHEN OTHERS THEN
       NULL;
END;

END;
/
