--
-- SEQ_EDI_AUDITORIA  (Sequence) 
--
CREATE SEQUENCE SEQ_EDI_AUDITORIA
  START WITH 1
  MAXVALUE 9999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER;


--
-- SEQ_EDI_MENSAJE  (Sequence) 
--
CREATE SEQUENCE SEQ_EDI_MENSAJE
  START WITH 1
  MAXVALUE 9999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER;


--
-- SEQ_EDI_MENSAJE_ERROR  (Sequence) 
--
CREATE SEQUENCE SEQ_EDI_MENSAJE_ERROR
  START WITH 1
  MAXVALUE 9999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER;


--
-- SEQ_EDI_MENSAJE_ESCALA  (Sequence) 
--
CREATE SEQUENCE SEQ_EDI_MENSAJE_ESCALA
  START WITH 1
  MAXVALUE 9999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER;


--
-- SEQ_GE_CAMBIO  (Sequence) 
--
CREATE SEQUENCE SEQ_GE_CAMBIO
  START WITH 1
  MAXVALUE 9999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER;


--
-- SEQ_GE_CONTROL_CAMBIO  (Sequence) 
--
CREATE SEQUENCE SEQ_GE_CONTROL_CAMBIO
  START WITH 1
  MAXVALUE 9999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER;


--
-- SEQ_GE_NOTIFICACION  (Sequence) 
--
CREATE SEQUENCE SEQ_GE_NOTIFICACION
  START WITH 1
  MAXVALUE 9999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER;


--
-- SEQ_GE_NOTIFICACION_CUERPO  (Sequence) 
--
CREATE SEQUENCE SEQ_GE_NOTIFICACION_CUERPO
  START WITH 1
  MAXVALUE 9999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER;


--
-- SEQ_GE_PROCESO  (Sequence) 
--
CREATE SEQUENCE SEQ_GE_PROCESO
  START WITH 1
  MAXVALUE 9999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER;


--
-- SEQ_INT_SINCRONIZACION  (Sequence) 
--
CREATE SEQUENCE SEQ_INT_SINCRONIZACION
  START WITH 1
  MAXVALUE 999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER;


--
-- SEQ_TMP_PUBLISH_AUDIT_DATOS  (Sequence) 
--
CREATE SEQUENCE SEQ_TMP_PUBLISH_AUDIT_DATOS
  START WITH 1
  MAXVALUE 9999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER;
