--
-- B4_BUQUEPESQUERO_SRV  (Trigger) 
--
CREATE OR REPLACE TRIGGER "B4_BUQUEPESQUERO_SRV" 
BEFORE INSERT
ON B4_BUQUEPESQUERO REFERENCING NEW AS New OLD AS Old
FOR EACH ROW
DECLARE
BEGIN
   :NEW.GUIDSRV := SYS_GUID();

   EXCEPTION
     WHEN OTHERS THEN
       RAISE;
END ;
/


--
-- B4_MANIFIESTO_SRV  (Trigger) 
--
CREATE OR REPLACE TRIGGER "B4_MANIFIESTO_SRV" 
BEFORE INSERT
ON B4_MANIFIESTO REFERENCING NEW AS New OLD AS Old
FOR EACH ROW
DECLARE
V_REF NUMBER(9);
V_CODTIPOMANIFIESTO VARCHAR2(1 BYTE);
V_ANYO INTEGER;
BEGIN
    V_CODTIPOMANIFIESTO := :NEW.CODTIPOMANIFIESTO;
    V_ANYO := :NEW.ANYO;
   :NEW.GUIDSRV := SYS_GUID();
   EXECUTE IMMEDIATE 'SELECT NVL(COUNT(1),0)+1 FROM B4_MANIFIESTO WHERE CODTIPOMANIFIESTO=:1 AND ANYO=:2' INTO V_REF USING V_CODTIPOMANIFIESTO,V_ANYO ;
   :NEW.REFERENCIA := V_REF;
   EXCEPTION
     WHEN OTHERS THEN
       RAISE;
END ;
/


--
-- DIVERSO_GENERICO_SRV  (Trigger) 
--
CREATE OR REPLACE TRIGGER "DIVERSO_GENERICO_SRV" 
BEFORE INSERT
ON DIVERSO_GENERICO REFERENCING NEW AS New OLD AS Old
FOR EACH ROW
DECLARE
BEGIN
   :NEW.GUIDSRV := SYS_GUID();

   EXCEPTION
     WHEN OTHERS THEN
       RAISE;
END ;
/


--
-- DIVERSO_PERIODICO_SRV  (Trigger) 
--
CREATE OR REPLACE TRIGGER "DIVERSO_PERIODICO_SRV" 
BEFORE INSERT
ON DIVERSO_PERIODICO REFERENCING NEW AS New OLD AS Old
FOR EACH ROW
DECLARE
BEGIN
   :NEW.GUIDSRV := SYS_GUID();

   EXCEPTION
     WHEN OTHERS THEN
       RAISE;
END ;
/


--
-- DP_CANONACTIV_SRV  (Trigger) 
--
CREATE OR REPLACE TRIGGER "DP_CANONACTIV_SRV" 
BEFORE INSERT
ON DP_CANONACTIV
REFERENCING NEW AS New OLD AS Old
FOR EACH ROW
DECLARE
BEGIN
   :NEW.GUIDSRV := SYS_GUID();

   EXCEPTION
     WHEN OTHERS THEN
       RAISE;
END ;
/


--
-- DP_CANONOCUPACION_SRV  (Trigger) 
--
CREATE OR REPLACE TRIGGER "DP_CANONOCUPACION_SRV" 
BEFORE INSERT
ON DP_CANONOCUPACION
REFERENCING NEW AS New OLD AS Old
FOR EACH ROW
DECLARE
BEGIN
   :NEW.GUIDSRV := SYS_GUID();

   EXCEPTION
     WHEN OTHERS THEN
       RAISE;
END ;
/


--
-- DP_EXPCONTADORAGUA_SRV  (Trigger) 
--
CREATE OR REPLACE TRIGGER "DP_EXPCONTADORAGUA_SRV" 
BEFORE INSERT
ON DP_EXPCONTADORAGUA REFERENCING NEW AS New OLD AS Old
FOR EACH ROW
DECLARE
BEGIN
   :NEW.GUIDSRV := SYS_GUID();

   EXCEPTION
     WHEN OTHERS THEN
       RAISE;
END ;
/


--
-- DP_EXPEDIENTE_SRV  (Trigger) 
--
CREATE OR REPLACE TRIGGER "DP_EXPEDIENTE_SRV" 
BEFORE INSERT
ON DP_EXPEDIENTE
REFERENCING NEW AS New OLD AS Old
FOR EACH ROW
DECLARE
BEGIN
   :NEW.GUIDSRV := SYS_GUID();

   EXCEPTION
     WHEN OTHERS THEN
       RAISE;
END ;
/


--
-- DP_MEJORACONCURSO_SRV  (Trigger) 
--
CREATE OR REPLACE TRIGGER "DP_MEJORACONCURSO_SRV" 
BEFORE INSERT ON DP_MEJORACONCURSO REFERENCING NEW AS New OLD AS Old
FOR EACH ROW
DECLARE
BEGIN
   :NEW.GUIDSRV := SYS_GUID();

   EXCEPTION
     WHEN OTHERS THEN
       RAISE;
END ;
/


--
-- ESCALA_SRV  (Trigger) 
--
CREATE OR REPLACE TRIGGER "ESCALA_SRV" 
BEFORE INSERT
ON ESCALA 
REFERENCING NEW AS New OLD AS Old
FOR EACH ROW
DECLARE
BEGIN
   :NEW.GUIDSRV := SYS_GUID();

   EXCEPTION
     WHEN OTHERS THEN
       -- Consider logging the error and then re-raise
       RAISE;
END ;
/


--
-- EXPAGUA_NODP_CONTADOR_SRV  (Trigger) 
--
CREATE OR REPLACE TRIGGER "EXPAGUA_NODP_CONTADOR_SRV" 
BEFORE INSERT
ON EXPAGUA_NODP_CONTADOR REFERENCING NEW AS New OLD AS Old
FOR EACH ROW
DECLARE
BEGIN
   :NEW.GUIDSRV := SYS_GUID();

   EXCEPTION
     WHEN OTHERS THEN
       RAISE;
END ;
/


--
-- EXPAGUA_NODP_SRV  (Trigger) 
--
CREATE OR REPLACE TRIGGER "EXPAGUA_NODP_SRV" 
BEFORE INSERT
ON EXPAGUA_NODP REFERENCING NEW AS New OLD AS Old
FOR EACH ROW
DECLARE
BEGIN
   :NEW.GUIDSRV := SYS_GUID();

   EXCEPTION
     WHEN OTHERS THEN
       RAISE;
END ;
/


--
-- G0_PESCALITORAL_SRV  (Trigger) 
--
CREATE OR REPLACE TRIGGER "G0_PESCALITORAL_SRV" 
BEFORE INSERT
ON G0_PESCALITORAL
REFERENCING NEW AS New OLD AS Old
FOR EACH ROW
DECLARE
BEGIN
   :NEW.GUIDSRV := SYS_GUID();

   EXCEPTION
     WHEN OTHERS THEN
       RAISE;
END ;
/


--
-- G3_CABECERA_SRV  (Trigger) 
--
CREATE OR REPLACE TRIGGER "G3_CABECERA_SRV" 
BEFORE INSERT
ON G3_CABECERA
REFERENCING NEW AS New OLD AS Old
FOR EACH ROW
DECLARE
BEGIN
   :NEW.GUIDSRV := SYS_GUID();

   EXCEPTION
     WHEN OTHERS THEN
       -- Consider logging the error and then re-raise
       RAISE;
END ;
/


--
-- G3_TRAFINT_SRV  (Trigger) 
--
CREATE OR REPLACE TRIGGER "G3_TRAFINT_SRV" 
BEFORE INSERT
ON G3_TRAFINT REFERENCING NEW AS New OLD AS Old
FOR EACH ROW
DECLARE
BEGIN
   :NEW.GUIDSRV := SYS_GUID();

   EXCEPTION
     WHEN OTHERS THEN
       -- Consider logging the error and then re-raise
       RAISE;
END ;
/


--
-- G3_TRAMO_SRV  (Trigger) 
--
CREATE OR REPLACE TRIGGER "G3_TRAMO_SRV" 
BEFORE INSERT
ON G3_TRAMO
REFERENCING NEW AS New OLD AS Old
FOR EACH ROW
DECLARE
BEGIN
   :NEW.GUIDSRV := SYS_GUID();

   EXCEPTION
     WHEN OTHERS THEN
       -- Consider logging the error and then re-raise
       RAISE;
END ;
/


--
-- G4_PESCA_SRV  (Trigger) 
--
CREATE OR REPLACE TRIGGER "G4_PESCA_SRV" 
BEFORE INSERT
ON G4_PESCA
REFERENCING NEW AS New OLD AS Old
FOR EACH ROW
DECLARE
BEGIN
   :NEW.GUIDSRV := SYS_GUID();

   EXCEPTION
     WHEN OTHERS THEN
       RAISE;
END ;
/


--
-- G5_BASE_CONTADOR_SRV  (Trigger) 
--
CREATE OR REPLACE TRIGGER "G5_BASE_CONTADOR_SRV" 
BEFORE INSERT
ON G5_BASE_CONTADOR REFERENCING NEW AS New OLD AS Old
FOR EACH ROW
DECLARE
BEGIN
   :NEW.GUIDSRV := SYS_GUID();

   EXCEPTION
     WHEN OTHERS THEN
       RAISE;
END ;
/


--
-- G5_EXPGESTDIRECTA_SRV  (Trigger) 
--
CREATE OR REPLACE TRIGGER "G5_EXPGESTDIRECTA_SRV" 
BEFORE INSERT
ON G5_EXPGESTDIRECTA
REFERENCING NEW AS New OLD AS Old
FOR EACH ROW
DECLARE
BEGIN
   :NEW.GUIDSRV := SYS_GUID();

   EXCEPTION
     WHEN OTHERS THEN
       RAISE;
END ;
/


--
-- G5_MARINA_SRV  (Trigger) 
--
CREATE OR REPLACE TRIGGER "G5_MARINA_SRV" 
BEFORE INSERT
ON G5_MARINA
REFERENCING NEW AS New OLD AS Old
FOR EACH ROW
DECLARE
BEGIN
   :NEW.GUIDSRV := SYS_GUID();

   EXCEPTION
     WHEN OTHERS THEN
       RAISE;
END ;
/


--
-- G5_TRANSITO_SRV  (Trigger) 
--
CREATE OR REPLACE TRIGGER "G5_TRANSITO_SRV" 
BEFORE INSERT
ON G5_TRANSITO REFERENCING NEW AS New OLD AS Old
FOR EACH ROW
DECLARE
BEGIN
   :NEW.GUIDSRV := SYS_GUID();

   EXCEPTION
     WHEN OTHERS THEN
       RAISE;
END ;
/


--
-- M_BUQUECERT_SRV  (Trigger) 
--
CREATE OR REPLACE TRIGGER "M_BUQUECERT_SRV" 
BEFORE INSERT
ON M_BUQUECERT REFERENCING NEW AS New OLD AS Old
FOR EACH ROW
DECLARE
BEGIN
   :NEW.GUIDSRV := SYS_GUID();

   EXCEPTION
     WHEN OTHERS THEN
       RAISE;
END ;
/


--
-- M_CONTADOR_SRV  (Trigger) 
--
CREATE OR REPLACE TRIGGER "M_CONTADOR_SRV" 
BEFORE INSERT
ON M_CONTADOR REFERENCING NEW AS New OLD AS Old
FOR EACH ROW
DECLARE
BEGIN
   :NEW.GUIDSRV := SYS_GUID();

   EXCEPTION
     WHEN OTHERS THEN
       RAISE;
END ;
/


--
-- OCUPSUPBUQUE_SRV  (Trigger) 
--
CREATE OR REPLACE TRIGGER "OCUPSUPBUQUE_SRV" 
BEFORE INSERT
ON OCUPSUPBUQUE REFERENCING NEW AS New OLD AS Old
FOR EACH ROW
DECLARE
BEGIN
   :NEW.GUIDSRV := SYS_GUID();

   EXCEPTION
     WHEN OTHERS THEN
       -- Consider logging the error and then re-raise
       RAISE;
END ;
/


--
-- OCUPSUP_RODANTE_SRV  (Trigger) 
--
CREATE OR REPLACE TRIGGER "OCUPSUP_RODANTE_SRV" 
BEFORE INSERT
ON OCUPSUP_RODANTE REFERENCING NEW AS New OLD AS Old
FOR EACH ROW
DECLARE
BEGIN
   :NEW.GUIDSRV := SYS_GUID();

   EXCEPTION
     WHEN OTHERS THEN
       RAISE;
END ;
/


--
-- OPERACION_SRV  (Trigger) 
--
CREATE OR REPLACE TRIGGER "OPERACION_SRV" 
BEFORE INSERT
ON OPERACION
REFERENCING NEW AS New OLD AS Old
FOR EACH ROW
DECLARE
BEGIN
   :NEW.GUIDSRV := SYS_GUID();

   EXCEPTION
     WHEN OTHERS THEN
       -- Consider logging the error and then re-raise
       RAISE;
END ;
/


--
-- SAN_EXPEDIENTE  (Trigger) 
--
CREATE OR REPLACE TRIGGER "SAN_EXPEDIENTE" 
BEFORE INSERT
ON SAN_EXPEDIENTE REFERENCING NEW AS New OLD AS Old
FOR EACH ROW
DECLARE
BEGIN
   :NEW.GUIDSRV := SYS_GUID();

   EXCEPTION
     WHEN OTHERS THEN
       RAISE;
END ;
/


--
-- SERVBAS_AMARRE_SRV  (Trigger) 
--
CREATE OR REPLACE TRIGGER "SERVBAS_AMARRE_SRV" 
BEFORE INSERT
ON SERVBAS_AMARRE REFERENCING NEW AS New OLD AS Old
FOR EACH ROW
DECLARE
BEGIN
   :NEW.GUIDSRV := SYS_GUID();

   EXCEPTION
     WHEN OTHERS THEN
       -- Consider logging the error and then re-raise
       RAISE;
END ;
/


--
-- SERVBAS_PRACTICAJE_SRV  (Trigger) 
--
CREATE OR REPLACE TRIGGER "SERVBAS_PRACTICAJE_SRV" 
BEFORE INSERT
ON SERVBAS_PRACTICAJE REFERENCING NEW AS New OLD AS Old
FOR EACH ROW
DECLARE
BEGIN
   :NEW.GUIDSRV := SYS_GUID();

   EXCEPTION
     WHEN OTHERS THEN
       -- Consider logging the error and then re-raise
       RAISE;
END ;
/


--
-- SERVBAS_REMOLCADOR_SRV  (Trigger) 
--
CREATE OR REPLACE TRIGGER "SERVBAS_REMOLCADOR_SRV" 
BEFORE INSERT
ON SERVBAS_REMOLCADOR REFERENCING NEW AS New OLD AS Old
FOR EACH ROW
DECLARE
BEGIN
   :NEW.GUIDSRV := SYS_GUID();

   EXCEPTION
     WHEN OTHERS THEN
       -- Consider logging the error and then re-raise
       RAISE;
END ;
/


--
-- SGC_MAQUINARIA_SRV  (Trigger) 
--
CREATE OR REPLACE TRIGGER SGC_MAQUINARIA_SRV BEFORE INSERT
ON SGC_MAQUINARIA REFERENCING NEW AS New OLD AS Old
FOR EACH ROW
DECLARE
BEGIN
   :NEW.GUIDSRV := SYS_GUID();

   EXCEPTION
     WHEN OTHERS THEN
       RAISE;
END ;
/


--
-- T0_EMBDEPBASENOAP_SRV  (Trigger) 
--
CREATE OR REPLACE TRIGGER "T0_EMBDEPBASENOAP_SRV" 
BEFORE INSERT
ON T0_EMBDEPBASENOAP REFERENCING NEW AS New OLD AS Old
FOR EACH ROW
DECLARE
BEGIN
   :NEW.GUIDSRV := SYS_GUID();

   EXCEPTION
     WHEN OTHERS THEN
       RAISE;
END ;
/


--
-- T2_EXCURSIONISTA_SRV  (Trigger) 
--
CREATE OR REPLACE TRIGGER "T2_EXCURSIONISTA_SRV" 
BEFORE INSERT
ON T2_EXCURSIONISTA 
REFERENCING NEW AS New OLD AS Old
FOR EACH ROW
DECLARE
BEGIN
   :NEW.GUIDSRV := SYS_GUID();

   EXCEPTION
     WHEN OTHERS THEN
       -- Consider logging the error and then re-raise
       RAISE;
END ;
/


--
-- T3_SUMINTRAFINT_SRV  (Trigger) 
--
CREATE OR REPLACE TRIGGER "T3_SUMINTRAFINT_SRV" 
BEFORE INSERT
ON T3_SUMINTRAFINT 
REFERENCING NEW AS New OLD AS Old
FOR EACH ROW
DECLARE
BEGIN
   :NEW.GUIDSRV := SYS_GUID();

   EXCEPTION
     WHEN OTHERS THEN
       -- Consider logging the error and then re-raise
       RAISE;
END ;
/


--
-- T8_SUMINBUQUE_SRV  (Trigger) 
--
CREATE OR REPLACE TRIGGER "T8_SUMINBUQUE_SRV" 
BEFORE INSERT
ON T8_SUMINBUQUE REFERENCING NEW AS New OLD AS Old
FOR EACH ROW
DECLARE
BEGIN
   :NEW.GUIDSRV := SYS_GUID();

   EXCEPTION
     WHEN OTHERS THEN
       RAISE;
END ;
/


--
-- T8_SUMINGENERICO_SRV  (Trigger) 
--
CREATE OR REPLACE TRIGGER "T8_SUMINGENERICO_SRV" 
BEFORE INSERT
ON T8_SUMINGENERICO REFERENCING NEW AS New OLD AS Old
FOR EACH ROW
DECLARE
BEGIN
   :NEW.GUIDSRV := SYS_GUID();

   EXCEPTION
     WHEN OTHERS THEN
       RAISE;
END ;
/


--
-- T8_SUMININSTFIJA_SRV  (Trigger) 
--
CREATE OR REPLACE TRIGGER "T8_SUMININSTFIJA_SRV" 
BEFORE INSERT
ON T8_SUMININSTFIJA REFERENCING NEW AS New OLD AS Old
FOR EACH ROW
DECLARE
BEGIN
   :NEW.GUIDSRV := SYS_GUID();

   EXCEPTION
     WHEN OTHERS THEN
       RAISE;
END ;
/
