-- SELECT COUNT(1) FROM tbl_traduccion_ids_trid;
-- SELECT * FROM tbl_traduccion_ids_trid;
-- SELECT * FROM tbl_traduccion_ids_trid WHERE TRID_TABLE_NAME = 'IAUD_EVENTO_AEVT' and TRID_OLD_ID = 23601;

INSERT INTO tbl_traduccion_ids_trid (trid_old_id, trid_new_id, trid_table_name) SELECT amat_id, seq_migracion.nextval, 'IAMA_AMARREMEDIOTIPO_AMAT' FROM IAMA_AMARREMEDIOTIPO_AMAT;
INSERT INTO tbl_traduccion_ids_trid (trid_old_id, trid_new_id, trid_table_name) SELECT amam_id, seq_migracion.nextval, 'IAMA_AMARREMEDIO_AMAM' FROM IAMA_AMARREMEDIO_AMAM;
INSERT INTO tbl_traduccion_ids_trid (trid_old_id, trid_new_id, trid_table_name) SELECT amar_id, seq_migracion.nextval, 'IAMA_AMARRE_AMAR' FROM IAMA_AMARRE_AMAR;
INSERT INTO tbl_traduccion_ids_trid (trid_old_id, trid_new_id, trid_table_name) SELECT ammt_id, seq_migracion.nextval, 'IAMA_MOVIMIENTOTIPO_AMMT' FROM IAMA_MOVIMIENTOTIPO_AMMT;
-- INSERT INTO tbl_traduccion_ids_trid (trid_old_id, trid_new_id, trid_table_name) SELECT aevt_id, seq_migracion.nextval, 'IAUD_EVENTO_AEVT' FROM IAUD_EVENTO_AEVT;
INSERT INTO tbl_traduccion_ids_trid (trid_old_id, trid_new_id, trid_table_name) SELECT viat_id, seq_migracion.nextval, 'IAUD_VISATRIBUTO_VIAT' FROM IAUD_VISATRIBUTO_VIAT;
INSERT INTO tbl_traduccion_ids_trid (trid_old_id, trid_new_id, trid_table_name) SELECT coad_id, seq_migracion.nextval, 'ICEN_CONSEJO_COAD' FROM ICEN_CONSEJO_COAD;
INSERT INTO tbl_traduccion_ids_trid (trid_old_id, trid_new_id, trid_table_name) SELECT dcec_id, seq_migracion.nextval, 'ICEN_DIRECCION_CONT_DCEC' FROM ICEN_DIRECCION_CONT_DCEC;
INSERT INTO tbl_traduccion_ids_trid (trid_old_id, trid_new_id, trid_table_name) SELECT dnec_id, seq_migracion.nextval, 'ICEN_DIRECCION_NOTI_DNEC' FROM ICEN_DIRECCION_NOTI_DNEC;
INSERT INTO tbl_traduccion_ids_trid (trid_old_id, trid_new_id, trid_table_name) SELECT dced_id, seq_migracion.nextval, 'ICEN_DOCUMENTODATA_DCED' FROM ICEN_DOCUMENTODATA_DCED;
INSERT INTO tbl_traduccion_ids_trid (trid_old_id, trid_new_id, trid_table_name) SELECT dcen_id, seq_migracion.nextval, 'ICEN_DOCUMENTO_DCEN' FROM ICEN_DOCUMENTO_DCEN;
INSERT INTO tbl_traduccion_ids_trid (trid_old_id, trid_new_id, trid_table_name) SELECT empc_id, seq_migracion.nextval, 'ICEN_EMPLEADO_EMPC' FROM ICEN_EMPLEADO_EMPC;
INSERT INTO tbl_traduccion_ids_trid (trid_old_id, trid_new_id, trid_table_name) SELECT emce_id, seq_migracion.nextval, 'ICEN_EMPRESACENSADA_EMCE' FROM ICEN_EMPRESACENSADA_EMCE;
INSERT INTO tbl_traduccion_ids_trid (trid_old_id, trid_new_id, trid_table_name) SELECT epig_id, seq_migracion.nextval, 'ICEN_EPIGRAFE_EPIG' FROM ICEN_EPIGRAFE_EPIG;
INSERT INTO tbl_traduccion_ids_trid (trid_old_id, trid_new_id, trid_table_name) SELECT exco_id, seq_migracion.nextval, 'ICEN_EXPEDIENTECONSEJO_EXCO' FROM ICEN_EXPEDIENTECONSEJO_EXCO;
INSERT INTO tbl_traduccion_ids_trid (trid_old_id, trid_new_id, trid_table_name) SELECT seem_subp_id, seq_migracion.nextval, 'ICEN_SECUENCIA_EMPRESA_SEEM' FROM ICEN_SECUENCIA_EMPRESA_SEEM;
INSERT INTO tbl_traduccion_ids_trid (trid_old_id, trid_new_id, trid_table_name) SELECT veec_id, seq_migracion.nextval, 'ICEN_VEHICULO_VEEC' FROM ICEN_VEHICULO_VEEC;
INSERT INTO tbl_traduccion_ids_trid (trid_old_id, trid_new_id, trid_table_name) SELECT orgt_id, seq_migracion.nextval, 'ICOM_ORGANIZACIONTIPO_ORGT' FROM ICOM_ORGANIZACIONTIPO_ORGT;
INSERT INTO tbl_traduccion_ids_trid (trid_old_id, trid_new_id, trid_table_name) SELECT orga_id, seq_migracion.nextval, 'ICOM_ORGANIZACION_ORGA' FROM ICOM_ORGANIZACION_ORGA;
INSERT INTO tbl_traduccion_ids_trid (trid_old_id, trid_new_id, trid_table_name) SELECT perm_id, seq_migracion.nextval, 'ICOM_PERMISO_PERM' FROM ICOM_PERMISO_PERM;
INSERT INTO tbl_traduccion_ids_trid (trid_old_id, trid_new_id, trid_table_name) SELECT pret_id, seq_migracion.nextval, 'ICOM_PRESTADORTIPO_PRET' FROM ICOM_PRESTADORTIPO_PRET;
INSERT INTO tbl_traduccion_ids_trid (trid_old_id, trid_new_id, trid_table_name) SELECT serv_id, seq_migracion.nextval, 'ICOM_SERVICIO_SERV' FROM ICOM_SERVICIO_SERV;
INSERT INTO tbl_traduccion_ids_trid (trid_old_id, trid_new_id, trid_table_name) SELECT tvia_id, seq_migracion.nextval, 'ICOM_TIPOVIA_TVIA' FROM ICOM_TIPOVIA_TVIA;
INSERT INTO tbl_traduccion_ids_trid (trid_old_id, trid_new_id, trid_table_name) SELECT usut_id, seq_migracion.nextval, 'ICOM_USUARIOTIPO_USUT' FROM ICOM_USUARIOTIPO_USUT;
INSERT INTO tbl_traduccion_ids_trid (trid_old_id, trid_new_id, trid_table_name) SELECT usua_id, seq_migracion.nextval, 'ICOM_USUARIO_USUA' FROM ICOM_USUARIO_USUA;
INSERT INTO tbl_traduccion_ids_trid (trid_old_id, trid_new_id, trid_table_name) SELECT acci_id, seq_migracion.nextval, 'ICON_ACCION_ACCI' FROM ICON_ACCION_ACCI;
INSERT INTO tbl_traduccion_ids_trid (trid_old_id, trid_new_id, trid_table_name) SELECT codr_id, seq_migracion.nextval, 'ICON_CODIGOREFERENCIA_CODR' FROM ICON_CODIGOREFERENCIA_CODR;
INSERT INTO tbl_traduccion_ids_trid (trid_old_id, trid_new_id, trid_table_name) SELECT conf_id, seq_migracion.nextval, 'ICON_CONFIGURACION_CONF' FROM ICON_CONFIGURACION_CONF;
INSERT INTO tbl_traduccion_ids_trid (trid_old_id, trid_new_id, trid_table_name) SELECT eatf_id, seq_migracion.nextval, 'ICON_ENTIDADATRIBUTOFILTR_EATF' FROM ICON_ENTIDADATRIBUTOFILTR_EATF;
INSERT INTO tbl_traduccion_ids_trid (trid_old_id, trid_new_id, trid_table_name) SELECT eatt_id, seq_migracion.nextval, 'ICON_ENTIDADATRIBUTO_EATT' FROM ICON_ENTIDADATRIBUTO_EATT;
INSERT INTO tbl_traduccion_ids_trid (trid_old_id, trid_new_id, trid_table_name) SELECT ente_id, seq_migracion.nextval, 'ICON_ENTIDAD_ENTE' FROM ICON_ENTIDAD_ENTE;
INSERT INTO tbl_traduccion_ids_trid (trid_old_id, trid_new_id, trid_table_name) SELECT fcat_id, seq_migracion.nextval, 'ICON_FILTROCONFIGATRIBUTO_FCAT' FROM ICON_FILTROCONFIGATRIBUTO_FCAT;
-- OJO!!!!
-- INSERT INTO tbl_traduccion_ids_trid (trid_old_id, trid_new_id, trid_table_name) SELECT fcon_id, seq_migracion.nextval, 'ICON_FILTROCONFIGURACION_FCON' FROM ICON_FILTROCONFIGURACION_FCON;
INSERT INTO tbl_traduccion_ids_trid (trid_old_id, trid_new_id, trid_table_name) SELECT fatt_id, seq_migracion.nextval, 'ICON_FILTROELEMENTO_FATT' FROM ICON_FILTROELEMENTO_FATT;
INSERT INTO tbl_traduccion_ids_trid (trid_old_id, trid_new_id, trid_table_name) SELECT filt_id, seq_migracion.nextval, 'ICON_FILTRO_FILT' FROM ICON_FILTRO_FILT;

INSERT INTO tbl_traduccion_ids_trid (trid_old_id, trid_new_id, trid_table_name) SELECT modb_id, seq_migracion.nextval, 'ICON_MODULOBATCH_MODB' FROM ICON_MODULOBATCH_MODB;
INSERT INTO tbl_traduccion_ids_trid (trid_old_id, trid_new_id, trid_table_name) SELECT modu_id, seq_migracion.nextval, 'ICON_MODULO_MODU' FROM ICON_MODULO_MODU;

INSERT INTO tbl_traduccion_ids_trid (trid_old_id, trid_new_id, trid_table_name) SELECT dore_id, seq_migracion.nextval, 'IDIV_DOMINIOREF_DORE' FROM IDIV_DOMINIOREF_DORE;
INSERT INTO tbl_traduccion_ids_trid (trid_old_id, trid_new_id, trid_table_name) SELECT elva_id, seq_migracion.nextval, 'IDIV_ELEMENTOVAR_ELVA' FROM IDIV_ELEMENTOVAR_ELVA;
INSERT INTO tbl_traduccion_ids_trid (trid_old_id, trid_new_id, trid_table_name) SELECT lsdi_id, seq_migracion.nextval, 'IDIV_LINEASERVICIODIV_LSDI' FROM IDIV_LINEASERVICIODIV_LSDI;
INSERT INTO tbl_traduccion_ids_trid (trid_old_id, trid_new_id, trid_table_name) SELECT sedi_id, seq_migracion.nextval, 'IDIV_SERVICIODIV_SEDI' FROM IDIV_SERVICIODIV_SEDI;
INSERT INTO tbl_traduccion_ids_trid (trid_old_id, trid_new_id, trid_table_name) SELECT tsdi_id, seq_migracion.nextval, 'IDIV_TIPOSERVICIODIV_TSDI' FROM IDIV_TIPOSERVICIODIV_TSDI;
INSERT INTO tbl_traduccion_ids_trid (trid_old_id, trid_new_id, trid_table_name) SELECT vdre_id, seq_migracion.nextval, 'IDIV_VALORDOMINIOREF_VDRE' FROM IDIV_VALORDOMINIOREF_VDRE;

INSERT INTO tbl_traduccion_ids_trid (trid_old_id, trid_new_id, trid_table_name) SELECT docd_id, seq_migracion.nextval, 'IDOC_DOCUMENTODATA_DOCD' FROM IDOC_DOCUMENTODATA_DOCD;
INSERT INTO tbl_traduccion_ids_trid (trid_old_id, trid_new_id, trid_table_name) SELECT documentotipo_accion_id, seq_migracion.nextval, 'IDOC_DOCUMENTOTIPO_ACCION' FROM IDOC_DOCUMENTOTIPO_ACCION;
INSERT INTO tbl_traduccion_ids_trid (trid_old_id, trid_new_id, trid_table_name) SELECT doct_id, seq_migracion.nextval, 'IDOC_DOCUMENTOTIPO_DOCT' FROM IDOC_DOCUMENTOTIPO_DOCT;
INSERT INTO tbl_traduccion_ids_trid (trid_old_id, trid_new_id, trid_table_name) SELECT documento_accion_id, seq_migracion.nextval, 'IDOC_DOCUMENTO_ACCION' FROM IDOC_DOCUMENTO_ACCION;
INSERT INTO tbl_traduccion_ids_trid (trid_old_id, trid_new_id, trid_table_name) SELECT docu_id, seq_migracion.nextval, 'IDOC_DOCUMENTO_DOCU' FROM IDOC_DOCUMENTO_DOCU;

INSERT INTO tbl_traduccion_ids_trid (trid_old_id, trid_new_id, trid_table_name) SELECT amad_id, seq_migracion.nextval, 'IEMD_AMARRE_AMAD' FROM IEMD_AMARRE_AMAD;
INSERT INTO tbl_traduccion_ids_trid (trid_old_id, trid_new_id, trid_table_name) SELECT asam_id, seq_migracion.nextval, 'IEMD_ASIGNACIONAMARRE_ASAM' FROM IEMD_ASIGNACIONAMARRE_ASAM;
INSERT INTO tbl_traduccion_ids_trid (trid_old_id, trid_new_id, trid_table_name) SELECT eacl_id, seq_migracion.nextval, 'IEMD_EMBARCACIONAUTCLI_EACL' FROM IEMD_EMBARCACIONAUTCLI_EACL;
INSERT INTO tbl_traduccion_ids_trid (trid_old_id, trid_new_id, trid_table_name) SELECT emba_id, seq_migracion.nextval, 'IEMD_EMBARCACIONAUT_EMBA' FROM IEMD_EMBARCACIONAUT_EMBA;
INSERT INTO tbl_traduccion_ids_trid (trid_old_id, trid_new_id, trid_table_name) SELECT embd_id, seq_migracion.nextval, 'IEMD_EMBARCACION_EMBD' FROM IEMD_EMBARCACION_EMBD;
INSERT INTO tbl_traduccion_ids_trid (trid_old_id, trid_new_id, trid_table_name) SELECT inda_id, seq_migracion.nextval, 'IEMD_INSTALACIONDEPA_INDA' FROM IEMD_INSTALACIONDEPA_INDA;
INSERT INTO tbl_traduccion_ids_trid (trid_old_id, trid_new_id, trid_table_name) SELECT indp_id, seq_migracion.nextval, 'IEMD_INSTALACIONDEP_INDP' FROM IEMD_INSTALACIONDEP_INDP;
INSERT INTO tbl_traduccion_ids_trid (trid_old_id, trid_new_id, trid_table_name) SELECT ipam_id, seq_migracion.nextval, 'IEMD_INSTPETICIONAMARRE_IPAM' FROM IEMD_INSTPETICIONAMARRE_IPAM;
INSERT INTO tbl_traduccion_ids_trid (trid_old_id, trid_new_id, trid_table_name) SELECT peam_id, seq_migracion.nextval, 'IEMD_PETICIONAMARRE_PEAM' FROM IEMD_PETICIONAMARRE_PEAM;
INSERT INTO tbl_traduccion_ids_trid (trid_old_id, trid_new_id, trid_table_name) SELECT sdep_id, seq_migracion.nextval, 'IEMD_SERVICIODEP_SDEP' FROM IEMD_SERVICIODEP_SDEP;
INSERT INTO tbl_traduccion_ids_trid (trid_old_id, trid_new_id, trid_table_name) SELECT seda_id, seq_migracion.nextval, 'IEMD_SERVICIOEMBAUT_SEDA' FROM IEMD_SERVICIOEMBAUT_SEDA;
INSERT INTO tbl_traduccion_ids_trid (trid_old_id, trid_new_id, trid_table_name) SELECT tamd_id, seq_migracion.nextval, 'IEMD_TIPOAMARRE_TAMD' FROM IEMD_TIPOAMARRE_TAMD;
INSERT INTO tbl_traduccion_ids_trid (trid_old_id, trid_new_id, trid_table_name) SELECT temd_id, seq_migracion.nextval, 'IEMD_TIPOEMBARCACION_TEMD' FROM IEMD_TIPOEMBARCACION_TEMD;

INSERT INTO tbl_traduccion_ids_trid (trid_old_id, trid_new_id, trid_table_name) SELECT acet_id, seq_migracion.nextval, 'IESC_ACTIVIDADEDITIPO_ACET' FROM IESC_ACTIVIDADEDITIPO_ACET;
INSERT INTO tbl_traduccion_ids_trid (trid_old_id, trid_new_id, trid_table_name) SELECT actt_id, seq_migracion.nextval, 'IESC_ACTIVIDADTIPO_ACTT' FROM IESC_ACTIVIDADTIPO_ACTT;
INSERT INTO tbl_traduccion_ids_trid (trid_old_id, trid_new_id, trid_table_name) SELECT acue_id, seq_migracion.nextval, 'IESC_ACUERDO_ACUE' FROM IESC_ACUERDO_ACUE;
INSERT INTO tbl_traduccion_ids_trid (trid_old_id, trid_new_id, trid_table_name) SELECT alit_id, seq_migracion.nextval, 'IESC_ALINEACIONTIPO_ALIT' FROM IESC_ALINEACIONTIPO_ALIT;
INSERT INTO tbl_traduccion_ids_trid (trid_old_id, trid_new_id, trid_table_name) SELECT atrd_id, seq_migracion.nextval, 'IESC_ATRAQUEDETALLE_ATRD' FROM IESC_ATRAQUEDETALLE_ATRD;
INSERT INTO tbl_traduccion_ids_trid (trid_old_id, trid_new_id, trid_table_name) SELECT atet_id, seq_migracion.nextval, 'IESC_ATRAQUEEDITIPO_ATET' FROM IESC_ATRAQUEEDITIPO_ATET;
INSERT INTO tbl_traduccion_ids_trid (trid_old_id, trid_new_id, trid_table_name) SELECT atop_id, seq_migracion.nextval, 'IESC_ATRAQUEOPERACION_ATOP' FROM IESC_ATRAQUEOPERACION_ATOP;
INSERT INTO tbl_traduccion_ids_trid (trid_old_id, trid_new_id, trid_table_name) SELECT atrt_id, seq_migracion.nextval, 'IESC_ATRAQUETIPO_ATRT' FROM IESC_ATRAQUETIPO_ATRT;
INSERT INTO tbl_traduccion_ids_trid (trid_old_id, trid_new_id, trid_table_name) SELECT atra_id, seq_migracion.nextval, 'IESC_ATRAQUE_ATRA' FROM IESC_ATRAQUE_ATRA;
INSERT INTO tbl_traduccion_ids_trid (trid_old_id, trid_new_id, trid_table_name) SELECT bqte_id, seq_migracion.nextval, 'IESC_BUQUETIPOEDI_BQTE' FROM IESC_BUQUETIPOEDI_BQTE;
INSERT INTO tbl_traduccion_ids_trid (trid_old_id, trid_new_id, trid_table_name) SELECT buqu_buque_id, seq_migracion.nextval, 'IESC_BUQUE_BUQU' FROM IESC_BUQUE_BUQU;
INSERT INTO tbl_traduccion_ids_trid (trid_old_id, trid_new_id, trid_table_name) SELECT cerb_id, seq_migracion.nextval, 'IESC_CERTIFICADOBUQUE_CERB' FROM IESC_CERTIFICADOBUQUE_CERB;
INSERT INTO tbl_traduccion_ids_trid (trid_old_id, trid_new_id, trid_table_name) SELECT cert_id, seq_migracion.nextval, 'IESC_CERTIFICADOTIPO_CERT' FROM IESC_CERTIFICADOTIPO_CERT;
INSERT INTO tbl_traduccion_ids_trid (trid_old_id, trid_new_id, trid_table_name) SELECT conv_id, seq_migracion.nextval, 'IESC_CONVENIO_CONV' FROM IESC_CONVENIO_CONV;
INSERT INTO tbl_traduccion_ids_trid (trid_old_id, trid_new_id, trid_table_name) SELECT escr_id, seq_migracion.nextval, 'IESC_ESCALARESIDUO_ESCR' FROM IESC_ESCALARESIDUO_ESCR;
INSERT INTO tbl_traduccion_ids_trid (trid_old_id, trid_new_id, trid_table_name) SELECT esca_id, seq_migracion.nextval, 'IESC_ESCALA_ESCA' FROM IESC_ESCALA_ESCA;
INSERT INTO tbl_traduccion_ids_trid (trid_old_id, trid_new_id, trid_table_name) SELECT mert_id, seq_migracion.nextval, 'IESC_MERCANCIATIPO_MERT' FROM IESC_MERCANCIATIPO_MERT;
INSERT INTO tbl_traduccion_ids_trid (trid_old_id, trid_new_id, trid_table_name) SELECT muel_id, seq_migracion.nextval, 'IESC_MUELLE_MUEL' FROM IESC_MUELLE_MUEL;
INSERT INTO tbl_traduccion_ids_trid (trid_old_id, trid_new_id, trid_table_name) SELECT navi_id, seq_migracion.nextval, 'IESC_NAVIERA_NAVI' FROM IESC_NAVIERA_NAVI;
INSERT INTO tbl_traduccion_ids_trid (trid_old_id, trid_new_id, trid_table_name) SELECT noes_id, seq_migracion.nextval, 'IESC_NOTIFICACIONES_NOES' FROM IESC_NOTIFICACIONES_NOES;
INSERT INTO tbl_traduccion_ids_trid (trid_old_id, trid_new_id, trid_table_name) SELECT ratt_id, seq_migracion.nextval, 'IESC_RELACIONATRAQUETIPO_RATT' FROM IESC_RELACIONATRAQUETIPO_RATT;
INSERT INTO tbl_traduccion_ids_trid (trid_old_id, trid_new_id, trid_table_name) SELECT ress_id, seq_migracion.nextval, 'IESC_RESIDUOSSUBTIPO_RESS' FROM IESC_RESIDUOSSUBTIPO_RESS;
INSERT INTO tbl_traduccion_ids_trid (trid_old_id, trid_new_id, trid_table_name) SELECT rest_id, seq_migracion.nextval, 'IESC_RESIDUOSTIPO_REST' FROM IESC_RESIDUOSTIPO_REST;
INSERT INTO tbl_traduccion_ids_trid (trid_old_id, trid_new_id, trid_table_name) SELECT sett_id, seq_migracion.nextval, 'IESC_SERVICIOTIPO_SETT' FROM IESC_SERVICIOTIPO_SETT;
INSERT INTO tbl_traduccion_ids_trid (trid_old_id, trid_new_id, trid_table_name) SELECT trbu_id, seq_migracion.nextval, 'IESC_TRAFICOBUQUE_TRBU' FROM IESC_TRAFICOBUQUE_TRBU;
INSERT INTO tbl_traduccion_ids_trid (trid_old_id, trid_new_id, trid_table_name) SELECT traf_id, seq_migracion.nextval, 'IESC_TRAFICO_TRAF' FROM IESC_TRAFICO_TRAF;

INSERT INTO tbl_traduccion_ids_trid (trid_old_id, trid_new_id, trid_table_name) SELECT acpe_id, seq_migracion.nextval, 'IEST_ACTIVIDADPESQUERA_ACPE' FROM IEST_ACTIVIDADPESQUERA_ACPE;
INSERT INTO tbl_traduccion_ids_trid (trid_old_id, trid_new_id, trid_table_name) SELECT ages_id, seq_migracion.nextval, 'IEST_AGREGACIONESCALA_AGES' FROM IEST_AGREGACIONESCALA_AGES;
INSERT INTO tbl_traduccion_ids_trid (trid_old_id, trid_new_id, trid_table_name) SELECT agos_id, seq_migracion.nextval, 'IEST_AGREGACIONSUPERFICIE_AGOS' FROM IEST_AGREGACIONSUPERFICIE_AGOS;
INSERT INTO tbl_traduccion_ids_trid (trid_old_id, trid_new_id, trid_table_name) SELECT ageo_id, seq_migracion.nextval, 'IEST_AREAGEOGRAFICA_AGEO' FROM IEST_AREAGEOGRAFICA_AGEO;
INSERT INTO tbl_traduccion_ids_trid (trid_old_id, trid_new_id, trid_table_name) SELECT amun_id, seq_migracion.nextval, 'IEST_AREAMUNDIAL_AMUN' FROM IEST_AREAMUNDIAL_AMUN;
INSERT INTO tbl_traduccion_ids_trid (trid_old_id, trid_new_id, trid_table_name) SELECT avit_id, seq_migracion.nextval, 'IEST_AVITUALLAMIENTO_AVIT' FROM IEST_AVITUALLAMIENTO_AVIT;
INSERT INTO tbl_traduccion_ids_trid (trid_old_id, trid_new_id, trid_table_name) SELECT bufa_id, seq_migracion.nextval, 'IEST_BUQUEFONDEOATRAQUE_BUFA' FROM IEST_BUQUEFONDEOATRAQUE_BUFA;
INSERT INTO tbl_traduccion_ids_trid (trid_old_id, trid_new_id, trid_table_name) SELECT buqt_id, seq_migracion.nextval, 'IEST_BUQUETIPOEEE_BUQT' FROM IEST_BUQUETIPOEEE_BUQT;
INSERT INTO tbl_traduccion_ids_trid (trid_old_id, trid_new_id, trid_table_name) SELECT buqt_id, seq_migracion.nextval, 'IEST_BUQUETIPOEST_BUQT' FROM IEST_BUQUETIPOEST_BUQT;
INSERT INTO tbl_traduccion_ids_trid (trid_old_id, trid_new_id, trid_table_name) SELECT bgte_id, seq_migracion.nextval, 'IEST_BUQUETIPOGTEEE_BGTE' FROM IEST_BUQUETIPOGTEEE_BGTE;
INSERT INTO tbl_traduccion_ids_trid (trid_old_id, trid_new_id, trid_table_name) SELECT bugt_id, seq_migracion.nextval, 'IEST_BUQUETIPOGT_BUGT' FROM IEST_BUQUETIPOGT_BUGT;
INSERT INTO tbl_traduccion_ids_trid (trid_old_id, trid_new_id, trid_table_name) SELECT cocu_id, seq_migracion.nextval, 'IEST_CONCEPTOCUADRO_COCU' FROM IEST_CONCEPTOCUADRO_COCU;
INSERT INTO tbl_traduccion_ids_trid (trid_old_id, trid_new_id, trid_table_name) SELECT cmes_id, seq_migracion.nextval, 'IEST_CUADROMES_CMES' FROM IEST_CUADROMES_CMES;
INSERT INTO tbl_traduccion_ids_trid (trid_old_id, trid_new_id, trid_table_name) SELECT ctri_id, seq_migracion.nextval, 'IEST_CUADROTRIMESTRE_CTRI' FROM IEST_CUADROTRIMESTRE_CTRI;
INSERT INTO tbl_traduccion_ids_trid (trid_old_id, trid_new_id, trid_table_name) SELECT fama_id, seq_migracion.nextval, 'IEST_FACHADAMARITIMA_FAMA' FROM IEST_FACHADAMARITIMA_FAMA;
INSERT INTO tbl_traduccion_ids_trid (trid_old_id, trid_new_id, trid_table_name) SELECT gnat_id, seq_migracion.nextval, 'IEST_GRUPONATURALEZA_GNAT' FROM IEST_GRUPONATURALEZA_GNAT;
INSERT INTO tbl_traduccion_ids_trid (trid_old_id, trid_new_id, trid_table_name) SELECT gnst_id, seq_migracion.nextval, 'IEST_GRUPONST_GNST' FROM IEST_GRUPONST_GNST;
INSERT INTO tbl_traduccion_ids_trid (trid_old_id, trid_new_id, trid_table_name) SELECT emet_id, seq_migracion.nextval, 'IEST_MERCANCIATIPO_EMET' FROM IEST_MERCANCIATIPO_EMET;
INSERT INTO tbl_traduccion_ids_trid (trid_old_id, trid_new_id, trid_table_name) SELECT mmee_id, seq_migracion.nextval, 'IEST_MOVIMIENTOMERCEEE_MMEE' FROM IEST_MOVIMIENTOMERCEEE_MMEE;
INSERT INTO tbl_traduccion_ids_trid (trid_old_id, trid_new_id, trid_table_name) SELECT mome_id, seq_migracion.nextval, 'IEST_MOVIMIENTOMERC_MOME' FROM IEST_MOVIMIENTOMERC_MOME;
INSERT INTO tbl_traduccion_ids_trid (trid_old_id, trid_new_id, trid_table_name) SELECT mtbe_id, seq_migracion.nextval, 'IEST_MOVIMIENTOTBUQUEEEE_MTBE' FROM IEST_MOVIMIENTOTBUQUEEEE_MTBE;
INSERT INTO tbl_traduccion_ids_trid (trid_old_id, trid_new_id, trid_table_name) SELECT natu_id, seq_migracion.nextval, 'IEST_NATURALEZA_NATU' FROM IEST_NATURALEZA_NATU;
INSERT INTO tbl_traduccion_ids_trid (trid_old_id, trid_new_id, trid_table_name) SELECT pags_id, seq_migracion.nextval, 'IEST_PARAMAGREAGACIONSP_PAGS' FROM IEST_PARAMAGREAGACIONSP_PAGS;
INSERT INTO tbl_traduccion_ids_trid (trid_old_id, trid_new_id, trid_table_name) SELECT pagr_id, seq_migracion.nextval, 'IEST_PARAMAGREAGACION_PAGR' FROM IEST_PARAMAGREAGACION_PAGR;
INSERT INTO tbl_traduccion_ids_trid (trid_old_id, trid_new_id, trid_table_name) SELECT pepr_id, seq_migracion.nextval, 'IEST_PERIODOPROCESO_PEPR' FROM IEST_PERIODOPROCESO_PEPR;
INSERT INTO tbl_traduccion_ids_trid (trid_old_id, trid_new_id, trid_table_name) SELECT buet_id, seq_migracion.nextval, 'IEST_REGISTROBUQUEEEETIPO_BUET' FROM IEST_REGISTROBUQUEEEETIPO_BUET;
INSERT INTO tbl_traduccion_ids_trid (trid_old_id, trid_new_id, trid_table_name) SELECT burt_id, seq_migracion.nextval, 'IEST_REGISTROBUQUETIPO_BURT' FROM IEST_REGISTROBUQUETIPO_BURT;
INSERT INTO tbl_traduccion_ids_trid (trid_old_id, trid_new_id, trid_table_name) SELECT subg_id, seq_migracion.nextval, 'IEST_SUBGRUPO_SUBG' FROM IEST_SUBGRUPO_SUBG;
INSERT INTO tbl_traduccion_ids_trid (trid_old_id, trid_new_id, trid_table_name) SELECT zcos_id, seq_migracion.nextval, 'IEST_ZONACOSTERAEEE_ZCOS' FROM IEST_ZONACOSTERAEEE_ZCOS;

INSERT INTO tbl_traduccion_ids_trid (trid_old_id, trid_new_id, trid_table_name) SELECT acex_id, seq_migracion.nextval, 'IEXP_ACTIVEXPEDIENTE_ACEX' FROM IEXP_ACTIVEXPEDIENTE_ACEX;
INSERT INTO tbl_traduccion_ids_trid (trid_old_id, trid_new_id, trid_table_name) SELECT biex_id, seq_migracion.nextval, 'IEXP_BIENEXPEDIENTE_BIEX' FROM IEXP_BIENEXPEDIENTE_BIEX;
INSERT INTO tbl_traduccion_ids_trid (trid_old_id, trid_new_id, trid_table_name) SELECT bien_id, seq_migracion.nextval, 'IEXP_BIEN_BIEN' FROM IEXP_BIEN_BIEN;
INSERT INTO tbl_traduccion_ids_trid (trid_old_id, trid_new_id, trid_table_name) SELECT daex_id, seq_migracion.nextval, 'IEXP_DATOSEXPLOTACION_DAEX' FROM IEXP_DATOSEXPLOTACION_DAEX;
INSERT INTO tbl_traduccion_ids_trid (trid_old_id, trid_new_id, trid_table_name) SELECT dotr_id, seq_migracion.nextval, 'IEXP_DOCUMENTOTRAMITE_DOTR' FROM IEXP_DOCUMENTOTRAMITE_DOTR;
INSERT INTO tbl_traduccion_ids_trid (trid_old_id, trid_new_id, trid_table_name) SELECT esex_id, seq_migracion.nextval, 'IEXP_ESTADOEXPEDIENTE_ESEX' FROM IEXP_ESTADOEXPEDIENTE_ESEX;
INSERT INTO tbl_traduccion_ids_trid (trid_old_id, trid_new_id, trid_table_name) SELECT exex_id, seq_migracion.nextval, 'IEXP_EXPEDIENTEREL_EXEX' FROM IEXP_EXPEDIENTEREL_EXEX;
INSERT INTO tbl_traduccion_ids_trid (trid_old_id, trid_new_id, trid_table_name) SELECT expe_id, seq_migracion.nextval, 'IEXP_EXPEDIENTE_EXPE' FROM IEXP_EXPEDIENTE_EXPE;
INSERT INTO tbl_traduccion_ids_trid (trid_old_id, trid_new_id, trid_table_name) SELECT faex_id, seq_migracion.nextval, 'IEXP_FASE_FAEX' FROM IEXP_FASE_FAEX;
INSERT INTO tbl_traduccion_ids_trid (trid_old_id, trid_new_id, trid_table_name) SELECT gexp_id, seq_migracion.nextval, 'IEXP_GARANTIAEXPEDIENTE_GEXP' FROM IEXP_GARANTIAEXPEDIENTE_GEXP;
INSERT INTO tbl_traduccion_ids_trid (trid_old_id, trid_new_id, trid_table_name) SELECT gtae_id, seq_migracion.nextval, 'IEXP_GRAVAMENTASAACT_GTAE' FROM IEXP_GRAVAMENTASAACT_GTAE;
INSERT INTO tbl_traduccion_ids_trid (trid_old_id, trid_new_id, trid_table_name) SELECT gtoe_id, seq_migracion.nextval, 'IEXP_GRAVAMENTTASAOCUP_GTOE' FROM IEXP_GRAVAMENTTASAOCUP_GTOE;
INSERT INTO tbl_traduccion_ids_trid (trid_old_id, trid_new_id, trid_table_name) SELECT mdod_id, seq_migracion.nextval, 'IEXP_MODELODOCUMENTODATA_MDOD' FROM IEXP_MODELODOCUMENTODATA_MDOD;
INSERT INTO tbl_traduccion_ids_trid (trid_old_id, trid_new_id, trid_table_name) SELECT mdov_id, seq_migracion.nextval, 'IEXP_MODELODOCUMENTOVAR_MDOV' FROM IEXP_MODELODOCUMENTOVAR_MDOV;
INSERT INTO tbl_traduccion_ids_trid (trid_old_id, trid_new_id, trid_table_name) SELECT mdoc_id, seq_migracion.nextval, 'IEXP_MODELODOCUMENTO_MDOC' FROM IEXP_MODELODOCUMENTO_MDOC;
INSERT INTO tbl_traduccion_ids_trid (trid_old_id, trid_new_id, trid_table_name) SELECT prde_id, seq_migracion.nextval, 'IEXP_PROYECTODETALLE_PRDE' FROM IEXP_PROYECTODETALLE_PRDE;
INSERT INTO tbl_traduccion_ids_trid (trid_old_id, trid_new_id, trid_table_name) SELECT prex_id, seq_migracion.nextval, 'IEXP_PROYECTO_PREX' FROM IEXP_PROYECTO_PREX;
-- OJO!!!!!
-- INSERT INTO tbl_traduccion_ids_trid (trid_old_id, trid_new_id, trid_table_name) SELECT setr_id, seq_migracion.nextval, 'IEXP_SECUENCIA_TRAMITTEOR_SETR' FROM IEXP_SECUENCIA_TRAMITTEOR_SETR;
INSERT INTO tbl_traduccion_ids_trid (trid_old_id, trid_new_id, trid_table_name) SELECT subi_id, seq_migracion.nextval, 'IEXP_SUPERFICIEBIEN_SUBI' FROM IEXP_SUPERFICIEBIEN_SUBI;
INSERT INTO tbl_traduccion_ids_trid (trid_old_id, trid_new_id, trid_table_name) SELECT sbie_id, seq_migracion.nextval, 'IEXP_SUPRABIEN_SBIE' FROM IEXP_SUPRABIEN_SBIE;
INSERT INTO tbl_traduccion_ids_trid (trid_old_id, trid_new_id, trid_table_name) SELECT ttte_id, seq_migracion.nextval, 'IEXP_TASATARIFATRAMITE_TTTE' FROM IEXP_TASATARIFATRAMITE_TTTE;
INSERT INTO tbl_traduccion_ids_trid (trid_old_id, trid_new_id, trid_table_name) SELECT tage_id, seq_migracion.nextval, 'IEXP_TIPOACTIVIDADG_TAGE' FROM IEXP_TIPOACTIVIDADG_TAGE;
INSERT INTO tbl_traduccion_ids_trid (trid_old_id, trid_new_id, trid_table_name) SELECT taex_id, seq_migracion.nextval, 'IEXP_TIPOACTIVIDAD_TAEX' FROM IEXP_TIPOACTIVIDAD_TAEX;
INSERT INTO tbl_traduccion_ids_trid (trid_old_id, trid_new_id, trid_table_name) SELECT tbie_id, seq_migracion.nextval, 'IEXP_TIPOBIEN_TBIE' FROM IEXP_TIPOBIEN_TBIE;
INSERT INTO tbl_traduccion_ids_trid (trid_old_id, trid_new_id, trid_table_name) SELECT texp_id, seq_migracion.nextval, 'IEXP_TIPOEXPEDIENTE_TEXP' FROM IEXP_TIPOEXPEDIENTE_TEXP;
INSERT INTO tbl_traduccion_ids_trid (trid_old_id, trid_new_id, trid_table_name) SELECT tsex_id, seq_migracion.nextval, 'IEXP_TIPOSUPERFICIEB_TSEX' FROM IEXP_TIPOSUPERFICIEB_TSEX;
INSERT INTO tbl_traduccion_ids_trid (trid_old_id, trid_new_id, trid_table_name) SELECT teed_id, seq_migracion.nextval, 'IEXP_TRAMITEEXPEDIENTE_TEED' FROM IEXP_TRAMITEEXPEDIENTE_TEED;
INSERT INTO tbl_traduccion_ids_trid (trid_old_id, trid_new_id, trid_table_name) SELECT trte_id, seq_migracion.nextval, 'IEXP_TRAMITETEORICO_TRTE' FROM IEXP_TRAMITETEORICO_TRTE;
INSERT INTO tbl_traduccion_ids_trid (trid_old_id, trid_new_id, trid_table_name) SELECT trex_id, seq_migracion.nextval, 'IEXP_TRAMITE_TREX' FROM IEXP_TRAMITE_TREX;
INSERT INTO tbl_traduccion_ids_trid (trid_old_id, trid_new_id, trid_table_name) SELECT udex_id, seq_migracion.nextval, 'IEXP_UNIDADDATOEXP_UDEX' FROM IEXP_UNIDADDATOEXP_UDEX;
INSERT INTO tbl_traduccion_ids_trid (trid_old_id, trid_new_id, trid_table_name) SELECT vzpc_id, seq_migracion.nextval, 'IEXP_ZONAPORTUARIAHIST_VZPC' FROM IEXP_ZONAPORTUARIAHIST_VZPC;
INSERT INTO tbl_traduccion_ids_trid (trid_old_id, trid_new_id, trid_table_name) SELECT zopo_id, seq_migracion.nextval, 'IEXP_ZONAPORTUARIA_ZOPO' FROM IEXP_ZONAPORTUARIA_ZOPO;

-- INSERT INTO tbl_traduccion_ids_trid (trid_old_id, trid_new_id, trid_table_name) SELECT cfac_id, seq_migracion.nextval, 'IFAC_CABECERAFACTURA_CFAC' FROM IFAC_CABECERAFACTURA_CFAC;
-- INSERT INTO tbl_traduccion_ids_trid (trid_old_id, trid_new_id, trid_table_name) SELECT cval_id, seq_migracion.nextval, 'IFAC_CABECERAVALORACION_CVAL' FROM IFAC_CABECERAVALORACION_CVAL;
INSERT INTO tbl_traduccion_ids_trid (trid_old_id, trid_new_id, trid_table_name) SELECT cobu_id, seq_migracion.nextval, 'IFAC_CONTADORBUQUE_COBU' FROM IFAC_CONTADORBUQUE_COBU;
INSERT INTO tbl_traduccion_ids_trid (trid_old_id, trid_new_id, trid_table_name) SELECT coes_id, seq_migracion.nextval, 'IFAC_CONTADORESCALA_COES' FROM IFAC_CONTADORESCALA_COES;
INSERT INTO tbl_traduccion_ids_trid (trid_old_id, trid_new_id, trid_table_name) SELECT cots_id, seq_migracion.nextval, 'IFAC_CONTADORTRAFICO_COTS' FROM IFAC_CONTADORTRAFICO_COTS;
-- INSERT INTO tbl_traduccion_ids_trid (trid_old_id, trid_new_id, trid_table_name) SELECT dfac_id, seq_migracion.nextval, 'IFAC_DETALLEFACTURA_DFAC' FROM IFAC_DETALLEFACTURA_DFAC;
-- INSERT INTO tbl_traduccion_ids_trid (trid_old_id, trid_new_id, trid_table_name) SELECT dval_id, seq_migracion.nextval, 'IFAC_DETALLEVALORACION_DVAL' FROM IFAC_DETALLEVALORACION_DVAL;
-- INSERT INTO tbl_traduccion_ids_trid (trid_old_id, trid_new_id, trid_table_name) SELECT dofd_id, seq_migracion.nextval, 'IFAC_DOCUMENTOFACTURADATA_DOFD' FROM IFAC_DOCUMENTOFACTURADATA_DOFD;
-- INSERT INTO tbl_traduccion_ids_trid (trid_old_id, trid_new_id, trid_table_name) SELECT docf_id, seq_migracion.nextval, 'IFAC_DOCUMENTOFACTURA_DOCF' FROM IFAC_DOCUMENTOFACTURA_DOCF;
INSERT INTO tbl_traduccion_ids_trid (trid_old_id, trid_new_id, trid_table_name) SELECT enpr_id, seq_migracion.nextval, 'IFAC_ENTIDADPROCESO_ENPR' FROM IFAC_ENTIDADPROCESO_ENPR;
INSERT INTO tbl_traduccion_ids_trid (trid_old_id, trid_new_id, trid_table_name) SELECT envi_id, seq_migracion.nextval, 'IFAC_ENTIDADVISTA_ENVI' FROM IFAC_ENTIDADVISTA_ENVI;
INSERT INTO tbl_traduccion_ids_trid (trid_old_id, trid_new_id, trid_table_name) SELECT errp_id, seq_migracion.nextval, 'IFAC_ERRORPROCESO_ERRP' FROM IFAC_ERRORPROCESO_ERRP;
INSERT INTO tbl_traduccion_ids_trid (trid_old_id, trid_new_id, trid_table_name) SELECT etvi_id, seq_migracion.nextval, 'IFAC_ETIQUETAVISTA_ETVI' FROM IFAC_ETIQUETAVISTA_ETVI;
-- INSERT INTO tbl_traduccion_ids_trid (trid_old_id, trid_new_id, trid_table_name) SELECT fase_id, seq_migracion.nextval, 'IFAC_FACTURASERVICIO_FASE' FROM IFAC_FACTURASERVICIO_FASE;
INSERT INTO tbl_traduccion_ids_trid (trid_old_id, trid_new_id, trid_table_name) SELECT incf_id, seq_migracion.nextval, 'IFAC_INCIDENCIAFACTURA_INCF' FROM IFAC_INCIDENCIAFACTURA_INCF;
-- INSERT INTO tbl_traduccion_ids_trid (trid_old_id, trid_new_id, trid_table_name) SELECT ivaf_id, seq_migracion.nextval, 'IFAC_IVAFACTURA_IVAF' FROM IFAC_IVAFACTURA_IVAF;
INSERT INTO tbl_traduccion_ids_trid (trid_old_id, trid_new_id, trid_table_name) SELECT ivat_id, seq_migracion.nextval, 'IFAC_IVATIPO_IVAT' FROM IFAC_IVATIPO_IVAT;
-- INSERT INTO tbl_traduccion_ids_trid (trid_old_id, trid_new_id, trid_table_name) SELECT ivav_id, seq_migracion.nextval, 'IFAC_IVAVALORACION_IVAV' FROM IFAC_IVAVALORACION_IVAV;
-- INSERT INTO tbl_traduccion_ids_trid (trid_old_id, trid_new_id, trid_table_name) SELECT lfac_id, seq_migracion.nextval, 'IFAC_LINEAFACTURA_LFAC' FROM IFAC_LINEAFACTURA_LFAC;
-- INSERT INTO tbl_traduccion_ids_trid (trid_old_id, trid_new_id, trid_table_name) SELECT lval_id, seq_migracion.nextval, 'IFAC_LINEAVALORACION_LVAL' FROM IFAC_LINEAVALORACION_LVAL;
INSERT INTO tbl_traduccion_ids_trid (trid_old_id, trid_new_id, trid_table_name) SELECT para_id, seq_migracion.nextval, 'IFAC_PARAMETRIZACION_PARA' FROM IFAC_PARAMETRIZACION_PARA;
INSERT INTO tbl_traduccion_ids_trid (trid_old_id, trid_new_id, trid_table_name) SELECT proc_id, seq_migracion.nextval, 'IFAC_PROCEDIMIENTO_PROC' FROM IFAC_PROCEDIMIENTO_PROC;
INSERT INTO tbl_traduccion_ids_trid (trid_old_id, trid_new_id, trid_table_name) SELECT elcu_id, seq_migracion.nextval, 'IFAC_PROCELEMCUANTITATIVO_ELCU' FROM IFAC_PROCELEMCUANTITATIVO_ELCU;
INSERT INTO tbl_traduccion_ids_trid (trid_old_id, trid_new_id, trid_table_name) SELECT prfa_id, seq_migracion.nextval, 'IFAC_PROCESO_PRFA' FROM IFAC_PROCESO_PRFA;
INSERT INTO tbl_traduccion_ids_trid (trid_old_id, trid_new_id, trid_table_name) SELECT inco_id, seq_migracion.nextval, 'IFAC_PROCINCOMPATIB_INCO' FROM IFAC_PROCINCOMPATIB_INCO;
INSERT INTO tbl_traduccion_ids_trid (trid_old_id, trid_new_id, trid_table_name) SELECT prje_id, seq_migracion.nextval, 'IFAC_PROCJERARQUIA_PRJE' FROM IFAC_PROCJERARQUIA_PRJE;
INSERT INTO tbl_traduccion_ids_trid (trid_old_id, trid_new_id, trid_table_name) SELECT oppr_id, seq_migracion.nextval, 'IFAC_PROCOPERANDOPRECIO_OPPR' FROM IFAC_PROCOPERANDOPRECIO_OPPR;
INSERT INTO tbl_traduccion_ids_trid (trid_old_id, trid_new_id, trid_table_name) SELECT sefa_id, seq_migracion.nextval, 'IFAC_SERIEFACTURA_SEFA' FROM IFAC_SERIEFACTURA_SEFA;
-- INSERT INTO tbl_traduccion_ids_trid (trid_old_id, trid_new_id, trid_table_name) SELECT ttsa_id, seq_migracion.nextval, 'IFAC_TASATARIFASERVICIOAN_TTSA' FROM IFAC_TASATARIFASERVICIOAN_TTSA;
-- INSERT INTO tbl_traduccion_ids_trid (trid_old_id, trid_new_id, trid_table_name) SELECT ttse_id, seq_migracion.nextval, 'IFAC_TASATARIFASERVICIO_TTSE' FROM IFAC_TASATARIFASERVICIO_TTSE;
INSERT INTO tbl_traduccion_ids_trid (trid_old_id, trid_new_id, trid_table_name) SELECT tata_id, seq_migracion.nextval, 'IFAC_TASATARIFA_TATA' FROM IFAC_TASATARIFA_TATA;
INSERT INTO tbl_traduccion_ids_trid (trid_old_id, trid_new_id, trid_table_name) SELECT aspa_id, seq_migracion.nextval, 'IFAC_TATAASPECTOAGR_ASPA' FROM IFAC_TATAASPECTOAGR_ASPA;
INSERT INTO tbl_traduccion_ids_trid (trid_old_id, trid_new_id, trid_table_name) SELECT aspc_id, seq_migracion.nextval, 'IFAC_TATAASPECTOCAB_ASPC' FROM IFAC_TATAASPECTOCAB_ASPC;
INSERT INTO tbl_traduccion_ids_trid (trid_old_id, trid_new_id, trid_table_name) SELECT aspx_id, seq_migracion.nextval, 'IFAC_TATAASPECTOEXC_ASPX' FROM IFAC_TATAASPECTOEXC_ASPX;
INSERT INTO tbl_traduccion_ids_trid (trid_old_id, trid_new_id, trid_table_name) SELECT asje_id, seq_migracion.nextval, 'IFAC_TATAASPECTOJERARQUIA_ASJE' FROM IFAC_TATAASPECTOJERARQUIA_ASJE;
INSERT INTO tbl_traduccion_ids_trid (trid_old_id, trid_new_id, trid_table_name) SELECT aspl_id, seq_migracion.nextval, 'IFAC_TATAASPECTOLIN_ASPL' FROM IFAC_TATAASPECTOLIN_ASPL;
INSERT INTO tbl_traduccion_ids_trid (trid_old_id, trid_new_id, trid_table_name) SELECT aspe_id, seq_migracion.nextval, 'IFAC_TATAASPECTO_ASPE' FROM IFAC_TATAASPECTO_ASPE;
INSERT INTO tbl_traduccion_ids_trid (trid_old_id, trid_new_id, trid_table_name) SELECT ttco_id, seq_migracion.nextval, 'IFAC_TATACOMPUESTA_TTCO' FROM IFAC_TATACOMPUESTA_TTCO;
INSERT INTO tbl_traduccion_ids_trid (trid_old_id, trid_new_id, trid_table_name) SELECT tepf_id, seq_migracion.nextval, 'IFAC_TIPOERRORPROC_TEPF' FROM IFAC_TIPOERRORPROC_TEPF;
INSERT INTO tbl_traduccion_ids_trid (trid_old_id, trid_new_id, trid_table_name) SELECT tivi_id, seq_migracion.nextval, 'IFAC_TIPOVISTA_TIVI' FROM IFAC_TIPOVISTA_TIVI;
INSERT INTO tbl_traduccion_ids_trid (trid_old_id, trid_new_id, trid_table_name) SELECT vist_id, seq_migracion.nextval, 'IFAC_VISTA_VIST' FROM IFAC_VISTA_VIST;

INSERT INTO tbl_traduccion_ids_trid (trid_old_id, trid_new_id, trid_table_name) SELECT aipc_id, seq_migracion.nextval, 'IFAP_ACTUALIZACIONIPC_AIPC' FROM IFAP_ACTUALIZACIONIPC_AIPC;
INSERT INTO tbl_traduccion_ids_trid (trid_old_id, trid_new_id, trid_table_name) SELECT bapr_id, seq_migracion.nextval, 'IFAP_BAREMO_BAPR' FROM IFAP_BAREMO_BAPR;
INSERT INTO tbl_traduccion_ids_trid (trid_old_id, trid_new_id, trid_table_name) SELECT bcfp_id, seq_migracion.nextval, 'IFAP_BONIFICACIONCABFP_BCFP' FROM IFAP_BONIFICACIONCABFP_BCFP;
INSERT INTO tbl_traduccion_ids_trid (trid_old_id, trid_new_id, trid_table_name) SELECT bofp_id, seq_migracion.nextval, 'IFAP_BONIFICACIONFP_BOFP' FROM IFAP_BONIFICACIONFP_BOFP;
INSERT INTO tbl_traduccion_ids_trid (trid_old_id, trid_new_id, trid_table_name) SELECT blfp_id, seq_migracion.nextval, 'IFAP_BONIFICACIONLINEAFP_BLFP' FROM IFAP_BONIFICACIONLINEAFP_BLFP;
INSERT INTO tbl_traduccion_ids_trid (trid_old_id, trid_new_id, trid_table_name) SELECT cafp_id, seq_migracion.nextval, 'IFAP_CABECERAFP_CAFP' FROM IFAP_CABECERAFP_CAFP;
INSERT INTO tbl_traduccion_ids_trid (trid_old_id, trid_new_id, trid_table_name) SELECT lifp_id, seq_migracion.nextval, 'IFAP_LINEAFP_LIFP' FROM IFAP_LINEAFP_LIFP;
INSERT INTO tbl_traduccion_ids_trid (trid_old_id, trid_new_id, trid_table_name) SELECT tcan_id, seq_migracion.nextval, 'IFAP_TIPOCANON_TCAN' FROM IFAP_TIPOCANON_TCAN;

INSERT INTO tbl_traduccion_ids_trid (trid_old_id, trid_new_id, trid_table_name) SELECT alin_id, seq_migracion.nextval, 'IGEN_ALINEACION_ALIN' FROM IGEN_ALINEACION_ALIN;
INSERT INTO tbl_traduccion_ids_trid (trid_old_id, trid_new_id, trid_table_name) SELECT babe_id, seq_migracion.nextval, 'IGEN_BUQUEAUXILIARBERMAN_BABE' FROM IGEN_BUQUEAUXILIARBERMAN_BABE;
INSERT INTO tbl_traduccion_ids_trid (trid_old_id, trid_new_id, trid_table_name) SELECT buqt_id, seq_migracion.nextval, 'IGEN_BUQUETIPO_BUQT' FROM IGEN_BUQUETIPO_BUQT;
INSERT INTO tbl_traduccion_ids_trid (trid_old_id, trid_new_id, trid_table_name) SELECT dead_id, seq_migracion.nextval, 'IGEN_DESCUENTOADIC_DEAD' FROM IGEN_DESCUENTOADIC_DEAD;
INSERT INTO tbl_traduccion_ids_trid (trid_old_id, trid_new_id, trid_table_name) SELECT eted_id, seq_migracion.nextval, 'IGEN_ERROREDITIPO_ETED' FROM IGEN_ERROREDITIPO_ETED;
INSERT INTO tbl_traduccion_ids_trid (trid_old_id, trid_new_id, trid_table_name) SELECT eedi_id, seq_migracion.nextval, 'IGEN_ERROREDI_EEDI' FROM IGEN_ERROREDI_EEDI;
INSERT INTO tbl_traduccion_ids_trid (trid_old_id, trid_new_id, trid_table_name) SELECT exet_id, seq_migracion.nextval, 'IGEN_EXENCIONTIPO_EXET' FROM IGEN_EXENCIONTIPO_EXET;
INSERT INTO tbl_traduccion_ids_trid (trid_old_id, trid_new_id, trid_table_name) SELECT edif_id, seq_migracion.nextval, 'IGEN_FICHEROEDI_EDIF' FROM IGEN_FICHEROEDI_EDIF;
INSERT INTO tbl_traduccion_ids_trid (trid_old_id, trid_new_id, trid_table_name) SELECT muni_id, seq_migracion.nextval, 'IGEN_MUNICIPIO_MUNI' FROM IGEN_MUNICIPIO_MUNI;
INSERT INTO tbl_traduccion_ids_trid (trid_old_id, trid_new_id, trid_table_name) SELECT navt_id, seq_migracion.nextval, 'IGEN_NAVEGACIONTIPO_NAVT' FROM IGEN_NAVEGACIONTIPO_NAVT;
INSERT INTO tbl_traduccion_ids_trid (trid_old_id, trid_new_id, trid_table_name) SELECT opet_id, seq_migracion.nextval, 'IGEN_OPERACIONTIPO_OPET' FROM IGEN_OPERACIONTIPO_OPET;
INSERT INTO tbl_traduccion_ids_trid (trid_old_id, trid_new_id, trid_table_name) SELECT pais_id, seq_migracion.nextval, 'IGEN_PAIS_PAIS' FROM IGEN_PAIS_PAIS;
INSERT INTO tbl_traduccion_ids_trid (trid_old_id, trid_new_id, trid_table_name) SELECT prov_id, seq_migracion.nextval, 'IGEN_PROVINCIA_PROV' FROM IGEN_PROVINCIA_PROV;
INSERT INTO tbl_traduccion_ids_trid (trid_old_id, trid_new_id, trid_table_name) SELECT subp_id, seq_migracion.nextval, 'IGEN_SUBPUERTO_SUBP' FROM IGEN_SUBPUERTO_SUBP;
INSERT INTO tbl_traduccion_ids_trid (trid_old_id, trid_new_id, trid_table_name) SELECT unlo_id, seq_migracion.nextval, 'IGEN_UNLOCODE_UNLO' FROM IGEN_UNLOCODE_UNLO;

INSERT INTO tbl_traduccion_ids_trid (trid_old_id, trid_new_id, trid_table_name) SELECT inct_id, seq_migracion.nextval, 'IINC_INCIDENCIATIPO_INCT' FROM IINC_INCIDENCIATIPO_INCT;
INSERT INTO tbl_traduccion_ids_trid (trid_old_id, trid_new_id, trid_table_name) SELECT inci_id, seq_migracion.nextval, 'IINC_INCIDENCIA_INCI' FROM IINC_INCIDENCIA_INCI;

INSERT INTO tbl_traduccion_ids_trid (trid_old_id, trid_new_id, trid_table_name) SELECT inde_id, seq_migracion.nextval, 'IIND_INDICADORENTIDAD_INDE' FROM IIND_INDICADORENTIDAD_INDE;
INSERT INTO tbl_traduccion_ids_trid (trid_old_id, trid_new_id, trid_table_name) SELECT indl_id, seq_migracion.nextval, 'IIND_INDICADORLISTA_INDL' FROM IIND_INDICADORLISTA_INDL;
INSERT INTO tbl_traduccion_ids_trid (trid_old_id, trid_new_id, trid_table_name) SELECT indi_id, seq_migracion.nextval, 'IIND_INDICADOR_INDI' FROM IIND_INDICADOR_INDI;

INSERT INTO tbl_traduccion_ids_trid (trid_old_id, trid_new_id, trid_table_name) SELECT mabl_id, seq_migracion.nextval, 'IMAN_BL_MABL' FROM IMAN_BL_MABL;
INSERT INTO tbl_traduccion_ids_trid (trid_old_id, trid_new_id, trid_table_name) SELECT maco_id, seq_migracion.nextval, 'IMAN_CONSIGNATARIO_MACO' FROM IMAN_CONSIGNATARIO_MACO;
INSERT INTO tbl_traduccion_ids_trid (trid_old_id, trid_new_id, trid_table_name) SELECT equi_id, seq_migracion.nextval, 'IMAN_EQUIPAMIENTO_EQUI' FROM IMAN_EQUIPAMIENTO_EQUI;
INSERT INTO tbl_traduccion_ids_trid (trid_old_id, trid_new_id, trid_table_name) SELECT gara_id, seq_migracion.nextval, 'IMAN_GRUPOARANCEL_GARA' FROM IMAN_GRUPOARANCEL_GARA;
INSERT INTO tbl_traduccion_ids_trid (trid_old_id, trid_new_id, trid_table_name) SELECT iesp_id, seq_migracion.nextval, 'IMAN_INSTESPECIAL_IESP' FROM IMAN_INSTESPECIAL_IESP;
INSERT INTO tbl_traduccion_ids_trid (trid_old_id, trid_new_id, trid_table_name) SELECT imar_id, seq_migracion.nextval, 'IMAN_INSTRUCCMARCAJE_IMAR' FROM IMAN_INSTRUCCMARCAJE_IMAR;
INSERT INTO tbl_traduccion_ids_trid (trid_old_id, trid_new_id, trid_table_name) SELECT vmar_id, seq_migracion.nextval, 'IMAN_MARCAVEHICULO_VMAR' FROM IMAN_MARCAVEHICULO_VMAR;
INSERT INTO tbl_traduccion_ids_trid (trid_old_id, trid_new_id, trid_table_name) SELECT merc_id, seq_migracion.nextval, 'IMAN_MERCANCIA_MERC' FROM IMAN_MERCANCIA_MERC;
INSERT INTO tbl_traduccion_ids_trid (trid_old_id, trid_new_id, trid_table_name) SELECT mmpp_id, seq_migracion.nextval, 'IMAN_MMPP_MMPP' FROM IMAN_MMPP_MMPP;
INSERT INTO tbl_traduccion_ids_trid (trid_old_id, trid_new_id, trid_table_name) SELECT tedi_id, seq_migracion.nextval, 'IMAN_MODOTRANSPEDI_TEDI' FROM IMAN_MODOTRANSPEDI_TEDI;
INSERT INTO tbl_traduccion_ids_trid (trid_old_id, trid_new_id, trid_table_name) SELECT pado_id, seq_migracion.nextval, 'IMAN_PARTIDADOCU_PADO' FROM IMAN_PARTIDADOCU_PADO;
INSERT INTO tbl_traduccion_ids_trid (trid_old_id, trid_new_id, trid_table_name) SELECT paeq_id, seq_migracion.nextval, 'IMAN_PARTIDAEQUIP_PAEQ' FROM IMAN_PARTIDAEQUIP_PAEQ;
INSERT INTO tbl_traduccion_ids_trid (trid_old_id, trid_new_id, trid_table_name) SELECT paim_id, seq_migracion.nextval, 'IMAN_PARTIDAIM_PAIM' FROM IMAN_PARTIDAIM_PAIM;
INSERT INTO tbl_traduccion_ids_trid (trid_old_id, trid_new_id, trid_table_name) SELECT pamp_id, seq_migracion.nextval, 'IMAN_PARTIDAMMPP_PAMP' FROM IMAN_PARTIDAMMPP_PAMP;
INSERT INTO tbl_traduccion_ids_trid (trid_old_id, trid_new_id, trid_table_name) SELECT part_id, seq_migracion.nextval, 'IMAN_PARTIDA_PART' FROM IMAN_PARTIDA_PART;
INSERT INTO tbl_traduccion_ids_trid (trid_old_id, trid_new_id, trid_table_name) SELECT preq_id, seq_migracion.nextval, 'IMAN_PRECINTOEQUIP_PREQ' FROM IMAN_PRECINTOEQUIP_PREQ;
INSERT INTO tbl_traduccion_ids_trid (trid_old_id, trid_new_id, trid_table_name) SELECT rece_id, seq_migracion.nextval, 'IMAN_RECEPTOR_RECE' FROM IMAN_RECEPTOR_RECE;
INSERT INTO tbl_traduccion_ids_trid (trid_old_id, trid_new_id, trid_table_name) SELECT radu_id, seq_migracion.nextval, 'IMAN_RECINTOADUANERO_RADU' FROM IMAN_RECINTOADUANERO_RADU;
INSERT INTO tbl_traduccion_ids_trid (trid_old_id, trid_new_id, trid_table_name) SELECT term_id, seq_migracion.nextval, 'IMAN_TERMINAL_TERM' FROM IMAN_TERMINAL_TERM;
INSERT INTO tbl_traduccion_ids_trid (trid_old_id, trid_new_id, trid_table_name) SELECT tbul_id, seq_migracion.nextval, 'IMAN_TIPOBULTO_TBUL' FROM IMAN_TIPOBULTO_TBUL;
INSERT INTO tbl_traduccion_ids_trid (trid_old_id, trid_new_id, trid_table_name) SELECT attd_id, seq_migracion.nextval, 'IMAN_TIPODOCAEAT_ATTD' FROM IMAN_TIPODOCAEAT_ATTD;
INSERT INTO tbl_traduccion_ids_trid (trid_old_id, trid_new_id, trid_table_name) SELECT tequ_id, seq_migracion.nextval, 'IMAN_TIPOEQUIPAMIENTO_TEQU' FROM IMAN_TIPOEQUIPAMIENTO_TEQU;
INSERT INTO tbl_traduccion_ids_trid (trid_old_id, trid_new_id, trid_table_name) SELECT tobl_id, seq_migracion.nextval, 'IMAN_TIPOOPERACION_TOBL' FROM IMAN_TIPOOPERACION_TOBL;
INSERT INTO tbl_traduccion_ids_trid (trid_old_id, trid_new_id, trid_table_name) SELECT unic_id, seq_migracion.nextval, 'IMAN_UNIDADCARGA_UNIC' FROM IMAN_UNIDADCARGA_UNIC;

INSERT INTO tbl_traduccion_ids_trid (trid_old_id, trid_new_id, trid_table_name) SELECT arpe_id, seq_migracion.nextval, 'IPES_ARTEPESCA_ARPE' FROM IPES_ARTEPESCA_ARPE;
INSERT INTO tbl_traduccion_ids_trid (trid_old_id, trid_new_id, trid_table_name) SELECT btpe_id, seq_migracion.nextval, 'IPES_BUQUETIPO_BTPE' FROM IPES_BUQUETIPO_BTPE;
INSERT INTO tbl_traduccion_ids_trid (trid_old_id, trid_new_id, trid_table_name) SELECT bupe_id, seq_migracion.nextval, 'IPES_BUQUE_BUPE' FROM IPES_BUQUE_BUPE;
INSERT INTO tbl_traduccion_ids_trid (trid_old_id, trid_new_id, trid_table_name) SELECT cati_id, seq_migracion.nextval, 'IPES_CAPTURATIPO_CATI' FROM IPES_CAPTURATIPO_CATI;
INSERT INTO tbl_traduccion_ids_trid (trid_old_id, trid_new_id, trid_table_name) SELECT cope_id, seq_migracion.nextval, 'IPES_COMPRADOR_COPE' FROM IPES_COMPRADOR_COPE;
INSERT INTO tbl_traduccion_ids_trid (trid_old_id, trid_new_id, trid_table_name) SELECT espe_id, seq_migracion.nextval, 'IPES_ESPECIEPESCA_ESPE' FROM IPES_ESPECIEPESCA_ESPE;
INSERT INTO tbl_traduccion_ids_trid (trid_old_id, trid_new_id, trid_table_name) SELECT fape_id, seq_migracion.nextval, 'IPES_FAMILIA_FAPE' FROM IPES_FAMILIA_FAPE;
INSERT INTO tbl_traduccion_ids_trid (trid_old_id, trid_new_id, trid_table_name) SELECT gfpe_id, seq_migracion.nextval, 'IPES_GRUPOFAMILIA_GFPE' FROM IPES_GRUPOFAMILIA_GFPE;
INSERT INTO tbl_traduccion_ids_trid (trid_old_id, trid_new_id, trid_table_name) SELECT mpst_id, seq_migracion.nextval, 'IPES_MANIFIESTOSTIPO_MPST' FROM IPES_MANIFIESTOSTIPO_MPST;
INSERT INTO tbl_traduccion_ids_trid (trid_old_id, trid_new_id, trid_table_name) SELECT mpst_id, seq_migracion.nextval, 'IPES_MANIFIESTOSUBTIPO_MPST' FROM IPES_MANIFIESTOSUBTIPO_MPST;
INSERT INTO tbl_traduccion_ids_trid (trid_old_id, trid_new_id, trid_table_name) SELECT mpti_id, seq_migracion.nextval, 'IPES_MANIFIESTOTIPO_MPTI' FROM IPES_MANIFIESTOTIPO_MPTI;
INSERT INTO tbl_traduccion_ids_trid (trid_old_id, trid_new_id, trid_table_name) SELECT topp_id, seq_migracion.nextval, 'IPES_OPERACIONTIPO_TOPP' FROM IPES_OPERACIONTIPO_TOPP;
INSERT INTO tbl_traduccion_ids_trid (trid_old_id, trid_new_id, trid_table_name) SELECT pape_id, seq_migracion.nextval, 'IPES_PARTIDA_PAPE' FROM IPES_PARTIDA_PAPE;
INSERT INTO tbl_traduccion_ids_trid (trid_old_id, trid_new_id, trid_table_name) SELECT prpe_id, seq_migracion.nextval, 'IPES_PRESENTACION_PRPE' FROM IPES_PRESENTACION_PRPE;
INSERT INTO tbl_traduccion_ids_trid (trid_old_id, trid_new_id, trid_table_name) SELECT zope_id, seq_migracion.nextval, 'IPES_ZONAPESCA_ZOPE' FROM IPES_ZONAPESCA_ZOPE;

INSERT INTO tbl_traduccion_ids_trid (trid_old_id, trid_new_id, trid_table_name) SELECT prat_id, seq_migracion.nextval, 'IPRA_MANIOBRATIPO_PRAT' FROM IPRA_MANIOBRATIPO_PRAT;
INSERT INTO tbl_traduccion_ids_trid (trid_old_id, trid_new_id, trid_table_name) SELECT prac_id, seq_migracion.nextval, 'IPRA_PRACTICAJE_PRAC' FROM IPRA_PRACTICAJE_PRAC;
INSERT INTO tbl_traduccion_ids_trid (trid_old_id, trid_new_id, trid_table_name) SELECT prap_id, seq_migracion.nextval, 'IPRA_PRACTICO_PRAP' FROM IPRA_PRACTICO_PRAP;

INSERT INTO tbl_traduccion_ids_trid (trid_old_id, trid_new_id, trid_table_name) SELECT prog_id, seq_migracion.nextval, 'IPRO_PROGRAMACION_PROG' FROM IPRO_PROGRAMACION_PROG;

INSERT INTO tbl_traduccion_ids_trid (trid_old_id, trid_new_id, trid_table_name) SELECT remt_id, seq_migracion.nextval, 'IREM_MOVIMIENTOTIPO_REMT' FROM IREM_MOVIMIENTOTIPO_REMT;
INSERT INTO tbl_traduccion_ids_trid (trid_old_id, trid_new_id, trid_table_name) SELECT remm_id, seq_migracion.nextval, 'IREM_REMOLQUEMEDIO_REMM' FROM IREM_REMOLQUEMEDIO_REMM;
INSERT INTO tbl_traduccion_ids_trid (trid_old_id, trid_new_id, trid_table_name) SELECT remt_id, seq_migracion.nextval, 'IREM_REMOLQUEMEDTIPO_REMT' FROM IREM_REMOLQUEMEDTIPO_REMT;
INSERT INTO tbl_traduccion_ids_trid (trid_old_id, trid_new_id, trid_table_name) SELECT remo_id, seq_migracion.nextval, 'IREM_REMOLQUE_REMO' FROM IREM_REMOLQUE_REMO;

INSERT INTO tbl_traduccion_ids_trid (trid_old_id, trid_new_id, trid_table_name) SELECT clsu_id, seq_migracion.nextval, 'ISUM_CLIENTEPUNTORED_CLSU' FROM ISUM_CLIENTEPUNTORED_CLSU;
INSERT INTO tbl_traduccion_ids_trid (trid_old_id, trid_new_id, trid_table_name) SELECT sucd_id, seq_migracion.nextval, 'ISUM_CONSUMODETALLE_SUCD' FROM ISUM_CONSUMODETALLE_SUCD;
INSERT INTO tbl_traduccion_ids_trid (trid_old_id, trid_new_id, trid_table_name) SELECT suco_id, seq_migracion.nextval, 'ISUM_CONSUMO_SUCO' FROM ISUM_CONSUMO_SUCO;
INSERT INTO tbl_traduccion_ids_trid (trid_old_id, trid_new_id, trid_table_name) SELECT cpsu_id, seq_migracion.nextval, 'ISUM_CONTADORPUNTORED_CPSU' FROM ISUM_CONTADORPUNTORED_CPSU;
INSERT INTO tbl_traduccion_ids_trid (trid_old_id, trid_new_id, trid_table_name) SELECT cosu_id, seq_migracion.nextval, 'ISUM_CONTADOR_COSU' FROM ISUM_CONTADOR_COSU;
INSERT INTO tbl_traduccion_ids_trid (trid_old_id, trid_new_id, trid_table_name) SELECT gcsu_id, seq_migracion.nextval, 'ISUM_GASTOCONSUMO_GCSU' FROM ISUM_GASTOCONSUMO_GCSU;
INSERT INTO tbl_traduccion_ids_trid (trid_old_id, trid_new_id, trid_table_name) SELECT gpsu_id, seq_migracion.nextval, 'ISUM_GASTOPUNTORED_GPSU' FROM ISUM_GASTOPUNTORED_GPSU;
INSERT INTO tbl_traduccion_ids_trid (trid_old_id, trid_new_id, trid_table_name) SELECT lcsu_id, seq_migracion.nextval, 'ISUM_LECTURACONSUMO_LCSU' FROM ISUM_LECTURACONSUMO_LCSU;
INSERT INTO tbl_traduccion_ids_trid (trid_old_id, trid_new_id, trid_table_name) SELECT lpsu_id, seq_migracion.nextval, 'ISUM_LECTURAPUNTORED_LPSU' FROM ISUM_LECTURAPUNTORED_LPSU;
INSERT INTO tbl_traduccion_ids_trid (trid_old_id, trid_new_id, trid_table_name) SELECT prsu_id, seq_migracion.nextval, 'ISUM_PUNTORED_PRSU' FROM ISUM_PUNTORED_PRSU;
INSERT INTO tbl_traduccion_ids_trid (trid_old_id, trid_new_id, trid_table_name) SELECT reds_id, seq_migracion.nextval, 'ISUM_RED_REDS' FROM ISUM_RED_REDS;
INSERT INTO tbl_traduccion_ids_trid (trid_old_id, trid_new_id, trid_table_name) SELECT tcsu_id, seq_migracion.nextval, 'ISUM_TIPOCONTADOR_TCSU' FROM ISUM_TIPOCONTADOR_TCSU;
INSERT INTO tbl_traduccion_ids_trid (trid_old_id, trid_new_id, trid_table_name) SELECT tgsu_id, seq_migracion.nextval, 'ISUM_TIPOGASTO_TGSU' FROM ISUM_TIPOGASTO_TGSU;
INSERT INTO tbl_traduccion_ids_trid (trid_old_id, trid_new_id, trid_table_name) SELECT tsum_id, seq_migracion.nextval, 'ISUM_TIPOSUMINISTRO_TSUM' FROM ISUM_TIPOSUMINISTRO_TSUM;

INSERT INTO tbl_traduccion_ids_trid (trid_old_id, trid_new_id, trid_table_name) SELECT gzsu_id, seq_migracion.nextval, 'ISUP_GRUPOZONA_GZSU' FROM ISUP_GRUPOZONA_GZSU;
INSERT INTO tbl_traduccion_ids_trid (trid_old_id, trid_new_id, trid_table_name) SELECT sulo_id, seq_migracion.nextval, 'ISUP_LINEAOCUPACION_SULO' FROM ISUP_LINEAOCUPACION_SULO;
INSERT INTO tbl_traduccion_ids_trid (trid_old_id, trid_new_id, trid_table_name) SELECT sude_id, seq_migracion.nextval, 'ISUP_SUPERFICIEDETALLE_SUDE' FROM ISUP_SUPERFICIEDETALLE_SUDE;
INSERT INTO tbl_traduccion_ids_trid (trid_old_id, trid_new_id, trid_table_name) SELECT suoc_id, seq_migracion.nextval, 'ISUP_SUPERFICIE_SUOC' FROM ISUP_SUPERFICIE_SUOC;
INSERT INTO tbl_traduccion_ids_trid (trid_old_id, trid_new_id, trid_table_name) SELECT tosu_id, seq_migracion.nextval, 'ISUP_TIPOOPERACION_TOSU' FROM ISUP_TIPOOPERACION_TOSU;
INSERT INTO tbl_traduccion_ids_trid (trid_old_id, trid_new_id, trid_table_name) SELECT tsup_id, seq_migracion.nextval, 'ISUP_TIPOSUPERFICIE_TSUP' FROM ISUP_TIPOSUPERFICIE_TSUP;
INSERT INTO tbl_traduccion_ids_trid (trid_old_id, trid_new_id, trid_table_name) SELECT unis_id, seq_migracion.nextval, 'ISUP_UNIDAD_UNIS' FROM ISUP_UNIDAD_UNIS;
INSERT INTO tbl_traduccion_ids_trid (trid_old_id, trid_new_id, trid_table_name) SELECT zons_id, seq_migracion.nextval, 'ISUP_ZONA_ZONS' FROM ISUP_ZONA_ZONS;
