-- Borrado del contenido de las tablas

DELETE FROM XE_SUBGRUPO_4_3_POR_PUERTO;
DELETE FROM X3_MERCANCIAS;
DELETE FROM TOAD_PLAN_TABLE;
DELETE FROM TMP_PUBLISH_AUDIT_DATOS;
DELETE FROM TMP_MELILLA_TARIFAS;
DELETE FROM TMP_MELILLA_MUELLES;
DELETE FROM TMP_MELILLA_BUQUES;
DELETE FROM TIPO_TERMINAL;
DELETE FROM TIPO_MOD_YOKOHAMA;
DELETE FROM TIPO_ACTIVIDAD_BUQUE;
DELETE FROM TESTCODIF;
DELETE FROM TEST_SMARTPORT_SUBSCRIBER;
DELETE FROM TEST_PDF;
DELETE FROM TCON_CONFIG;
DELETE FROM SERVBAS_REM_TARIFAHORARIA;
DELETE FROM SERVBAS_REM_TARIFAGTPOT;
DELETE FROM SERVBAS_PRAC_TARIFA;
DELETE FROM SERVBAS_AMARRE_TARIFA;
DELETE FROM SAN_PARAMETRO;
DELETE FROM PROCESOSERVBAS;
DELETE FROM PARAMETRO;
DELETE FROM PARAM_VALORADOR;
DELETE FROM PARAM_FORMULARIO;
DELETE FROM PARAM_FACTURAE;
DELETE FROM PARAM_FACTURACION;
DELETE FROM PARAM_ESTADISTICA;
DELETE FROM PARAM_EDI;
DELETE FROM PARAM_DOCUMENTOS;
DELETE FROM M_USUARIOAUX;
DELETE FROM M_USUARIO_TIPOUSUARIOAUX;
DELETE FROM M_MERCANCIASIGMA;
DELETE FROM M_MERCANCIAPESOVEHIC;
DELETE FROM M_MERCANCIAAUXSUBGRUPONAT2;
DELETE FROM M_MERCANCIAAUX43;
DELETE FROM M_MERCANCIAAUX;
DELETE FROM M_GABARRA;
DELETE FROM M_ESTADO_MIEMBRO;
DELETE FROM M_EMBARCACIONAUX;
DELETE FROM M_DOMICILIOAUX;
DELETE FROM M_CONTADORDIAMETRO;
DELETE FROM M_CONTADORAUX;
DELETE FROM M_BUQUECERTAUX;
DELETE FROM M_BUQUE_BACKUP;
DELETE FROM LQ_TIPOTEMPORADA;
DELETE FROM LQ_TIPOT3TRAFINT;
DELETE FROM LQ_TIPIMPUESTO_SUBCUENTA;
DELETE FROM LQ_TEMPORADA;
DELETE FROM LQ_RANGOGT_RESIDUO;
DELETE FROM LQ_PARAMVEHICT3;
DELETE FROM LQ_PARAMCODARANT2;
DELETE FROM LQ_PARAMCODARAN2453;
DELETE FROM LQ_INTERFACE_CONTABLE;
DELETE FROM LQ_ESCALA_COEFENTRADA;
DELETE FROM LQ_ASPECTO_PREFORMATO;
DELETE FROM INT_SINCRONIZACION;
DELETE FROM INT_ASPECTOS_FACTURA;
DELETE FROM GLOBAL_FILTRO;
DELETE FROM EST_TIPO_SCHENGENPASAJE;
DELETE FROM EST_TARAESTIMADA;
DELETE FROM ESCALA_MIGRACION_DOCEDI;
DELETE FROM DP_TIPOCOMPLEM;
DELETE FROM CFG_AUDIT_ENTIDAD_ORDEN;
DELETE FROM CEN_CONSEJO;
DELETE FROM ALERTA_RODANTE;
DELETE FROM DIVERSO_PERIODICO;
DELETE FROM LQ_BORRADORAGRUPADO;
DELETE FROM OCUPSUPBUQUE_LECTURA;
DELETE FROM M_USUARIO_FACTURAEFACE;
DELETE FROM M_BUQUEVERSION;
DELETE FROM LQ_PERIODOANULADO;
DELETE FROM ESCALA_FTBUQUE;
DELETE FROM G3_TRAMO_COARRIDETALLE;
DELETE FROM T8_SUMINGENERICO;
DELETE FROM LQ_TARIFA_SERIE;
DELETE FROM T8_SUMININSTFIJA;
DELETE FROM SAN_EXPEDIENTE;
DELETE FROM B4_PARTIDA;
DELETE FROM T2_EXCURSIONISTA;
DELETE FROM SERVBAS_REMOLCADOR;
DELETE FROM SERVBAS_PRACTICAJE;
DELETE FROM LQ_BORRADORSUMINAGUA;
DELETE FROM LQ_BORRADORLINEACOEF;
DELETE FROM G3_PARTIDADOCADUAN;
DELETE FROM EDI_MENSAJE_MANIFIESTO;
DELETE FROM EDI_MENSAJE_ESCALA;
DELETE FROM M_DOMICILIO;
DELETE FROM M_CONTADOR_LECTURA;
DELETE FROM LQ_NOTIFICACION_INCID;
DELETE FROM LQ_FACTURA_HECHO_IMPONIBLE;
DELETE FROM G3_EQUIP_PARTIDA;
DELETE FROM G3_CABECERA_TRAMOS_PREVISTOS;
DELETE FROM ESCALA_LOGMODIFOFICIO;
DELETE FROM CEN_DOMICILIO;
DELETE FROM RENDIMIENTO_GRUA;
DELETE FROM M_BUQUE_ART194;
DELETE FROM LQ_FACTURA_LOTE_INCIDENCIA;
DELETE FROM LQ_CAMBIOSERVVALORADO;
DELETE FROM LQ_BORRADORRODANTE;
DELETE FROM G3_TRAFINT_PARTIDA;
DELETE FROM G3_NDP_IMPPARTIDA;
DELETE FROM G3_NDP_EXPPARTIDA;
DELETE FROM ESCALA_CONTRASTEBUQUE;
DELETE FROM B5_M_AMARRE_VERSION;
DELETE FROM SERVBAS_AMARRE;
DELETE FROM PROCESO_COARRI_ERROR;
DELETE FROM MALLAAGUA_ASOCCONTADOR;
DELETE FROM LQ_REGLALIQNOCTURNA;
DELETE FROM LQ_FACTURAE_INCID;
DELETE FROM LQ_BORRADORLINEABONIF;
DELETE FROM LQ_ASPECTO_IDIOMA;
DELETE FROM LQ_ASPECTO_CAMPO_PREF_IDIOMA;
DELETE FROM GE_NOTIFICACION_LISTADISTRIB;
DELETE FROM GE_CAMBIO;
DELETE FROM G4_PARTIDA;
DELETE FROM G3_TRAMO_MOTIVVERSION;
DELETE FROM G3_NDP_IMPEQUIP;
DELETE FROM G3_NDP_EXPEQUIP;
DELETE FROM ESCALA_PLANIFDETALLE;
DELETE FROM ESCALA_DOCPIDE;
DELETE FROM EDI_MENSAJE_ERROR;
DELETE FROM B5_M_EMBARCACION_VERSION;
DELETE FROM T3_SUMINTRAFINTPARTIDA;
DELETE FROM SAN_PARTE;
DELETE FROM LQ_TARIFA_FIRMA;
DELETE FROM LQ_PARAMEQUIPT3;
DELETE FROM LQ_FACTURA_TIPAGRLOTE_TARIFA;
DELETE FROM LQ_FACTURA_INCIDENCIA_SPYRO;
DELETE FROM LQ_AGRUPAP_TASA;
DELETE FROM LOG_TRAMITATRAQUE;
DELETE FROM GE_NOTIFICACION_EDIMENSAJE;
DELETE FROM G4_DECLARANTECONFIG;
DELETE FROM G3_TRAMO_COARRICONT;
DELETE FROM G3_NDP_CONTPART;
DELETE FROM G3_NDP_CONTEQUIP;
DELETE FROM EDI_BUZON;
DELETE FROM EDI_AUDITORIA;
DELETE FROM DP_USOCONSUNTIVO;
DELETE FROM DP_OCUPACION_BONIF;
DELETE FROM DP_FIANZA;
DELETE FROM DP_EXPEDIENTERELACION;
DELETE FROM DP_CANONACTIV_HISTUNIDAD;
DELETE FROM DP_BIENPUBLICO_ZONA;
DELETE FROM DP_ACTIVIDAD_BONIF;
DELETE FROM CEN_EXPEDIENTE;
DELETE FROM ALERTA_AEBORRADOR;
DELETE FROM PARAM_REFERENCIA_FACTURA;
DELETE FROM MALLAAGUA_CONTADOR;
DELETE FROM M_USUARIO_CUENTAS;
DELETE FROM M_USU_CONTAC_PUERTO;
DELETE FROM M_SERVMARIT_PUERTO;
DELETE FROM M_BUQUEAUX;
DELETE FROM M_AREAGEOG_PUERTO;
DELETE FROM LQ_FACTURA_LOTE_AGRUPA;
DELETE FROM GE_NOTIFICACION_CUERPO;
DELETE FROM GE_ASOCIACION_DOCUMENTOS;
DELETE FROM G3_TIPOTAMEQUIP_OPCIONAL;
DELETE FROM G3_TERMPOLIVAL;
DELETE FROM G3_CABECERALOG;
DELETE FROM EST_PARAMUTIEQ;
DELETE FROM EST_PARAMTUCAEQNOCN;
DELETE FROM ESCALA_PLANENTMARPOL;
DELETE FROM ESCALA_ENTREGAMARPOL;
DELETE FROM ESCALA_CONTROLSOLAPADA;
DELETE FROM DPP_VOLUMENACTIVIDAD;
DELETE FROM DP_PROYECTO;
DELETE FROM DP_MEJORACONCURSO;
DELETE FROM DP_INCIDENCIA;
DELETE FROM DP_HIPOTECA;
DELETE FROM DP_EXPEDIENTE_COMPLEM;
DELETE FROM DP_CIFRANEGOCIO;
DELETE FROM DP_CANONACTIV_RANGOUNID;
DELETE FROM CEN_EMPLEADO;
DELETE FROM TRAM_TRAMITE_INFOADIC;
DELETE FROM TRAM_TIPOTRAM_TIPOEXPDP;
DELETE FROM TRAM_TIPOCAMPO_TIPOTRAM;
DELETE FROM TIPO_BUQUEBONIF;
DELETE FROM PARAM_SUJPASB4_PUERTO;
DELETE FROM OPER_PARAM_GET_CALL;
DELETE FROM MEN_COARRIDETALLE_INFO;
DELETE FROM MEN_COARRIDETALLE_ENTI;
DELETE FROM MEN_COARRIDETALLE_ADIC;
DELETE FROM M_USUARIO_TIPOUSUARIO;
DELETE FROM M_USUARIO_PUERTO;
DELETE FROM M_SERVMARIT_NAVIERA;
DELETE FROM M_SERVMARIT_BUQUE;
DELETE FROM M_NORAY;
DELETE FROM M_MUELLEBONIF;
DELETE FROM M_BUQUEBONIF;
DELETE FROM M_BUQUE_FEC_ULT_LIQ_TR_SIGMA;
DELETE FROM M_AREAOPPE_PAIS;
DELETE FROM LQ_FACTURACION_COLA;
DELETE FROM LQ_FACTURA_LOTE_PDF;
DELETE FROM LQ_ACUMCLIENTEBONIF;
DELETE FROM GU_USUAPLI_PUERTO;
DELETE FROM GU_PERFIL_FUNCIONALIDAD;
DELETE FROM G5_MARINACOMPLEMENTARIA;
DELETE FROM G5_MARINAATRAQUE;
DELETE FROM G3_EXCEPCIONCN;
DELETE FROM EST_PARAMFPTUCA;
DELETE FROM EST_PARAMFPTIPOBULTO;
DELETE FROM ESCALA_PLANIFCONSIGNATARIO;
DELETE FROM ESCALA_PLANIFBUQUE;
DELETE FROM DPP_ZONAVALORPRECIO;
DELETE FROM DP_TIPOOCUP_TIPOEXP;
DELETE FROM DP_TASACION;
DELETE FROM DP_LOGFECULTLIQEXPED;
DELETE FROM DP_EXPEDIENTEREVACTIV;
DELETE FROM CONTADOR_SERVMARIT;
DELETE FROM CONTADOR_BUQUE;
DELETE FROM CEN_VEHICULO;
DELETE FROM B4_CARGAFICHEROCOR_TEMP;
DELETE FROM TM_PROCESOCARGAERROR;
DELETE FROM TIPO_BUQUE_GIS;
DELETE FROM PROCESOLIQUID_ERROR;
DELETE FROM PROCESOFACT_ERROR;
DELETE FROM PROCESO_MIGRACION_ERROR;
DELETE FROM PARAM_INTEGRATION;
DELETE FROM OPER_PARAM_INTEGRATION;
DELETE FROM NOVEDAD_RODANTE;
DELETE FROM MENU;
DELETE FROM M_USUARIO_SUBCUENTA;
DELETE FROM M_TMCD;
DELETE FROM M_SHENGEN;
DELETE FROM M_SERVICIOMARIT_NAV;
DELETE FROM M_REMOLCADOR;
DELETE FROM M_PAISUE;
DELETE FROM M_FESTIVO_SERVBAS;
DELETE FROM M_FESTIVO;
DELETE FROM LQ_TEXTOSBOR;
DELETE FROM LQ_FACTURAE_APERAK_ERROR;
DELETE FROM LQ_FACTURA_SERIE_NUMERACION;
DELETE FROM LQ_FACTURA_SERIE_ERP;
DELETE FROM LQ_BORRADOR_LOG_ANUL;
DELETE FROM LOGRODANTE;
DELETE FROM LOGMENSAJERIA;
DELETE FROM LOGMAESTROCOARRI;
DELETE FROM LOGDP;
DELETE FROM LOGCONTMERC;
DELETE FROM LOGAE;
DELETE FROM GU_USUAPLI_PERFIL;
DELETE FROM GU_USUAPLI_FILTRO;
DELETE FROM GU_USUAPLI_CONFIG;
DELETE FROM GLOBAL_CONFIG;
DELETE FROM GE_ALARMA_EMAIL;
DELETE FROM G5_PROCESOCARGAERROR;
DELETE FROM G5_MARINA_PDTELIQ;
DELETE FROM G5_MARINA_COEF;
DELETE FROM G5_EXPGESTDIRECTA_PDTELIQ;
DELETE FROM G5_BASEAGUA_PDTELIQ;
DELETE FROM G4_PROCESOCARGAWARNING;
DELETE FROM G4_PROCESOCARGAERROR;
DELETE FROM G4_ESPECIEPRECIO;
DELETE FROM G3_PROCESOCARGAERROR;
DELETE FROM EXPAGUA_NODP_PDTELIQ;
DELETE FROM EST_TIPOMERC_FP_MEM;
DELETE FROM EST_TIPOMERC_FP_EMC;
DELETE FROM EST_PARAMCODVEHREGMERC;
DELETE FROM DP_UNIDADMAXPRECIO;
DELETE FROM DP_EXPAGUA_PDTELIQ;
DELETE FROM CFG_PUBLISH_CAMPO_VALOR;
DELETE FROM CEN_SEC_CARNET;
DELETE FROM CEN_EPIGRAFE;
DELETE FROM B4_ESPECIE_FAO;
DELETE FROM DIVERSO_GENERICO;
DELETE FROM G4_PESCA;
DELETE FROM GE_CONTROL_CAMBIO;
DELETE FROM TRAM_TRAMITE;
DELETE FROM SAN_INFRACCION_COMUN;
DELETE FROM LQ_FACTURAE_APERAK;
DELETE FROM EDI_ERROR;
DELETE FROM GE_OPERACION_CAMBIO;
DELETE FROM CFG_PUBLISH_CAMPO;
DELETE FROM B5_M_CATEGORIA;
DELETE FROM TIPO_BUQUE_EDI;
DELETE FROM T3_TIPOSUMINTRAFINT;
DELETE FROM SAN_VEHICULO;
DELETE FROM LQ_CUANTIABASICA;
DELETE FROM LQ_COEFSERVICIO;
DELETE FROM LQ_COEFPUERTO;
DELETE FROM GE_ALARMA;
DELETE FROM G5_PROCESOCARGA;
DELETE FROM B5_M_TIPO_EMBARCACION;
DELETE FROM B5_M_AMARRE;
DELETE FROM GE_NOTIFICACION;
DELETE FROM G4_ESPECIE;
DELETE FROM MALLAAGUA;
DELETE FROM M_SUCURSAL;
DELETE FROM M_NAVIERA;
DELETE FROM T3_SUMINTRAFINT;
DELETE FROM T8_SUMINBUQUE;
DELETE FROM G5_TRANSITO;
DELETE FROM OCUPSUP_RODANTE;
DELETE FROM TM_SERVICIO;
DELETE FROM G3_TRAFINT;
DELETE FROM B4_ESPECIE;
DELETE FROM GU_FUNCIONALIDAD;
DELETE FROM ESCALA_PLANIF;
DELETE FROM G3_TRAMO_COARRI;
DELETE FROM ESCALA_REVISION;
DELETE FROM CEN_EMPRESA;
DELETE FROM G3_NDPCAB;
DELETE FROM LQ_ASPECTO_CAMPO_PREFORMATO;
DELETE FROM B4_MANIFIESTO;
DELETE FROM LQ_BORRADORLINEA;
DELETE FROM M_POBLACION;
DELETE FROM OCUPSUPBUQUE;
DELETE FROM M_CAMION;
DELETE FROM GE_PROCESO;
DELETE FROM GE_ORIGEN_CAMBIO_TIPO;
DELETE FROM GE_NOTIFICACION_ESTADO;
DELETE FROM B4_TIPOOPERACION;
DELETE FROM B5_M_PANTALAN;
DELETE FROM B4_SUBTIPOMANIFIESTO;
DELETE FROM T8_TIPOSUMINOTROS;
DELETE FROM T8_TIPOSUMINAGUA;
DELETE FROM GE_NOTIFICACION_TIPO;
DELETE FROM EDI_TIPO_ERROR;
DELETE FROM B4_BUQUEPESQUERO;
DELETE FROM T8_TIPOSUMINELEC;
DELETE FROM SAN_APARTADO_ARTICULO;
DELETE FROM EDI_MENSAJE;
DELETE FROM M_ZONAOCUP;
DELETE FROM DP_CANONOCUPACION;
DELETE FROM OPERACION;
DELETE FROM DP_CANONACTIV;
DELETE FROM LQ_BORRADOR;
DELETE FROM G3_PARTIDA;
DELETE FROM LQ_BAREMOAP;
DELETE FROM EXPAGUA_NODP_CONTADOR;
DELETE FROM G0_PESCALITORAL;
DELETE FROM T0_EMBDEPBASENOAP;
DELETE FROM GE_PROCESO_TIPO;
DELETE FROM M_PASARELA;
DELETE FROM DP_EXPCONTADORAGUA;
DELETE FROM G5_BASE_CONTADOR;
DELETE FROM M_GRUA;
DELETE FROM EDI_TIPO_MENSAJE;
DELETE FROM B5_M_INSTALACION;
DELETE FROM B4_TIPOMANIFIESTO;
DELETE FROM G5_MARINA;
DELETE FROM DP_BIENPUBLICO;
DELETE FROM G5_EXPGESTDIRECTA;
DELETE FROM M_CONTADOR;
DELETE FROM M_AMARRE;
DELETE FROM M_TOMACONTADOR;
DELETE FROM LQ_FACTURA;
DELETE FROM MEN_COARRIDETALLE;
DELETE FROM G3_EQUIPAMIENTO;
DELETE FROM G3_CONOCIMIENTO;
DELETE FROM G3_TRAMO;
DELETE FROM MEN_COARRI;
DELETE FROM G3_CABECERA;
DELETE FROM ESTADIA;
DELETE FROM ESCALA;
DELETE FROM M_MUELLE;
DELETE FROM M_ARMADORCONTENEDOR;
DELETE FROM M_PANTALAN;
DELETE FROM LQ_NOTIFICACION;
DELETE FROM M_RUTACONTADOR;
DELETE FROM M_BUQUECERT;
DELETE FROM M_ZONAMUELLE;
DELETE FROM EXPAGUA_NODP;
DELETE FROM M_INSTALACION;
DELETE FROM LQ_NOTIFICACION_PROCESO;
DELETE FROM DPP_INSTALACION;
DELETE FROM M_ZONACONTAGUA;
DELETE FROM M_SERVICIOMARITIMO;
DELETE FROM M_TERMINAL;
DELETE FROM LQ_FACTURA_LOTE;
DELETE FROM M_BONIFICACION;
DELETE FROM DPP_ZONAVALOR;
DELETE FROM DP_EXPEDIENTE;
DELETE FROM SAN_ARTICULO;
DELETE FROM EDI_CLASE_MENSAJE;
DELETE FROM M_EMBARCACION;
DELETE FROM EDI_ESTADO;
DELETE FROM EDI_CIRCUITO;
DELETE FROM M_MERCANCIA;
DELETE FROM TIPO_BUQUE;
DELETE FROM LQ_ASPECTO;
DELETE FROM M_PUERTO_LOCAL;
DELETE FROM DP_SUBTIPOACTIVIDAD;
DELETE FROM TIPO_BUQUEOPPE;
DELETE FROM SUBTIPO_CONTADORFIJO;
DELETE FROM EST_SUBGRUPO_NATURALEZA;
DELETE FROM DP_TIPOACTIVOCUPACION;
DELETE FROM CFG_PUBLISH_TOPIC;
DELETE FROM B4_FAMILIA;
DELETE FROM PROCESOLIQUID;
DELETE FROM LQ_TIPO_IMPUESTO;
DELETE FROM LQ_AGRUPAP;
DELETE FROM B4_TIPOVENTA;
DELETE FROM TIPO_ACTIV_ESTADIA;
DELETE FROM DP_TIPOEXPEDIENTE;
DELETE FROM M_MUELLETRAMO;
DELETE FROM EST_TIPO_NAVEGACION;
DELETE FROM EST_TUCAOPPE;
DELETE FROM M_TIPO_TRAFICO;
DELETE FROM LQ_TARIFA;
DELETE FROM M_PUERTO;
DELETE FROM GU_USUARIO_APLICACION;
DELETE FROM M_USUARIO;
DELETE FROM TRAM_ESTADOTRAMITE;
DELETE FROM TM_TIPOTARIFA;
DELETE FROM TM_PROCESOCARGA;
DELETE FROM TIPOEXPAGUA_NODP;
DELETE FROM TIPODIRECNORAY;
DELETE FROM TIPOCERT_BUQUE;
DELETE FROM TIPO_UNIDAD_OPERACION;
DELETE FROM TIPO_TRAFINTERIOR;
DELETE FROM TIPO_TONELAJEGRUA;
DELETE FROM TIPO_TERRITSERVMARIT;
DELETE FROM TIPO_T2EXCURSIONISTA;
DELETE FROM TIPO_SUMINAGUA;
DELETE FROM TIPO_PROPIETARIOGRUA;
DELETE FROM TIPO_OPERACION;
DELETE FROM TIPO_MEDIO_MANIPULACION;
DELETE FROM TIPO_LECTURA_CONTADORAGUA;
DELETE FROM TIPO_ENGANCHEGRUA;
DELETE FROM TIPO_EMBARCACION;
DELETE FROM TIPO_ELEM_RODANTE_TABLET;
DELETE FROM TIPO_ELEM_RODANTE;
DELETE FROM TIPO_DOC_PIDE;
DELETE FROM TIPO_DESECHO;
DELETE FROM TIPO_CONTRASTEBUQUE;
DELETE FROM TIPO_COMB_SUMINCOMB;
DELETE FROM TIPO_CARGA_OPERACION;
DELETE FROM TIPO_CALIBREAGUA;
DELETE FROM TIPO_BUQUECOMERCIAL;
DELETE FROM TIPO_ALQPASARELA;
DELETE FROM SUBTIPO_ACTIVIDAD;
DELETE FROM SAN_TURNO;
DELETE FROM SAN_ESTADO_EXP;
DELETE FROM PROCESO_MIGRACION;
DELETE FROM PROCESO_COARRI;
DELETE FROM OCUPSUP_TIPORODANTE;
DELETE FROM OCUPSUP_TIPOEMB;
DELETE FROM OCUPSUP_TIPOALM;
DELETE FROM OCUPSUP_EXENHORAS;
DELETE FROM M_SERVMARITENCALIDAD;
DELETE FROM M_RECEPTOR_MERCANCIA;
DELETE FROM M_INSTALESPECIAL;
DELETE FROM M_BARCAZA;
DELETE FROM M_BANCO;
DELETE FROM M_AREAOPPE;
DELETE FROM LQ_TIPOBORRADOR;
DELETE FROM LQ_TIPO_COBRO;
DELETE FROM LQ_NOTIF_INCID_TIPO;
DELETE FROM LQ_MOTIVOIMPORTECERO;
DELETE FROM LQ_FACTURAE_TIPO_INCID;
DELETE FROM LQ_FACTURAE_FIRMAS;
DELETE FROM LQ_FACTURAE_ESTADOS;
DELETE FROM LQ_FACTURA_MOTIVO_ANULACION;
DELETE FROM LQ_FACTURA_LOTE_TIPO_INCID;
DELETE FROM LQ_FACTURA_ESTADO_LOTE;
DELETE FROM LQ_FACTURA_ESTADO;
DELETE FROM LQ_ESTADOBORRADOR;
DELETE FROM LQ_ESTADOALERTA_AE;
DELETE FROM LQ_BORRADOR_MOTIVO_ANUL;
DELETE FROM LQ_AGRUPA_TARIFA;
DELETE FROM GU_SUBSISTEMA;
DELETE FROM GU_PERFIL;
DELETE FROM GE_TIPO_DOCUMENTO_ASOC;
DELETE FROM G5_TIPOPTOBASETRANSITO;
DELETE FROM G5_MOTIVEXTINCION;
DELETE FROM G5_ESTADOAUTBASE;
DELETE FROM G4_TIPOOPERACION;
DELETE FROM G4_FORMAPRESENTACION;
DELETE FROM G4_COFRADIA;
DELETE FROM G3_TIPOVEHICULO;
DELETE FROM G3_TIPOTRANSPORTE;
DELETE FROM G3_TIPOOPERACION;
DELETE FROM G3_TIPOOPECOARRI;
DELETE FROM G3_TIPOCONOCIMIENTO;
DELETE FROM G3_TIPOCN;
DELETE FROM G3_TIPO_TRAFINT;
DELETE FROM G3_SITEMBARQUE;
DELETE FROM G3_SITADUANERA;
DELETE FROM G3_MARCAVEHICULO;
DELETE FROM G3_INSTMARCAJE;
DELETE FROM G3_ESTADOEQUIP;
DELETE FROM G3_ESTADO;
DELETE FROM G3_CLASIFADICPARTIDA;
DELETE FROM ESTADO_ESTADIA;
DELETE FROM ESTADO_ESCALA;
DELETE FROM ESTADO_DOC_PIDE;
DELETE FROM ESTADO_CONTRASTE;
DELETE FROM EST_TIPOOPEROPPE;
DELETE FROM EST_TIPOMERC_SIGMA;
DELETE FROM EST_TIPOMERC43;
DELETE FROM EST_TIPOBUQOPPE_EMC;
DELETE FROM EST_TIPO_SITESCALAOPPE;
DELETE FROM EST_TIPO_OPECONOC;
DELETE FROM EST_TIPO_NAVGLOBAL;
DELETE FROM EST_GRUPO_NATURALEZA;
DELETE FROM EST_FORMAPRESENTFAC;
DELETE FROM ESCALA_FORMATRAQPLANIF;
DELETE FROM DP_TIPORANGOUNIDADES;
DELETE FROM DP_TIPOPROYECTO;
DELETE FROM DP_TIPOINCIDENCIA;
DELETE FROM DP_TIPOFIANZA;
DELETE FROM DP_TIPOEXPEDIENTEGLOBAL;
DELETE FROM DP_TIPOBIENPUBLICO;
DELETE FROM DP_TIPOACTIVPRINCIPAL;
DELETE FROM DP_MOTIVEXTINCION;
DELETE FROM DP_MOTIVAMPPERLIQ;
DELETE FROM DP_FORMAVALORACION;
DELETE FROM DP_FORMAFIANZA;
DELETE FROM DP_ESTADOEXPEDIENTE;
DELETE FROM DP_CRITFECHATASACION;
DELETE FROM DP_BANCO;
DELETE FROM CLASECABO;
DELETE FROM CEN_TIPO_VEHICULO;
DELETE FROM CEN_EXPEDIENTE_ESTADO;
DELETE FROM B5_MOTIVO_AMARRE_NODISP;
DELETE FROM B5_M_TIPO_PROPULSION;
DELETE FROM B5_M_LISTA_EMBARCACION;
DELETE FROM B5_M_ESTADO_AMARRE;
DELETE FROM B5_M_EMBARCACION;
DELETE FROM B4_TIPOTAMANYO;
DELETE FROM B4_TIPOFRESCURA;
DELETE FROM B4_TIPOCAPTURA;
DELETE FROM B4_TIPOBUQUE;
DELETE FROM B4_PRESENTACION;
DELETE FROM B4_GRUPOFAMILIA;
DELETE FROM B4_DESTINO;
DELETE FROM B4_COMPRADOR;
DELETE FROM TRAM_TIPOCAMPO;
DELETE FROM TIPO_MOD_SUMINCOMB;
DELETE FROM TIPO_CONTADORFIJO;
DELETE FROM TIPO_CONCESIONMUELLE;
DELETE FROM T8_TIPOCANONXUNTA;
DELETE FROM SAN_DENUNCIADO;
DELETE FROM PROCESOFACT;
DELETE FROM OPER_EVENT_AIS;
DELETE FROM OCUPSUP_TIPOOPE;
DELETE FROM M_USUARIO_CONTACTO;
DELETE FROM M_PRACTICO;
DELETE FROM M_EMPRESA_SUMIN;
DELETE FROM M_EMBPESCALITORAL;
DELETE FROM M_DOMICILIO_SIGLAS;
DELETE FROM M_AREA_GEOGRAFICA;
DELETE FROM LQ_TIPOSUJETO;
DELETE FROM LQ_GRUPOBORRADOR;
DELETE FROM LQ_FACTURA_TIPO_AGRUPA_LOTE;
DELETE FROM G4_TIPOGRAVAMEN;
DELETE FROM G4_TIPOCAPTURA;
DELETE FROM G4_PROCESOCARGA;
DELETE FROM G4_FAMILIA;
DELETE FROM G4_CLASE;
DELETE FROM G4_CENTROPRIMERAVENTA;
DELETE FROM G3_TIPOTRANS_SIMPLIF;
DELETE FROM G3_TIPOTERRITORIO;
DELETE FROM G3_TIPOCABECERA;
DELETE FROM G3_TIPOBULTO;
DELETE FROM G3_NDP_ESTADODUA;
DELETE FROM G3_LLENOVACIO;
DELETE FROM G3_GRUPOMERCANCIA;
DELETE FROM EST_TIPOTRANSPOPPE;
DELETE FROM EST_TIPOEQPARTMEM;
DELETE FROM EST_TIPO_VEHREGMERC;
DELETE FROM EST_TIPO_UTI;
DELETE FROM DP_UNIDADMAX;
DELETE FROM DP_TIPOUSO;
DELETE FROM DP_TIPOACTIVIDAD;
DELETE FROM DP_MOTIVEXENCION;
DELETE FROM CFG_PUBLISH_AUDIT_ENTIDAD;
DELETE FROM B4_ZONAPESCA;
DELETE FROM B4_ARTEPESCA;
DELETE FROM TRAM_TIPOTRAMITE;
DELETE FROM TIPO_PROPULSION;
DELETE FROM TIPO_PLANRESIDUO;
DELETE FROM TIPO_DOCUMENTO;
DELETE FROM TIPO_AMARRE;
DELETE FROM M_ZONA_AGUA;
DELETE FROM M_MOTIVOVERSION;
DELETE FROM LQ_TIPO_NOTIFICACION;
DELETE FROM LQ_PERIODICIDAD;
DELETE FROM G3_TIPOEQUIPLIQ;
DELETE FROM G3_FICHEROCARGA;
DELETE FROM EST_TIPO_NAVOPPE;
DELETE FROM DP_TIPOOCUPACION;
DELETE FROM DP_PERIODOLIQ;
DELETE FROM B5_M_TIPO_ATRAQUE;
DELETE FROM B4_TIPODOCUMENTO;
DELETE FROM AGUA_MOTIVEXENCION;
DELETE FROM TIPO_USUARIO;
DELETE FROM TIPO_CONCESIONB2;
DELETE FROM LQ_FORMALIQ;
DELETE FROM GU_IDIOMA;
DELETE FROM G3_TIPOREGIMEN;
DELETE FROM G3_TIPOMOVMERC;
DELETE FROM FORMA_ATRAQUE;
DELETE FROM TIPO_CONCESIONB3;
DELETE FROM LQ_SUBCUENTA;
DELETE FROM TIPOMANIOBRA;
DELETE FROM TIPO_PRESTACIONBUQUE;
DELETE FROM T8_TIPOSUMINISTRO;
DELETE FROM M_PROVINCIA;
DELETE FROM LQ_CENTROCOSTE;
DELETE FROM G3_TIPOTAMEQUIP;
DELETE FROM G3_TIPOEQUIP;
DELETE FROM EST_FORMAPRESENT;
DELETE FROM EST_TIPO_TERRITORIO;
DELETE FROM APAC_TIPOPUERTO;
DELETE FROM LQ_FACTURA_SERIE;
DELETE FROM LQ_TIPO_SERVICIO;
DELETE FROM M_BUQUE;
DELETE FROM M_PAIS;
DELETE FROM LQ_TIPO_IMPUESTOGLOBAL;

-- Carga de maestros predefinidos por prodevelop
@plantilla/LQ_TIPO_IMPUESTOGLOBAL.sql
@plantilla/M_PAIS.sql
@plantilla/LQ_TIPO_SERVICIO
@plantilla/EST_TIPO_TERRITORIO
@plantilla/EST_FORMAPRESENT
@plantilla/G3_TIPOEQUIP
@plantilla/G3_TIPOTAMEQUIP
@plantilla/LQ_CENTROCOSTE
@plantilla/T8_TIPOSUMINISTRO
@plantilla/TIPO_PRESTACIONBUQUE
@plantilla/TIPOMANIOBRA
@plantilla/TIPO_CONCESIONB3
@plantilla/FORMA_ATRAQUE
@plantilla/G3_TIPOMOVMERC
@plantilla/G3_TIPOREGIMEN
@plantilla/GU_IDIOMA
@plantilla/LQ_FORMALIQ
@plantilla/TIPO_CONCESIONB2
@plantilla/DP_PERIODOLIQ
@plantilla/DP_TIPOOCUPACION
@plantilla/EST_TIPO_NAVOPPE
@plantilla/G3_TIPOEQUIPLIQ
@plantilla/LQ_PERIODICIDAD
@plantilla/LQ_TIPO_NOTIFICACION
@plantilla/M_ZONA_AGUA
@plantilla/TIPO_AMARRE
@plantilla/TIPO_DOCUMENTO
@plantilla/TIPO_PLANRESIDUO
@plantilla/TIPO_PROPULSION
@plantilla/B4_ARTEPESCA
@plantilla/B4_ZONAPESCA
@plantilla/DP_TIPOACTIVIDAD
@plantilla/DP_TIPOUSO
@plantilla/DP_UNIDADMAX
@plantilla/EST_TIPO_UTI
@plantilla/EST_TIPO_VEHREGMERC
@plantilla/EST_TIPOEQPARTMEM
@plantilla/EST_TIPOTRANSPOPPE
@plantilla/G3_GRUPOMERCANCIA
@plantilla/G3_LLENOVACIO
@plantilla/G3_NDP_ESTADODUA
@plantilla/G3_TIPOBULTO
@plantilla/G3_TIPOCABECERA
@plantilla/G3_TIPOTERRITORIO
@plantilla/G3_TIPOTRANS_SIMPLIF
@plantilla/G4_CLASE
@plantilla/G4_FAMILIA
@plantilla/G4_TIPOCAPTURA
@plantilla/G4_TIPOGRAVAMEN
@plantilla/LQ_FACTURA_TIPO_AGRUPA_LOTE
@plantilla/LQ_GRUPOBORRADOR
@plantilla/LQ_TIPOSUJETO
@plantilla/M_AREA_GEOGRAFICA
@plantilla/M_DOMICILIO_SIGLAS
@plantilla/M_PRACTICO
@plantilla/OCUPSUP_TIPOOPE
@plantilla/TIPO_CONCESIONMUELLE
@plantilla/TIPO_CONTADORFIJO
@plantilla/TIPO_MOD_SUMINCOMB
@plantilla/B4_DESTINO
@plantilla/B4_GRUPOFAMILIA
@plantilla/B4_PRESENTACION
@plantilla/B4_TIPOBUQUE
@plantilla/B4_TIPOCAPTURA
@plantilla/B4_TIPOFRESCURA
@plantilla/B4_TIPOTAMANYO
@plantilla/CEN_EXPEDIENTE_ESTADO
@plantilla/DP_CRITFECHATASACION
@plantilla/DP_ESTADOEXPEDIENTE
@plantilla/DP_FORMAFIANZA
@plantilla/DP_FORMAVALORACION
@plantilla/DP_MOTIVEXTINCION
@plantilla/DP_TIPOACTIVPRINCIPAL
@plantilla/DP_TIPOBIENPUBLICO
@plantilla/DP_TIPOEXPEDIENTEGLOBAL
@plantilla/DP_TIPOFIANZA
@plantilla/DP_TIPOINCIDENCIA
@plantilla/DP_TIPOPROYECTO
@plantilla/DP_TIPORANGOUNIDADES
@plantilla/EST_FORMAPRESENTFAC
@plantilla/EST_GRUPO_NATURALEZA
@plantilla/EST_TIPO_NAVGLOBAL
@plantilla/EST_TIPO_OPECONOC
@plantilla/EST_TIPO_SITESCALAOPPE
@plantilla/EST_TIPOBUQOPPE_EMC
@plantilla/EST_TIPOMERC43
@plantilla/EST_TIPOMERC_SIGMA
@plantilla/EST_TIPOOPEROPPE
@plantilla/ESTADO_CONTRASTE
@plantilla/ESTADO_ESCALA
@plantilla/ESTADO_ESTADIA
@plantilla/G3_ESTADO
@plantilla/G3_ESTADOEQUIP
@plantilla/G3_MARCAVEHICULO
@plantilla/G3_SITADUANERA
@plantilla/G3_SITEMBARQUE
@plantilla/G3_TIPO_TRAFINT
@plantilla/G3_TIPOCN
@plantilla/G3_TIPOCONOCIMIENTO
@plantilla/G3_TIPOOPECOARRI
@plantilla/G3_TIPOOPERACION
@plantilla/G3_TIPOTRANSPORTE
@plantilla/G3_TIPOVEHICULO
@plantilla/G4_FORMAPRESENTACION
@plantilla/G4_TIPOOPERACION
@plantilla/G5_ESTADOAUTBASE
@plantilla/G5_MOTIVEXTINCION
@plantilla/G5_TIPOPTOBASETRANSITO
@plantilla/GU_PERFIL
@plantilla/GU_SUBSISTEMA
@plantilla/LQ_AGRUPA_TARIFA
@plantilla/LQ_BORRADOR_MOTIVO_ANUL
@plantilla/LQ_ESTADOBORRADOR
@plantilla/LQ_FACTURA_ESTADO
@plantilla/LQ_FACTURA_ESTADO_LOTE
@plantilla/LQ_FACTURA_LOTE_TIPO_INCID
@plantilla/LQ_FACTURA_MOTIVO_ANULACION
@plantilla/LQ_TIPO_COBRO
@plantilla/LQ_TIPOBORRADOR
@plantilla/M_SERVMARITENCALIDAD
@plantilla/OCUPSUP_EXENHORAS
@plantilla/OCUPSUP_TIPOALM
@plantilla/OCUPSUP_TIPOEMB
@plantilla/OCUPSUP_TIPORODANTE
@plantilla/SAN_ESTADO_EXP
@plantilla/SAN_TURNO
@plantilla/SUBTIPO_ACTIVIDAD
@plantilla/TIPO_ALQPASARELA
@plantilla/TIPO_CALIBREAGUA
@plantilla/TIPO_CARGA_OPERACION
@plantilla/TIPO_COMB_SUMINCOMB
@plantilla/TIPO_CONTRASTEBUQUE
@plantilla/TIPO_DESECHO
@plantilla/TIPO_ELEM_RODANTE
@plantilla/TIPO_ELEM_RODANTE_TABLET
@plantilla/TIPO_EMBARCACION
@plantilla/TIPO_ENGANCHEGRUA
@plantilla/TIPO_LECTURA_CONTADORAGUA
@plantilla/TIPO_MEDIO_MANIPULACION
@plantilla/TIPO_OPERACION
@plantilla/TIPO_PROPIETARIOGRUA
@plantilla/TIPO_SUMINAGUA
@plantilla/TIPO_T2EXCURSIONISTA
@plantilla/TIPO_TERRITSERVMARIT
@plantilla/TIPO_TONELAJEGRUA
@plantilla/TIPO_TRAFINTERIOR
@plantilla/TIPO_UNIDAD_OPERACION
@plantilla/TIPOCERT_BUQUE
@plantilla/TIPODIRECNORAY
@plantilla/TIPOEXPAGUA_NODP
@plantilla/GU_USUARIO_APLICACION
@plantilla/M_PUERTO
@plantilla/LQ_TARIFA
@plantilla/M_TIPO_TRAFICO
@plantilla/EST_TUCAOPPE
@plantilla/EST_TIPO_NAVEGACION
@plantilla/DP_TIPOEXPEDIENTE
@plantilla/TIPO_ACTIV_ESTADIA
@plantilla/B4_TIPOVENTA
@plantilla/LQ_AGRUPAP
@plantilla/LQ_TIPO_IMPUESTO
@plantilla/B4_FAMILIA
@plantilla/DP_TIPOACTIVOCUPACION
@plantilla/EST_SUBGRUPO_NATURALEZA
@plantilla/SUBTIPO_CONTADORFIJO
@plantilla/DP_SUBTIPOACTIVIDAD
@plantilla/M_PUERTO_LOCAL
@plantilla/LQ_ASPECTO
@plantilla/M_MERCANCIA
@plantilla/EDI_CIRCUITO
@plantilla/EDI_ESTADO
@plantilla/EDI_CLASE_MENSAJE
@plantilla/SAN_ARTICULO
@plantilla/M_BONIFICACION
@plantilla/B4_TIPOMANIFIESTO
@plantilla/EDI_TIPO_MENSAJE
@plantilla/GE_PROCESO_TIPO
@plantilla/SAN_APARTADO_ARTICULO
@plantilla/EDI_TIPO_ERROR
@plantilla/GE_NOTIFICACION_TIPO
@plantilla/T8_TIPOSUMINOTROS
@plantilla/B4_SUBTIPOMANIFIESTO
@plantilla/B4_TIPOOPERACION
@plantilla/GE_NOTIFICACION_ESTADO
@plantilla/GE_ORIGEN_CAMBIO_TIPO
@plantilla/LQ_ASPECTO_CAMPO_PREFORMATO
@plantilla/GU_FUNCIONALIDAD
@plantilla/B4_ESPECIE
@plantilla/G4_ESPECIE
@plantilla/LQ_COEFPUERTO
@plantilla/LQ_COEFSERVICIO
@plantilla/LQ_CUANTIABASICA
@plantilla/T3_TIPOSUMINTRAFINT
@plantilla/DP_UNIDADMAXPRECIO
@plantilla/EST_PARAMCODVEHREGMERC
@plantilla/EST_TIPOMERC_FP_EMC
@plantilla/EST_TIPOMERC_FP_MEM
@plantilla/G4_ESPECIEPRECIO
@plantilla/GLOBAL_CONFIG
@plantilla/GU_USUAPLI_CONFIG
@plantilla/GU_USUAPLI_FILTRO
@plantilla/GU_USUAPLI_PERFIL
@plantilla/LQ_TEXTOSBOR
@plantilla/M_PAISUE
@plantilla/M_SHENGEN
@plantilla/M_TMCD
@plantilla/MENU
@plantilla/DP_TIPOOCUP_TIPOEXP
@plantilla/EST_PARAMFPTIPOBULTO
@plantilla/EST_PARAMFPTUCA
@plantilla/GU_PERFIL_FUNCIONALIDAD
@plantilla/GU_USUAPLI_PUERTO
@plantilla/EST_PARAMTUCAEQNOCN
@plantilla/EST_PARAMUTIEQ
@plantilla/LQ_AGRUPAP_TASA
@plantilla/LQ_PARAMEQUIPT3
@plantilla/GE_NOTIFICACION_LISTADISTRIB
@plantilla/LQ_ASPECTO_CAMPO_PREF_IDIOMA
@plantilla/LQ_ASPECTO_IDIOMA
@plantilla/EST_TARAESTIMADA
@plantilla/EST_TIPO_SCHENGENPASAJE
@plantilla/GLOBAL_FILTRO
-- @plantilla/LQ_ASPECTO_PREFORMATO
@plantilla/LQ_ESCALA_COEFENTRADA
@plantilla/LQ_PARAMCODARANT2
@plantilla/LQ_PARAMVEHICT3
@plantilla/LQ_RANGOGT_RESIDUO
@plantilla/M_CONTADORDIAMETRO
@plantilla/M_ESTADO_MIEMBRO
@plantilla/PARAM_DOCUMENTOS
@plantilla/PARAM_EDI
@plantilla/PARAM_ESTADISTICA
@plantilla/PARAM_FACTURACION
@plantilla/PARAM_FACTURAE
@plantilla/PARAM_FORMULARIO
@plantilla/PARAM_VALORADOR
@plantilla/PARAMETRO
@plantilla/SAN_PARAMETRO
@plantilla/TCON_CONFIG
@plantilla/TESTCODIF
@plantilla/TIPO_MOD_YOKOHAMA
@plantilla/TIPO_TERMINAL












-- Fallo en FKs
-- @plantilla/LQ_ASPECTO
-- @plantilla/LQ_ASPECTO_CAMPO_PREFORMATO
-- @plantilla/LQ_TEXTOSBOR
-- @plantilla/LQ_ASPECTO_CAMPO_PREF_IDIOMA
-- @plantilla/LQ_ASPECTO_IDIOMA

-- Fallo de campo demasiado largo
-- @plantilla/LQ_ASPECTO_PREFORMATO
