DELETE FROM OPERACION;
DELETE FROM ESTADIA;
delete from ESCALA_FTBUQUE;
DELETE FROM ESCALA;

SELECT * FROM OPERACION;
SELECT * FROM ESTADIA
where estindexenta = '0';
select * from ESCALA_FTBUQUE;
SELECT * FROM ESCALA
where codpue = 'A' and anyo = '2016' and codescala > 500
;

A201600512

SELECT * FROM v_est_escala;


INSERT INTO ESCALA (
    CODPUE
    , ANYO
    , CODESCALA
    , ETA
    , ETD
    , CODPAIORIGEN
    , CODPUEORIGEN
    , CODPAIDESTINO
    , CODPUEDESTINO
    , NUMVIAJE
    , INDAUTCABOTAJE
    , INDNAVINT
    , INDENTFESTIVO
    , INDCONVCALIDAD
    , INDGREENAWARD
    , CODCONSIGNATARIO
    , CODPAIDESPTIEMPO
    , CODPUEDESPTIEMPO
    , FECVALDESPTIEMPO
    , PERDESPTIEMPO
    , NOMBRECAPITAN
    , ENTRADANUMTRIP
    , ENTRADANUMPASAJ
    , ENTRADANUMPOLIZ
    , SALIDANUMTRIP
    , SALIDANUMPASAJE
    , SALIDANUMPOLIZ
    , NUMESCALA
    , INDINSPMOUEFEC
    , FECINSPMOU
    , INDCRUDOFUELALQ
    , INDMMPPABORDO
    , INDMMPPCARGA
    , INDMMPPDESCARGA
    , FECSOLICITUD
    , FECAUTORIZACION
    , FECINIREAL
    , FECFINREAL
    , CODESTADO
    , FECAUTCAPITANIA
    , INDAUTCAPITANIA
    , OBSERVACIONES
    , INDEXISTEACUERDORES
    , CODPAIACUERDORES
    , CODPUEACUERDORES
    , EMPRESAACUERDORES
    , INDCERTSOLAS
    , EMPRESAEMICERTSOLAS
    , FECVENCICERTSOLAS
    , INDMEDPROTECSOLAS
    , INDPROCADECSOLAS
    , NIVELPROTECSOLAS
    , CONTENTRADASERVMARIT
    , INDNECESITAAUTCAPIT
    , DECLARACIONCAPITAN
    , ACUERDORES
    , CONTENTRADABUQUE
    , FECALTA
    , FECMODIF
    , USRALTA
    , USRMODIF
    , OBSCAMBIOESTADO
    , CODSERVMARIT
    , GUIDSRV
    , INDNOLIQUIDABLE
    , INDLIQT0
    , INDLIQT7
    , INDRESIDUOSZONA2
    , INDENTDESULTPUERTO
    , INDRESNOAPLIC10C
    , NUMPUERTOSRES
    , CODPAIORIGENDEC
    , CODPUEORIGENDEC
    , CODPAIDESTINODEC
    , CODPUEDESTINODEC
    , NUMTONMARPOLI
    , NUMTONMARPOLV
    , INDAPLICARB
    , INDEXENTOT0
    , INDREVISAUTORIZACION
    , CODBUQUECERT
    , INDMANUAL
    , TIPTRAFICO
    , INDRECMODIFESCINI
    , CODMUELLEEST1
    , CODTIPACTIVREALEST1
    , INDAPLICAVI193EST1
    , IDSUJPASIVOT0
    , INDLIQT1
    , INDNOLIQT1NOCT
    , INDNOLIQT7NOCT
    , INDNOLIQT0NOCT
    , INDTRAFINT
    , CODTIPOTRAFINT
    , ESTCODTIPNAV
    , ESTCODTIPNAVENT
    , ESTCODTIPNAVSAL
    , ESTCODTIPTER
    , ESTCODTIPSITOPPE
    , ESTINDDESGUACE
    , ESTINDEXENTA
    , INDTINUMESCSUMIN
    , CODTIPOMOVMERCMC
    , CODTIPOMOVMERCDS
    , ESTCODTIPNAVENTOPPE
    , ESTCODTIPNAVSALOPPE
    , ESTCODTIPTERORIG
    , ESTCODTIPTERDEST
    , INDREVISION
    , MODOREVISION
    , TIPOREVISION
    , NUMRESOLUCION
    , FACTRECTIF
    , FECREGSALIDA
    , DOCSUSTRECT
    , CODMOTREVISION
    , INDAPLIC2453PESCA
    , INDAPLIC2453CABL
    , INDAPLIC2453INACT
    , CODTERMINAL
    , INDINISINSECTEMP
    , INDPERIODOMANUAL
    , INDLIQT0PROLONGADA
    , JUSTIFEXENTOT7
    , JUSTIFEXENTOT0
    , CODTIPOIVAT0
    , CODTIPOIVAT1
    , CODTIPOIVAT7
    , IND2453
    , CODBON2453
    , PORC2453
    , IND2454
    , CODBON2454
    , PORC2454
    , IND2455
    , CODBON2455
    , PORC2455
    , IDSUJPASIVOT7
    , INDLIQPORATRAQUES
    , SERVMARITIMOEDI
    , CODBUQUE
    , CODBON24532
    , PORC24532
    , CODBON24533
    , PORC24533
    , CODBON24534
    , PORC24534
    , OBSERVACIONESFACT
    , INDMIGRACION
)
SELECT * FROM (
    SELECT 
        (SELECT SUBP_CODIGO FROM IGEN_SUBPUERTO_SUBP WHERE SUBP_ID = serv_subp_id) AS CODPUE
        , serv_anno AS ANYO
        , serv_numero CODESCALA
        , coalesce(ESCA_FECHA_INICIO, esca_fecha_entrada) AS ETA
        , coalesce(ESCA_FECHA_finalizacion, esca_fecha_salida) AS ETD
        , (select pais_iso from igen_pais_pais where pais_id = ESCA_PAIS_ID_ANTERIOR) AS CODPAIORIGEN
        , (select unlo_codigo from igen_unlocode_unlo where unlo_id = ESCA_loco_ID_ANTERIOR) AS CODPUEORIGEN
        , (select pais_iso from igen_pais_pais where pais_id = ESCA_PAIS_ID_siguiente) AS CODPAIDESTINO
        , (select unlo_codigo from igen_unlocode_unlo where unlo_id = ESCA_loco_ID_siguiente) AS CODPUEDESTINO
        , ESCA_REF_MENSAJE_EDI AS NUMVIAJE
        , ES_AUT_CABOTAJE AS INDAUTCABOTAJE
        , ESCA_ES_NAVEGACION_INT AS INDNAVINT
        , 0 AS INDENTFESTIVO
        , 0 AS INDCONVCALIDAD
        , 0 AS INDGREENAWARD
        , (select trid_new_id from tbl_traduccion_ids_trid where trid_table_name = 'ICOM_ORGANIZACION_ORGA' AND trid_old_id = ESCA_ORGA_ID_CONSIGNAT) AS CODCONSIGNATARIO
        , NULL AS CODPAIDESPTIEMPO
        , NULL AS CODPUEDESPTIEMPO
        , NULL AS FECVALDESPTIEMPO
        , NULL AS PERDESPTIEMPO
        , COALESCE(ESCA_CAPITAN_ENTRADA, ESCA_CAPITAN_SALIDA) AS NOMBRECAPITAN
        , COALESCE(ESCA_TRIPULANTES_ENTRADA, 0) AS ENTRADANUMTRIP
        , COALESCE(ESCA_PASAJEROS_ENTRADA, 0) AS ENTRADANUMPASAJ
        , COALESCE(ESCA_POLIZONES_ENTRADA, 0) AS ENTRADANUMPOLIZ
        , COALESCE(ESCA_TRIPULANTES_SALIDA, 0) AS SALIDANUMTRIP
        , COALESCE(ESCA_PASAJEROS_SALIDA, 0) AS SALIDANUMPASAJE
        , COALESCE(ESCA_POLIZONES_SALIDA, 0) AS SALIDANUMPOLIZ
        , CONCAT((SELECT SUBP_CODIGO FROM IGEN_SUBPUERTO_SUBP WHERE SUBP_ID = serv_subp_id), CONCAT(serv_anno, serv_numero)) AS NUMESCALA
        , buqut.BUQU_ES_MOU_PSC_INSPECCION AS INDINSPMOUEFEC
        , buqut.BUQU_FECHA_MOU_PSC_INSPECCION AS FECINSPMOU
        , ES_CRUDO_TRANSPORTADO AS INDCRUDOFUELALQ
        , 0 AS INDMMPPABORDO
        , 0 AS INDMMPPCARGA
        , 0 AS INDMMPPDESCARGA
        , NULL AS FECSOLICITUD
        , NULL AS FECAUTORIZACION
        , ESCA_FECHA_INICIO AS FECINIREAL
        , ESCA_FECHA_FINALIZACION AS FECFINREAL
        , (case ESCA_ESTADO 
            when 'I' then 'IN' 
            when 'F' then 'FI' 
            when 'A' then 'AN' 
            when 'D' then 'DE' 
            when 'C' then 'AU' 
            when 'S' then 'AC' 
        end) AS CODESTADO
        , ESCA_FECHA_CAP_MAR AS FECAUTCAPITANIA
        , (case when ESCA_FECHA_CAP_MAR is null then '0' else '1' end) AS INDAUTCAPITANIA
        , ESCA_OBSERV AS OBSERVACIONES
        , (case when ESCA_ACUE_ID is null then '0' else '1' end) AS INDEXISTEACUERDORES
        , NULL AS CODPAIACUERDORES
        , NULL AS CODPUEACUERDORES
        , NULL AS EMPRESAACUERDORES
        , 0 AS INDCERTSOLAS
        , NULL AS EMPRESAEMICERTSOLAS
        , NULL AS FECVENCICERTSOLAS
        , 0 AS INDMEDPROTECSOLAS
        , 0 AS INDPROCADECSOLAS
        , NULL AS NIVELPROTECSOLAS
        , NULL AS CONTENTRADASERVMARIT
        , 0 AS INDNECESITAAUTCAPIT
        , NULL AS DECLARACIONCAPITAN
        , NULL AS ACUERDORES
        , NULL AS CONTENTRADABUQUE
        , SYSDATE AS FECALTA
        , SYSDATE AS FECMODIF
        , 'prueba' AS USRALTA
        , 'prueba' AS USRMODIF
        , NULL AS OBSCAMBIOESTADO
        , NULL AS CODSERVMARIT
        , esca_id AS GUIDSRV
        , 0 AS INDNOLIQUIDABLE
        , 0 AS INDLIQT0
        , 0 AS INDLIQT7
        , 0 AS INDRESIDUOSZONA2
        , 0 AS INDENTDESULTPUERTO
        , 0 AS INDRESNOAPLIC10C
        , NULL AS NUMPUERTOSRES
        , (select pais_iso from igen_pais_pais where pais_id = ESCA_PAIS_ID_ANTERIOR) AS CODPAIORIGENDEC
        , (select unlo_codigo from igen_unlocode_unlo where unlo_id = ESCA_loco_ID_ANTERIOR) AS CODPUEORIGENDEC
        , (select pais_iso from igen_pais_pais where pais_id = ESCA_PAIS_ID_siguiente) AS CODPAIDESTINODEC
        , (select unlo_codigo from igen_unlocode_unlo where unlo_id = ESCA_loco_ID_siguiente) AS CODPUEDESTINODEC
        , NULL AS NUMTONMARPOLI
        , NULL AS NUMTONMARPOLV
        , 0 AS INDAPLICARB
        , 0 AS INDEXENTOT0
        , 0 AS INDREVISAUTORIZACION
        , NULL AS CODBUQUECERT
        , 0 AS INDMANUAL -- OJO
        , NULL AS TIPTRAFICO
        , 0 AS INDRECMODIFESCINI
        , NULL AS CODMUELLEEST1
        , NULL AS CODTIPACTIVREALEST1
        , 0 AS INDAPLICAVI193EST1
        , NULL AS IDSUJPASIVOT0 -- OJO
        , 0 AS INDLIQT1
        , 0 AS INDNOLIQT1NOCT
        , 0 AS INDNOLIQT7NOCT
        , 0 AS INDNOLIQT0NOCT
        , 0 AS INDTRAFINT -- OJO
        , NULL AS CODTIPOTRAFINT
        , (select navt_codigo from IGEN_NAVEGACIONTIPO_NAVT where navt_id = ESCA_NAVT_ID_ENTRADA) AS ESTCODTIPNAV
        , (select navt_codigo from IGEN_NAVEGACIONTIPO_NAVT where navt_id = ESCA_NAVT_ID_ENTRADA) AS ESTCODTIPNAVENT
        , (select navt_codigo from IGEN_NAVEGACIONTIPO_NAVT where navt_id = ESCA_NAVT_ID_salida) AS ESTCODTIPNAVSAL
        , NULL AS ESTCODTIPTER
        , NULL AS ESTCODTIPSITOPPE
        , 0 AS ESTINDDESGUACE
        , 0 AS ESTINDEXENTA
        , 0 AS INDTINUMESCSUMIN
        , NULL AS CODTIPOMOVMERCMC
        , NULL AS CODTIPOMOVMERCDS
        , NULL AS ESTCODTIPNAVENTOPPE
        , NULL AS ESTCODTIPNAVSALOPPE
        , NULL AS ESTCODTIPTERORIG
        , NULL AS ESTCODTIPTERDEST
        , 0 AS INDREVISION
        , NULL AS MODOREVISION
        , NULL AS TIPOREVISION
        , NULL AS NUMRESOLUCION
        , NULL AS FACTRECTIF
        , NULL AS FECREGSALIDA
        , NULL AS DOCSUSTRECT
        , NULL AS CODMOTREVISION
        , 0 AS INDAPLIC2453PESCA
        , 0 AS INDAPLIC2453CABL
        , 0 AS INDAPLIC2453INACT
        , NULL AS CODTERMINAL
        , 0 AS INDINISINSECTEMP
        , 0 AS INDPERIODOMANUAL
        , 0 AS INDLIQT0PROLONGADA
        , NULL AS JUSTIFEXENTOT7
        , NULL AS JUSTIFEXENTOT0
        , NULL AS CODTIPOIVAT0 -- OJO
        , NULL AS CODTIPOIVAT1 -- OJO
        , NULL AS CODTIPOIVAT7 -- OJO
        , 0 AS IND2453
        , NULL AS CODBON2453
        , NULL AS PORC2453
        , 0 AS IND2454
        , NULL AS CODBON2454
        , NULL AS PORC2454
        , 0 AS IND2455
        , NULL AS CODBON2455
        , NULL AS PORC2455
        , NULL AS IDSUJPASIVOT7 -- OJO
        , 0 AS INDLIQPORATRAQUES
        , NULL AS SERVMARITIMOEDI
        , (select trid_new_id from tbl_traduccion_ids_trid where trid_table_name = 'IESC_BUQUE_BUQU' AND trid_old_id = ESCA_BUQUE_ID) as CODBUQUE
        , NULL AS CODBON24532
        , NULL AS PORC24532
        , NULL AS CODBON24533
        , NULL AS PORC24533
        , NULL AS CODBON24534
        , NULL AS PORC24534
        , ESCA_OBSERV_FACTURACION AS OBSERVACIONESFACT
        , 1 AS INDMIGRACION
    FROM iesc_escala_esca 
        INNER JOIN ICOM_SERVICIO_SERV on serv_id = esca_id
        left join iesc_buque_buqu buqu on esca_buque_id = buqu.BUQU_BUQUE_ID 
        left join IESC_BUQUETEMP_BUQU buqut on 
            esca_buque_id = buqut.BUQU_BUQUE_ID
            and ESCA_FECHA_ENTRADA >= buqut.BUQU_FECHA_CREACION
            and (buqut.BUQU_FECHA_fin is null or buqut.BUQU_FECHA_fin > ESCA_FECHA_ENTRADA)
            and buqut.buqu_es_activo = 1
    WHERE SERV_FECHA_BAJA IS NULL
) sql
/*
WHERE
    NOT EXISTS (
        SELECT 1 FROM M_PUERTO
        WHERE codpais = CODPAIORIGEN
            and codpue = CODPUEORIGEN
    )
    OR NOT EXISTS (
        SELECT 1 FROM M_PUERTO
        WHERE codpais = CODPAIDESTINO
            and codpue = CODPUEDESTINO
    )
*/
;


insert into escala_ftbuque (
    CODPUE
    , ANYO
    , CODESCALA
    , NOMBREARMADOR
    , DIRECARMADOR
    , POBARMADOR
    , CPARMADOR
    , CODPAIARMADOR
    , CIFARMADOR
    , CODPAIREGISTRO
    , CODPUEREGISTRO
    , SOCCLASIFICACION
    , CIAASEGURADORA
    , CLUBPI
    , FECCONSTRUCCION
    , CALMAXIMO
    , GT
    , TPM
    , TRB
    , ESLORATOTAL
    , MANGA
    , PUNTAL
    , ALTURAARBOLADURA
    , POTENCIA
    , VELCRUCERO
    , VELMAXIMA
    , INDDOBLECASCO
    , SBTVOLUMEN
    , SBTUNIDADES
    , RAMPA1SITUACION
    , RAMPA1ALCANCE
    , RAMPA1ANCHURA
    , RAMPA2SITUACION
    , RAMPA2ALCANCE
    , RAMPA2ANCHURA
    , RAMPA3SITUACION
    , RAMPA3ALCANCE
    , RAMPA3ANCHURA
    , RAMPA4SITUACION
    , RAMPA4ALCANCE
    , RAMPA4ANCHURA
    , NUMHELICES
    , SITUACIONHELICES
    , LASTRESUCIO
    , TANFANGOS
    , TANAGUASOLEOSAS
    , AGUASSUCIAS
    , BASURAS
    , INDCERTARQ
    , FECEMICERTARQ
    , LIBROREGISTRO
    , INDINSPMOU
    , CODPAIINSPMOU
    , CODPUEINSPMOU
    , FECINSPMOU
    , NUMDEFINSPMOU
    , CODPAIMATRICULA
    , CODPUEMATRICULA
    , FECMATRICULA
    , MATRICULA
    , INDCERTIGS
    , FECVIGCERTIGS
    , NUMREGCERTIGS
    , CODMMSI
    , OBSERVACIONES
    , FECALTA
    , FECMODIF
    , USRALTA
    , USRMODIF
    , NOMBRE
    , CODTIPBUQUE
    , CODIMO
    , BANDERA
    , CALLSIGN
    , INDCERTMATRICULA
    , CODNAVIERAPORTEL
    , DESCNAVIERAPORTEL
    , CODTIPBUQUEEDI
)
/*
;
select * from escala;

;
*/
SELECT 
    CODPUE AS CODPUE
    , ANYO AS ANYO
    , CODESCALA AS CODESCALA
    , NULL AS NOMBREARMADOR
    , NULL AS DIRECARMADOR
    , NULL AS POBARMADOR
    , NULL AS CPARMADOR
    , NULL AS CODPAIARMADOR
    , NULL AS CIFARMADOR
    , NULL AS CODPAIREGISTRO
    , NULL AS CODPUEREGISTRO
    , NULL AS SOCCLASIFICACION
    , NULL AS CIAASEGURADORA
    , NULL AS CLUBPI
    , NULL AS FECCONSTRUCCION
    , NULL AS CALMAXIMO
    , NULL AS GT
    , NULL AS TPM
    , NULL AS TRB
    , NULL AS ESLORATOTAL
    , NULL AS MANGA
    , NULL AS PUNTAL
    , NULL AS ALTURAARBOLADURA
    , NULL AS POTENCIA
    , NULL AS VELCRUCERO
    , NULL AS VELMAXIMA
    , NULL AS INDDOBLECASCO
    , NULL AS SBTVOLUMEN
    , NULL AS SBTUNIDADES
    , NULL AS RAMPA1SITUACION
    , NULL AS RAMPA1ALCANCE
    , NULL AS RAMPA1ANCHURA
    , NULL AS RAMPA2SITUACION
    , NULL AS RAMPA2ALCANCE
    , NULL AS RAMPA2ANCHURA
    , NULL AS RAMPA3SITUACION
    , NULL AS RAMPA3ALCANCE
    , NULL AS RAMPA3ANCHURA
    , NULL AS RAMPA4SITUACION
    , NULL AS RAMPA4ALCANCE
    , NULL AS RAMPA4ANCHURA
    , NULL AS NUMHELICES
    , NULL AS SITUACIONHELICES
    , NULL AS LASTRESUCIO
    , NULL AS TANFANGOS
    , NULL AS TANAGUASOLEOSAS
    , NULL AS AGUASSUCIAS
    , NULL AS BASURAS
    , NULL AS INDCERTARQ
    , NULL AS FECEMICERTARQ
    , NULL AS LIBROREGISTRO
    , NULL AS INDINSPMOU
    , NULL AS CODPAIINSPMOU
    , NULL AS CODPUEINSPMOU
    , NULL AS FECINSPMOU
    , NULL AS NUMDEFINSPMOU
    , NULL AS CODPAIMATRICULA
    , NULL AS CODPUEMATRICULA
    , NULL AS FECMATRICULA
    , NULL AS MATRICULA
    , NULL AS INDCERTIGS
    , NULL AS FECVIGCERTIGS
    , NULL AS NUMREGCERTIGS
    , NULL AS CODMMSI
    , NULL AS OBSERVACIONES
    , NULL AS FECALTA
    , NULL AS FECMODIF
    , NULL AS USRALTA
    , NULL AS USRMODIF
    , (select nombre from m_buque buq where buq.codbuque = esc.codbuque) AS NOMBRE
    , NULL AS CODTIPBUQUE
    , NULL AS CODIMO
    , bver.bandera AS BANDERA
    , NULL AS CALLSIGN
    , NULL AS INDCERTMATRICULA
    , NULL AS CODNAVIERAPORTEL
    , NULL AS DESCNAVIERAPORTEL
    , NULL AS CODTIPBUQUEEDI
FROM ESCALA esc
    left join M_BUQUEVERSION bver on 
        bver.codbuque = esc.codbuque 
        and bver.FECINIVIG <= esc.FECALTA
        and (bver.FECfinVIG is null or bver.FECfinVIG > esc.FECALTA)
;





SELECT codpue, anyo, codescala, count(1) FROM (
    SELECT 
        (SELECT SUBP_CODIGO FROM IGEN_SUBPUERTO_SUBP WHERE SUBP_ID = serv_subp_id) AS CODPUE
        , serv_anno AS ANYO
        , serv_numero CODESCALA
    FROM iesc_escala_esca 
        INNER JOIN ICOM_SERVICIO_SERV on serv_id = esca_id
        left join iesc_buque_buqu buqu on esca_buque_id = buqu.BUQU_BUQUE_ID
        left join IESC_BUQUETEMP_BUQU buqut on 
            esca_buque_id = buqut.BUQU_BUQUE_ID
            and ESCA_FECHA_ENTRADA >= buqut.BUQU_FECHA_CREACION
            and (buqut.BUQU_FECHA_fin is null or buqut.BUQU_FECHA_fin > ESCA_FECHA_ENTRADA)
            and buqut.buqu_es_activo = 1
    WHERE SERV_FECHA_BAJA IS NULL
) sql
group by codpue, anyo, codescala
having count(1) > 1
;







INSERT INTO ESTADIA (
    CODPUE
    , ANYO
    , CODESCALA
    , CODESTADIA
    , INDMANUAL
    , FECSOLICITUD
    , FECATRAQUEPREV
    , FECDESATRAQUEPREV
    , CODTIPATRAQUEPREV
    , CODMUELLEINIPREV
    , NORAYINIPREV
    , INDEXCPRACTICAJE
    , INDESTPROLONGADA
    , CODTIPACTIVIDAD
    , FECAUTORIZACION
    , INDAGUA
    , INDHIELO
    , INDCOMBUSTIBLE
    , INDLUZ
    , INDFUERZA
    , NORAYFINPREV
    , INDLASTRES
    , INDFANGOS
    , INDSENTINAS
    , INDFECALES
    , INDBASURAS
    , FECATRAQUEREAL
    , FECDESATRAQUEREAL
    , CODTIPATRAQUEREAL
    , CODMUELLEINIREAL
    , NORAYINIREAL
    , CALADOENTRADA
    , CALADOSALIDA
    , NORAYFINREAL
    , CODESTADO
    , INDAVERIAS
    , OBSERVACIONES
    , CODESTADIADUE
    , FECALTA
    , FECMODIF
    , USRALTA
    , USRMODIF
    , OBSCAMBIOESTADO
    , CODTIPPRESTREAL
    , INDOPCOMZONA1FEST
    , INDOPCOMZONA2
    , FECINIOPZONA2
    , CODTIPACTIVREAL
    , IDSUJPASIVO
    , INDLIQT1
    , NORAYINIAUT
    , NORAYFINAUT
    , FECINIAUT
    , CODPRESTPREV
    , CODPRESTINICIO
    , INDEXENTAT1
    , INDESCALAFIN
    , CODMUELLEINIAUT
    , FECFINAUT
    , CODSUBTIPOACTIVIDAD
    , INDAPLICAVI193
    , NOMBRECONSIGESCALA
    , INDTRAFINT
    , INDFINESCMAN
    , INDLIQT7
    , INDEXENTAT7
    , DESCOPERACIONES
    , ESTINDFONDEO
    , NUMOPEPESQUERAS
    , NUMESCEXCURSION
    , PERIODOMANUAL
    , CODTIPATRAQUEAUT
    , INDREVT1DESCPESQUERA
    , CODMUELLEINIPLA
    , NORAYINIPLA
    , NORAYFINPLA
    , FECINIPLA
    , FECFINPLA
    , CODTIPATRAQUEPLA
    , CODTIPOCONCESIONT1
    , JUSTIFEXENTOT1
    , JUSTIFEXENTOT7
    , INDNOAPLICSERVMARIT
    , CODTRAMUEAUT
    , CODTRAMUECODAUT
    , CODTRAMUEREAL
    , CODTRAMUECODREAL
    , INDINICIOVIAAPLICEXT
    , INDFINVIAAPLICEXT
    , INDINISINESTARAUT
    , INDGNL
    , ESTINDEXENTA
)
SELECT 
    (SELECT SUBP_CODIGO FROM IGEN_SUBPUERTO_SUBP WHERE SUBP_ID = serv_subp_id) AS CODPUE
    , serv_anno AS ANYO
    , serv_numero CODESCALA
    , atra_numero AS CODESTADIA
    , NULL AS INDMANUAL
    , ATRA_FECHA_SOLICITUD AS FECSOLICITUD
    , atrds.ATRD_FECHA_INICIO AS FECATRAQUEPREV
    , atrds.ATRD_FECHA_FINALIZACION AS FECDESATRAQUEPREV
    , CONCAT(
        CONCAT(
            (SELECT atet_codigo FROM IESC_ATRAQUEEDITIPO_ATET WHERE atet_id = atrds.ATRD_TIPO_ATRAQUE_EDI_1)
            , (SELECT atet_codigo FROM IESC_ATRAQUEEDITIPO_ATET WHERE atet_id = atrds.ATRD_TIPO_ATRAQUE_EDI_2)
        )
        , (SELECT atet_codigo FROM IESC_ATRAQUEEDITIPO_ATET WHERE atet_id = atrds.ATRD_TIPO_ATRAQUE_EDI_3)
    )
    AS CODTIPATRAQUEPREV
    , (SELECT alin_codigo from igen_alineacion_alin where alin_id = atrds.ATRD_ALINEACION) AS CODMUELLEINIPREV
    , atrds.ATRD_NORAY_INICIAL AS NORAYINIPREV
    , COALESCE(COALESCE(atrdr.ATRD_ES_EXENCION_PRAC_SOL, atrda.ATRD_ES_EXENCION_PRAC_SOL), atrds.ATRD_ES_EXENCION_PRAC_SOL) AS INDEXCPRACTICAJE
    , (case COALESCE(COALESCE(atrdr.ATRD_tipo_estancia, atrda.ATRD_tipo_estancia), atrds.ATRD_tipo_estancia) 
      when 'C' then '0'
      else '1'
      end)
    AS INDESTPROLONGADA
    , (SELECT acet_codigo FROM IESC_ACTIVIDADEDITIPO_ACET where acet_id = atrds.atrd_tipo_actividad_edi) AS CODTIPACTIVIDAD
    , ATRA_FECHA_AUTORIZACION AS FECAUTORIZACION
    , coalesce(coalesce(atrdr.ATRD_ES_AGUA_SOLICITADA, atrda.ATRD_ES_AGUA_SOLICITADA), atrds.ATRD_ES_AGUA_SOLICITADA) AS INDAGUA
    , coalesce(coalesce(atrdr.atrd_es_hielo_solicitado, atrda.atrd_es_hielo_solicitado), atrds.atrd_es_hielo_solicitado) AS INDHIELO
    , coalesce(coalesce(atrdr.atrd_es_combust_solicitado, atrda.atrd_es_combust_solicitado), atrds.atrd_es_combust_solicitado) AS INDCOMBUSTIBLE
    , coalesce(coalesce(atrdr.atrd_es_luz_solicitada, atrda.atrd_es_luz_solicitada), atrds.atrd_es_luz_solicitada) AS INDLUZ
    , coalesce(coalesce(atrdr.atrd_es_fuerza_solicitada, atrda.atrd_es_fuerza_solicitada), atrds.atrd_es_fuerza_solicitada) AS INDFUERZA
    , atrds.ATRD_NORAY_final AS NORAYFINPREV
    , NULL AS INDLASTRES
    , NULL AS INDFANGOS
    , NULL AS INDSENTINAS
    , NULL AS INDFECALES
    , NULL AS INDBASURAS
    , atrdr.ATRD_FECHA_INICIO AS FECATRAQUEREAL
    , atrdr.atrd_fecha_finalizacion AS FECDESATRAQUEREAL
    , CONCAT(
        CONCAT(
            (SELECT atet_codigo FROM IESC_ATRAQUEEDITIPO_ATET WHERE atet_id = atrdr.ATRD_TIPO_ATRAQUE_EDI_1)
            , (SELECT atet_codigo FROM IESC_ATRAQUEEDITIPO_ATET WHERE atet_id = atrdr.ATRD_TIPO_ATRAQUE_EDI_2)
        )
        , (SELECT atet_codigo FROM IESC_ATRAQUEEDITIPO_ATET WHERE atet_id = atrdr.ATRD_TIPO_ATRAQUE_EDI_3)
    )
    AS CODTIPATRAQUEREAL
    , (SELECT alin_codigo from igen_alineacion_alin where alin_id = atrdr.ATRD_ALINEACION) AS CODMUELLEINIREAL
    , atrdr.ATRD_NORAY_INICIAL AS NORAYINIREAL
    , coalesce(coalesce(atrdr.ATRD_CALADO_ENTRADA, atrda.ATRD_CALADO_ENTRADA), atrds.ATRD_CALADO_ENTRADA) AS CALADOENTRADA
    , coalesce(coalesce(atrdr.atrd_calado_salida, atrda.atrd_calado_salida), atrds.atrd_calado_salida) AS CALADOSALIDA
    , atrdr.ATRD_NORAY_final AS NORAYFINREAL
    , (case atra_estado
        when 'I' then 'IN'
        when 'F' then 'FI'
        when 'S' then 'AC'
        when 'D' then 'DE'
        when 'C' then 'AU'
        when 'A' then 'AN'
    end) AS CODESTADO
    , NULL AS INDAVERIAS
    , coalesce(coalesce(atrdr.ATRD_OBSERVACIONES, atrda.ATRD_OBSERVACIONES), atrds.ATRD_OBSERVACIONES) AS OBSERVACIONES
    , NULL AS CODESTADIADUE
    , sysdate AS FECALTA
    , NULL AS FECMODIF
    , NULL AS USRALTA
    , NULL AS USRMODIF
    , NULL AS OBSCAMBIOESTADO
    , NULL AS CODTIPPRESTREAL
    , NULL AS INDOPCOMZONA1FEST
    , NULL AS INDOPCOMZONA2
    , coalesce(coalesce(atrdr.ATRD_FECHA_INICIO_OPERAC, atrda.ATRD_FECHA_INICIO_OPERAC), atrds.ATRD_FECHA_INICIO_OPERAC) AS FECINIOPZONA2
    , (SELECT acet_codigo FROM IESC_ACTIVIDADEDITIPO_ACET where acet_id = atrdr.atrd_tipo_actividad_edi) AS CODTIPACTIVREAL
    , /*ATRA_ES_SUJETO_PAS_SUSTIT */ null AS IDSUJPASIVO
    , NULL AS INDLIQT1
    , atrda.ATRD_NORAY_INICIAL AS NORAYINIAUT
    , atrda.ATRD_NORAY_final AS NORAYFINAUT
    , atrda.ATRD_FECHA_INICIO AS FECINIAUT
    , NULL AS CODPRESTPREV
    , NULL AS CODPRESTINICIO
    , NULL AS INDEXENTAT1
    , NULL AS INDESCALAFIN
    , (SELECT alin_codigo from igen_alineacion_alin where alin_id = atrda.ATRD_ALINEACION) AS CODMUELLEINIAUT
    , atrda.ATRD_FECHA_FINALIZACION AS FECFINAUT
    , NULL AS CODSUBTIPOACTIVIDAD
    , NULL AS INDAPLICAVI193
    , (select orga_nombre from icom_organizacion_orga where orga_id = ATRA_ORGA_ID_CONSIGNATARIO) AS NOMBRECONSIGESCALA
    , '0' AS INDTRAFINT
    , NULL AS INDFINESCMAN
    , NULL AS INDLIQT7
    , NULL AS INDEXENTAT7
    , NULL AS DESCOPERACIONES
    , NULL AS ESTINDFONDEO
    , NULL AS NUMOPEPESQUERAS
    , NULL AS NUMESCEXCURSION
    , NULL AS PERIODOMANUAL
    , CONCAT(
        CONCAT(
            (SELECT atet_codigo FROM IESC_ATRAQUEEDITIPO_ATET WHERE atet_id = atrda.ATRD_TIPO_ATRAQUE_EDI_1)
            , (SELECT atet_codigo FROM IESC_ATRAQUEEDITIPO_ATET WHERE atet_id = atrda.ATRD_TIPO_ATRAQUE_EDI_2)
        )
        , (SELECT atet_codigo FROM IESC_ATRAQUEEDITIPO_ATET WHERE atet_id = atrda.ATRD_TIPO_ATRAQUE_EDI_3)
    )
    AS CODTIPATRAQUEAUT
    , NULL AS INDREVT1DESCPESQUERA
    , NULL AS CODMUELLEINIPLA
    , NULL AS NORAYINIPLA
    , NULL AS NORAYFINPLA
    , NULL AS FECINIPLA
    , NULL AS FECFINPLA
    , NULL AS CODTIPATRAQUEPLA
    , NULL AS CODTIPOCONCESIONT1
    , NULL AS JUSTIFEXENTOT1
    , NULL AS JUSTIFEXENTOT7
    , NULL AS INDNOAPLICSERVMARIT
    , NULL AS CODTRAMUEAUT
    , NULL AS CODTRAMUECODAUT
    , NULL AS CODTRAMUEREAL
    , NULL AS CODTRAMUECODREAL
    , NULL AS INDINICIOVIAAPLICEXT
    , NULL AS INDFINVIAAPLICEXT
    , NULL AS INDINISINESTARAUT
    , NULL AS INDGNL
    , (case atra_CODIGO_EXENCION when 0 then '0' when 1 then '0' else '1' end) AS ESTINDEXENTA
FROM 
    IESC_ATRAQUE_ATRA atra
    INNER JOIN icom_servicio_serv serv ON
        serv.serv_id = atra.atra_escala_id
    LEFT JOIN iesc_atraquedetalle_atrd atrds ON
        atrds.atrd_atra_id = atra.atra_id
        AND atrds.atrd_momento = 'S'
    LEFT JOIN iesc_atraquedetalle_atrd atrda ON
        atrda.atrd_atra_id = atra.atra_id
        AND atrda.atrd_momento = 'A'
    LEFT JOIN iesc_atraquedetalle_atrd atrdr ON
        atrdr.atrd_atra_id = atra.atra_id
        AND atrdr.atrd_momento = 'R'
WHERE SERV_FECHA_BAJA IS NULL
      AND atra_es_activo = 1
;




/*
AA	    Tráfico Terrestre
E	  ZE  Embarque
D	  ZD  Desembarque
ET	    Embarque en tránsito
DT	DT  Desembarque en tránsito
T	  ZT  Transbordo
TE	    Transbordo Embarque
TD	    Transbordo Desembarque
**	    Operación Genérica
R	      Residuos

ZD	Desembarque
ZE	Embarque
ZT	Trasbordo
ZR	Residuos
AV	Avituallamiento
DT	Desembarque en transito
RE	Reestiba
*/

select * from TIPO_OPERACION;
select * from TIPO_CARGA_OPERACION;
select * from TIPO_UNIDAD_OPERACION;
select * from m_usuario;

select * from operacion;

delete from operacion;

INSERT INTO OPERACION (
  CODPUE
  , ANYO
  , CODESCALA
  , CODESTADIA
  , CODOPERACION
  , INDMANUAL
  , CODTIPOPE
  , CODTIPCARGA
  , CODTIPUNIDAD
  , LUGAR
  , PESOMAXPORUNIDAD
  , FECINI
  , FECFIN
  , TERMINAL
  , CODTIPMEDIOMANIP
  , NUMMEDIOS
  , INDPROPPUERTO
  , OBSERVACIONES
  , CODOPERACIONDUE
  , NUMUNIDADES
  , CODGRUA
  , CODPUECONTADOR
  , NUMCONTADOR
  , LECINICIAL
  , LECFINAL
  , CODTIPODESECHO
  , INDJUSTIFENTDESECHO
  , CODMODSUMINCOMB
  , CODCOMBSUMINCOMB
  , CODBARCAZA
  , CODTIPSUMINAGUA
  , CODPASARELA
  , FECSOLICITUD
  , FECALTA
  , FECMODIF
  , USRALTA
  , USRMODIF
  , OBSMEDIOSMANIP
  , INDLIQUIDADO
  , GUIDSRV
  , INDYOKTRAS
  , INDYOKUSO
  , INDYOKCOLOC
  , INDRAMMANIPUSU
  , INDRAMMANIPMANTUSU
  , INDNOPOSIBLELEC
  , CODTIPOALQPAS
  , INDNOAPLICMIN
  , IDSUJPASIVO
  , INDACUERDOMARPOL
  , NUMTONMARPOLI
  , NUMTONMARPOLV
  , INDIGICINTERINSULAR
  , ESTINDEXENTA
  , INDRECJORNLAB
  , INDEXENTOLIQ
  , NUMKGGASOIL
  , NUMKGDIESEL
  , NUMKGFUELOIL
  , NUMKGACEITES
  , CODPUEESCTI
  , ANYOESCTI
  , CODESCTI
  , NUMKGFUELOIL380
  , DENSIDADFUELOIL
  , DENSIDADFUELOIL380
  , DENSIDADGASOIL
  , DENSIDADDIESEL
  , DENSIDADACEITE
  , LITROSFUELOIL
  , LITROSFUELOIL380
  , LITROSGASOIL
  , LITROSDIESEL
  , LITROSACEITE
  , INDAVITEXCLUSIVO
  , CODDECLARANTE
  , CODEMPSUMIN
  , NUMKGFUELOIL280, DENSIDADFUELOIL280, LITROSFUELOIL280, NUMKGFUELOIL120, DENSIDADFUELOIL120, LITROSFUELOIL120, NUMKGFUELOIL80, DENSIDADFUELOIL80, LITROSFUELOIL80, NUMKGFUELOIL60
  , DENSIDADFUELOIL60, LITROSFUELOIL60, NUMKGFUELOIL40, DENSIDADFUELOIL40, LITROSFUELOIL40, NUMKGFUELOIL30, DENSIDADFUELOIL30, LITROSFUELOIL30, NUMKGFUELOIL380LS, DENSIDADFUELOIL380LS, LITROSFUELOIL380LS
  , NUMKGFUELOIL280LS, DENSIDADFUELOIL280LS, LITROSFUELOIL280LS, NUMKGFUELOIL180LS, DENSIDADFUELOIL180LS, LITROSFUELOIL180LS, NUMKGFUELOIL120LS, DENSIDADFUELOIL120LS, LITROSFUELOIL120LS
  , NUMKGFUELOIL80LS, DENSIDADFUELOIL80LS, LITROSFUELOIL80LS, NUMKGFUELOIL60LS, DENSIDADFUELOIL60LS, LITROSFUELOIL60LS
  , NUMKGRKM
  , IDESTIBADOR
)
SELECT
    (SELECT SUBP_CODIGO FROM IGEN_SUBPUERTO_SUBP WHERE SUBP_ID = serv_subp_id) AS CODPUE
    , serv_anno AS ANYO
    , serv_numero CODESCALA
    , atra_numero AS CODESTADIA
    , ATOP_ORDEN as CODOPERACION
    , null as INDMANUAL
    , (case (SELECT opet_codigo FROM IGEN_OPERACIONTIPO_OPET where opet_id = atop_opet_id) 
        WHEN 'E' THEN 'ZE'
        WHEN 'D' THEN 'ZD'
        WHEN 'DT' THEN 'DT'
        WHEN 'T' THEN 'ZT'
        ELSE 'RE'
    end) as CODTIPOPE
    , (SELECT mert_codigo FROM IESC_MERCANCIATIPO_MERT WHERE mert_id = atop_mert_id) as CODTIPCARGA
    , null as CODTIPUNIDAD
    , null as LUGAR
    , null as PESOMAXPORUNIDAD
    , ATOP_FECHA_INICIO as FECINI
    , ATOP_FECHA_FINAL as FECFIN
    , null as TERMINAL
    , null as CODTIPMEDIOMANIP
    , null as NUMMEDIOS
    , null as INDPROPPUERTO
    , null as OBSERVACIONES
    , null as CODOPERACIONDUE
    , null as NUMUNIDADES
    , null as CODGRUA
    , null as CODPUECONTADOR
    , null as NUMCONTADOR
    , null as LECINICIAL
    , null as LECFINAL
    , null as CODTIPODESECHO
    , null as INDJUSTIFENTDESECHO
    , null as CODMODSUMINCOMB
    , null as CODCOMBSUMINCOMB
    , null as CODBARCAZA
    , null as CODTIPSUMINAGUA
    , null as CODPASARELA
    , null as FECSOLICITUD
    , null as FECALTA
    , null as FECMODIF
    , null as USRALTA
    , null as USRMODIF
    , null as OBSMEDIOSMANIP
    , null as INDLIQUIDADO
    , null as GUIDSRV
    , null as INDYOKTRAS
    , null as INDYOKUSO
    , null as INDYOKCOLOC
    , null as INDRAMMANIPUSU
    , null as INDRAMMANIPMANTUSU
    , null as INDNOPOSIBLELEC
    , null as CODTIPOALQPAS
    , null as INDNOAPLICMIN
    , null as IDSUJPASIVO
    , null as INDACUERDOMARPOL
    , null as NUMTONMARPOLI
    , null as NUMTONMARPOLV
    , null as INDIGICINTERINSULAR
    , null as ESTINDEXENTA
    , null as INDRECJORNLAB
    , null as INDEXENTOLIQ
    , null as NUMKGGASOIL
    , null as NUMKGDIESEL
    , null as NUMKGFUELOIL
    , null as NUMKGACEITES
    , null as CODPUEESCTI
    , null as ANYOESCTI
    , null as CODESCTI
    , null as NUMKGFUELOIL380
    , null as DENSIDADFUELOIL
    , null as DENSIDADFUELOIL380
    , null as DENSIDADGASOIL
    , null as DENSIDADDIESEL
    , null as DENSIDADACEITE
    , null as LITROSFUELOIL
    , null as LITROSFUELOIL380
    , null as LITROSGASOIL
    , null as LITROSDIESEL
    , null as LITROSACEITE
    , null as INDAVITEXCLUSIVO
    , null as CODDECLARANTE
    , null as CODEMPSUMIN
    , null as NUMKGFUELOIL280, null as DENSIDADFUELOIL280, null as LITROSFUELOIL280, null as NUMKGFUELOIL120, null as DENSIDADFUELOIL120, null as LITROSFUELOIL120
    , null as NUMKGFUELOIL80, null as DENSIDADFUELOIL80, null as LITROSFUELOIL80, null as NUMKGFUELOIL60, null as DENSIDADFUELOIL60, null as LITROSFUELOIL60
    , null as NUMKGFUELOIL40, null as DENSIDADFUELOIL40, null as LITROSFUELOIL40, null as NUMKGFUELOIL30, null as DENSIDADFUELOIL30, null as LITROSFUELOIL30
    , null as NUMKGFUELOIL380LS, null as DENSIDADFUELOIL380LS, null as LITROSFUELOIL380LS, null as NUMKGFUELOIL280LS, null as DENSIDADFUELOIL280LS, null as LITROSFUELOIL280LS
    , null as NUMKGFUELOIL180LS, null as DENSIDADFUELOIL180LS, null as LITROSFUELOIL180LS, null as NUMKGFUELOIL120LS, null as DENSIDADFUELOIL120LS, null as LITROSFUELOIL120LS
    , null as NUMKGFUELOIL80LS, null as DENSIDADFUELOIL80LS, null as LITROSFUELOIL80LS, null as NUMKGFUELOIL60LS, null as DENSIDADFUELOIL60LS, null as LITROSFUELOIL60LS
    , null as NUMKGRKM
    , (select trid_new_id from tbl_traduccion_ids_trid where trid_table_name = 'ICOM_ORGANIZACION_ORGA' AND trid_old_id = ATOP_ORGA_ID_ESTIBADOR) AS IDESTIBADOR
FROM IESC_ATRAQUEOPERACION_ATOP atop
    INNER JOIN IESC_ATRAQUE_ATRA atra ON 
        atra.atra_id = atop.atop_atra_id
    INNER JOIN icom_servicio_serv serv ON
        serv.serv_id = atra.atra_escala_id
WHERE SERV_FECHA_BAJA IS NULL
      AND atop_es_activo = 1
;

