DELETE FROM ESTADIA;
DELETE FROM ESCALA;

SELECT * FROM ESTADIA;
SELECT * FROM ESCALA;

INSERT INTO ESCALA (
    CODPUE
    , ANYO
    , CODESCALA
    , ETA
    , ETD
    , CODPAIORIGEN
    , CODPUEORIGEN
    , CODPAIDESTINO
    , CODPUEDESTINO
    , NUMVIAJE
    , INDAUTCABOTAJE
    , INDNAVINT
    , INDENTFESTIVO
    , INDCONVCALIDAD
    , INDGREENAWARD
    , CODCONSIGNATARIO
    , CODPAIDESPTIEMPO
    , CODPUEDESPTIEMPO
    , FECVALDESPTIEMPO
    , PERDESPTIEMPO
    , NOMBRECAPITAN
    , ENTRADANUMTRIP
    , ENTRADANUMPASAJ
    , ENTRADANUMPOLIZ
    , SALIDANUMTRIP
    , SALIDANUMPASAJE
    , SALIDANUMPOLIZ
    , NUMESCALA
    , INDINSPMOUEFEC
    , FECINSPMOU
    , INDCRUDOFUELALQ
    , INDMMPPABORDO
    , INDMMPPCARGA
    , INDMMPPDESCARGA
    , FECSOLICITUD
    , FECAUTORIZACION
    , FECINIREAL
    , FECFINREAL
    , CODESTADO
    , FECAUTCAPITANIA
    , INDAUTCAPITANIA
    , OBSERVACIONES
    , INDEXISTEACUERDORES
    , CODPAIACUERDORES
    , CODPUEACUERDORES
    , EMPRESAACUERDORES
    , INDCERTSOLAS
    , EMPRESAEMICERTSOLAS
    , FECVENCICERTSOLAS
    , INDMEDPROTECSOLAS
    , INDPROCADECSOLAS
    , NIVELPROTECSOLAS
    , CONTENTRADASERVMARIT
    , INDNECESITAAUTCAPIT
    , DECLARACIONCAPITAN
    , ACUERDORES
    , CONTENTRADABUQUE
    , FECALTA
    , FECMODIF
    , USRALTA
    , USRMODIF
    , OBSCAMBIOESTADO
    , CODSERVMARIT
    , GUIDSRV
    , INDNOLIQUIDABLE
    , INDLIQT0
    , INDLIQT7
    , INDRESIDUOSZONA2
    , INDENTDESULTPUERTO
    , INDRESNOAPLIC10C
    , NUMPUERTOSRES
    , CODPAIORIGENDEC
    , CODPUEORIGENDEC
    , CODPAIDESTINODEC
    , CODPUEDESTINODEC
    , NUMTONMARPOLI
    , NUMTONMARPOLV
    , INDAPLICARB
    , INDEXENTOT0
    , INDREVISAUTORIZACION
    , CODBUQUECERT
    , INDMANUAL
    , TIPTRAFICO
    , INDRECMODIFESCINI
    , CODMUELLEEST1
    , CODTIPACTIVREALEST1
    , INDAPLICAVI193EST1
    , IDSUJPASIVOT0
    , INDLIQT1
    , INDNOLIQT1NOCT
    , INDNOLIQT7NOCT
    , INDNOLIQT0NOCT
    , INDTRAFINT
    , CODTIPOTRAFINT
    , ESTCODTIPNAV
    , ESTCODTIPNAVENT
    , ESTCODTIPNAVSAL
    , ESTCODTIPTER
    , ESTCODTIPSITOPPE
    , ESTINDDESGUACE
    , ESTINDEXENTA
    , INDTINUMESCSUMIN
    , CODTIPOMOVMERCMC
    , CODTIPOMOVMERCDS
    , ESTCODTIPNAVENTOPPE
    , ESTCODTIPNAVSALOPPE
    , ESTCODTIPTERORIG
    , ESTCODTIPTERDEST
    , INDREVISION
    , MODOREVISION
    , TIPOREVISION
    , NUMRESOLUCION
    , FACTRECTIF
    , FECREGSALIDA
    , DOCSUSTRECT
    , CODMOTREVISION
    , INDAPLIC2453PESCA
    , INDAPLIC2453CABL
    , INDAPLIC2453INACT
    , CODTERMINAL
    , INDINISINSECTEMP
    , INDPERIODOMANUAL
    , INDLIQT0PROLONGADA
    , JUSTIFEXENTOT7
    , JUSTIFEXENTOT0
    , CODTIPOIVAT0
    , CODTIPOIVAT1
    , CODTIPOIVAT7
    , IND2453
    , CODBON2453
    , PORC2453
    , IND2454
    , CODBON2454
    , PORC2454
    , IND2455
    , CODBON2455
    , PORC2455
    , IDSUJPASIVOT7
    , INDLIQPORATRAQUES
    , SERVMARITIMOEDI
    , CODBUQUE
    , CODBON24532
    , PORC24532
    , CODBON24533
    , PORC24533
    , CODBON24534
    , PORC24534
    , OBSERVACIONESFACT
)
SELECT 
    (SELECT SUBP_CODIGO FROM IGEN_SUBPUERTO_SUBP WHERE SUBP_ID = serv_subp_id) AS CODPUE
    , serv_anno AS ANYO
    , serv_numero CODESCALA
    , coalesce(ESCA_FECHA_INICIO, esca_fecha_entrada) AS ETA
    , coalesce(ESCA_FECHA_finalizacion, esca_fecha_salida) AS ETD
    , (select pais_iso from igen_pais_pais where pais_id = ESCA_PAIS_ID_ANTERIOR) AS CODPAIORIGEN
    , (select unlo_codigo from igen_unlocode_unlo where unlo_id = ESCA_loco_ID_ANTERIOR) AS CODPUEORIGEN
    , (select pais_iso from igen_pais_pais where pais_id = ESCA_PAIS_ID_siguiente) AS CODPAIDESTINO
    , (select unlo_codigo from igen_unlocode_unlo where unlo_id = ESCA_loco_ID_siguiente) AS CODPUEDESTINO
    , ESCA_REF_MENSAJE_EDI AS NUMVIAJE
    , ES_AUT_CABOTAJE AS INDAUTCABOTAJE
    , ESCA_ES_NAVEGACION_INT AS INDNAVINT
    , NULL AS INDENTFESTIVO
    , NULL AS INDCONVCALIDAD
    , NULL AS INDGREENAWARD
    , (select trid_new_id from tbl_traduccion_ids_trid where trid_table_name = 'ICOM_ORGANIZACION_ORGA' AND trid_old_id = ESCA_ORGA_ID_CONSIGNAT) AS CODCONSIGNATARIO
    , NULL AS CODPAIDESPTIEMPO
    , NULL AS CODPUEDESPTIEMPO
    , NULL AS FECVALDESPTIEMPO
    , NULL AS PERDESPTIEMPO
    , COALESCE(ESCA_CAPITAN_ENTRADA, ESCA_CAPITAN_SALIDA) AS NOMBRECAPITAN
    , ESCA_TRIPULANTES_ENTRADA AS ENTRADANUMTRIP
    , ESCA_PASAJEROS_ENTRADA AS ENTRADANUMPASAJ
    , ESCA_POLIZONES_ENTRADA AS ENTRADANUMPOLIZ
    , ESCA_TRIPULANTES_SALIDA AS SALIDANUMTRIP
    , ESCA_PASAJEROS_SALIDA AS SALIDANUMPASAJE
    , ESCA_POLIZONES_SALIDA AS SALIDANUMPOLIZ
    , CONCAT((SELECT SUBP_CODIGO FROM IGEN_SUBPUERTO_SUBP WHERE SUBP_ID = serv_subp_id), CONCAT(serv_anno, serv_numero)) AS NUMESCALA
    , buqut.BUQU_ES_MOU_PSC_INSPECCION AS INDINSPMOUEFEC
    , buqut.BUQU_FECHA_MOU_PSC_INSPECCION AS FECINSPMOU
    , ES_CRUDO_TRANSPORTADO AS INDCRUDOFUELALQ
    , NULL AS INDMMPPABORDO
    , NULL AS INDMMPPCARGA
    , NULL AS INDMMPPDESCARGA
    , NULL AS FECSOLICITUD
    , NULL AS FECAUTORIZACION
    , ESCA_FECHA_INICIO AS FECINIREAL
    , ESCA_FECHA_FINALIZACION AS FECFINREAL
    , (case ESCA_ESTADO 
        when 'I' then 'IN' 
        when 'F' then 'FI' 
        when 'A' then 'AN' 
        when 'D' then 'DE' 
        when 'C' then 'AU' 
        when 'S' then 'AC' 
    end) AS CODESTADO
    , ESCA_FECHA_CAP_MAR AS FECAUTCAPITANIA
    , (case when ESCA_FECHA_CAP_MAR is null then '0' else '1' end) AS INDAUTCAPITANIA
    , ESCA_OBSERV AS OBSERVACIONES
    , (case when ESCA_ACUE_ID is null then '0' else '1' end) AS INDEXISTEACUERDORES
    , NULL AS CODPAIACUERDORES
    , NULL AS CODPUEACUERDORES
    , NULL AS EMPRESAACUERDORES
    , NULL AS INDCERTSOLAS
    , NULL AS EMPRESAEMICERTSOLAS
    , NULL AS FECVENCICERTSOLAS
    , NULL AS INDMEDPROTECSOLAS
    , NULL AS INDPROCADECSOLAS
    , NULL AS NIVELPROTECSOLAS
    , NULL AS CONTENTRADASERVMARIT
    , NULL AS INDNECESITAAUTCAPIT
    , NULL AS DECLARACIONCAPITAN
    , NULL AS ACUERDORES
    , NULL AS CONTENTRADABUQUE
    , NULL AS FECALTA
    , NULL AS FECMODIF
    , NULL AS USRALTA
    , NULL AS USRMODIF
    , NULL AS OBSCAMBIOESTADO
    , NULL AS CODSERVMARIT
    , esca_id AS GUIDSRV
    , NULL AS INDNOLIQUIDABLE
    , NULL AS INDLIQT0
    , NULL AS INDLIQT7
    , NULL AS INDRESIDUOSZONA2
    , NULL AS INDENTDESULTPUERTO
    , NULL AS INDRESNOAPLIC10C
    , NULL AS NUMPUERTOSRES
    , NULL AS CODPAIORIGENDEC
    , NULL AS CODPUEORIGENDEC
    , NULL AS CODPAIDESTINODEC
    , NULL AS CODPUEDESTINODEC
    , NULL AS NUMTONMARPOLI
    , NULL AS NUMTONMARPOLV
    , NULL AS INDAPLICARB
    , NULL AS INDEXENTOT0
    , NULL AS INDREVISAUTORIZACION
    , NULL AS CODBUQUECERT
    , NULL AS INDMANUAL
    , NULL AS TIPTRAFICO
    , NULL AS INDRECMODIFESCINI
    , NULL AS CODMUELLEEST1
    , NULL AS CODTIPACTIVREALEST1
    , NULL AS INDAPLICAVI193EST1
    , NULL AS IDSUJPASIVOT0
    , NULL AS INDLIQT1
    , NULL AS INDNOLIQT1NOCT
    , NULL AS INDNOLIQT7NOCT
    , NULL AS INDNOLIQT0NOCT
    , NULL AS INDTRAFINT
    , NULL AS CODTIPOTRAFINT
    , NULL AS ESTCODTIPNAV
    , NULL AS ESTCODTIPNAVENT
    , NULL AS ESTCODTIPNAVSAL
    , NULL AS ESTCODTIPTER
    , NULL AS ESTCODTIPSITOPPE
    , NULL AS ESTINDDESGUACE
    , NULL AS ESTINDEXENTA
    , NULL AS INDTINUMESCSUMIN
    , NULL AS CODTIPOMOVMERCMC
    , NULL AS CODTIPOMOVMERCDS
    , NULL AS ESTCODTIPNAVENTOPPE
    , NULL AS ESTCODTIPNAVSALOPPE
    , NULL AS ESTCODTIPTERORIG
    , NULL AS ESTCODTIPTERDEST
    , NULL AS INDREVISION
    , NULL AS MODOREVISION
    , NULL AS TIPOREVISION
    , NULL AS NUMRESOLUCION
    , NULL AS FACTRECTIF
    , NULL AS FECREGSALIDA
    , NULL AS DOCSUSTRECT
    , NULL AS CODMOTREVISION
    , NULL AS INDAPLIC2453PESCA
    , NULL AS INDAPLIC2453CABL
    , NULL AS INDAPLIC2453INACT
    , NULL AS CODTERMINAL
    , NULL AS INDINISINSECTEMP
    , NULL AS INDPERIODOMANUAL
    , NULL AS INDLIQT0PROLONGADA
    , NULL AS JUSTIFEXENTOT7
    , NULL AS JUSTIFEXENTOT0
    , NULL AS CODTIPOIVAT0
    , NULL AS CODTIPOIVAT1
    , NULL AS CODTIPOIVAT7
    , NULL AS IND2453
    , NULL AS CODBON2453
    , NULL AS PORC2453
    , NULL AS IND2454
    , NULL AS CODBON2454
    , NULL AS PORC2454
    , NULL AS IND2455
    , NULL AS CODBON2455
    , NULL AS PORC2455
    , NULL AS IDSUJPASIVOT7
    , NULL AS INDLIQPORATRAQUES
    , NULL AS SERVMARITIMOEDI
    , (select trid_new_id from tbl_traduccion_ids_trid where trid_table_name = 'IESC_BUQUE_BUQU' AND trid_old_id = ESCA_BUQUE_ID) as CODBUQUE
    , NULL AS CODBON24532
    , NULL AS PORC24532
    , NULL AS CODBON24533
    , NULL AS PORC24533
    , NULL AS CODBON24534
    , NULL AS PORC24534
    , ESCA_OBSERV_FACTURACION AS OBSERVACIONESFACT
FROM iesc_escala_esca 
    INNER JOIN ICOM_SERVICIO_SERV on serv_id = esca_id
    left join iesc_buque_buqu buqu on esca_buque_id = buqu.BUQU_BUQUE_ID
    left join IESC_BUQUETEMP_BUQU buqut on 
        esca_buque_id = buqut.BUQU_BUQUE_ID
        and ESCA_FECHA_ENTRADA >= buqut.BUQU_FECHA_CREACION
        and (buqut.BUQU_FECHA_fin is null or buqut.BUQU_FECHA_fin > ESCA_FECHA_ENTRADA)
WHERE SERV_FECHA_BAJA IS NULL
;