M_PUERTO
    FREAV
    FREUV
    ZZ***
    ES	ACU
    ZZZAB
    CNBYQ
    MDGIU
    CFTOG
    CAPNO

insert into m_puerto (CODPAIS, CODPUE, NOMBRE, FECALTA, FECMODIF, USRALTA, USRMODIF, INDCANARIAS, INDPROVTEN, INDBALEARES, INDESPUERTO) values ('GR', 'FLS', 'GRFLS', SYSDATE, NULL, NULL, NULL, 0, 0, 0, 0);
insert into m_puerto (CODPAIS, CODPUE, NOMBRE, FECALTA, FECMODIF, USRALTA, USRMODIF, INDCANARIAS, INDPROVTEN, INDBALEARES, INDESPUERTO) values ('FR', 'EAV', 'FREAV', SYSDATE, NULL, NULL, NULL, 0, 0, 0, 0);
insert into m_puerto (CODPAIS, CODPUE, NOMBRE, FECALTA, FECMODIF, USRALTA, USRMODIF, INDCANARIAS, INDPROVTEN, INDBALEARES, INDESPUERTO) values ('FR', 'EUV', 'FREUV', SYSDATE, NULL, NULL, NULL, 0, 0, 0, 0);
insert into m_puerto (CODPAIS, CODPUE, NOMBRE, FECALTA, FECMODIF, USRALTA, USRMODIF, INDCANARIAS, INDPROVTEN, INDBALEARES, INDESPUERTO) values ('ES', 'ACU', 'ESACU', SYSDATE, NULL, NULL, NULL, 0, 0, 0, 0);
insert into m_puerto (CODPAIS, CODPUE, NOMBRE, FECALTA, FECMODIF, USRALTA, USRMODIF, INDCANARIAS, INDPROVTEN, INDBALEARES, INDESPUERTO) values ('ZZ', 'ZAB', 'ZZZAB', SYSDATE, NULL, NULL, NULL, 0, 0, 0, 0);
insert into m_puerto (CODPAIS, CODPUE, NOMBRE, FECALTA, FECMODIF, USRALTA, USRMODIF, INDCANARIAS, INDPROVTEN, INDBALEARES, INDESPUERTO) values ('CN', 'BYQ', 'CNBYQ', SYSDATE, NULL, NULL, NULL, 0, 0, 0, 0);
insert into m_puerto (CODPAIS, CODPUE, NOMBRE, FECALTA, FECMODIF, USRALTA, USRMODIF, INDCANARIAS, INDPROVTEN, INDBALEARES, INDESPUERTO) values ('MD', 'GIU', 'MDGIU', SYSDATE, NULL, NULL, NULL, 0, 0, 0, 0);
insert into m_puerto (CODPAIS, CODPUE, NOMBRE, FECALTA, FECMODIF, USRALTA, USRMODIF, INDCANARIAS, INDPROVTEN, INDBALEARES, INDESPUERTO) values ('CF', 'TOG', 'CFTOG', SYSDATE, NULL, NULL, NULL, 0, 0, 0, 0);
insert into m_puerto (CODPAIS, CODPUE, NOMBRE, FECALTA, FECMODIF, USRALTA, USRMODIF, INDCANARIAS, INDPROVTEN, INDBALEARES, INDESPUERTO) values ('CA', 'PNO', 'CAPNO', SYSDATE, NULL, NULL, NULL, 0, 0, 0, 0);
-- insert into m_puerto (CODPAIS, CODPUE, NOMBRE, FECALTA, FECMODIF, USRALTA, USRMODIF, INDCANARIAS, INDPROVTEN, INDBALEARES, INDESPUERTO) values ('ZZ', '***', 'ZZ***', SYSDATE, NULL, NULL, NULL, 0, 0, 0, 0);
