-- Como system
-- DROP USER integra CASCADE;

CREATE USER integra IDENTIFIED BY integra;

GRANT
	RESOURCE
	, CREATE SESSION
	, CREATE TABLE
	, CREATE VIEW
	, CREATE ANY SYNONYM
	, INSERT ANY TABLE
	, DELETE ANY TABLE
	, CREATE TABLESPACE
TO integra WITH ADMIN OPTION;

-- Como integra
CREATE TABLESPACE "INTGENERAL" DATAFILE 'INTGENERAL.DBF' SIZE 10000M;
CREATE TABLESPACE "INTMAESTROS" DATAFILE 'INTMAESTROS.DBF' SIZE 500M;
CREATE TABLESPACE "INTGENERALIND" DATAFILE 'INTGENERALIND.DBF' SIZE 5000M;
CREATE TABLESPACE "INTMAESTROSIND" DATAFILE 'INTMAESTROSIND.DBF' SIZE 500M;


/* ---- UNDO ---- */
/* ---- UNDO ---- */
/* ---- UNDO ---- */
/* ---- UNDO ---- */
DROP USER integra CASCADE;

DROP TABLESPACE "INTGENERAL" INCLUDING CONTENTS;
DROP TABLESPACE "INTMAESTROS" INCLUDING CONTENTS;
DROP TABLESPACE "INTGENERALIND" INCLUDING CONTENTS;
DROP TABLESPACE "INTMAESTROSIND" INCLUDING CONTENTS;

set feedback off
set echo off
