-- Como system
-- DROP USER integra CASCADE;

CREATE USER integra IDENTIFIED BY integra;

GRANT
	RESOURCE
	, CREATE SESSION
	, CREATE TABLE
	, CREATE VIEW
	, CREATE ANY SYNONYM
	, INSERT ANY TABLE
	, DELETE ANY TABLE
	, CREATE TABLESPACE
TO integra WITH ADMIN OPTION;

-- Como integra
CREATE TABLESPACE "INTG-GENERAL" DATAFILE 'INTG_GENERAL.DBF' SIZE 500M;
CREATE TABLESPACE "INTG-MAESTROS" DATAFILE 'INTG_MAESTROS.DBF' SIZE 500M;
CREATE TABLESPACE "INTG-GENERALIND" DATAFILE 'INTG_GENERALIND.DBF' SIZE 500M;
CREATE TABLESPACE "INTG-MAESTROSIND" DATAFILE 'INTG_MAESTROSIND.DBF' SIZE 500M;
