SET DEFINE OFF;
Insert into B4_ESPECIE
   (CODIGO, CODFAO, NOMBRE, CODTIPOCAPTURA, CODFAMILIA, USRMODIF, FECMODIF)
 Values
   ('008', 'BET', 'ATUN (PATUDO)', 'FP', '18', 
    'JMCIDRAS', TO_DATE('06/19/2015 13:22:24', 'MM/DD/YYYY HH24:MI:SS'));
Insert into B4_ESPECIE
   (CODIGO, CODFAO, NOMBRE, CODTIPOCAPTURA, CODFAMILIA)
 Values
   ('127', 'ALC', 'TALISMAN', 'FP', '22');
Insert into B4_ESPECIE
   (CODIGO, CODFAO, NOMBRE, CODTIPOCAPTURA, CODFAMILIA)
 Values
   ('118', 'ALF', 'ALFONSINOS', 'FP', '13');
Insert into B4_ESPECIE
   (CODIGO, CODFAO, NOMBRE, CODTIPOCAPTURA, CODFAMILIA)
 Values
   ('090', 'AMB', 'PEZ LIMON', 'FP', '18');
Insert into B4_ESPECIE
   (CODIGO, CODFAO, NOMBRE, CODTIPOCAPTURA, CODFAMILIA)
 Values
   ('018', 'ANE', 'BOCARTE-BOQUERON', 'FP', '14');
Insert into B4_ESPECIE
   (CODIGO, CODFAO, NOMBRE, CODTIPOCAPTURA, CODFAMILIA)
 Values
   ('119', 'ARG', 'ARGENTINAS-TOMASES', 'FP', '22');
Insert into B4_ESPECIE
   (CODIGO, CODFAO, NOMBRE, CODTIPOCAPTURA, CODFAMILIA)
 Values
   ('051', 'ARI', 'GAMBAS', 'FC', '53');
Insert into B4_ESPECIE
   (CODIGO, CODFAO, NOMBRE, CODTIPOCAPTURA, CODFAMILIA)
 Values
   ('101', 'ASZ', 'SABLE', 'FP', '18');
Insert into B4_ESPECIE
   (CODIGO, CODFAO, NOMBRE, CODTIPOCAPTURA, CODFAMILIA)
 Values
   ('109', 'BAS', 'SERRANOS', 'FP', '18');
Insert into B4_ESPECIE
   (CODIGO, CODFAO, NOMBRE, CODTIPOCAPTURA, CODFAMILIA)
 Values
   ('009', 'BFT', 'ATUN ROJO', 'FP', '18');
Insert into B4_ESPECIE
   (CODIGO, CODFAO, NOMBRE, CODTIPOCAPTURA, CODFAMILIA)
 Values
   ('046', 'BIB', 'FANECA', 'FP', '16');
Insert into B4_ESPECIE
   (CODIGO, CODFAO, NOMBRE, CODTIPOCAPTURA, CODFAMILIA)
 Values
   ('003', 'BIL', 'AGUJAS', 'FP', '18');
Insert into B4_ESPECIE
   (CODIGO, CODFAO, NOMBRE, CODTIPOCAPTURA, CODFAMILIA)
 Values
   ('039', 'BLL', 'CORUJO (REMOL)', 'FP', '20');
Insert into B4_ESPECIE
   (CODIGO, CODFAO, NOMBRE, CODTIPOCAPTURA, CODFAMILIA, USRMODIF, FECMODIF)
 Values
   ('022', 'ALB', 'BONITO (ATUN BLANCO)', 'FP', '18', 
    'JMCIDRAS', TO_DATE('06/19/2015 13:23:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into B4_ESPECIE
   (CODIGO, CODFAO, NOMBRE, CODTIPOCAPTURA, CODFAMILIA)
 Values
   ('019', 'BOZ', 'BOGA', 'FP', '18');
Insert into B4_ESPECIE
   (CODIGO, CODFAO, NOMBRE, CODTIPOCAPTURA, CODFAMILIA)
 Values
   ('034', 'BRB', 'CHOUPA (CHOPA)', 'FP', '18');
Insert into B4_ESPECIE
   (CODIGO, CODFAO, NOMBRE, CODTIPOCAPTURA, CODFAMILIA)
 Values
   ('095', 'BSH', 'QUENLLA TINTORERA', 'FP', '25');
Insert into B4_ESPECIE
   (CODIGO, CODFAO, NOMBRE, CODTIPOCAPTURA, CODFAMILIA)
 Values
   ('061', 'BSS', 'LUBINA-ROBALIZA', 'FP', '18');
Insert into B4_ESPECIE
   (CODIGO, CODFAO, NOMBRE, CODTIPOCAPTURA, CODFAMILIA)
 Values
   ('081', 'BUT', 'PALOMETA ROJA', 'FP', '13');
Insert into B4_ESPECIE
   (CODIGO, CODFAO, NOMBRE, CODTIPOCAPTURA, CODFAMILIA)
 Values
   ('122', 'CAT', 'PERRO', 'FP', '18');
Insert into B4_ESPECIE
   (CODIGO, CODFAO, NOMBRE, CODTIPOCAPTURA, CODFAMILIA)
 Values
   ('002', 'CET', 'ACEDIAS', 'FP', '20');
Insert into B4_ESPECIE
   (CODIGO, CODFAO, NOMBRE, CODTIPOCAPTURA, CODFAMILIA)
 Values
   ('037', 'CGZ', 'CONGRIO', 'FP', '11');
Insert into B4_ESPECIE
   (CODIGO, CODFAO, NOMBRE, CODTIPOCAPTURA, CODFAMILIA)
 Values
   ('029', 'CHA', 'CARACOLA', 'FM', '63');
Insert into B4_ESPECIE
   (CODIGO, CODFAO, NOMBRE, CODTIPOCAPTURA, CODFAMILIA)
 Values
   ('014', 'COC', 'BERBERECHO', 'FM', '61');
Insert into B4_ESPECIE
   (CODIGO, CODFAO, NOMBRE, CODTIPOCAPTURA, CODFAMILIA)
 Values
   ('011', 'COD', 'BACALAO', 'FP', '16');
Insert into B4_ESPECIE
   (CODIGO, CODFAO, NOMBRE, CODTIPOCAPTURA, CODFAMILIA)
 Values
   ('024', 'CRE', 'BUEY', 'FC', '51');
Insert into B4_ESPECIE
   (CODIGO, CODFAO, NOMBRE, CODTIPOCAPTURA, CODFAMILIA)
 Values
   ('063', 'CRU', 'MARISCO VARIADO', 'FC', '81');
Insert into B4_ESPECIE
   (CODIGO, CODFAO, NOMBRE, CODTIPOCAPTURA, CODFAMILIA)
 Values
   ('033', 'CTC', 'CHOCO-SEPIA', 'FM', '62');
Insert into B4_ESPECIE
   (CODIGO, CODFAO, NOMBRE, CODTIPOCAPTURA, CODFAMILIA)
 Values
   ('058', 'DAB', 'LIMANDA', 'FP', '20');
Insert into B4_ESPECIE
   (CODIGO, CODFAO, NOMBRE, CODTIPOCAPTURA, CODFAMILIA)
 Values
   ('126', 'DEL', 'REYES-DENTON', 'FP', '18');
Insert into B4_ESPECIE
   (CODIGO, CODFAO, NOMBRE, CODTIPOCAPTURA, CODFAMILIA)
 Values
   ('072', 'DGZ', 'MIELGA', 'FP', '24');
Insert into B4_ESPECIE
   (CODIGO, CODFAO, NOMBRE, CODTIPOCAPTURA, CODFAMILIA)
 Values
   ('026', 'DON', 'CADELUCHA (COQUINA)', 'FM', '61');
Insert into B4_ESPECIE
   (CODIGO, CODFAO, NOMBRE, CODTIPOCAPTURA, CODFAMILIA)
 Values
   ('006', 'ELE', 'ANGUILA', 'FP', '11');
Insert into B4_ESPECIE
   (CODIGO, CODFAO, NOMBRE, CODTIPOCAPTURA, CODFAMILIA)
 Values
   ('060', 'EQI', 'LONGUEIRON (MUERGO)', 'FM', '61');
Insert into B4_ESPECIE
   (CODIGO, CODFAO, NOMBRE, CODTIPOCAPTURA, CODFAMILIA)
 Values
   ('113', 'FIN', 'VARIADO', 'FP', '29');
Insert into B4_ESPECIE
   (CODIGO, CODFAO, NOMBRE, CODTIPOCAPTURA, CODFAMILIA)
 Values
   ('079', 'FLA', 'PALO', 'FP', '16');
Insert into B4_ESPECIE
   (CODIGO, CODFAO, NOMBRE, CODTIPOCAPTURA, CODFAMILIA)
 Values
   ('016', 'FOX', 'BERTAN-BROTOLA', 'FP', '16');
Insert into B4_ESPECIE
   (CODIGO, CODFAO, NOMBRE, CODTIPOCAPTURA, CODFAMILIA)
 Values
   ('128', 'GAC', 'CAZON', 'FP', '25');
Insert into B4_ESPECIE
   (CODIGO, CODFAO, NOMBRE, CODTIPOCAPTURA, CODFAMILIA)
 Values
   ('071', 'GPD', 'MERO-CHERNA', 'FP', '18');
Insert into B4_ESPECIE
   (CODIGO, CODFAO, NOMBRE, CODTIPOCAPTURA, CODFAMILIA)
 Values
   ('131', 'GRX', 'RONCOS-BURROS', 'FP', '18');
Insert into B4_ESPECIE
   (CODIGO, CODFAO, NOMBRE, CODTIPOCAPTURA, CODFAMILIA)
 Values
   ('015', 'GUX', 'BERETE RUBIO', 'FP', '15');
Insert into B4_ESPECIE
   (CODIGO, CODFAO, NOMBRE, CODTIPOCAPTURA, CODFAMILIA)
 Values
   ('041', 'HAD', 'EGLEFINO', 'FP', '16');
Insert into B4_ESPECIE
   (CODIGO, CODFAO, NOMBRE, CODTIPOCAPTURA, CODFAMILIA)
 Values
   ('047', 'HAL', 'FLETAN ATLANTICO', 'FP', '20');
Insert into B4_ESPECIE
   (CODIGO, CODFAO, NOMBRE, CODTIPOCAPTURA, CODFAMILIA)
 Values
   ('007', 'HER', 'ARENQUE ATLANTICO', 'FP', '14');
Insert into B4_ESPECIE
   (CODIGO, CODFAO, NOMBRE, CODTIPOCAPTURA, CODFAMILIA)
 Values
   ('070', 'HKX', 'MERLUZA NEGRA', 'FP', '16');
Insert into B4_ESPECIE
   (CODIGO, CODFAO, NOMBRE, CODTIPOCAPTURA, CODFAMILIA)
 Values
   ('088', 'HKX', 'PESCADILLA NEGRA', 'FP', '16');
Insert into B4_ESPECIE
   (CODIGO, CODFAO, NOMBRE, CODTIPOCAPTURA, CODFAMILIA)
 Values
   ('087', 'HOF', 'PESCADILLA BLANCA', 'FP', '16');
Insert into B4_ESPECIE
   (CODIGO, CODFAO, NOMBRE, CODTIPOCAPTURA, CODFAMILIA, USRMODIF, FECMODIF)
 Values
   ('069', 'HKE', 'MERLUZA BLANCA', 'FP', '16', 
    'DAVIDS', TO_DATE('02/02/2015 10:48:02', 'MM/DD/YYYY HH24:MI:SS'));
Insert into B4_ESPECIE
   (CODIGO, CODFAO, NOMBRE, CODTIPOCAPTURA, CODFAMILIA, USRMODIF, FECMODIF)
 Values
   ('053', 'JAX', 'JUREL-CHINCHO', 'FP', '18', 
    'JMCIDRAS', TO_DATE('05/05/2015 12:09:57', 'MM/DD/YYYY HH24:MI:SS'));
Insert into B4_ESPECIE
   (CODIGO, CODFAO, NOMBRE, CODTIPOCAPTURA, CODFAMILIA, USRMODIF, FECMODIF)
 Values
   ('064', 'SMA', 'MARRAJO', 'FP', '25', 
    'JMCIDRAS', TO_DATE('06/19/2015 13:16:12', 'MM/DD/YYYY HH24:MI:SS'));
Insert into B4_ESPECIE
   (CODIGO, CODFAO, NOMBRE, CODTIPOCAPTURA, CODFAMILIA)
 Values
   ('032', 'KCA', 'CENTOLLA', 'FC', '51');
Insert into B4_ESPECIE
   (CODIGO, CODFAO, NOMBRE, CODTIPOCAPTURA, CODFAMILIA)
 Values
   ('054', 'LAM', 'LAMPREA', 'FP', '19');
Insert into B4_ESPECIE
   (CODIGO, CODFAO, NOMBRE, CODTIPOCAPTURA, CODFAMILIA)
 Values
   ('020', 'LBE', 'BOGAVANTE', 'FC', '53');
Insert into B4_ESPECIE
   (CODIGO, CODFAO, NOMBRE, CODTIPOCAPTURA, CODFAMILIA, USRMODIF, FECMODIF)
 Values
   ('050', 'LEZ', 'GALLO', 'FP', '20', 
    'JMCIDRAS', TO_DATE('05/05/2015 11:56:21', 'MM/DD/YYYY HH24:MI:SS'));
Insert into B4_ESPECIE
   (CODIGO, CODFAO, NOMBRE, CODTIPOCAPTURA, CODFAMILIA)
 Values
   ('067', 'LEM', 'MENDO-LIMON', 'FP', '20');
Insert into B4_ESPECIE
   (CODIGO, CODFAO, NOMBRE, CODTIPOCAPTURA, CODFAMILIA)
 Values
   ('036', 'LFO', 'COCHINILLA (ATUN NEGRO)', 'FP', '18');
Insert into B4_ESPECIE
   (CODIGO, CODFAO, NOMBRE, CODTIPOCAPTURA, CODFAMILIA)
 Values
   ('065', 'LIN', 'MARUCA', 'FP', '16');
Insert into B4_ESPECIE
   (CODIGO, CODFAO, NOMBRE, CODTIPOCAPTURA, CODFAMILIA)
 Values
   ('076', 'LIO', 'NECORA', 'FC', '51');
Insert into B4_ESPECIE
   (CODIGO, CODFAO, NOMBRE, CODTIPOCAPTURA, CODFAMILIA)
 Values
   ('055', 'LOY', 'LANGOSTA', 'FC', '53');
Insert into B4_ESPECIE
   (CODIGO, CODFAO, NOMBRE, CODTIPOCAPTURA, CODFAMILIA)
 Values
   ('013', 'LTA', 'BACORETA', 'FP', '18');
Insert into B4_ESPECIE
   (CODIGO, CODFAO, NOMBRE, CODTIPOCAPTURA, CODFAMILIA)
 Values
   ('025', 'MAC', 'CABALLA-RINCHA', 'FP', '18');
Insert into B4_ESPECIE
   (CODIGO, CODFAO, NOMBRE, CODTIPOCAPTURA, CODFAMILIA)
 Values
   ('139', 'MAS', 'CABALON-ESTORNINO', 'FP', '18');
Insert into B4_ESPECIE
   (CODIGO, CODFAO, NOMBRE, CODTIPOCAPTURA, CODFAMILIA)
 Values
   ('129', 'MEG', 'MEIGA', 'FP', '20');
Insert into B4_ESPECIE
   (CODIGO, CODFAO, NOMBRE, CODTIPOCAPTURA, CODFAMILIA, USRMODIF, FECMODIF)
 Values
   ('097', 'ANF', 'RAPE-SAPO', 'FP', '17', 
    'JMCIDRAS', TO_DATE('05/05/2015 12:08:35', 'MM/DD/YYYY HH24:MI:SS'));
Insert into B4_ESPECIE
   (CODIGO, CODFAO, NOMBRE, CODTIPOCAPTURA, CODFAMILIA)
 Values
   ('073', 'MUL', 'MUGEL (LIZA)', 'FP', '18');
Insert into B4_ESPECIE
   (CODIGO, CODFAO, NOMBRE, CODTIPOCAPTURA, CODFAMILIA)
 Values
   ('066', 'MUS', 'MEJILLON', 'FM', '61');
Insert into B4_ESPECIE
   (CODIGO, CODFAO, NOMBRE, CODTIPOCAPTURA, CODFAMILIA)
 Values
   ('104', 'MUX', 'SALMONETE', 'FP', '18');
Insert into B4_ESPECIE
   (CODIGO, CODFAO, NOMBRE, CODTIPOCAPTURA, CODFAMILIA)
 Values
   ('035', 'NEP', 'CIGALA', 'FC', '53');
Insert into B4_ESPECIE
   (CODIGO, CODFAO, NOMBRE, CODTIPOCAPTURA, CODFAMILIA)
 Values
   ('093', 'OCC', 'PULPO', 'FM', '62');
Insert into B4_ESPECIE
   (CODIGO, CODFAO, NOMBRE, CODTIPOCAPTURA, CODFAMILIA)
 Values
   ('094', 'OCZ', 'PULPO CABEZUDO', 'FM', '62');
Insert into B4_ESPECIE
   (CODIGO, CODFAO, NOMBRE, CODTIPOCAPTURA, CODFAMILIA)
 Values
   ('125', 'ORY', 'RELOJ ANARANJADO', 'FP', '13');
Insert into B4_ESPECIE
   (CODIGO, CODFAO, NOMBRE, CODTIPOCAPTURA, CODFAMILIA)
 Values
   ('078', 'OYF', 'OSTRA', 'FM', '61');
Insert into B4_ESPECIE
   (CODIGO, CODFAO, NOMBRE, CODTIPOCAPTURA, CODFAMILIA)
 Values
   ('023', 'PAC', 'BRECA', 'FP', '18');
Insert into B4_ESPECIE
   (CODIGO, CODFAO, NOMBRE, CODTIPOCAPTURA, CODFAMILIA)
 Values
   ('086', 'PCB', 'PERCEBES', 'FC', '52');
Insert into B4_ESPECIE
   (CODIGO, CODFAO, NOMBRE, CODTIPOCAPTURA, CODFAMILIA)
 Values
   ('028', 'PDZ', 'CAMARON', 'FC', '53');
Insert into B4_ESPECIE
   (CODIGO, CODFAO, NOMBRE, CODTIPOCAPTURA, CODFAMILIA)
 Values
   ('030', 'PEE', 'CARAMUXO (B\CDGARO)', 'FM', '63');
Insert into B4_ESPECIE
   (CODIGO, CODFAO, NOMBRE, CODTIPOCAPTURA, CODFAMILIA)
 Values
   ('056', 'PEN', 'LANGOSTINOS', 'FC', '53');
Insert into B4_ESPECIE
   (CODIGO, NOMBRE, CODTIPOCAPTURA, CODFAMILIA, USRMODIF, FECMODIF)
 Values
   ('085', 'PARROCHA XOUBA', 'FP', '14', 
    'JMCIDRAS', TO_DATE('05/05/2015 11:43:34', 'MM/DD/YYYY HH24:MI:SS'));
Insert into B4_ESPECIE
   (CODIGO, CODFAO, NOMBRE, CODTIPOCAPTURA, CODFAMILIA, USRMODIF, FECMODIF)
 Values
   ('107', 'PIL', 'SARDINA', 'FP', '14', 
    'JMCIDRAS', TO_DATE('05/05/2015 11:43:51', 'MM/DD/YYYY HH24:MI:SS'));
Insert into B4_ESPECIE
   (CODIGO, NOMBRE, CODTIPOCAPTURA, CODFAMILIA)
 Values
   ('117', 'XOUBA', 'FP', '14');
Insert into B4_ESPECIE
   (CODIGO, CODFAO, NOMBRE, CODTIPOCAPTURA, CODFAMILIA)
 Values
   ('110', 'PLE', 'SOLLA', 'FP', '20');
Insert into B4_ESPECIE
   (CODIGO, CODFAO, NOMBRE, CODTIPOCAPTURA, CODFAMILIA)
 Values
   ('091', 'PLZ', 'PLATIJA', 'FP', '20');
Insert into B4_ESPECIE
   (CODIGO, CODFAO, NOMBRE, CODTIPOCAPTURA, CODFAMILIA)
 Values
   ('080', 'POA', 'PALOMETA-JAPUTA', 'FP', '18');
Insert into B4_ESPECIE
   (CODIGO, CODFAO, NOMBRE, CODTIPOCAPTURA, CODFAMILIA)
 Values
   ('048', 'POD', 'FODON (CAPELLAN)', 'FP', '16');
Insert into B4_ESPECIE
   (CODIGO, CODFAO, NOMBRE, CODTIPOCAPTURA, CODFAMILIA)
 Values
   ('031', 'POK', 'CARBONERO FOGONERO', 'FP', '16');
Insert into B4_ESPECIE
   (CODIGO, CODFAO, NOMBRE, CODTIPOCAPTURA, CODFAMILIA)
 Values
   ('001', 'POL', 'ABADEJO', 'FP', '16');
Insert into B4_ESPECIE
   (CODIGO, CODFAO, NOMBRE, CODTIPOCAPTURA, CODFAMILIA)
 Values
   ('082', 'POX', 'PAMPANOS', 'FP', '18');
Insert into B4_ESPECIE
   (CODIGO, CODFAO, NOMBRE, CODTIPOCAPTURA, CODFAMILIA, USRMODIF, FECMODIF)
 Values
   ('049', 'REG', 'GALLINETA NORDICA', 'FP', '15', 
    'JMCIDRAS', TO_DATE('06/22/2015 11:23:38', 'MM/DD/YYYY HH24:MI:SS'));
Insert into B4_ESPECIE
   (CODIGO, CODFAO, NOMBRE, CODTIPOCAPTURA, CODFAMILIA)
 Values
   ('135', 'RJC', 'RAYA DE CLAVOS', 'FP', '21');
Insert into B4_ESPECIE
   (CODIGO, CODFAO, NOMBRE, CODTIPOCAPTURA, CODFAMILIA)
 Values
   ('134', 'RJE', 'RAYA COLORADA', 'FP', '21');
Insert into B4_ESPECIE
   (CODIGO, CODFAO, NOMBRE, CODTIPOCAPTURA, CODFAMILIA)
 Values
   ('133', 'RJF', 'RAYA CARDADORA', 'FP', '21');
Insert into B4_ESPECIE
   (CODIGO, CODFAO, NOMBRE, CODTIPOCAPTURA, CODFAMILIA)
 Values
   ('132', 'RJH', 'RAYA BOCA ROSA', 'FP', '21');
Insert into B4_ESPECIE
   (CODIGO, CODFAO, NOMBRE, CODTIPOCAPTURA, CODFAMILIA)
 Values
   ('136', 'RJI', 'RAYA FALSA VELA', 'FP', '21');
Insert into B4_ESPECIE
   (CODIGO, CODFAO, NOMBRE, CODTIPOCAPTURA, CODFAMILIA)
 Values
   ('137', 'RJM', 'RAYA PINTADA', 'FP', '21');
Insert into B4_ESPECIE
   (CODIGO, CODFAO, NOMBRE, CODTIPOCAPTURA, CODFAMILIA)
 Values
   ('138', 'RJN', 'RAYA SANTIAGUESA', 'FP', '21');
Insert into B4_ESPECIE
   (CODIGO, CODFAO, NOMBRE, CODTIPOCAPTURA, CODFAMILIA)
 Values
   ('140', 'RJO', 'RAYA PICUDA', 'FP', '21');
Insert into B4_ESPECIE
   (CODIGO, CODFAO, NOMBRE, CODTIPOCAPTURA, CODFAMILIA)
 Values
   ('052', 'RNG', 'GRANADERO', 'FP', '16');
Insert into B4_ESPECIE
   (CODIGO, CODFAO, NOMBRE, CODTIPOCAPTURA, CODFAMILIA)
 Values
   ('077', 'RPO', 'NEGRITA (ESCOLAR)', 'FP', '18');
Insert into B4_ESPECIE
   (CODIGO, CODFAO, NOMBRE, CODTIPOCAPTURA, CODFAMILIA)
 Values
   ('043', 'RSE', 'ESCARAPOTA CABRA', 'FP', '15');
Insert into B4_ESPECIE
   (CODIGO, CODFAO, NOMBRE, CODTIPOCAPTURA, CODFAMILIA)
 Values
   ('012', 'SAF', 'BACALAO VERDE', 'FP', '26');
Insert into B4_ESPECIE
   (CODIGO, CODFAO, NOMBRE, CODTIPOCAPTURA, CODFAMILIA)
 Values
   ('103', 'SAL', 'SALMON', 'FP', '22');
Insert into B4_ESPECIE
   (CODIGO, CODFAO, NOMBRE, CODTIPOCAPTURA, CODFAMILIA)
 Values
   ('021', 'SAN', 'BOLO (LANZON)', 'FP', '18');
Insert into B4_ESPECIE
   (CODIGO, CODFAO, NOMBRE, CODTIPOCAPTURA, CODFAMILIA)
 Values
   ('004', 'SAU', 'ALCRIQUE (PAPARDA)', 'FP', '12');
Insert into B4_ESPECIE
   (CODIGO, CODFAO, NOMBRE, CODTIPOCAPTURA, CODFAMILIA)
 Values
   ('083', 'SBA', 'PANCHO-BICUDO', 'FP', '18');
Insert into B4_ESPECIE
   (CODIGO, CODFAO, NOMBRE, CODTIPOCAPTURA, CODFAMILIA)
 Values
   ('040', 'SBG', 'DORADA', 'FP', '18');
Insert into B4_ESPECIE
   (CODIGO, CODFAO, NOMBRE, CODTIPOCAPTURA, CODFAMILIA)
 Values
   ('084', 'SBP', 'PARGO', 'FP', '18');
Insert into B4_ESPECIE
   (CODIGO, CODFAO, NOMBRE, CODTIPOCAPTURA, CODFAMILIA)
 Values
   ('017', 'SBR', 'BESUGO', 'FP', '18');
Insert into B4_ESPECIE
   (CODIGO, CODFAO, NOMBRE, CODTIPOCAPTURA, CODFAMILIA)
 Values
   ('114', 'SCE', 'VIEIRAS', 'FM', '61');
Insert into B4_ESPECIE
   (CODIGO, CODFAO, NOMBRE, CODTIPOCAPTURA, CODFAMILIA)
 Values
   ('106', 'SCY', 'SANTIAGUI\D1O', 'FC', '53');
Insert into B4_ESPECIE
   (CODIGO, CODFAO, NOMBRE, CODTIPOCAPTURA, CODFAMILIA)
 Values
   ('098', 'SKA', 'RAYA', 'FP', '21');
Insert into B4_ESPECIE
   (CODIGO, CODFAO, NOMBRE, CODTIPOCAPTURA, CODFAMILIA)
 Values
   ('059', 'SKJ', 'LISTADO', 'FP', '18');
Insert into B4_ESPECIE
   (CODIGO, CODFAO, NOMBRE, CODTIPOCAPTURA, CODFAMILIA)
 Values
   ('074', 'SMD', 'MUSOLA', 'FP', '25');
Insert into B4_ESPECIE
   (CODIGO, CODFAO, NOMBRE, CODTIPOCAPTURA, CODFAMILIA)
 Values
   ('075', 'SOI', 'NAVAJA', 'FM', '61');
Insert into B4_ESPECIE
   (CODIGO, CODFAO, NOMBRE, CODTIPOCAPTURA, CODFAMILIA)
 Values
   ('057', 'SOL', 'LENGUADO', 'FP', '20');
Insert into B4_ESPECIE
   (CODIGO, CODFAO, NOMBRE, CODTIPOCAPTURA, CODFAMILIA)
 Values
   ('038', 'SPN', 'CORNUDA (P.MARTILLO)', 'FP', '25');
Insert into B4_ESPECIE
   (CODIGO, CODFAO, NOMBRE, CODTIPOCAPTURA, CODFAMILIA)
 Values
   ('045', 'SPR', 'ESPADIN', 'FP', '14');
Insert into B4_ESPECIE
   (CODIGO, CODFAO, NOMBRE, CODTIPOCAPTURA, CODFAMILIA)
 Values
   ('027', 'SQC', 'CALAMAR', 'FM', '62');
Insert into B4_ESPECIE
   (CODIGO, CODFAO, NOMBRE, CODTIPOCAPTURA, CODFAMILIA)
 Values
   ('092', 'SQX', 'POTA-VOLADORA', 'FM', '62');
Insert into B4_ESPECIE
   (CODIGO, CODFAO, NOMBRE, CODTIPOCAPTURA, CODFAMILIA)
 Values
   ('120', 'SSH', 'CARABINEROS', 'FC', '53');
Insert into B4_ESPECIE
   (CODIGO, CODFAO, NOMBRE, CODTIPOCAPTURA, CODFAMILIA)
 Values
   ('108', 'SWA', 'SARGO', 'FP', '18');
Insert into B4_ESPECIE
   (CODIGO, CODFAO, NOMBRE, CODTIPOCAPTURA, CODFAMILIA)
 Values
   ('089', 'SWO', 'PEZ ESPADA', 'FP', '18');
Insert into B4_ESPECIE
   (CODIGO, CODFAO, NOMBRE, CODTIPOCAPTURA, CODFAMILIA)
 Values
   ('121', 'SYX', 'GATA', 'FP', '25');
Insert into B4_ESPECIE
   (CODIGO, CODFAO, NOMBRE, CODTIPOCAPTURA, CODFAMILIA)
 Values
   ('123', 'SYX', 'PINTARROJA', 'FP', '25');
Insert into B4_ESPECIE
   (CODIGO, CODFAO, NOMBRE, CODTIPOCAPTURA, CODFAMILIA)
 Values
   ('005', 'TPS', 'ALMEJAS', 'FM', '61');
Insert into B4_ESPECIE
   (CODIGO, CODFAO, NOMBRE, CODTIPOCAPTURA, CODFAMILIA)
 Values
   ('116', 'TRH', 'ZORROS', 'FP', '25');
Insert into B4_ESPECIE
   (CODIGO, CODFAO, NOMBRE, CODTIPOCAPTURA, CODFAMILIA)
 Values
   ('044', 'TRK', 'ESCUALOS', 'FP', '25');
Insert into B4_ESPECIE
   (CODIGO, CODFAO, NOMBRE, CODTIPOCAPTURA, CODFAMILIA)
 Values
   ('111', 'TRO', 'TRUCHA', 'FP', '22');
Insert into B4_ESPECIE
   (CODIGO, CODFAO, NOMBRE, CODTIPOCAPTURA, CODFAMILIA)
 Values
   ('099', 'TRS', 'REO', 'FP', '22');
Insert into B4_ESPECIE
   (CODIGO, CODFAO, NOMBRE, CODTIPOCAPTURA, CODFAMILIA)
 Values
   ('102', 'TSD', 'SABOGA', 'FP', '18');
Insert into B4_ESPECIE
   (CODIGO, CODFAO, NOMBRE, CODTIPOCAPTURA, CODFAMILIA)
 Values
   ('112', 'TUN', 'TUNIDOS', 'FP', '18');
Insert into B4_ESPECIE
   (CODIGO, CODFAO, NOMBRE, CODTIPOCAPTURA, CODFAMILIA)
 Values
   ('100', 'TUR', 'RODABALLO', 'FP', '20');
Insert into B4_ESPECIE
   (CODIGO, CODFAO, NOMBRE, CODTIPOCAPTURA, CODFAMILIA)
 Values
   ('042', 'URM', 'ERIZO DE MAR', 'FC', '71');
Insert into B4_ESPECIE
   (CODIGO, CODFAO, NOMBRE, CODTIPOCAPTURA, CODFAMILIA)
 Values
   ('124', 'USK', 'RAMONA-BROSMIO', 'FP', '16');
Insert into B4_ESPECIE
   (CODIGO, CODFAO, NOMBRE, CODTIPOCAPTURA, CODFAMILIA)
 Values
   ('115', 'VSC', 'ZAMBURI\D1A', 'FM', '61');
Insert into B4_ESPECIE
   (CODIGO, CODFAO, NOMBRE, CODTIPOCAPTURA, CODFAMILIA)
 Values
   ('010', 'WHB', 'BACALADILLA-LIRIO', 'FP', '16');
Insert into B4_ESPECIE
   (CODIGO, CODFAO, NOMBRE, CODTIPOCAPTURA, CODFAMILIA)
 Values
   ('130', 'WIT', 'MENDO', 'FP', '20');
Insert into B4_ESPECIE
   (CODIGO, CODFAO, NOMBRE, CODTIPOCAPTURA, CODFAMILIA)
 Values
   ('068', 'WKG', 'MERLAN', 'FP', '16');
Insert into B4_ESPECIE
   (CODIGO, CODFAO, NOMBRE, CODTIPOCAPTURA, CODFAMILIA)
 Values
   ('062', 'WRA', 'MARAGOTA PINTO', 'FP', '18');
Insert into B4_ESPECIE
   (CODIGO, CODFAO, NOMBRE, CODTIPOCAPTURA, CODFAMILIA)
 Values
   ('096', 'YFT', 'RABIL', 'FP', '18');
Insert into B4_ESPECIE
   (CODIGO, CODFAO, NOMBRE, CODTIPOCAPTURA, CODFAMILIA)
 Values
   ('105', 'ZEX', 'SANMARTI\D1O', 'FP', '23');
Insert into B4_ESPECIE
   (CODIGO, NOMBRE, CODTIPOCAPTURA, CODFAMILIA)
 Values
   ('816', 'MEJILLON', 'FM', '92');
Insert into B4_ESPECIE
   (CODIGO, NOMBRE, CODTIPOCAPTURA, CODFAMILIA)
 Values
   ('815', 'ALMEJA', 'FM', '92');
Insert into B4_ESPECIE
   (CODIGO, NOMBRE, CODTIPOCAPTURA, CODFAMILIA)
 Values
   ('911', 'MARISCO CONG', 'FC', '99');
Insert into B4_ESPECIE
   (CODIGO, NOMBRE, CODTIPOCAPTURA, CODFAMILIA)
 Values
   ('910', 'VARIADO CONG', 'FP', '99');
Insert into B4_ESPECIE
   (CODIGO, NOMBRE, CODTIPOCAPTURA, CODFAMILIA)
 Values
   ('909', 'T\DANIDOS CONG', 'FP', '99');
Insert into B4_ESPECIE
   (CODIGO, NOMBRE, CODTIPOCAPTURA, CODFAMILIA)
 Values
   ('908', 'PEZ ESPADA CONG', 'FP', '99');
Insert into B4_ESPECIE
   (CODIGO, NOMBRE, CODTIPOCAPTURA, CODFAMILIA)
 Values
   ('907', 'PESCADILLA CONG', 'FP', '99');
Insert into B4_ESPECIE
   (CODIGO, NOMBRE, CODTIPOCAPTURA, CODFAMILIA)
 Values
   ('906', 'POTA CONG', 'FM', '99');
Insert into B4_ESPECIE
   (CODIGO, NOMBRE, CODTIPOCAPTURA, CODFAMILIA)
 Values
   ('905', 'PULPO CONG', 'FM', '99');
Insert into B4_ESPECIE
   (CODIGO, NOMBRE, CODTIPOCAPTURA, CODFAMILIA)
 Values
   ('904', 'CHOCO CONG', 'FM', '99');
Insert into B4_ESPECIE
   (CODIGO, NOMBRE, CODTIPOCAPTURA, CODFAMILIA)
 Values
   ('903', 'CALAMAR CONG', 'FM', '99');
Insert into B4_ESPECIE
   (CODIGO, NOMBRE, CODTIPOCAPTURA, CODFAMILIA)
 Values
   ('902', 'MERLUZA CONG', 'FP', '99');
Insert into B4_ESPECIE
   (CODIGO, NOMBRE, CODTIPOCAPTURA, CODFAMILIA)
 Values
   ('901', 'FILETE CONG', 'FP', '99');
Insert into B4_ESPECIE
   (CODIGO, NOMBRE, CODTIPOCAPTURA, CODFAMILIA)
 Values
   ('814', 'BOGAVANTE Y OTROS', 'FC', '92');
Insert into B4_ESPECIE
   (CODIGO, NOMBRE, CODTIPOCAPTURA, CODFAMILIA)
 Values
   ('813', 'NECORA', 'FC', '92');
Insert into B4_ESPECIE
   (CODIGO, NOMBRE, CODTIPOCAPTURA, CODFAMILIA)
 Values
   ('812', 'BUEY', 'FC', '92');
Insert into B4_ESPECIE
   (CODIGO, NOMBRE, CODTIPOCAPTURA, CODFAMILIA)
 Values
   ('811', 'CENTOLLA', 'FC', '92');
Insert into B4_ESPECIE
   (CODIGO, NOMBRE, CODTIPOCAPTURA, CODFAMILIA)
 Values
   ('817', 'BERBERECHO Y OTRS', 'FM', '92');
Insert into B4_ESPECIE
   (CODIGO, NOMBRE, CODTIPOCAPTURA, CODFAMILIA)
 Values
   ('801', 'MEJILL\D3N', 'FM', '91');
Insert into B4_ESPECIE
   (CODIGO, NOMBRE, CODTIPOCAPTURA, CODFAMILIA)
 Values
   ('802', 'OSTRA', 'FM', '91');
Insert into B4_ESPECIE
   (CODIGO, CODFAO, NOMBRE, CODTIPOCAPTURA, CODFAMILIA, USRALTA, USRMODIF, FECALTA, FECMODIF)
 Values
   ('141', 'USB', 'MARAGOTA', 'FP', '18', 
    'JMCIDRAS', 'JMCIDRAS', TO_DATE('05/05/2015 12:15:34', 'MM/DD/YYYY HH24:MI:SS'), TO_DATE('05/05/2015 12:15:34', 'MM/DD/YYYY HH24:MI:SS'));
Insert into B4_ESPECIE
   (CODIGO, CODFAO, NOMBRE, CODTIPOCAPTURA, CODFAMILIA, USRALTA, USRMODIF, FECALTA, FECMODIF)
 Values
   ('142', 'MON', 'RAPE', 'FP', '17', 
    'JMCIDRAS', 'JMCIDRAS', TO_DATE('05/05/2015 12:16:32', 'MM/DD/YYYY HH24:MI:SS'), TO_DATE('05/05/2015 12:16:32', 'MM/DD/YYYY HH24:MI:SS'));
Insert into B4_ESPECIE
   (CODIGO, CODFAO, NOMBRE, CODTIPOCAPTURA, CODFAMILIA, USRALTA, USRMODIF, FECALTA, FECMODIF)
 Values
   ('144', 'WHG', 'MERLAN', 'FP', '16', 
    'JMCIDRAS', 'JMCIDRAS', TO_DATE('06/16/2015 12:39:25', 'MM/DD/YYYY HH24:MI:SS'), TO_DATE('06/16/2015 12:39:25', 'MM/DD/YYYY HH24:MI:SS'));
Insert into B4_ESPECIE
   (CODIGO, CODFAO, NOMBRE, CODTIPOCAPTURA, CODFAMILIA, USRALTA, USRMODIF, FECALTA, FECMODIF)
 Values
   ('145', 'SQI', 'POTA-VOLADOR', 'FM', '62', 
    'JMCIDRAS', 'JMCIDRAS', TO_DATE('06/16/2015 12:40:26', 'MM/DD/YYYY HH24:MI:SS'), TO_DATE('06/16/2015 12:40:26', 'MM/DD/YYYY HH24:MI:SS'));
Insert into B4_ESPECIE
   (CODIGO, CODFAO, NOMBRE, CODTIPOCAPTURA, CODFAMILIA, USRALTA, USRMODIF, FECALTA, FECMODIF)
 Values
   ('146', 'OCM', 'PULPO', 'FM', '62', 
    'JMCIDRAS', 'JMCIDRAS', TO_DATE('06/16/2015 12:41:19', 'MM/DD/YYYY HH24:MI:SS'), TO_DATE('06/16/2015 12:41:19', 'MM/DD/YYYY HH24:MI:SS'));
Insert into B4_ESPECIE
   (CODIGO, CODFAO, NOMBRE, CODTIPOCAPTURA, CODFAMILIA, USRALTA, USRMODIF, FECALTA, FECMODIF)
 Values
   ('148', 'GFB', 'BROTOLA DE FANGO', 'FP', '16', 
    'JMCIDRAS', 'JMCIDRAS', TO_DATE('06/16/2015 12:43:23', 'MM/DD/YYYY HH24:MI:SS'), TO_DATE('06/16/2015 12:43:23', 'MM/DD/YYYY HH24:MI:SS'));
Insert into B4_ESPECIE
   (CODIGO, CODFAO, NOMBRE, CODTIPOCAPTURA, CODFAMILIA, USRALTA, USRMODIF, FECALTA, FECMODIF)
 Values
   ('149', 'OIL', 'COCHINILLA', 'FP', '18', 
    'JMCIDRAS', 'JMCIDRAS', TO_DATE('06/19/2015 13:24:21', 'MM/DD/YYYY HH24:MI:SS'), TO_DATE('06/19/2015 13:24:21', 'MM/DD/YYYY HH24:MI:SS'));
Insert into B4_ESPECIE
   (CODIGO, CODFAO, NOMBRE, CODTIPOCAPTURA, CODFAMILIA, USRALTA, USRMODIF, FECALTA, FECMODIF)
 Values
   ('143', 'COE', 'CONGRIO', 'FP', '11', 
    'JMCIDRAS', 'JMCIDRAS', TO_DATE('06/16/2015 11:50:40', 'MM/DD/YYYY HH24:MI:SS'), TO_DATE('06/16/2015 11:50:40', 'MM/DD/YYYY HH24:MI:SS'));
Insert into B4_ESPECIE
   (CODIGO, CODFAO, NOMBRE, CODTIPOCAPTURA, CODFAMILIA, USRALTA, USRMODIF, FECALTA, FECMODIF)
 Values
   ('147', 'JOD', 'SANMARTI\D1O / GALLO DE SAN PEDRO', 'FP', '23', 
    'JMCIDRAS', 'JMCIDRAS', TO_DATE('06/16/2015 12:42:40', 'MM/DD/YYYY HH24:MI:SS'), TO_DATE('06/16/2015 12:44:13', 'MM/DD/YYYY HH24:MI:SS'));
Insert into B4_ESPECIE
   (CODIGO, CODFAO, NOMBRE, CODTIPOCAPTURA, CODFAMILIA, USRALTA, USRMODIF, FECALTA, FECMODIF)
 Values
   ('150', 'BRF', 'GALLINETA', 'FP', '15', 
    'JMCIDRAS', 'JMCIDRAS', TO_DATE('06/22/2015 11:23:12', 'MM/DD/YYYY HH24:MI:SS'), TO_DATE('06/22/2015 11:23:12', 'MM/DD/YYYY HH24:MI:SS'));
COMMIT;
