SET DEFINE OFF;
Insert into B4_GRUPOFAMILIA
   (CODIGO, DESCRIPCION)
 Values
   ('1', 'PECES');
Insert into B4_GRUPOFAMILIA
   (CODIGO, DESCRIPCION)
 Values
   ('2', 'CRUSTACEOS');
Insert into B4_GRUPOFAMILIA
   (CODIGO, DESCRIPCION, USRMODIF, FECMODIF)
 Values
   ('3', 'MOLUSCOS', 'prueba', TO_DATE('09/25/2014 17:33:24', 'MM/DD/YYYY HH24:MI:SS'));
Insert into B4_GRUPOFAMILIA
   (CODIGO, DESCRIPCION)
 Values
   ('4', 'EQUINODERMOS');
Insert into B4_GRUPOFAMILIA
   (CODIGO, DESCRIPCION)
 Values
   ('5', 'OTROS');
Insert into B4_GRUPOFAMILIA
   (CODIGO, DESCRIPCION, USRMODIF, FECMODIF)
 Values
   ('6', 'VIVEROS', 'prueba', TO_DATE('09/25/2014 17:33:52', 'MM/DD/YYYY HH24:MI:SS'));
Insert into B4_GRUPOFAMILIA
   (CODIGO, DESCRIPCION)
 Values
   ('9', 'PESCA CONGELADA');
COMMIT;
