SET DEFINE OFF;
Insert into B4_PRESENTACION
   (CODIGO, DESCRIPCION, FECMODIF)
 Values
   ('1', 'COLAS CONGELADAS', TO_DATE('09/30/2014 10:17:19', 'MM/DD/YYYY HH24:MI:SS'));
Insert into B4_PRESENTACION
   (CODIGO, DESCRIPCION)
 Values
   ('2', 'COLAS FRESCAS');
Insert into B4_PRESENTACION
   (CODIGO, DESCRIPCION)
 Values
   ('3', 'CONGELADO LIMPIO');
Insert into B4_PRESENTACION
   (CODIGO, DESCRIPCION)
 Values
   ('4', 'CONGELADO NO LIMPIADO');
Insert into B4_PRESENTACION
   (CODIGO, DESCRIPCION)
 Values
   ('5', 'CONGELADO, OTRAS PRESENTACIONES');
Insert into B4_PRESENTACION
   (CODIGO, DESCRIPCION)
 Values
   ('6', 'DESCABEZADO Y EVISCERADO CONGELADO');
Insert into B4_PRESENTACION
   (CODIGO, DESCRIPCION)
 Values
   ('7', 'EN SALAZÓN');
Insert into B4_PRESENTACION
   (CODIGO, DESCRIPCION)
 Values
   ('8', 'ENTERO CONGELADO');
Insert into B4_PRESENTACION
   (CODIGO, DESCRIPCION)
 Values
   ('9', 'ENTERO FRESCO');
Insert into B4_PRESENTACION
   (CODIGO, DESCRIPCION, FECMODIF)
 Values
   ('10', 'EVISCERADO FRESCO', TO_DATE('10/01/2014 08:58:22', 'MM/DD/YYYY HH24:MI:SS'));
Insert into B4_PRESENTACION
   (CODIGO, DESCRIPCION)
 Values
   ('11', 'FILETES CONGELADOS');
Insert into B4_PRESENTACION
   (CODIGO, DESCRIPCION)
 Values
   ('90', 'DESCRIPCIÓN CÓDIGO 90');
COMMIT;
