SET DEFINE OFF;
Insert into B4_TIPOBUQUE
   (CODIGO, NOMBRE, ALTURALITORAL)
 Values
   ('PL', 'PESQUERO DE LITORAL', 'L');
Insert into B4_TIPOBUQUE
   (CODIGO, NOMBRE, ALTURALITORAL)
 Values
   ('PA', 'PESQUERO DE ALTURA', 'A');
Insert into B4_TIPOBUQUE
   (CODIGO, NOMBRE, ALTURALITORAL)
 Values
   ('OC', 'PESQUERO DE ALTURA CONGELADOR', 'A');
COMMIT;
