SET DEFINE OFF;
Insert into B4_TIPOVENTA
   (CODIGO, DESCRIPCION, CODTIPOIVA, USRMODIF, FECMODIF)
 Values
   ('1', '1ª Venta', 'E', 'prueba', TO_DATE('10/23/2014 10:38:21', 'MM/DD/YYYY HH24:MI:SS'));
Insert into B4_TIPOVENTA
   (CODIGO, DESCRIPCION, CODTIPOIVA, USRMODIF, FECMODIF)
 Values
   ('2', '2ª Venta', 'G', 'prueba', TO_DATE('10/23/2014 14:04:49', 'MM/DD/YYYY HH24:MI:SS'));
COMMIT;
