SET DEFINE OFF;
Insert into B4_TIPOOPERACION
   (CODIGO, NOMBRE, INDGENERAB0, CODTIPOVENTA, CODBAREMOB4, INDEXENTOB4, BAJA, USRMODIF, FECMODIF)
 Values
   ('1', 'DESEMBARQUE CON VENTA EN LONJA NO CONCESIONADA O AUTORIZADA', '1', '1', 'T4-00001', 
    '0', '0', 'prueba', TO_DATE('10/23/2014 13:59:40', 'MM/DD/YYYY HH24:MI:SS'));
Insert into B4_TIPOOPERACION
   (CODIGO, NOMBRE, INDGENERAB0, CODTIPOVENTA, CODBAREMOB4, INDEXENTOB4, BAJA, USRMODIF, FECMODIF)
 Values
   ('2', 'ENTRADA TERRESTRE SIN USO LONJA', '0', '1', 'T4-00004', 
    '0', '0', 'prueba', TO_DATE('10/23/2014 13:54:07', 'MM/DD/YYYY HH24:MI:SS'));
Insert into B4_TIPOOPERACION
   (CODIGO, NOMBRE, INDGENERAB0, CODTIPOVENTA, CODBAREMOB4, INDEXENTOB4, BAJA, USRMODIF, FECMODIF)
 Values
   ('3', 'ENTRADA TERRESTRE CON VENTA EN LONJA NO CONCESIONADA O AUTORIZADA', '0', '1', 'T4-00002', 
    '0', '0', 'prueba', TO_DATE('05/22/2015 08:42:25', 'MM/DD/YYYY HH24:MI:SS'));
Insert into B4_TIPOOPERACION
   (CODIGO, NOMBRE, INDGENERAB0, CODTIPOVENTA, CODBAREMOB4, INDEXENTOB4, BAJA)
 Values
   ('4', 'DESEMBARQUE SIN USO LONJA', '1', '1', 'T4-00003', 
    '0', '0');
Insert into B4_TIPOOPERACION
   (CODIGO, NOMBRE, INDGENERAB0, CODTIPOVENTA, INDEXENTOB4, BAJA)
 Values
   ('5', 'SERVICIOS DIVERSOS', '0', '1', 
    '1', '0');
Insert into B4_TIPOOPERACION
   (CODIGO, NOMBRE, INDGENERAB0, CODTIPOVENTA, CODBAREMOB4, INDEXENTOB4, BAJA)
 Values
   ('8', 'DESEMBARQUE CON VENTA EN LONJA CONCESIONADA O AUTORIZADA', '1', '1', 'T4-00005', 
    '0', '1');
Insert into B4_TIPOOPERACION
   (CODIGO, NOMBRE, INDGENERAB0, CODTIPOVENTA, CODBAREMOB4, INDEXENTOB4, BAJA)
 Values
   ('7', 'ENTRADA TERRESTRE CON VENTA EN LONJA CONCESIONADA O AUTORIZADA', '0', '1', 'T4-00006', 
    '0', '1');
COMMIT;
