SET DEFINE OFF;
Insert into CEN_EXPEDIENTE_ESTADO
   (CODESTEXPEDIENTE, DESESTESPEDIENTE)
 Values
   ('A', 'Aprobado');
Insert into CEN_EXPEDIENTE_ESTADO
   (CODESTEXPEDIENTE, DESESTESPEDIENTE)
 Values
   ('P', 'Pendiente');
Insert into CEN_EXPEDIENTE_ESTADO
   (CODESTEXPEDIENTE, DESESTESPEDIENTE)
 Values
   ('R', 'Rechazado');
COMMIT;
