SET DEFINE OFF;
Insert into DP_TIPOBIENPUBLICO
   (CODIGO, DESCRIPCION, INDINSTALACION)
 Values
   (3, 'NAVE', '1');
Insert into DP_TIPOBIENPUBLICO
   (CODIGO, DESCRIPCION, INDINSTALACION)
 Values
   (4, 'EDIFICIO', '1');
Insert into DP_TIPOBIENPUBLICO
   (CODIGO, DESCRIPCION, INDINSTALACION)
 Values
   (5, 'LOCAL', '1');
Insert into DP_TIPOBIENPUBLICO
   (CODIGO, DESCRIPCION, INDINSTALACION, USRALTA, USRMODIF, FECALTA, FECMODIF)
 Values
   (6, 'USO INSTITUCIONAL', '1', 'PRODEVELOP', 'PRODEVELOP', 
    TO_DATE('01/14/2015 10:34:13', 'MM/DD/YYYY HH24:MI:SS'), TO_DATE('01/14/2015 10:34:13', 'MM/DD/YYYY HH24:MI:SS'));
Insert into DP_TIPOBIENPUBLICO
   (CODIGO, DESCRIPCION, INDINSTALACION, USRALTA, USRMODIF, FECALTA, FECMODIF)
 Values
   (8, 'VARIOS', '0', 'MARIAJOG', 'MARIAJOG', 
    TO_DATE('02/05/2015 10:48:30', 'MM/DD/YYYY HH24:MI:SS'), TO_DATE('02/05/2015 10:48:30', 'MM/DD/YYYY HH24:MI:SS'));
Insert into DP_TIPOBIENPUBLICO
   (CODIGO, DESCRIPCION, INDINSTALACION, USRALTA, USRMODIF, FECALTA, FECMODIF)
 Values
   (7, 'VADO APARCAMIENTO', '0', 'PRODEVELOP', 'PRODEVELOP', 
    TO_DATE('01/14/2015 10:35:01', 'MM/DD/YYYY HH24:MI:SS'), TO_DATE('01/14/2015 10:35:01', 'MM/DD/YYYY HH24:MI:SS'));
Insert into DP_TIPOBIENPUBLICO
   (CODIGO, DESCRIPCION, INDINSTALACION)
 Values
   (9, 'ASTILLERO', '1');
Insert into DP_TIPOBIENPUBLICO
   (CODIGO, DESCRIPCION, INDINSTALACION)
 Values
   (10, 'FRIGORIFICO', '1');
Insert into DP_TIPOBIENPUBLICO
   (CODIGO, DESCRIPCION, INDINSTALACION)
 Values
   (1, 'SUPERFICIE TERRENO', '0');
Insert into DP_TIPOBIENPUBLICO
   (CODIGO, DESCRIPCION, INDINSTALACION)
 Values
   (2, 'SUPERFICIE LÁMINA AGUA', '0');
COMMIT;
