SET DEFINE OFF;
Insert into DP_TIPOACTIVPRINCIPAL
   (CODIGO, DESCRIPCION, USRALTA, USRMODIF, FECALTA, FECMODIF)
 Values
   ('HOS', 'Recinto dedicado a la hosteleria', 'prueba', 'prueba', TO_DATE('01/28/2016 17:08:33', 'MM/DD/YYYY HH24:MI:SS'), 
    TO_DATE('01/28/2016 17:08:33', 'MM/DD/YYYY HH24:MI:SS'));
COMMIT;
