SET DEFINE OFF;
Insert into EDI_TIPO_MENSAJE
   (IDTIPOMENSAJE, DESTIPOMENSAJE, IDCLASEMENSAJE, USRALTA, FECALTA)
 Values
   (8, 'IFTDGN (Notificación Mercancia Peligrosa)', 5, 'SISTEMA', TO_DATE('09/01/2014 00:00:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into EDI_TIPO_MENSAJE
   (IDTIPOMENSAJE, DESTIPOMENSAJE, IDCLASEMENSAJE, USRALTA, FECALTA, USRMODIF, FECMODIF)
 Values
   (7, 'IFCSUM (Declaración Sumaria/Manifiesto de Carga)', 4, 'SISTEMA', TO_DATE('09/01/2014 01:00:00', 'MM/DD/YYYY HH24:MI:SS'), 
    'SISTEMA', TO_DATE('09/01/2014 01:00:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into EDI_TIPO_MENSAJE
   (IDTIPOMENSAJE, DESTIPOMENSAJE, IDCLASEMENSAJE, USRALTA, FECALTA, USRMODIF)
 Values
   (2, 'APERAK (Respuesta Berman)', 2, 'SISTEMA', TO_DATE('09/01/2014 01:00:00', 'MM/DD/YYYY HH24:MI:SS'), 
    'SISTEMA');
Insert into EDI_TIPO_MENSAJE
   (IDTIPOMENSAJE, DESTIPOMENSAJE, IDCLASEMENSAJE, USRALTA, FECALTA, USRMODIF, FECMODIF)
 Values
   (1, 'BERMAN (Solicitud de Escala)', 1, 'SISTEMA', TO_DATE('09/01/2014 01:00:00', 'MM/DD/YYYY HH24:MI:SS'), 
    'SISTEMA', TO_DATE('09/01/2014 01:00:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into EDI_TIPO_MENSAJE
   (IDTIPOMENSAJE, DESTIPOMENSAJE, IDCLASEMENSAJE, USRALTA, FECALTA)
 Values
   (3, 'APEDGM (Autorizar/Denegar la escala DGMM)', 2, 'SISTEMA', TO_DATE('09/01/2014 01:00:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into EDI_TIPO_MENSAJE
   (IDTIPOMENSAJE, DESTIPOMENSAJE, IDCLASEMENSAJE, USRALTA, FECALTA)
 Values
   (4, 'BERATA (Comunicar ATA para una Escala)', 1, 'SISTEMA', TO_DATE('09/01/2014 01:00:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into EDI_TIPO_MENSAJE
   (IDTIPOMENSAJE, DESTIPOMENSAJE, IDCLASEMENSAJE, USRALTA, FECALTA)
 Values
   (5, 'BERATD (Comunicar ATD para una Escala)', 1, 'SISTEMA', TO_DATE('09/01/2014 01:00:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into EDI_TIPO_MENSAJE
   (IDTIPOMENSAJE, DESTIPOMENSAJE, IDCLASEMENSAJE, USRALTA, FECALTA)
 Values
   (6, 'CUSRP2 (Notificación de Petición de Práctico)', 3, 'SISTEMA', TO_DATE('09/01/2014 01:00:00', 'MM/DD/YYYY HH24:MI:SS'));
COMMIT;
