SET DEFINE OFF;
Insert into EST_PARAMFPTIPOBULTO
   (CODIGO, FECINIVIG, CODTIPOBULTO, FORMAPRESENT)
 Values
   (1, TO_DATE('01/01/2016 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'VG', 'GL');
Insert into EST_PARAMFPTIPOBULTO
   (CODIGO, FECINIVIG, CODTIPOBULTO, FORMAPRESENT)
 Values
   (2, TO_DATE('01/01/2016 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'VL', 'GL');
Insert into EST_PARAMFPTIPOBULTO
   (CODIGO, FECINIVIG, CODTIPOBULTO, FORMAPRESENT)
 Values
   (3, TO_DATE('01/01/2016 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'VQ', 'GL');
Insert into EST_PARAMFPTIPOBULTO
   (CODIGO, FECINIVIG, CODTIPOBULTO, FORMAPRESENT)
 Values
   (4, TO_DATE('01/01/2016 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'VR', 'GS');
Insert into EST_PARAMFPTIPOBULTO
   (CODIGO, FECINIVIG, CODTIPOBULTO, FORMAPRESENT)
 Values
   (5, TO_DATE('01/01/2016 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'VO', 'GS');
Insert into EST_PARAMFPTIPOBULTO
   (CODIGO, FECINIVIG, CODTIPOBULTO, FORMAPRESENT)
 Values
   (6, TO_DATE('01/01/2016 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'VY', 'GS');
COMMIT;
