SET DEFINE OFF;
Insert into EST_TUCAOPPE
   (CODIGO, DESCRIPCION, CODTIPOMERCSIGMA)
 Values
   ('N11', 'GR. LIQ. GAS LÍQUIDO, GAS NATURAL', 'LO');
Insert into EST_TUCAOPPE
   (CODIGO, DESCRIPCION, CODTIPOMERCSIGMA)
 Values
   ('N12', 'GR. LIQ. PETRÓLEO BRUTO', 'LP');
Insert into EST_TUCAOPPE
   (CODIGO, DESCRIPCION, CODTIPOMERCSIGMA)
 Values
   ('N13', 'GR. LIQ. PRODUCTOS PETROLIFER', 'LP');
Insert into EST_TUCAOPPE
   (CODIGO, DESCRIPCION, CODTIPOMERCSIGMA)
 Values
   ('N19', 'OTRAS MERC. A GRANEL LÍQUIDA', 'LO');
Insert into EST_TUCAOPPE
   (CODIGO, DESCRIPCION, CODTIPOMERCSIGMA)
 Values
   ('N21', 'GR. SOL. MINERAL', 'SG');
Insert into EST_TUCAOPPE
   (CODIGO, DESCRIPCION, CODTIPOMERCSIGMA)
 Values
   ('N22', 'GR. SOL. CARBÓN', 'SG');
Insert into EST_TUCAOPPE
   (CODIGO, DESCRIPCION, CODTIPOMERCSIGMA)
 Values
   ('N23', 'GR. SOL. PRODUCTOS AGRÍCOLAS', 'SG');
Insert into EST_TUCAOPPE
   (CODIGO, DESCRIPCION, CODTIPOMERCSIGMA)
 Values
   ('N29', 'OTRAS MERCANCÍAS A GRAN. SOL', 'SG');
Insert into EST_TUCAOPPE
   (CODIGO, DESCRIPCION, CODTIPOMERCSIGMA)
 Values
   ('N31', 'CONTENEDOR 20', 'MG');
Insert into EST_TUCAOPPE
   (CODIGO, DESCRIPCION, CODTIPOMERCSIGMA)
 Values
   ('N32', 'CONTENEDOR 40', 'MG');
Insert into EST_TUCAOPPE
   (CODIGO, DESCRIPCION, CODTIPOMERCSIGMA)
 Values
   ('N52', 'VEHÍCUL.PARTICUL(REMOL.CARAV ', 'PA');
Insert into EST_TUCAOPPE
   (CODIGO, DESCRIPCION, CODTIPOMERCSIGMA)
 Values
   ('N53', 'AUTOCARES PARA PASAJEROS ', 'PA');
Insert into EST_TUCAOPPE
   (CODIGO, DESCRIPCION, CODTIPOMERCSIGMA)
 Values
   ('N54', 'VEHÍCULO PARA IMPORT/EXPORT ', 'MG');
Insert into EST_TUCAOPPE
   (CODIGO, DESCRIPCION, CODTIPOMERCSIGMA)
 Values
   ('N56', 'ANIMALES VIVOS DE PIE', 'MG');
Insert into EST_TUCAOPPE
   (CODIGO, DESCRIPCION, CODTIPOMERCSIGMA)
 Values
   ('N91', 'CARGA GRAL. PRODUC. FORESTAL', 'MG');
Insert into EST_TUCAOPPE
   (CODIGO, DESCRIPCION, CODTIPOMERCSIGMA)
 Values
   ('N92', 'CARGA GRAL. PRODUC. SIDERURG', 'MG');
Insert into EST_TUCAOPPE
   (CODIGO, DESCRIPCION, CODTIPOMERCSIGMA)
 Values
   ('N99', 'OTROS CARGAMENTOS GENERALES', 'MG');
Insert into EST_TUCAOPPE
   (CODIGO, DESCRIPCION, CODTIPOMERCSIGMA)
 Values
   ('RP1', 'PLATAFORMA <=6', 'MG');
Insert into EST_TUCAOPPE
   (CODIGO, DESCRIPCION, CODTIPOMERCSIGMA)
 Values
   ('RP2', 'PLATAFORMA >6', 'MG');
Insert into EST_TUCAOPPE
   (CODIGO, DESCRIPCION, CODTIPOMERCSIGMA)
 Values
   ('RP3', 'PLATAFORMA CON CONTE. 20', 'MG');
Insert into EST_TUCAOPPE
   (CODIGO, DESCRIPCION, CODTIPOMERCSIGMA)
 Values
   ('RP4', 'PLATAFORMA CON CONTE. 40', 'MG');
Insert into EST_TUCAOPPE
   (CODIGO, DESCRIPCION, CODTIPOMERCSIGMA)
 Values
   ('RM+', 'CAMIÓN > 3500 ', 'MG');
Insert into EST_TUCAOPPE
   (CODIGO, DESCRIPCION, CODTIPOMERCSIGMA)
 Values
   ('RM-', 'CAMIÓN <=3500', 'MG');
Insert into EST_TUCAOPPE
   (CODIGO, DESCRIPCION, CODTIPOMERCSIGMA)
 Values
   ('NPA', 'PASAJEROS', 'PS');
Insert into EST_TUCAOPPE
   (CODIGO, DESCRIPCION, CODTIPOMERCSIGMA)
 Values
   ('RTR', 'CABEZA TRACTORA', 'MG');
Insert into EST_TUCAOPPE
   (CODIGO, DESCRIPCION, CODTIPOMERCSIGMA)
 Values
   ('RTA', 'TREN DE CARRETERA', 'MG');
Insert into EST_TUCAOPPE
   (CODIGO, DESCRIPCION, CODTIPOMERCSIGMA)
 Values
   ('N51', 'VEHÍCUL.AUTÓM.MERCANC.REMOLQ', 'MG');
Insert into EST_TUCAOPPE
   (CODIGO, DESCRIPCION, CODTIPOMERCSIGMA)
 Values
   ('N63', 'VAGONES, REMOL. MARIT. N/A', 'MG');
Insert into EST_TUCAOPPE
   (CODIGO, DESCRIPCION, CODTIPOMERCSIGMA)
 Values
   ('R31', 'CONTENEDOR 20 RO-RO', 'MG');
Insert into EST_TUCAOPPE
   (CODIGO, DESCRIPCION, CODTIPOMERCSIGMA)
 Values
   ('R32', 'CONTENEDOR 40 RO-RO', 'MG');
Insert into EST_TUCAOPPE
   (CODIGO, DESCRIPCION, CODTIPOMERCSIGMA)
 Values
   ('RFR', 'FURGONES', 'MG');
Insert into EST_TUCAOPPE
   (CODIGO, DESCRIPCION, CODTIPOMERCSIGMA)
 Values
   ('N62', 'CARAV. REMOL. AGR. INDUS. N/A', 'MG');
Insert into EST_TUCAOPPE
   (CODIGO, DESCRIPCION, CODTIPOMERCSIGMA)
 Values
   ('R54', 'VEHÍCULO PARA IMPORT/EXPORT', 'MG');
Insert into EST_TUCAOPPE
   (CODIGO, DESCRIPCION, CODTIPOMERCSIGMA)
 Values
   ('R53', 'AUTOCARES PARA PASAJEROS', 'PA');
Insert into EST_TUCAOPPE
   (CODIGO, DESCRIPCION, CODTIPOMERCSIGMA)
 Values
   ('R52', 'VEHÍCUL.PARTICUL(REMOL.CARAV', 'PA');
Insert into EST_TUCAOPPE
   (CODIGO, DESCRIPCION, CODTIPOMERCSIGMA)
 Values
   ('N61', 'REMOLQUES NO ACOMPAÑADOS', 'MG');
Insert into EST_TUCAOPPE
   (CODIGO, DESCRIPCION, CODTIPOMERCSIGMA)
 Values
   ('R61', 'REMOLQUES NO ACOMPAÑADOS', 'MG');
Insert into EST_TUCAOPPE
   (CODIGO, DESCRIPCION, CODTIPOMERCSIGMA)
 Values
   ('R62', 'CARAV. REMOL. AGR. INDUS. N/A', 'MG');
Insert into EST_TUCAOPPE
   (CODIGO, DESCRIPCION, CODTIPOMERCSIGMA)
 Values
   ('R63', 'VAGONES, REMOL. MARIT. N/A', 'MG');
Insert into EST_TUCAOPPE
   (CODIGO, DESCRIPCION, CODTIPOMERCSIGMA)
 Values
   ('R99', 'OTROS CARGAMENTOS GENERALES', 'MG');
Insert into EST_TUCAOPPE
   (CODIGO, DESCRIPCION, CODTIPOMERCSIGMA)
 Values
   ('R51', 'VEHÍCUL.AUTÓM.MERCANC.REMOLQ.', 'MG');
COMMIT;
