SET DEFINE OFF;
Insert into EST_TIPOMERC_SIGMA
   (CODIGO, DESCRIPCION)
 Values
   ('LO', 'OTROS GRANELES LIQUIDOS');
Insert into EST_TIPOMERC_SIGMA
   (CODIGO, DESCRIPCION)
 Values
   ('LP', 'GRANEL LIQUIDO PETROLIFERO');
Insert into EST_TIPOMERC_SIGMA
   (CODIGO, DESCRIPCION)
 Values
   ('MG', 'MERCANCIA GENERAL');
Insert into EST_TIPOMERC_SIGMA
   (CODIGO, DESCRIPCION)
 Values
   ('PA', 'AUTOMOVILES DE PASAJE');
Insert into EST_TIPOMERC_SIGMA
   (CODIGO, DESCRIPCION)
 Values
   ('PS', 'PASAJE');
Insert into EST_TIPOMERC_SIGMA
   (CODIGO, DESCRIPCION)
 Values
   ('SG', 'GRANEL SOLIDO');
COMMIT;
