SET DEFINE OFF;
Insert into GU_IDIOMA
   (CODIDIOMA, DESCIDIOMA, INDAPLICAUSUAPLI, INDAPLICACLIENTE)
 Values
   ('EN', 'Inglés', '0', '0');
Insert into GU_IDIOMA
   (CODIDIOMA, DESCIDIOMA, INDAPLICAUSUAPLI, INDAPLICACLIENTE)
 Values
   ('ES', 'Castellano', '1', '1');
COMMIT;
