SET DEFINE OFF;
Insert into GU_USUARIO_APLICACION
   (USR, NOMBRE, INDBAJA, CODIDIOMA)
 Values
   ('prueba', 'Usuario Prueba', '0', 'ES');
Insert into GU_USUARIO_APLICACION
   (USR, NOMBRE, INDBAJA, CODIDIOMA)
 Values
   ('SISTEMA', 'Sistema', '0', 'ES');
Insert into GU_USUARIO_APLICACION
   (USR, NOMBRE, INDBAJA, FECALTA, FECMODIF, USRALTA, USRMODIF, CODIDIOMA)
 Values
   ('MJLABUIGA', 'Maria José Labuiga', '0', 
    TO_DATE('03/31/2016 17:18:13', 'MM/DD/YYYY HH24:MI:SS'), TO_DATE('03/31/2016 17:18:24', 'MM/DD/YYYY HH24:MI:SS'), 'prueba', 'prueba', 'ES');
Insert into GU_USUARIO_APLICACION
   (USR, NOMBRE, INDBAJA, FECALTA, FECMODIF, USRALTA, USRMODIF, CODIDIOMA)
 Values
   ('RMARCO', 'Ramón Marco', '0', 
    TO_DATE('04/01/2016 08:19:42', 'MM/DD/YYYY HH24:MI:SS'), TO_DATE('04/01/2016 08:20:13', 'MM/DD/YYYY HH24:MI:SS'), 'FPABLO', 'FPABLO', 'ES');
Insert into GU_USUARIO_APLICACION
   (USR, NOMBRE, INDBAJA, FECALTA, FECMODIF, USRALTA, USRMODIF, CODIDIOMA)
 Values
   ('FPABLO', 'Fernando Pablo', '0', 
    TO_DATE('03/31/2016 17:16:54', 'MM/DD/YYYY HH24:MI:SS'), TO_DATE('03/31/2016 17:17:27', 'MM/DD/YYYY HH24:MI:SS'), 'prueba', 'prueba', 'ES');
Insert into GU_USUARIO_APLICACION
   (USR, NOMBRE, INDBAJA, FECALTA, FECMODIF, USRALTA, USRMODIF, CODIDIOMA)
 Values
   ('ACARRASCO', 'Aurora Carrasco', '0', 
    TO_DATE('03/31/2016 17:17:41', 'MM/DD/YYYY HH24:MI:SS'), TO_DATE('03/31/2016 17:17:41', 'MM/DD/YYYY HH24:MI:SS'), 'prueba', 'prueba', 'ES');
Insert into GU_USUARIO_APLICACION
   (USR, NOMBRE, INDBAJA, FECALTA, FECMODIF, USRALTA, USRMODIF, CODIDIOMA)
 Values
   ('SFRAJ', 'Sergio Fraj', '0', 
    TO_DATE('04/01/2016 08:17:52', 'MM/DD/YYYY HH24:MI:SS'), TO_DATE('04/01/2016 08:18:06', 'MM/DD/YYYY HH24:MI:SS'), 'FPABLO', 'FPABLO', 'ES');
Insert into GU_USUARIO_APLICACION
   (USR, NOMBRE, INDBAJA, FECALTA, FECMODIF, USRALTA, USRMODIF, CODIDIOMA)
 Values
   ('CJOUBERT', 'Christophe Joubert', '0', 
    TO_DATE('04/01/2016 08:18:39', 'MM/DD/YYYY HH24:MI:SS'), TO_DATE('04/01/2016 08:19:26', 'MM/DD/YYYY HH24:MI:SS'), 'FPABLO', 'FPABLO', 'ES');
Insert into GU_USUARIO_APLICACION
   (USR, NOMBRE, INDBAJA, FECALTA, FECMODIF, USRALTA, USRMODIF, CODIDIOMA)
 Values
   ('JFERRI', 'Pepe Ferri', '0', 
    TO_DATE('04/01/2016 08:24:06', 'MM/DD/YYYY HH24:MI:SS'), TO_DATE('04/01/2016 08:24:27', 'MM/DD/YYYY HH24:MI:SS'), 'FPABLO', 'FPABLO', 'ES');
Insert into GU_USUARIO_APLICACION
   (USR, NOMBRE, INDBAJA, FECALTA, FECMODIF, USRALTA, USRMODIF, CODIDIOMA)
 Values
   ('MRODRIGO', 'Marta Rodrigo', '0', 
    TO_DATE('04/01/2016 08:28:58', 'MM/DD/YYYY HH24:MI:SS'), TO_DATE('04/01/2016 08:29:12', 'MM/DD/YYYY HH24:MI:SS'), 'FPABLO', 'FPABLO', 'ES');
COMMIT;
