SET DEFINE OFF;
Insert into LQ_AGRUPAP_TASA
   (CODAGRUP, CODTASA, CODSUBTASA, EXTENSION)
 Values
   ('B0A0', 'B0', '00', '0000');
Insert into LQ_AGRUPAP_TASA
   (CODAGRUP, CODTASA, CODSUBTASA, EXTENSION)
 Values
   ('B0A4', 'B0', '40', '0000');
Insert into LQ_AGRUPAP_TASA
   (CODAGRUP, CODTASA, CODSUBTASA, EXTENSION)
 Values
   ('B0A5', 'B0', '50', '0000');
Insert into LQ_AGRUPAP_TASA
   (CODAGRUP, CODTASA, CODSUBTASA, EXTENSION)
 Values
   ('B0C0', 'B0', '00', '0000');
Insert into LQ_AGRUPAP_TASA
   (CODAGRUP, CODTASA, CODSUBTASA, EXTENSION)
 Values
   ('B0C4', 'B0', '40', '0000');
Insert into LQ_AGRUPAP_TASA
   (CODAGRUP, CODTASA, CODSUBTASA, EXTENSION)
 Values
   ('B0C5', 'B0', '50', '0000');
COMMIT;
