SET DEFINE OFF;
Insert into LQ_AGRUPA_TARIFA
   (IDTARIFA, DESCRIPCION)
 Values
   ('B0', 'TASA AYUDA A LA NAVEGACIÓN');
Insert into LQ_AGRUPA_TARIFA
   (IDTARIFA, DESCRIPCION)
 Values
   ('B1', 'TASA BUQUE');
Insert into LQ_AGRUPA_TARIFA
   (IDTARIFA, DESCRIPCION)
 Values
   ('B2', 'TASA PASAJE');
Insert into LQ_AGRUPA_TARIFA
   (IDTARIFA, DESCRIPCION)
 Values
   ('B3', 'TASA MERCANCÍAS');
Insert into LQ_AGRUPA_TARIFA
   (IDTARIFA, DESCRIPCION)
 Values
   ('B4', 'TASA PESCA FRESCA');
Insert into LQ_AGRUPA_TARIFA
   (IDTARIFA, DESCRIPCION)
 Values
   ('B5', 'TASA EMB. DEPORTIVAS');
Insert into LQ_AGRUPA_TARIFA
   (IDTARIFA, DESCRIPCION)
 Values
   ('B6', 'TASA UTILIZAC. ESPECIAL ZONA TRÁNSITO');
Insert into LQ_AGRUPA_TARIFA
   (IDTARIFA, DESCRIPCION)
 Values
   ('B7', 'TASA APROVECHAMIENTO ACTIVIDAD');
Insert into LQ_AGRUPA_TARIFA
   (IDTARIFA, DESCRIPCION)
 Values
   ('T7', 'TASA DE ALMACENAJE');
Insert into LQ_AGRUPA_TARIFA
   (IDTARIFA, DESCRIPCION)
 Values
   ('T8', 'TARIFA SUMINISTROS');
Insert into LQ_AGRUPA_TARIFA
   (IDTARIFA, DESCRIPCION)
 Values
   ('TR', 'TARIFA DE RESIDUOS');
Insert into LQ_AGRUPA_TARIFA
   (IDTARIFA, DESCRIPCION)
 Values
   ('CA', 'TASA ACTIVIDAD');
Insert into LQ_AGRUPA_TARIFA
   (IDTARIFA, DESCRIPCION)
 Values
   ('CO', 'TASA OCUPACIÓN');
Insert into LQ_AGRUPA_TARIFA
   (IDTARIFA, DESCRIPCION)
 Values
   ('ZZ', 'RESTO DE SERVICIOS');
COMMIT;
