SET DEFINE OFF;
Insert into LQ_CENTROCOSTE
   (CODIGO, DESCRIPCION, USRALTA, FECALTA)
 Values
   ('ZZZZZZ', 'ZZZZZZ', 'SISTEMA', TO_DATE('02/05/2016 13:48:15', 'MM/DD/YYYY HH24:MI:SS'));
Insert into LQ_CENTROCOSTE
   (CODIGO, DESCRIPCION, USRALTA, FECALTA)
 Values
   ('*********', 'CENTRO DE COSTE FICTICIO', 'SISTEMA', TO_DATE('02/05/2016 13:48:15', 'MM/DD/YYYY HH24:MI:SS'));
COMMIT;
