SET DEFINE OFF;
Insert into LQ_FACTURA_MOTIVO_ANULACION
   (CODMOTANULACION, DESMOTANULACION)
 Values
   (1, 'Motivo 1');
Insert into LQ_FACTURA_MOTIVO_ANULACION
   (CODMOTANULACION, DESMOTANULACION)
 Values
   (2, 'Motivo 2');
COMMIT;
