SET DEFINE OFF;
Insert into LQ_FACTURA_LOTE_TIPO_INCID
   (CODTIPOINCIDENCIA, ESWARNING)
 Values
   ('PF-3', '1');
Insert into LQ_FACTURA_LOTE_TIPO_INCID
   (CODTIPOINCIDENCIA, ESWARNING)
 Values
   ('9999999999', '0');
Insert into LQ_FACTURA_LOTE_TIPO_INCID
   (CODTIPOINCIDENCIA, ESWARNING)
 Values
   ('PF-1', '0');
Insert into LQ_FACTURA_LOTE_TIPO_INCID
   (CODTIPOINCIDENCIA, ESWARNING)
 Values
   ('PF-2', '0');
Insert into LQ_FACTURA_LOTE_TIPO_INCID
   (CODTIPOINCIDENCIA, ESWARNING)
 Values
   ('PF-4', '1');
Insert into LQ_FACTURA_LOTE_TIPO_INCID
   (CODTIPOINCIDENCIA, ESWARNING)
 Values
   ('PF-5', '0');
COMMIT;
