SET DEFINE OFF;
Insert into LQ_FACTURA_ESTADO
   (CODESTFACTURA, DESESTFACTURA)
 Values
   ('EM', 'EMITIDA');
Insert into LQ_FACTURA_ESTADO
   (CODESTFACTURA, DESESTFACTURA)
 Values
   ('AN', 'ANULADA');
COMMIT;
