SET DEFINE OFF;
Insert into LQ_GRUPOBORRADOR
   (CODIGO, DESCRIPCION)
 Values
   ('B0S', 'TASA AYUDA A LA NAVEGACION B0S');
Insert into LQ_GRUPOBORRADOR
   (CODIGO, DESCRIPCION)
 Values
   ('B00', 'TASA AYUDA A LA NAVEGACION B00');
Insert into LQ_GRUPOBORRADOR
   (CODIGO, DESCRIPCION)
 Values
   ('B10', 'TASA DEL BUQUE');
Insert into LQ_GRUPOBORRADOR
   (CODIGO, DESCRIPCION)
 Values
   ('B20', 'TASA DEL PASAJE');
Insert into LQ_GRUPOBORRADOR
   (CODIGO, DESCRIPCION)
 Values
   ('B30', 'TASA DE LA MERCANCIA');
Insert into LQ_GRUPOBORRADOR
   (CODIGO, DESCRIPCION)
 Values
   ('B40', 'TASA DE LA PESCA FRESCA ');
Insert into LQ_GRUPOBORRADOR
   (CODIGO, DESCRIPCION)
 Values
   ('B50', 'TASA DE LAS EMBARC. DEPORTIVAS Y RECREO');
Insert into LQ_GRUPOBORRADOR
   (CODIGO, DESCRIPCION)
 Values
   ('CAA', 'TASAS SOBRE AUTORIZACIONES');
Insert into LQ_GRUPOBORRADOR
   (CODIGO, DESCRIPCION)
 Values
   ('B70', 'TASA APROVECHAMIENTO ACTIVIDAD');
Insert into LQ_GRUPOBORRADOR
   (CODIGO, DESCRIPCION)
 Values
   ('CAG', 'TASAS SOBRE GABARRAS');
Insert into LQ_GRUPOBORRADOR
   (CODIGO, DESCRIPCION)
 Values
   ('T60', 'TARIFA T6: ELEVADORES');
Insert into LQ_GRUPOBORRADOR
   (CODIGO, DESCRIPCION)
 Values
   ('T70', 'TARIFA T7: ALMACENAMIENTO');
Insert into LQ_GRUPOBORRADOR
   (CODIGO, DESCRIPCION)
 Values
   ('T80', 'TARIFA T8: SERVICIO SUMINISTROS');
Insert into LQ_GRUPOBORRADOR
   (CODIGO, DESCRIPCION)
 Values
   ('T81', 'TARIFA T8: ENERGIA ELECTRICA');
Insert into LQ_GRUPOBORRADOR
   (CODIGO, DESCRIPCION)
 Values
   ('T82', 'TARIFA T8: AGUA SALADA');
Insert into LQ_GRUPOBORRADOR
   (CODIGO, DESCRIPCION)
 Values
   ('T83', 'TARIFA T8: DERECHOS ENGANCHE');
Insert into LQ_GRUPOBORRADOR
   (CODIGO, DESCRIPCION)
 Values
   ('T84', 'TARIFA T8: LIQ. CONTADORES');
Insert into LQ_GRUPOBORRADOR
   (CODIGO, DESCRIPCION)
 Values
   ('T85', 'TARIFA T8: DISPONIBILIDAD SERVICIO');
Insert into LQ_GRUPOBORRADOR
   (CODIGO, DESCRIPCION)
 Values
   ('T91', 'VEHICULOS (T9.1)');
Insert into LQ_GRUPOBORRADOR
   (CODIGO, DESCRIPCION)
 Values
   ('T94', 'PESAD EN BASCULA (T94)');
Insert into LQ_GRUPOBORRADOR
   (CODIGO, DESCRIPCION)
 Values
   ('T95', 'APARCAMIENTOS (T9.2)');
Insert into LQ_GRUPOBORRADOR
   (CODIGO, DESCRIPCION)
 Values
   ('T97', 'APERTURA TINGLADOS (T9.7)');
Insert into LQ_GRUPOBORRADOR
   (CODIGO, DESCRIPCION)
 Values
   ('T98', 'HORAS PERSONAL Y DOCUMENTOS (T9.7)');
Insert into LQ_GRUPOBORRADOR
   (CODIGO, DESCRIPCION)
 Values
   ('T99', 'RED WIFI');
Insert into LQ_GRUPOBORRADOR
   (CODIGO, DESCRIPCION)
 Values
   ('T9A', 'DEPOSITO INTERVENCION JUDICIAL');
Insert into LQ_GRUPOBORRADOR
   (CODIGO, DESCRIPCION)
 Values
   ('TR1', 'TARIFA DE RESIDUOS (TR)');
Insert into LQ_GRUPOBORRADOR
   (CODIGO, DESCRIPCION)
 Values
   ('CS0', 'EXPEDIENTES Y RECLAMACIONES');
Insert into LQ_GRUPOBORRADOR
   (CODIGO, DESCRIPCION)
 Values
   ('DC0', 'DERECHOS');
Insert into LQ_GRUPOBORRADOR
   (CODIGO, DESCRIPCION)
 Values
   ('RD0', 'REHABILITACION');
Insert into LQ_GRUPOBORRADOR
   (CODIGO, DESCRIPCION)
 Values
   ('RE0', 'RECARGOS');
Insert into LQ_GRUPOBORRADOR
   (CODIGO, DESCRIPCION)
 Values
   ('SR0', 'SANCIONES');
Insert into LQ_GRUPOBORRADOR
   (CODIGO, DESCRIPCION)
 Values
   ('OI0', 'OTROS INGRESOS EXPLOTACION');
Insert into LQ_GRUPOBORRADOR
   (CODIGO, DESCRIPCION)
 Values
   ('CAC', 'TASAS SOBRE CONCESIONES');
COMMIT;
