SET DEFINE OFF;
Insert into LQ_TARIFA
   (IDTARIFA, IDSUBTARIFA, EXTENSION, DESCRIPCION, INDPRECIOPUBLICO, USRALTA, FECALTA, CENTROCOSTE, CODTIPOSUJETO, INDAPLICADIVERSOS, CODGRUPO, IDTARIFAAGRUP, INDRECALCULOIVA)
 Values
   ('B0', '00', '0000', 'TASA AYUDAS A NAVEGACION MERCANTES', '1', 
    'SISTEMA', TO_DATE('04/11/2016 11:10:56', 'MM/DD/YYYY HH24:MI:SS'), 
    '*********', 'SPS', '0', 'B00', 'B0', '0');
Insert into LQ_TARIFA
   (IDTARIFA, IDSUBTARIFA, EXTENSION, DESCRIPCION, INDPRECIOPUBLICO, USRALTA, FECALTA, CENTROCOSTE, CODTIPOSUJETO, INDAPLICADIVERSOS, CODGRUPO, IDTARIFAAGRUP, INDRECALCULOIVA)
 Values
   ('B0', '40', '0000', 'TASA AYUDAS A NAVEGACION BUQUE PESCA', '1', 
    'SISTEMA', TO_DATE('04/11/2016 11:10:56', 'MM/DD/YYYY HH24:MI:SS'), 
    '*********', 'SPS', '0', 'B00', 'B0', '0');
Insert into LQ_TARIFA
   (IDTARIFA, IDSUBTARIFA, EXTENSION, DESCRIPCION, INDPRECIOPUBLICO, USRALTA, FECALTA, CENTROCOSTE, CODTIPOSUJETO, INDAPLICADIVERSOS, CODGRUPO, IDTARIFAAGRUP, INDRECALCULOIVA)
 Values
   ('B0', '50', '0000', 'TASA AYUDAS A NAVEGACION EMBARCACIONES DEPORTIVAS', '1', 
    'SISTEMA', TO_DATE('04/11/2016 11:10:56', 'MM/DD/YYYY HH24:MI:SS'), 
    '*********', 'SPS', '0', 'B00', 'B0', '0');
Insert into LQ_TARIFA
   (IDTARIFA, IDSUBTARIFA, EXTENSION, DESCRIPCION, INDPRECIOPUBLICO, USRALTA, FECALTA, CENTROCOSTE, CODTIPOSUJETO, INDAPLICADIVERSOS, CODGRUPO, IDTARIFAAGRUP, INDRECALCULOIVA)
 Values
   ('B1', '10', '0000', 'TASA BUQUE (ESTANCIAS CORTAS)', '1', 
    'SISTEMA', TO_DATE('04/11/2016 11:10:56', 'MM/DD/YYYY HH24:MI:SS'), 
    '*********', 'SPS', '0', 'B10', 'B1', '0');
Insert into LQ_TARIFA
   (IDTARIFA, IDSUBTARIFA, EXTENSION, DESCRIPCION, INDPRECIOPUBLICO, USRALTA, FECALTA, CENTROCOSTE, CODTIPOSUJETO, INDAPLICADIVERSOS, CODGRUPO, IDTARIFAAGRUP, INDRECALCULOIVA)
 Values
   ('B1', '20', '0000', 'TASA BUQUE (ESTANCIAS LARGAS)', '1', 
    'SISTEMA', TO_DATE('04/11/2016 11:10:56', 'MM/DD/YYYY HH24:MI:SS'), 
    '*********', 'SPS', '0', 'B10', 'B1', '0');
Insert into LQ_TARIFA
   (IDTARIFA, IDSUBTARIFA, EXTENSION, DESCRIPCION, INDPRECIOPUBLICO, USRALTA, FECALTA, CENTROCOSTE, CODTIPOSUJETO, INDAPLICADIVERSOS, CODGRUPO, IDTARIFAAGRUP, INDRECALCULOIVA)
 Values
   ('B1', '30', '0000', 'TASA BUQUE (ESTANCIAS MIXTAS)', '1', 
    'SISTEMA', TO_DATE('04/11/2016 11:10:56', 'MM/DD/YYYY HH24:MI:SS'), 
    '*********', 'SPS', '0', 'B10', 'B1', '0');
Insert into LQ_TARIFA
   (IDTARIFA, IDSUBTARIFA, EXTENSION, DESCRIPCION, INDPRECIOPUBLICO, USRALTA, FECALTA, CENTROCOSTE, CODTIPOSUJETO, INDAPLICADIVERSOS, CODGRUPO, IDTARIFAAGRUP, INDRECALCULOIVA)
 Values
   ('B2', '00', '0000', 'TASA DEL PASAJE (T-2)', '1', 
    'SISTEMA', TO_DATE('04/11/2016 11:10:56', 'MM/DD/YYYY HH24:MI:SS'), 
    '*********', 'SPS', '0', 'B20', 'B2', '0');
Insert into LQ_TARIFA
   (IDTARIFA, IDSUBTARIFA, EXTENSION, DESCRIPCION, INDPRECIOPUBLICO, USRALTA, FECALTA, CENTROCOSTE, CODTIPOSUJETO, INDAPLICADIVERSOS, CODGRUPO, IDTARIFAAGRUP, INDRECALCULOIVA)
 Values
   ('B3', '00', '0000', 'TASA  DE LA MERCANCIA (T-3)', '1', 
    'SISTEMA', TO_DATE('04/11/2016 11:10:56', 'MM/DD/YYYY HH24:MI:SS'), 
    '*********', 'SPS', '0', 'B30', 'B3', '0');
Insert into LQ_TARIFA
   (IDTARIFA, IDSUBTARIFA, EXTENSION, DESCRIPCION, INDPRECIOPUBLICO, USRALTA, FECALTA, CENTROCOSTE, CODTIPOSUJETO, INDAPLICADIVERSOS, CODGRUPO, IDTARIFAAGRUP, INDRECALCULOIVA)
 Values
   ('B3', '10', '0000', 'B3-TASA MERCANCIAS PARTIDAS', '1', 
    'SISTEMA', TO_DATE('04/11/2016 11:10:56', 'MM/DD/YYYY HH24:MI:SS'), 
    '*********', 'SPS', '0', 'B30', 'B3', '0');
Insert into LQ_TARIFA
   (IDTARIFA, IDSUBTARIFA, EXTENSION, DESCRIPCION, INDPRECIOPUBLICO, USRALTA, FECALTA, CENTROCOSTE, CODTIPOSUJETO, INDAPLICADIVERSOS, CODGRUPO, IDTARIFAAGRUP, INDRECALCULOIVA)
 Values
   ('B3', '20', '0000', 'B3-TASA MERCANCIAS SIMPLIFICADO', '1', 
    'SISTEMA', TO_DATE('04/11/2016 11:10:56', 'MM/DD/YYYY HH24:MI:SS'), 
    '*********', 'SPS', '0', 'B30', 'B3', '0');
Insert into LQ_TARIFA
   (IDTARIFA, IDSUBTARIFA, EXTENSION, DESCRIPCION, INDPRECIOPUBLICO, USRALTA, FECALTA, CENTROCOSTE, CODTIPOSUJETO, INDAPLICADIVERSOS, CODGRUPO, IDTARIFAAGRUP, INDRECALCULOIVA)
 Values
   ('B4', '00', '0000', 'TASA PESCA FRESCA', '1', 
    'SISTEMA', TO_DATE('04/11/2016 11:10:56', 'MM/DD/YYYY HH24:MI:SS'), 
    '*********', 'SPS', '0', 'B40', 'B4', '0');
Insert into LQ_TARIFA
   (IDTARIFA, IDSUBTARIFA, EXTENSION, DESCRIPCION, INDPRECIOPUBLICO, USRALTA, FECALTA, CENTROCOSTE, CODTIPOSUJETO, INDAPLICADIVERSOS, CODGRUPO, IDTARIFAAGRUP, INDRECALCULOIVA)
 Values
   ('B5', '00', '0000', 'TASA EMB.DPTVAS Y RECREO (T-5)', '1', 
    'SISTEMA', TO_DATE('04/11/2016 11:10:56', 'MM/DD/YYYY HH24:MI:SS'), 
    '*********', 'SPS', '0', 'B50', 'B5', '0');
Insert into LQ_TARIFA
   (IDTARIFA, IDSUBTARIFA, EXTENSION, DESCRIPCION, INDPRECIOPUBLICO, USRALTA, FECALTA, CENTROCOSTE, CODTIPOSUJETO, INDAPLICADIVERSOS, IDTARIFAAGRUP, INDRECALCULOIVA)
 Values
   ('B6', '00', '0000', 'TASA UT.ESP.ZONA TRANSITO(T-6)', '1', 
    'SISTEMA', TO_DATE('04/11/2016 11:10:56', 'MM/DD/YYYY HH24:MI:SS'), 
    '*********', 'SPS', '0', 'B6', '0');
Insert into LQ_TARIFA
   (IDTARIFA, IDSUBTARIFA, EXTENSION, DESCRIPCION, INDPRECIOPUBLICO, USRALTA, FECALTA, CENTROCOSTE, CODTIPOSUJETO, INDAPLICADIVERSOS, CODGRUPO, IDTARIFAAGRUP, INDRECALCULOIVA)
 Values
   ('CA', '30', '0000', 'TASA OCUPACION CONCESIONES', '1', 
    'SISTEMA', TO_DATE('04/11/2016 11:10:56', 'MM/DD/YYYY HH24:MI:SS'), 
    '*********', 'SP', '0', 'CAC', 'CO', '0');
Insert into LQ_TARIFA
   (IDTARIFA, IDSUBTARIFA, EXTENSION, DESCRIPCION, INDPRECIOPUBLICO, USRALTA, FECALTA, CENTROCOSTE, CODTIPOSUJETO, INDAPLICADIVERSOS, CODGRUPO, IDTARIFAAGRUP, INDRECALCULOIVA)
 Values
   ('CA', '40', '0000', 'TASA ACTIVIDAD CONCESIONES', '1', 
    'SISTEMA', TO_DATE('04/11/2016 11:10:56', 'MM/DD/YYYY HH24:MI:SS'), 
    '*********', 'SP', '0', 'CAA', 'CA', '0');
Insert into LQ_TARIFA
   (IDTARIFA, IDSUBTARIFA, EXTENSION, DESCRIPCION, INDPRECIOPUBLICO, USRALTA, FECALTA, CENTROCOSTE, CODTIPOSUJETO, INDAPLICADIVERSOS, CODGRUPO, IDTARIFAAGRUP, INDRECALCULOIVA)
 Values
   ('CA', '50', '0000', 'TASA OCUPACION AUTORIZACIONES', '1', 
    'SISTEMA', TO_DATE('04/11/2016 11:10:56', 'MM/DD/YYYY HH24:MI:SS'), 
    '*********', 'SP', '0', 'CAC', 'CO', '0');
Insert into LQ_TARIFA
   (IDTARIFA, IDSUBTARIFA, EXTENSION, DESCRIPCION, INDPRECIOPUBLICO, USRALTA, FECALTA, CENTROCOSTE, CODTIPOSUJETO, INDAPLICADIVERSOS, CODGRUPO, IDTARIFAAGRUP, INDRECALCULOIVA)
 Values
   ('CA', '60', '0000', 'TASA ACTIVIDAD AUTORIZACIONES', '1', 
    'SISTEMA', TO_DATE('04/11/2016 11:10:56', 'MM/DD/YYYY HH24:MI:SS'), 
    '*********', 'SP', '0', 'CAA', 'CA', '0');
Insert into LQ_TARIFA
   (IDTARIFA, IDSUBTARIFA, EXTENSION, DESCRIPCION, INDPRECIOPUBLICO, USRALTA, FECALTA, CENTROCOSTE, CODTIPOSUJETO, INDAPLICADIVERSOS, IDTARIFAAGRUP, INDRECALCULOIVA)
 Values
   ('TR', '00', '1000', 'TARIFA SERV.DESECHOS BUQUES', '0', 
    'SISTEMA', TO_DATE('04/11/2016 11:10:56', 'MM/DD/YYYY HH24:MI:SS'), 
    '*********', 'SPS', '0', 'TR', '0');
Insert into LQ_TARIFA
   (IDTARIFA, IDSUBTARIFA, EXTENSION, DESCRIPCION, INDPRECIOPUBLICO, USRALTA, FECALTA, CENTROCOSTE, CODTIPOSUJETO, INDAPLICADIVERSOS, IDTARIFAAGRUP, INDRECALCULOIVA)
 Values
   ('TR', '10', '0000', 'TR- TARIFA DE RESIDUOS TR', '0', 
    'SISTEMA', TO_DATE('04/11/2016 11:10:56', 'MM/DD/YYYY HH24:MI:SS'), 
    '*********', 'SPS', '0', 'TR', '0');
COMMIT;
