SET DEFINE OFF;
Insert into M_BONIFICACION
   (CODIGO, CODBONIFICACION, DESCRIPCION, FECINIVIG, PORCENTAJEBONIFICACION, TASATARIFA, INDVALORDEFECTO, INDT3TRAMOCOMPLETO, INDAPLICAMUELLE, INDAPLICABUQUE)
 Values
   (50, 'B0-00000', 'Bonificación Régimen Estimación Simplificada', TO_DATE('01/01/2014 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 
    20, 'B0', '1', '0', '0', '0');
Insert into M_BONIFICACION
   (CODIGO, CODBONIFICACION, DESCRIPCION, FECINIVIG, PORCENTAJEBONIFICACION, TASATARIFA, TIPO245, INDVALORDEFECTO, INDT3TRAMOCOMPLETO, INDAPLICAMUELLE, INDAPLICABUQUE)
 Values
   (2, 'B1-00000', 'Sin Bonificación Artículo 245.3', TO_DATE('01/01/2014 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 
    0, 
    'B1', '3', '0', '0', '0', '0');
Insert into M_BONIFICACION
   (CODIGO, CODBONIFICACION, DESCRIPCION, FECINIVIG, TASATARIFA, INDVALORDEFECTO, INDT3TRAMOCOMPLETO, INDAPLICAMUELLE, INDAPLICABUQUE)
 Values
   (6, 'B1-00001', 'Reducción Artículo 201 Entradas Servicio Marítimo', TO_DATE('01/01/2014 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 
    'B1', '0', '0', '0', '0');
Insert into M_BONIFICACION
   (CODIGO, CODBONIFICACION, DESCRIPCION, FECINIVIG, PORCENTAJEBONIFICACION, TASATARIFA, TIPO245, INDVALORDEFECTO, INDT3TRAMOCOMPLETO, INDAPLICAMUELLE, INDAPLICABUQUE)
 Values
   (7, 'B1-00002', 'Bonificación Artículo 245.1 Prácticas Medioambientales', TO_DATE('01/01/2014 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 
    5, 
    'B1', '1', '0', '0', '0', '0');
Insert into M_BONIFICACION
   (CODIGO, CODBONIFICACION, DESCRIPCION, FECINIVIG, PORCENTAJEBONIFICACION, TASATARIFA, TIPO245, INDVALORDEFECTO, INDT3TRAMOCOMPLETO, INDAPLICAMUELLE, INDAPLICABUQUE)
 Values
   (8, 'B1-00003', 'Bonificación Artículo 245.2 Calidad', TO_DATE('01/01/2014 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 
    5, 
    'B1', '2', '0', '0', '0', '0');
Insert into M_BONIFICACION
   (CODIGO, CODBONIFICACION, DESCRIPCION, FECINIVIG, PORCENTAJEBONIFICACION, TASATARIFA, INDVALORDEFECTO, INDT3TRAMOCOMPLETO, INDAPLICAMUELLE, INDAPLICABUQUE)
 Values
   (14, 'B2-00001', 'Reducción Artículo 208.d. Buque integrado en servicio marítimo regular', TO_DATE('01/01/2014 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 
    20, 'B2', '0', '0', '0', '0');
Insert into M_BONIFICACION
   (CODIGO, CODBONIFICACION, DESCRIPCION, FECINIVIG, PORCENTAJEBONIFICACION, TASATARIFA, INDVALORDEFECTO, INDT3TRAMOCOMPLETO, INDAPLICAMUELLE, INDAPLICABUQUE)
 Values
   (19, 'B2-00003', 'Bonificación Excursionistas - Tráfico Local Régimen Estimación Simplificada', TO_DATE('01/01/2014 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 
    30, 'B2', '0', '0', '0', '0');
Insert into M_BONIFICACION
   (CODIGO, CODBONIFICACION, DESCRIPCION, FECINIVIG, PORCENTAJEBONIFICACION, TASATARIFA, INDVALORDEFECTO, INDT3TRAMOCOMPLETO, INDAPLICAMUELLE, INDAPLICABUQUE)
 Values
   (47, 'B2-01000', 'Reducción Artículo 208.b. Atraques y estaciones marítimas otorgadas conjuntamente en concesión o autorización', TO_DATE('01/01/2014 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 
    50, 'B2', '0', '0', '0', '0');
Insert into M_BONIFICACION
   (CODIGO, CODBONIFICACION, DESCRIPCION, FECINIVIG, PORCENTAJEBONIFICACION, TASATARIFA, INDVALORDEFECTO, INDT3TRAMOCOMPLETO, INDAPLICAMUELLE, INDAPLICABUQUE)
 Values
   (48, 'B2-01001', 'Reducción Artículo 208.c. Estaciones marítimas otorgadas en concesión o autorización, sin que los atraques hayan sido otorgados en concesión o autorización', TO_DATE('01/01/2014 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 
    25, 'B2', '0', '0', '0', '0');
Insert into M_BONIFICACION
   (CODIGO, CODBONIFICACION, DESCRIPCION, FECINIVIG, PORCENTAJEBONIFICACION, TASATARIFA, INDVALORDEFECTO, INDT3TRAMOCOMPLETO, INDAPLICAMUELLE, INDAPLICABUQUE)
 Values
   (20, 'B3-00003', 'Reducción Artículo 215.a Terminal Concesionada. Atraque concesionado o autorizado. Entrada o Salida Marítima', TO_DATE('01/01/2014 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 
    50, 'B3', '0', '0', '0', '0');
Insert into M_BONIFICACION
   (CODIGO, CODBONIFICACION, DESCRIPCION, FECINIVIG, PORCENTAJEBONIFICACION, TASATARIFA, INDVALORDEFECTO, INDT3TRAMOCOMPLETO, INDAPLICAMUELLE, INDAPLICABUQUE)
 Values
   (21, 'B3-00004', 'Reducción Artículo 215.a Terminal Concesionada. Atraque concesionado o autorizado. Tránsito Marítimo', TO_DATE('01/01/2014 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 
    75, 'B3', '0', '0', '0', '0');
Insert into M_BONIFICACION
   (CODIGO, CODBONIFICACION, DESCRIPCION, FECINIVIG, PORCENTAJEBONIFICACION, TASATARIFA, INDVALORDEFECTO, INDT3TRAMOCOMPLETO, INDAPLICAMUELLE, INDAPLICABUQUE)
 Values
   (22, 'B3-00005', 'Reducción Artículo 215.a Terminal Concesionada. Atraque concesionado o autorizado. Transbordo', TO_DATE('01/01/2014 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 
    80, 'B3', '0', '0', '0', '0');
Insert into M_BONIFICACION
   (CODIGO, CODBONIFICACION, DESCRIPCION, FECINIVIG, PORCENTAJEBONIFICACION, TASATARIFA, INDVALORDEFECTO, INDT3TRAMOCOMPLETO, INDAPLICAMUELLE, INDAPLICABUQUE)
 Values
   (23, 'B3-00006', 'Reducción Artículo 215.b Terminal Concesionada. Atraque No Concesionado ni Autorizado', TO_DATE('01/01/2014 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 
    20, 'B3', '0', '0', '0', '0');
Insert into M_BONIFICACION
   (CODIGO, CODBONIFICACION, DESCRIPCION, FECINIVIG, PORCENTAJEBONIFICACION, TASATARIFA, INDVALORDEFECTO, INDT3TRAMOCOMPLETO, INDAPLICAMUELLE, INDAPLICABUQUE)
 Values
   (24, 'B3-00007', 'Reducción Artículo 216.a Tránsito Marítimo', TO_DATE('01/01/2014 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 
    75, 'B3', '0', '0', '0', '0');
Insert into M_BONIFICACION
   (CODIGO, CODBONIFICACION, DESCRIPCION, FECINIVIG, PORCENTAJEBONIFICACION, TASATARIFA, INDVALORDEFECTO, INDT3TRAMOCOMPLETO, INDAPLICAMUELLE, INDAPLICABUQUE)
 Values
   (25, 'B3-00008', 'Reducción Artículo 216.b Servicio Marítimo TMCD - Regular', TO_DATE('01/01/2014 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 
    20, 'B3', '0', '0', '0', '0');
Insert into M_BONIFICACION
   (CODIGO, CODBONIFICACION, DESCRIPCION, FECINIVIG, PORCENTAJEBONIFICACION, TASATARIFA, INDVALORDEFECTO, INDT3TRAMOCOMPLETO, INDAPLICAMUELLE, INDAPLICABUQUE)
 Values
   (26, 'B3-00009', 'Reducción Artículo 216.b Servicio Marítimo TMCD - Regular - Descarga por Rodadura', TO_DATE('01/01/2014 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 
    40, 'B3', '0', '0', '0', '0');
Insert into M_BONIFICACION
   (CODIGO, CODBONIFICACION, DESCRIPCION, FECINIVIG, PORCENTAJEBONIFICACION, TASATARIFA, INDVALORDEFECTO, INDT3TRAMOCOMPLETO, INDAPLICAMUELLE, INDAPLICABUQUE)
 Values
   (27, 'B3-00010', 'Reducción Artículo 216.d Transporte Ferroviario', TO_DATE('01/01/2014 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 
    50, 'B3', '0', '0', '0', '0');
Insert into M_BONIFICACION
   (CODIGO, CODBONIFICACION, DESCRIPCION, FECINIVIG, PORCENTAJEBONIFICACION, TASATARIFA, INDVALORDEFECTO, INDT3TRAMOCOMPLETO, INDAPLICAMUELLE, INDAPLICABUQUE)
 Values
   (53, 'B3-00020', 'Reducción Artículo 215.c Terminal Concesionada en tránsito terrestre', TO_DATE('01/01/2014 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 
    60, 'B3', '0', '0', '0', '0');
Insert into M_BONIFICACION
   (CODIGO, CODBONIFICACION, DESCRIPCION, FECINIVIG, PORCENTAJEBONIFICACION, TASATARIFA, INDVALORDEFECTO, INDT3TRAMOCOMPLETO, INDAPLICAMUELLE, INDAPLICABUQUE)
 Values
   (44, 'CA-00001', 'Bonificación Artículo 245.1', TO_DATE('01/01/2014 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 
    15, 'CA', '1', '0', '0', '0');
Insert into M_BONIFICACION
   (CODIGO, CODBONIFICACION, DESCRIPCION, FECINIVIG, PORCENTAJEBONIFICACION, USRMODIF, FECMODIF, TASATARIFA, INDVALORDEFECTO, INDT3TRAMOCOMPLETO, INDAPLICAMUELLE, INDAPLICABUQUE)
 Values
   (45, 'CA-00002', 'Bonificación Artículo 245.2', TO_DATE('01/01/2014 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 
    15, 'prueba', TO_DATE('12/01/2014 15:06:36', 'MM/DD/YYYY HH24:MI:SS'), 
    'CA', '1', '0', '0', '0');
Insert into M_BONIFICACION
   (CODIGO, CODBONIFICACION, DESCRIPCION, FECINIVIG, TASATARIFA, INDVALORDEFECTO, INDT3TRAMOCOMPLETO, INDAPLICAMUELLE, INDAPLICABUQUE)
 Values
   (35, 'CO-00001', 'Bonificación Artículo 181.a', TO_DATE('01/01/2014 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 
    'CO', '1', '0', '0', '0');
Insert into M_BONIFICACION
   (CODIGO, CODBONIFICACION, DESCRIPCION, FECINIVIG, TASATARIFA, INDVALORDEFECTO, INDT3TRAMOCOMPLETO, INDAPLICAMUELLE, INDAPLICABUQUE)
 Values
   (36, 'CO-00002', 'Bonificación Artículo 181.b', TO_DATE('01/01/2014 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 
    'CO', '1', '0', '0', '0');
Insert into M_BONIFICACION
   (CODIGO, CODBONIFICACION, DESCRIPCION, FECINIVIG, PORCENTAJEBONIFICACION, TASATARIFA, INDVALORDEFECTO, INDT3TRAMOCOMPLETO, INDAPLICAMUELLE, INDAPLICABUQUE)
 Values
   (37, 'CO-00003', 'Bonificación Artículo 181.c', TO_DATE('01/01/2014 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 
    50, 'CO', '1', '0', '0', '0');
Insert into M_BONIFICACION
   (CODIGO, CODBONIFICACION, DESCRIPCION, FECINIVIG, PORCENTAJEBONIFICACION, TASATARIFA, INDVALORDEFECTO, INDT3TRAMOCOMPLETO, INDAPLICAMUELLE, INDAPLICABUQUE)
 Values
   (38, 'CO-00004', 'Bonificación Artículo 181.d', TO_DATE('01/01/2014 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 
    50, 'CO', '1', '0', '0', '0');
Insert into M_BONIFICACION
   (CODIGO, CODBONIFICACION, DESCRIPCION, FECINIVIG, PORCENTAJEBONIFICACION, TASATARIFA, INDVALORDEFECTO, INDT3TRAMOCOMPLETO, INDAPLICAMUELLE, INDAPLICABUQUE)
 Values
   (39, 'CO-00005', 'Bonificación Artículo 181.e', TO_DATE('01/01/2014 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 
    30, 'CO', '1', '0', '0', '0');
Insert into M_BONIFICACION
   (CODIGO, CODBONIFICACION, DESCRIPCION, FECINIVIG, PORCENTAJEBONIFICACION, TASATARIFA, INDVALORDEFECTO, INDT3TRAMOCOMPLETO, INDAPLICAMUELLE, INDAPLICABUQUE)
 Values
   (40, 'CO-00006', 'Bonificación Artículo 181.f', TO_DATE('01/01/2014 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 
    95, 'CO', '1', '0', '0', '0');
Insert into M_BONIFICACION
   (CODIGO, CODBONIFICACION, DESCRIPCION, FECINIVIG, PORCENTAJEBONIFICACION, TASATARIFA, INDVALORDEFECTO, INDT3TRAMOCOMPLETO, INDAPLICAMUELLE, INDAPLICABUQUE)
 Values
   (41, 'CO-00007', 'Bonificación Artículo 181.g', TO_DATE('01/01/2014 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 
    30, 'CO', '1', '0', '0', '0');
Insert into M_BONIFICACION
   (CODIGO, CODBONIFICACION, DESCRIPCION, FECINIVIG, TASATARIFA, INDVALORDEFECTO, INDT3TRAMOCOMPLETO, INDAPLICAMUELLE, INDAPLICABUQUE)
 Values
   (42, 'CO-00008', 'Bonificación Artículo 181.h', TO_DATE('01/01/2014 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 
    'CO', '1', '0', '0', '0');
Insert into M_BONIFICACION
   (CODIGO, CODBONIFICACION, DESCRIPCION, FECINIVIG, TASATARIFA, INDVALORDEFECTO, INDT3TRAMOCOMPLETO, INDAPLICAMUELLE, INDAPLICABUQUE)
 Values
   (43, 'CO-00009', 'Bonificación Artículo 182', TO_DATE('01/01/2014 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 
    'CO', '1', '0', '0', '0');
Insert into M_BONIFICACION
   (CODIGO, CODBONIFICACION, DESCRIPCION, FECINIVIG, PORCENTAJEBONIFICACION, TASATARIFA, INDVALORDEFECTO, INDT3TRAMOCOMPLETO, INDAPLICAMUELLE, INDAPLICABUQUE)
 Values
   (16, 'TR-00001', 'Bonificación Artículo 132.10.a Emisión Reducida Desechos', TO_DATE('01/01/2014 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 
    20, 'TR', '0', '0', '0', '0');
Insert into M_BONIFICACION
   (CODIGO, CODBONIFICACION, DESCRIPCION, FECINIVIG, PORCENTAJEBONIFICACION, TASATARIFA, INDVALORDEFECTO, INDT3TRAMOCOMPLETO, INDAPLICAMUELLE, INDAPLICABUQUE)
 Values
   (17, 'TR-00002', 'Bonificación Artículo 132.10.b Entrega residuos en puerto anterior', TO_DATE('01/01/2014 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 
    50, 'TR', '0', '0', '0', '0');
Insert into M_BONIFICACION
   (CODIGO, CODBONIFICACION, DESCRIPCION, FECINIVIG, TASATARIFA, INDVALORDEFECTO, INDT3TRAMOCOMPLETO, INDAPLICAMUELLE, INDAPLICABUQUE)
 Values
   (18, 'TR-00003', 'Bonificación Artículo 132.10.c Plan Entrega Desechos', TO_DATE('01/01/2014 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 
    'TR', '0', '0', '0', '0');
Insert into M_BONIFICACION
   (CODIGO, CODBONIFICACION, DESCRIPCION, FECINIVIG, PORCENTAJEBONIFICACION, TASATARIFA, TIPO245, INDVALORDEFECTO, INDT3TRAMOCOMPLETO, INDAPLICAMUELLE, INDAPLICABUQUE)
 Values
   (9, 'B1-00004', 'Bonificación Artículo 245.3 Cruceros Turísticos', TO_DATE('01/01/2014 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 
    40, 
    'B1', '3', '0', '0', '0', '0');
Insert into M_BONIFICACION
   (CODIGO, CODBONIFICACION, DESCRIPCION, FECINIVIG, PORCENTAJEBONIFICACION, TASATARIFA, TIPO245, INDVALORDEFECTO, INDT3TRAMOCOMPLETO, INDAPLICAMUELLE, INDAPLICABUQUE)
 Values
   (10, 'B1-00005', 'Bonificación Artículo 245.3 Contenedores LO-LO en entrada/salida marítima en servicio marítimo regular', TO_DATE('01/01/2014 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 
    30, 
    'B1', '3', '1', '0', '0', '0');
Insert into M_BONIFICACION
   (CODIGO, CODBONIFICACION, DESCRIPCION, FECINIVIG, PORCENTAJEBONIFICACION, TASATARIFA, TIPO245, INDVALORDEFECTO, INDT3TRAMOCOMPLETO, INDAPLICAMUELLE, INDAPLICABUQUE)
 Values
   (11, 'B1-00006', 'Bonificación Artículo 245.3 Tráfico RO-RO', TO_DATE('01/01/2014 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 
    40, 
    'B1', '3', '0', '0', '0', '0');
Insert into M_BONIFICACION
   (CODIGO, CODBONIFICACION, DESCRIPCION, FECINIVIG, PORCENTAJEBONIFICACION, TASATARIFA, TIPO245, INDVALORDEFECTO, INDT3TRAMOCOMPLETO, INDAPLICAMUELLE, INDAPLICABUQUE)
 Values
   (12, 'B3-00001', 'Bonificación Artículo 245.3 Contenedores LO-LO en entrada/salida marítima en servicio marítimo regular', TO_DATE('01/01/2014 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 
    10, 
    'B3', '3', '1', '1', '0', '0');
Insert into M_BONIFICACION
   (CODIGO, CODBONIFICACION, DESCRIPCION, FECINIVIG, PORCENTAJEBONIFICACION, TASATARIFA, TIPO245, INDVALORDEFECTO, INDT3TRAMOCOMPLETO, INDAPLICAMUELLE, INDAPLICABUQUE)
 Values
   (13, 'B3-00002', 'Bonificación Artículo 245.3 Tráfico RO-RO ', TO_DATE('01/01/2014 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 
    35, 
    'B3', '3', '0', '1', '0', '0');
Insert into M_BONIFICACION
   (CODIGO, CODBONIFICACION, DESCRIPCION, FECINIVIG, PORCENTAJEBONIFICACION, TASATARIFA, TIPO245, INDVALORDEFECTO, INDT3TRAMOCOMPLETO, INDAPLICAMUELLE, INDAPLICABUQUE)
 Values
   (28, 'B3-00011', 'Bonificación Artículo 245.3 - Mineral de hierro a granel', TO_DATE('01/01/2014 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 
    10, 
    'B3', '3', '1', '0', '0', '0');
Insert into M_BONIFICACION
   (CODIGO, CODBONIFICACION, DESCRIPCION, FECINIVIG, PORCENTAJEBONIFICACION, TASATARIFA, TIPO245, INDVALORDEFECTO, INDT3TRAMOCOMPLETO, INDAPLICAMUELLE, INDAPLICABUQUE)
 Values
   (29, 'B3-00012', 'Bonificación Artículo 245.3 - Siderúrgicos sin contenerizar', TO_DATE('01/01/2014 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 
    20, 
    'B3', '3', '1', '0', '0', '0');
Insert into M_BONIFICACION
   (CODIGO, CODBONIFICACION, DESCRIPCION, FECINIVIG, PORCENTAJEBONIFICACION, TASATARIFA, TIPO245, INDVALORDEFECTO, INDT3TRAMOCOMPLETO, INDAPLICAMUELLE, INDAPLICABUQUE)
 Values
   (30, 'B3-00013', 'Bonificación Artículo 245.3 - Maderas y Otros', TO_DATE('01/01/2014 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 
    10, 
    'B3', '3', '1', '0', '0', '0');
Insert into M_BONIFICACION
   (CODIGO, CODBONIFICACION, DESCRIPCION, FECINIVIG, PORCENTAJEBONIFICACION, TASATARIFA, TIPO245, INDVALORDEFECTO, INDT3TRAMOCOMPLETO, INDAPLICAMUELLE, INDAPLICABUQUE)
 Values
   (31, 'B3-00014', 'Bonificación Artículo 245.3 - Papel y pasta de papel', TO_DATE('01/01/2014 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 
    10, 
    'B3', '3', '1', '0', '0', '0');
Insert into M_BONIFICACION
   (CODIGO, CODBONIFICACION, DESCRIPCION, FECINIVIG, PORCENTAJEBONIFICACION, TASATARIFA, TIPO245, INDVALORDEFECTO, INDT3TRAMOCOMPLETO, INDAPLICAMUELLE, INDAPLICABUQUE)
 Values
   (32, 'B3-00015', 'Bonificación Artículo 245.3 - Cereales y Otros', TO_DATE('01/01/2014 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 
    10, 
    'B3', '3', '1', '0', '0', '0');
Insert into M_BONIFICACION
   (CODIGO, CODBONIFICACION, DESCRIPCION, FECINIVIG, PORCENTAJEBONIFICACION, TASATARIFA, TIPO245, INDVALORDEFECTO, INDT3TRAMOCOMPLETO, INDAPLICAMUELLE, INDAPLICABUQUE)
 Values
   (33, 'B3-00016', 'Bonificación Artículo 245.3 - Abonos naturales y artificiales', TO_DATE('01/01/2014 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 
    10, 
    'B3', '3', '1', '0', '0', '0');
Insert into M_BONIFICACION
   (CODIGO, CODBONIFICACION, DESCRIPCION, FECINIVIG, PORCENTAJEBONIFICACION, TASATARIFA, TIPO245, INDVALORDEFECTO, INDT3TRAMOCOMPLETO, INDAPLICAMUELLE, INDAPLICABUQUE)
 Values
   (34, 'B3-00017', 'Bonificación Artículo 245.3 - Piensos y Forrajes', TO_DATE('01/01/2014 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 
    10, 
    'B3', '3', '1', '0', '0', '0');
Insert into M_BONIFICACION
   (CODIGO, CODBONIFICACION, DESCRIPCION, FECINIVIG, PORCENTAJEBONIFICACION, TASATARIFA, INDVALORDEFECTO, INDT3TRAMOCOMPLETO, INDAPLICAMUELLE, INDAPLICABUQUE)
 Values
   (49, 'B2-01001', 'Reducción Artículo 208.c. Estaciones marítimas otorgadas en concesión o autorización, sin que los atraques hayan sido otorgados en concesión o autorización', TO_DATE('01/01/2014 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 
    25, 'B2', '0', '0', '0', '0');
Insert into M_BONIFICACION
   (CODIGO, CODBONIFICACION, DESCRIPCION, FECINIVIG, TASATARIFA, TIPO245, INDVALORDEFECTO, INDT3TRAMOCOMPLETO, INDAPLICAMUELLE, INDAPLICABUQUE)
 Values
   (15, 'B2-00002', 'Bonificación Artículo 245.3 Cruceros turísticos', TO_DATE('01/01/2014 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 
    'B2', '3', '0', '0', '0', '0');
Insert into M_BONIFICACION
   (CODIGO, CODBONIFICACION, DESCRIPCION, FECINIVIG, PORCENTAJEBONIFICACION, TASATARIFA, TIPO245, INDVALORDEFECTO, INDT3TRAMOCOMPLETO, INDAPLICAMUELLE, INDAPLICABUQUE)
 Values
   (46, 'B1-00000', 'Sin Bonificación Artículo 245.3', TO_DATE('01/01/2014 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 
    0, 
    'B1', '3', '0', '0', '0', '0');
Insert into M_BONIFICACION
   (CODIGO, CODBONIFICACION, DESCRIPCION, FECINIVIG, PORCENTAJEBONIFICACION, TASATARIFA, INDVALORDEFECTO, INDT3TRAMOCOMPLETO, INDAPLICAMUELLE, INDAPLICABUQUE)
 Values
   (51, 'B3-00020', 'Reducción Artículo 215.c Terminal Concesionada en tránsito terrestre', TO_DATE('01/01/2014 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 
    60, 'B3', '0', '0', '0', '0');
Insert into M_BONIFICACION
   (CODIGO, CODBONIFICACION, DESCRIPCION, FECINIVIG, PORCENTAJEBONIFICACION, TASATARIFA, TIPO245, INDVALORDEFECTO, INDT3TRAMOCOMPLETO, INDAPLICAMUELLE, INDAPLICABUQUE)
 Values
   (1, 'B1-00080', 'Bonificación Artículo 245.5', TO_DATE('01/01/2014 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 
    40, 
    'B1', '5', '1', '0', '0', '0');
Insert into M_BONIFICACION
   (CODIGO, CODBONIFICACION, DESCRIPCION, FECINIVIG, PORCENTAJEBONIFICACION, TASATARIFA, INDVALORDEFECTO, INDT3TRAMOCOMPLETO, INDAPLICAMUELLE, INDAPLICABUQUE)
 Values
   (64, 'B2-01003', 'Bonificación Artículo 245.5 Pasajeros en régimen transporte', TO_DATE('01/01/2014 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 
    34, 'B2', '0', '0', '0', '0');
Insert into M_BONIFICACION
   (CODIGO, CODBONIFICACION, DESCRIPCION, FECINIVIG, PORCENTAJEBONIFICACION, TASATARIFA, INDVALORDEFECTO, INDT3TRAMOCOMPLETO, INDAPLICAMUELLE, INDAPLICABUQUE)
 Values
   (65, 'B2-01004', 'Bonificación Artículo 245.5 Vehículos en régimen transporte', TO_DATE('01/01/2014 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 
    30, 'B2', '0', '0', '0', '0');
Insert into M_BONIFICACION
   (CODIGO, CODBONIFICACION, DESCRIPCION, FECINIVIG, PORCENTAJEBONIFICACION, TASATARIFA, TIPO245, INDVALORDEFECTO, INDT3TRAMOCOMPLETO, INDAPLICAMUELLE, INDAPLICABUQUE)
 Values
   (80, 'B3-00051', 'Bonificación Artículo 245.5 Mercancías y Elementos de Transporte', TO_DATE('01/01/2014 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 
    40, 
    'B3', '5', '0', '0', '0', '0');
COMMIT;
