SET DEFINE OFF;
Insert into M_ESTADO_MIEMBRO
   (CODPAIS, NOMBRE, NUMECHARS, TIPOCHARS)
 Values
   ('DE', 'ALEMANIA', '9', 'NUMERIC');
Insert into M_ESTADO_MIEMBRO
   (CODPAIS, NOMBRE, NUMECHARS, TIPOCHARS)
 Values
   ('AT', 'AUSTRIA', '9', 'ALPHA');
Insert into M_ESTADO_MIEMBRO
   (CODPAIS, NOMBRE, NUMECHARS, TIPOCHARS)
 Values
   ('BE', 'BELGICA', '9|10', 'NUMERIC');
Insert into M_ESTADO_MIEMBRO
   (CODPAIS, NOMBRE, NUMECHARS, TIPOCHARS)
 Values
   ('BG', 'BULGARIA', '9|10', 'NUMERIC');
Insert into M_ESTADO_MIEMBRO
   (CODPAIS, NOMBRE, NUMECHARS, TIPOCHARS)
 Values
   ('CY', 'CHIPRE', '9', 'ALPHA');
Insert into M_ESTADO_MIEMBRO
   (CODPAIS, NOMBRE, NUMECHARS, TIPOCHARS)
 Values
   ('CZ', 'CHEQUIA', '8|9|10', 'NUMERIC');
Insert into M_ESTADO_MIEMBRO
   (CODPAIS, NOMBRE, NUMECHARS, TIPOCHARS)
 Values
   ('DK', 'DINAMARCA', '8', 'NUMERIC');
Insert into M_ESTADO_MIEMBRO
   (CODPAIS, NOMBRE, NUMECHARS, TIPOCHARS)
 Values
   ('EE', 'ESTONIA', '9', 'NUMERIC');
Insert into M_ESTADO_MIEMBRO
   (CODPAIS, NOMBRE, NUMECHARS, TIPOCHARS)
 Values
   ('FI', 'FINLANDIA', '8', 'NUMERIC');
Insert into M_ESTADO_MIEMBRO
   (CODPAIS, NOMBRE, NUMECHARS, TIPOCHARS)
 Values
   ('FR', 'FRANCIA', '11', 'ALPHA');
Insert into M_ESTADO_MIEMBRO
   (CODPAIS, NOMBRE, NUMECHARS, TIPOCHARS)
 Values
   ('EL', 'GRECIA', '9', 'NUMERIC');
Insert into M_ESTADO_MIEMBRO
   (CODPAIS, NOMBRE, NUMECHARS, TIPOCHARS)
 Values
   ('GB', 'GRAN BRETAÑA', '5|9|12', 'ALPHA');
Insert into M_ESTADO_MIEMBRO
   (CODPAIS, NOMBRE, NUMECHARS, TIPOCHARS)
 Values
   ('NL', 'HOLANDA', '12', 'ALPHA');
Insert into M_ESTADO_MIEMBRO
   (CODPAIS, NOMBRE, NUMECHARS, TIPOCHARS)
 Values
   ('HU', 'HUNGRIA', '8', 'NUMERIC');
Insert into M_ESTADO_MIEMBRO
   (CODPAIS, NOMBRE, NUMECHARS, TIPOCHARS)
 Values
   ('IT', 'ITALIA', '11', 'NUMERIC');
Insert into M_ESTADO_MIEMBRO
   (CODPAIS, NOMBRE, NUMECHARS, TIPOCHARS)
 Values
   ('IE', 'IRLANDA', '8', 'ALPHA');
Insert into M_ESTADO_MIEMBRO
   (CODPAIS, NOMBRE, NUMECHARS, TIPOCHARS)
 Values
   ('LT', 'LITUANIA', '9|12', 'NUMERIC');
Insert into M_ESTADO_MIEMBRO
   (CODPAIS, NOMBRE, NUMECHARS, TIPOCHARS)
 Values
   ('LU', 'LUXEMBURGO', '8', 'NUMERIC');
Insert into M_ESTADO_MIEMBRO
   (CODPAIS, NOMBRE, NUMECHARS, TIPOCHARS)
 Values
   ('LV', 'LETONIA', '11', 'NUMERIC');
Insert into M_ESTADO_MIEMBRO
   (CODPAIS, NOMBRE, NUMECHARS, TIPOCHARS)
 Values
   ('MT', 'MALTA', '8', 'NUMERIC');
Insert into M_ESTADO_MIEMBRO
   (CODPAIS, NOMBRE, NUMECHARS, TIPOCHARS)
 Values
   ('PL', 'POLONIA', '10', 'NUMERIC');
Insert into M_ESTADO_MIEMBRO
   (CODPAIS, NOMBRE, NUMECHARS, TIPOCHARS)
 Values
   ('PT', 'PORTUGAL', '9', 'NUMERIC');
Insert into M_ESTADO_MIEMBRO
   (CODPAIS, NOMBRE, NUMECHARS, TIPOCHARS)
 Values
   ('RO', 'RUMANIA', '2|3|4|5|6|7|8|9|10', 'NUMERIC');
Insert into M_ESTADO_MIEMBRO
   (CODPAIS, NOMBRE, NUMECHARS, TIPOCHARS)
 Values
   ('SE', 'SUECIA', '12', 'NUMERIC');
Insert into M_ESTADO_MIEMBRO
   (CODPAIS, NOMBRE, NUMECHARS, TIPOCHARS)
 Values
   ('SI', 'ESLOVENIA', '8', 'NUMERIC');
Insert into M_ESTADO_MIEMBRO
   (CODPAIS, NOMBRE, NUMECHARS, TIPOCHARS)
 Values
   ('SK', 'ESLOVAQUIA', '10', 'NUMERIC');
COMMIT;
