SET DEFINE OFF;
Insert into SAN_ESTADO_EXP
   (CODESTADO, DESESTADO, ORDEN)
 Values
   ('BOLDEN', 'BOLETÍN DENUNCIA', 1);
Insert into SAN_ESTADO_EXP
   (CODESTADO, DESESTADO, ORDEN)
 Values
   ('INIEXP', 'INICIO Y PROPUESTA RESOLUCIÓN', 2);
Insert into SAN_ESTADO_EXP
   (CODESTADO, DESESTADO, ORDEN)
 Values
   ('PRORES', 'SEGUNDA PROPUESTA RESOLUCIÓN', 3);
Insert into SAN_ESTADO_EXP
   (CODESTADO, DESESTADO, ORDEN)
 Values
   ('RESOL', 'RESOLUCIÓN', 4);
Insert into SAN_ESTADO_EXP
   (CODESTADO, DESESTADO, ORDEN)
 Values
   ('FINAL', 'FINALIZADO', 5);
Insert into SAN_ESTADO_EXP
   (CODESTADO, DESESTADO, ORDEN)
 Values
   ('APRE', 'APREMIO', 6);
COMMIT;
