SET DEFINE OFF;
Insert into SAN_APARTADO_ARTICULO
   (CODARTICULO, CODAPARTADO, DESAPARTADO, USRALTA, USRMODIF, FECALTA, FECMODIF)
 Values
   ('308', '1c', 'art. 308.1.c', 'prueba', 'prueba', 
    TO_DATE('09/22/2014 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), TO_DATE('09/22/2014 00:00:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into SAN_APARTADO_ARTICULO
   (CODARTICULO, CODAPARTADO, DESAPARTADO)
 Values
   ('306', '1b', 'art. 306.1.b');
Insert into SAN_APARTADO_ARTICULO
   (CODARTICULO, CODAPARTADO, DESAPARTADO)
 Values
   ('306', '1a', 'art. 306.1.a');
Insert into SAN_APARTADO_ARTICULO
   (CODARTICULO, CODAPARTADO, DESAPARTADO)
 Values
   ('306', '1c', 'art. 306.1.c');
Insert into SAN_APARTADO_ARTICULO
   (CODARTICULO, CODAPARTADO, DESAPARTADO)
 Values
   ('306', '1e', 'art. 306.1.e');
Insert into SAN_APARTADO_ARTICULO
   (CODARTICULO, CODAPARTADO, DESAPARTADO)
 Values
   ('306', '1d', 'art. 306.1.d');
Insert into SAN_APARTADO_ARTICULO
   (CODARTICULO, CODAPARTADO, DESAPARTADO)
 Values
   ('306', '1f', 'art. 306.1.f');
Insert into SAN_APARTADO_ARTICULO
   (CODARTICULO, CODAPARTADO, DESAPARTADO)
 Values
   ('306', '1g', 'art. 306.1.g');
Insert into SAN_APARTADO_ARTICULO
   (CODARTICULO, CODAPARTADO, DESAPARTADO)
 Values
   ('306', '1h', 'art. 306.1.h');
Insert into SAN_APARTADO_ARTICULO
   (CODARTICULO, CODAPARTADO, DESAPARTADO)
 Values
   ('306', '1i', 'art. 306.1.i');
Insert into SAN_APARTADO_ARTICULO
   (CODARTICULO, CODAPARTADO, DESAPARTADO)
 Values
   ('306', '1j', 'art. 306.1.i');
Insert into SAN_APARTADO_ARTICULO
   (CODARTICULO, CODAPARTADO, DESAPARTADO)
 Values
   ('306', '2a', 'art. 306.2.a');
Insert into SAN_APARTADO_ARTICULO
   (CODARTICULO, CODAPARTADO, DESAPARTADO)
 Values
   ('306', '2b', 'art. 306.2.b');
Insert into SAN_APARTADO_ARTICULO
   (CODARTICULO, CODAPARTADO, DESAPARTADO)
 Values
   ('306', '2c', 'art. 306.2.c');
Insert into SAN_APARTADO_ARTICULO
   (CODARTICULO, CODAPARTADO, DESAPARTADO)
 Values
   ('306', '2d', 'art. 306.2.d');
Insert into SAN_APARTADO_ARTICULO
   (CODARTICULO, CODAPARTADO, DESAPARTADO)
 Values
   ('306', '2e', 'art. 306.2.e');
Insert into SAN_APARTADO_ARTICULO
   (CODARTICULO, CODAPARTADO, DESAPARTADO)
 Values
   ('306', '5a', 'art. 306.5.a');
Insert into SAN_APARTADO_ARTICULO
   (CODARTICULO, CODAPARTADO, DESAPARTADO)
 Values
   ('306', '5b', 'art. 306.5.b');
Insert into SAN_APARTADO_ARTICULO
   (CODARTICULO, CODAPARTADO, DESAPARTADO)
 Values
   ('306', '5c', 'art. 306.5.c');
Insert into SAN_APARTADO_ARTICULO
   (CODARTICULO, CODAPARTADO, DESAPARTADO)
 Values
   ('307', '1a', 'art. 307.1.a');
Insert into SAN_APARTADO_ARTICULO
   (CODARTICULO, CODAPARTADO, DESAPARTADO)
 Values
   ('307', '1b', 'art. 307.1.b');
Insert into SAN_APARTADO_ARTICULO
   (CODARTICULO, CODAPARTADO, DESAPARTADO)
 Values
   ('307', '1c', 'art. 307.1.c');
Insert into SAN_APARTADO_ARTICULO
   (CODARTICULO, CODAPARTADO, DESAPARTADO)
 Values
   ('307', '1d', 'art. 307.1.d');
Insert into SAN_APARTADO_ARTICULO
   (CODARTICULO, CODAPARTADO, DESAPARTADO)
 Values
   ('307', '1e', 'art. 307.1.e');
Insert into SAN_APARTADO_ARTICULO
   (CODARTICULO, CODAPARTADO, DESAPARTADO)
 Values
   ('307', '1f', 'art. 307.1.f');
Insert into SAN_APARTADO_ARTICULO
   (CODARTICULO, CODAPARTADO, DESAPARTADO)
 Values
   ('307', '1g', 'art. 307.1.g');
Insert into SAN_APARTADO_ARTICULO
   (CODARTICULO, CODAPARTADO, DESAPARTADO)
 Values
   ('307', '1h', 'art. 307.1.h');
Insert into SAN_APARTADO_ARTICULO
   (CODARTICULO, CODAPARTADO, DESAPARTADO)
 Values
   ('307', '4a', 'art. 307.4.a');
Insert into SAN_APARTADO_ARTICULO
   (CODARTICULO, CODAPARTADO, DESAPARTADO)
 Values
   ('307', '4b', 'art. 307.4.b');
Insert into SAN_APARTADO_ARTICULO
   (CODARTICULO, CODAPARTADO, DESAPARTADO)
 Values
   ('307', '4c', 'art. 307.4.c');
Insert into SAN_APARTADO_ARTICULO
   (CODARTICULO, CODAPARTADO, DESAPARTADO)
 Values
   ('307', '4d', 'art. 307.4.d');
Insert into SAN_APARTADO_ARTICULO
   (CODARTICULO, CODAPARTADO, DESAPARTADO)
 Values
   ('307', '4e', 'art. 307.4.e');
Insert into SAN_APARTADO_ARTICULO
   (CODARTICULO, CODAPARTADO, DESAPARTADO)
 Values
   ('307', '4f', 'art. 307.4.f');
Insert into SAN_APARTADO_ARTICULO
   (CODARTICULO, CODAPARTADO, DESAPARTADO)
 Values
   ('307', '5a', 'art. 307.5.a');
Insert into SAN_APARTADO_ARTICULO
   (CODARTICULO, CODAPARTADO, DESAPARTADO)
 Values
   ('307', '5b', 'art. 307.5.b');
Insert into SAN_APARTADO_ARTICULO
   (CODARTICULO, CODAPARTADO, DESAPARTADO)
 Values
   ('307', '5c', 'art. 307.5.c');
Insert into SAN_APARTADO_ARTICULO
   (CODARTICULO, CODAPARTADO, DESAPARTADO)
 Values
   ('307', '5d', 'art. 307.5.d');
Insert into SAN_APARTADO_ARTICULO
   (CODARTICULO, CODAPARTADO, DESAPARTADO)
 Values
   ('307', '5e', 'art. 307.5.e');
Insert into SAN_APARTADO_ARTICULO
   (CODARTICULO, CODAPARTADO, DESAPARTADO)
 Values
   ('308', '1a', 'art. 308.1.a');
Insert into SAN_APARTADO_ARTICULO
   (CODARTICULO, CODAPARTADO, DESAPARTADO)
 Values
   ('308', '1b', 'art. 308.1.b');
Insert into SAN_APARTADO_ARTICULO
   (CODARTICULO, CODAPARTADO, DESAPARTADO)
 Values
   ('308', '4a', 'art. 308.4.a');
Insert into SAN_APARTADO_ARTICULO
   (CODARTICULO, CODAPARTADO, DESAPARTADO)
 Values
   ('308', '4b', 'art. 308.4.b');
Insert into SAN_APARTADO_ARTICULO
   (CODARTICULO, CODAPARTADO, DESAPARTADO)
 Values
   ('308', '4c', 'art. 308.4.c');
Insert into SAN_APARTADO_ARTICULO
   (CODARTICULO, CODAPARTADO, DESAPARTADO)
 Values
   ('308', '4d', 'art. 308.4.d');
Insert into SAN_APARTADO_ARTICULO
   (CODARTICULO, CODAPARTADO, DESAPARTADO)
 Values
   ('308', '5a', 'art. 308.5.a');
Insert into SAN_APARTADO_ARTICULO
   (CODARTICULO, CODAPARTADO, DESAPARTADO)
 Values
   ('308', '5b', 'art. 308.5.b');
Insert into SAN_APARTADO_ARTICULO
   (CODARTICULO, CODAPARTADO, DESAPARTADO)
 Values
   ('308', '5c', 'art. 308.5.c');
Insert into SAN_APARTADO_ARTICULO
   (CODARTICULO, CODAPARTADO, DESAPARTADO)
 Values
   ('308', '5d', 'art. 308.5.d');
COMMIT;
