SET DEFINE OFF;
Insert into T3_TIPOSUMINTRAFINT
   (CODIGO, DESCRIPCION, CODGRUPOFACTURACION, INDBAJA)
 Values
   (1, 'Gas-oil', '2', '0');
Insert into T3_TIPOSUMINTRAFINT
   (CODIGO, DESCRIPCION, CODGRUPOFACTURACION, INDBAJA)
 Values
   (2, 'Diesel-oil', '2', '0');
Insert into T3_TIPOSUMINTRAFINT
   (CODIGO, DESCRIPCION, CODGRUPOFACTURACION, INDBAJA)
 Values
   (3, 'Fuel-oil', '1', '0');
Insert into T3_TIPOSUMINTRAFINT
   (CODIGO, DESCRIPCION, CODGRUPOFACTURACION, INDBAJA)
 Values
   (4, 'GNL', '5', '0');
Insert into T3_TIPOSUMINTRAFINT
   (CODIGO, DESCRIPCION, CODGRUPOFACTURACION, INDBAJA)
 Values
   (9999, 'Otros', '5', '0');
COMMIT;
