SET DEFINE OFF;
Insert into T8_TIPOSUMINOTROS
   (CODIGO, DESCRIPCION, CODTIPOSUMIN, CODPUE, FECINIVIG)
 Values
   ('001', 'Suministro Hielo', 'H', 'M', TO_DATE('01/01/2014 00:00:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into T8_TIPOSUMINOTROS
   (CODIGO, DESCRIPCION, CODTIPOSUMIN, CODPUE, FECINIVIG)
 Values
   ('002', 'Otros Suministros (Estadísticas)', 'O', 'M', TO_DATE('01/01/2014 00:00:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into T8_TIPOSUMINOTROS
   (CODIGO, DESCRIPCION, CODTIPOSUMIN, BAREMOTARIFA, CODPUE, FECINIVIG)
 Values
   ('003', 'Suministro Gas', 'G', 'ZZZZ88', 'M', 
    TO_DATE('01/01/2014 00:00:00', 'MM/DD/YYYY HH24:MI:SS'));
COMMIT;
