SET DEFINE OFF;
Insert into T8_TIPOSUMINISTRO
   (CODIGO, DESCRIPCION, INDMTOCONTADOR, INDAPLICABUQUE, INDAPLICAOTROS, INDINSTFIJAS, INDLIQUIDABLE)
 Values
   ('A', 'Agua', '1', '1', '1', 
    '1', '1');
Insert into T8_TIPOSUMINISTRO
   (CODIGO, DESCRIPCION, INDMTOCONTADOR, INDAPLICABUQUE, INDAPLICAOTROS, INDINSTFIJAS, INDLIQUIDABLE)
 Values
   ('E', 'Energia eléctrica', '1', '1', '1', 
    '1', '1');
Insert into T8_TIPOSUMINISTRO
   (CODIGO, DESCRIPCION, INDMTOCONTADOR, INDAPLICABUQUE, INDAPLICAOTROS, INDINSTFIJAS, INDLIQUIDABLE)
 Values
   ('H', 'Hielo', '0', '0', '1', 
    '0', '0');
Insert into T8_TIPOSUMINISTRO
   (CODIGO, DESCRIPCION, INDMTOCONTADOR, INDAPLICABUQUE, INDAPLICAOTROS, INDINSTFIJAS, INDLIQUIDABLE)
 Values
   ('O', 'Otros (Estadísticas)', '0', '0', '1', 
    '0', '0');
Insert into T8_TIPOSUMINISTRO
   (CODIGO, DESCRIPCION, INDMTOCONTADOR, INDAPLICABUQUE, INDAPLICAOTROS, INDINSTFIJAS, INDLIQUIDABLE)
 Values
   ('G', 'Gas', '0', '0', '1', 
    '0', '1');
COMMIT;
