SET DEFINE OFF;
Insert into TIPO_OPERACION
   (CODTIPOPE, NOMBRE, INDDUE, BAJA)
 Values
   ('ZD', 'Desembarque', '1', '0');
Insert into TIPO_OPERACION
   (CODTIPOPE, NOMBRE, INDDUE, BAJA)
 Values
   ('ZE', 'Embarque', '1', '0');
Insert into TIPO_OPERACION
   (CODTIPOPE, NOMBRE, INDDUE, BAJA)
 Values
   ('ZT', 'Trasbordo', '1', '0');
Insert into TIPO_OPERACION
   (CODTIPOPE, NOMBRE, INDDUE, BAJA)
 Values
   ('ZR', 'Residuos', '1', '0');
Insert into TIPO_OPERACION
   (CODTIPOPE, NOMBRE, INDDUE, USRALTA, USRMODIF, FECALTA, FECMODIF)
 Values
   ('AV', 'Avituallamiento', '1', 'SISTEMA', 
    'SISTEMA', TO_DATE('12/28/2015 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), TO_DATE('12/28/2015 00:00:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into TIPO_OPERACION
   (CODTIPOPE, NOMBRE, INDDUE, USRALTA, USRMODIF, FECALTA, FECMODIF)
 Values
   ('DT', 'Desembarque en transito', '1', 'SISTEMA', 
    'SISTEMA', TO_DATE('12/28/2015 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), TO_DATE('12/28/2015 00:00:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into TIPO_OPERACION
   (CODTIPOPE, NOMBRE, INDDUE, USRALTA, USRMODIF, FECALTA, FECMODIF)
 Values
   ('RE', 'Reestiba', '1', 'SISTEMA', 
    'SISTEMA', TO_DATE('12/28/2015 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), TO_DATE('12/28/2015 00:00:00', 'MM/DD/YYYY HH24:MI:SS'));
COMMIT;
