SET DEFINE OFF;
Insert into TIPO_ALQPASARELA
   (CODIGO, DESCRIPCION)
 Values
   ('C', 'CUBIERTA');
Insert into TIPO_ALQPASARELA
   (CODIGO, DESCRIPCION)
 Values
   ('D', 'DESEMBARQUE');
COMMIT;
