






SELECT * FROM ISUM_RED_REDS;

SELECT * FROM IFAC_LECTURAPUNTORED_FLPR;
SELECT * FROM IFAC_GASTOPUNTORED_FGPR;

SELECT * FROM ICON_MODULO_MODU;



SELECT *
FROM ICOM_ORGANIZACION_ORGA 
    LEFT JOIN ICOM_DIRECCION_CONT_DIRC ON
        DIRC_ID_ORGANIZACION = ORGA_ID
;

		SELECT
		    MAES.ORGA_COD
		    , MAES.orga_nombre
		    , MAES.ORGA_TIPO_DOC_FISCAL
		    , COALESCE(MAES.ORGA_DOC_FISCAL_PREFIJO, '')
		    	|| COALESCE(MAES.ORGA_DOC_FISCAL, '')
		    	|| COALESCE(MAES.ORGA_DOC_FISCAL_SUFIJO, '')
		    AS ORGA_DOCUMENTO
		    , MAES.ORGA_DESCRIPCION
        , DIRC_DIRECCION || ', ' || DIRC_PORTAL || ', ' || DIRC_piso || DIRC_letra || DIRC_puerta as direccion
        , DIRC_COD_POSTAL
        , NULL AS UNLOCODE
        , DIRC_PERSONA_CONTACTO
        , DIRC_TELEFONOA
        , DIRC_TELEFONOB
        , DIRC_FAX
        , DIRC_EMAIL
        , DIRC_PAGINA_WEB
		FROM ICOM_ORGANIZACION_ORGA MAES
        LEFT JOIN ICOM_DIRECCION_CONT_DIRC ON
            DIRC_ID_ORGANIZACION = ORGA_ID
    order by MAES.ORGA_ES_ACTIVO desc
;


SELECT * 
FROM IGEN_PROVINCIA_PROV MAES
    join igen_provin
;

SELECT * 
FROM IGEN_municipio_muni
;


SELECT
  PRSU.PRSU_CODIGO
  , PRSU.PRSU_NOMBRE
  , PRSU.PRSU_REFERENCIA
  , PRSU.PRSU_ESTADO
  , (
    SELECT
      (
        SELECT subp_codigo
        FROM IGEN_SUBPUERTO_SUBP
        where subp_id = REDS_SUBP_ID
      )
      || reds_codigo
    FROM ISUM_RED_REDS
    where reds_id = PRSU_REDS_ID
  ) as PRSU_REDS
  , (
    SELECT TSUM_codigo
    FROM ISUM_TIPOSUMINISTRO_TSUM
    where TSUM_id = PRSU_TSUM_ID
  ) as PRSU_TSUM
  , (
    SELECT TCSU_CODIGO
    FROM ISUM_TIPOCONTADOR_TCSU
    WHERE TCSU_ID = PRSU_TCSU_ID
  ) AS PRSU_TCSU
  , (
    SELECT IVAT_CODIGO
    FROM IFAC_IVATIPO_IVAT
    where IVAT_id = PRSU_IVAT_ID
  ) AS PRSU_IVAT
  , PRSU.PRSU_CONSUMO_MIN
  , PRSU.PRSU_CONSUMO_MIN_PERIDO
  , PRSU.PRSU_TUBERIA_ENT_DIAMETRO
  , PRSU.PRSU_TUBERIA_SAL_DIAMETRO
  , PRSU.PRSU_DISTANCIA_ANTERIOR
  , PRSU.PRSU_RUTA_LECTURA
  , PRSU.PRSU_FORMA_REC_LECTURA
  , PRSU.PRSU_FECHA_ULTIMA_LECTURA
  , PRSU.PRSU_ULTIMA_LECTURA
  , PRSU.PRSU_POTENCIA
  , PRSU.PRSU_UBICACION
  , PRSU.PRSU_POSICION_RUTA
  , PRSU.PRSU_SECCION_CABLE
  , PRSU.PRSU_SEC_REPETIDORES
  , PRSU.PRSU_OBSERV
FROM ISUM_PUNTORED_PRSU PRSU
;

SELECT
  REDS.*
FROM ISUM_RED_REDS REDS
;

SELECT *
FROM IESC_TRAFICOBUQUE_TRBU TRBU;




SELECT SERV.*
  , (SELECT COUNT(1)
    FROM IMAN_BL_MABL
    where MABL_MANI_ID = serv_id
  ) AS numBl
  , (SELECT COUNT(1)
    FROM IMAN_PARTIDA_PART
    WHERE EXISTS (
      SELECT 1 FROM IMAN_BL_MABL
      WHERE
        MABL_ID = PART_MABL_ID
        aNd MABL_MANI_ID = SERV_ID
    )
  ) AS NUMPART
  , (SELECT COUNT(1)
    FROM IMAN_EQUIPAMIENTO_EQUI
    WHERE EXISTS (
      SELECT 1 FROM IMAN_BL_MABL
      WHERE
        MABL_ID = EQUI_MABL_ID
        aNd MABL_MANI_ID = SERV_ID
    )
  ) AS NUMEQUI
FROM ICOM_SERVICIO_SERV SERV
  JOIN IMAN_MANIFIESTO_MANI MANI ON
    MANI.MANI_ID = SERV.SERV_ID
;


select * from DEVUELVE_ENTRADAS_BUQUE;

select count(1) from IESC_ATRAQUE_ATRA;

select 
    atra.ATRA_FECHA_AUTORIZACION
    , atra.ATRA_EMISOR_EDI
    , atra.ATRA_NUMERO_EDI
    , atra.ATRA_CODIGO_EXENCION
    , atra.ATRA_ES_SUJETO_PAS_SUSTIT
    , atra.ATRA_FECHA_SOLICITUD
    , atra.ATRA_ORGA_ID_CLIENTE
    , atra.ATRA_TIPO_EXENCION
    , atra.ATRA_ORGA_ID_CONSIGNATARIO
    , atra.ATRA_ES_MODIFICADO_EDI
    , atra.ATRA_DEAD_ID
    , atrdSol.ATRD_NORAY_INICIAL
    , atrdSol.ATRD_NORAY_FINAL
    , atrdSol.ATRD_CALADO_ENTRADA
    , atrdSol.ATRD_CALADO_SALIDA
    , atrdSol.ATRD_RAMPA_ADICIONAL
    , atrdSol.ATRD_ESLORA_RAMPA
    , atrdSol.ATRD_OBSERVACIONES
    , atrdSol.ATRD_TIPO_ESTANCIA
    , atrdSol.ATRD_ES_LUZ_SOLICITADA
    , atrdSol.ATRD_ES_FUERZA_SOLICITADA
    , atrdSol.ATRD_ES_COMBUST_SOLICITADO
    , atrdSol.ATRD_ES_HIELO_SOLICITADO
    , atrdSol.ATRD_ES_AGUA_SOLICITADA
    , atrdSol.ATRD_ES_EXENCION_PRAC_SOL
from IESC_ATRAQUE_ATRA atra
    left join IESC_ATRAQUEDETALLE_ATRD atrdSol on
        atrdSol.ATRD_ATRA_ID = atra.ATRA_ID
        and atrdSol.ATRD_MOMENTO = 'S'
    left join IESC_ATRAQUEDETALLE_ATRD atrdAut on
        atrdAut.ATRD_ATRA_ID = atra.ATRA_ID
        and atrdAut.ATRD_MOMENTO = 'A'
    left join IESC_ATRAQUEDETALLE_ATRD atrdRea on
        atrdRea.ATRD_ATRA_ID = atra.ATRA_ID
        and atrdRea.ATRD_MOMENTO = 'R'
;


-- Tipos de Atraque EDI
select * from IESC_ATRAQUEEDITIPO_ATET;
select * from IESC_ATRAQUEEDITIPOI18N_ATET;
select * from IESC_ATRAQUETIPO_ATRT;
select * from IESC_ATRAQUETIPOI18N_ATRT;
select * from IESC_RELACIONATRAQUETIPO_RATT;

select 
    (SELECT atet_codigo FROM IESC_ATRAQUEEDITIPO_ATET where ATET_id = RATT_ATET_ID_1) 
      || (SELECT atet_codigo FROM IESC_ATRAQUEEDITIPO_ATET where ATET_id = RATT_ATET_ID_2) 
      || (SELECT atet_codigo FROM IESC_ATRAQUEEDITIPO_ATET where ATET_id = RATT_ATET_ID_3) 
      AS ratt_atet
    , (SELECT atrt_codigo from IESC_ATRAQUETIPO_ATRT where atrt_id = RATT_ATRT_ID) as ratt_atrt
    , (select atet_nombre from IESC_ATRAQUEEDITIPOI18N_ATET where atet_id = RATT_ATET_ID_1 and ATET_IDIOMA = idioma
        AND FREFERENCIA BETWEEN ATET_FECHA_CREACION AND COALESCE(ATET_FECHA_FIN, FREFERENCIA))
      || ' / ' ||
      (select atet_nombre from IESC_ATRAQUEEDITIPOI18N_ATET where atet_id = RATT_ATET_ID_2 and ATET_IDIOMA = idioma 
        AND FREFERENCIA BETWEEN ATET_FECHA_CREACION AND COALESCE(ATET_FECHA_FIN, FREFERENCIA))
      || ' / ' ||
      (select atet_nombre from IESC_ATRAQUEEDITIPOI18N_ATET where atet_id = RATT_ATET_ID_3 and ATET_IDIOMA = idioma
        AND FREFERENCIA BETWEEN ATET_FECHA_CREACION AND COALESCE(ATET_FECHA_FIN, FREFERENCIA))
        AS texto
from (
    select 'es_ES' as idioma, sysdate as FREFERENCIA, sysdate as fref, ratt.*
    from IESC_RELACIONATRAQUETIPO_RATT ratt
) sql
;

select sysdate as fref , sysdate as fref, ratt.*
from IESC_RELACIONATRAQUETIPO_RATT ratt;
